### ISSUE TITLE
Hexchat makes chaotic edits to chanopt.conf

### ISSUE THREAD

**Issue by badon** [hexchat/hexchat#1033]
The settings in chanopt.conf are unreliable and constantly changing, especially on restarts of Hexchat. So, consequently, Hexchat does not behave as it should for things like activity notifications. chanopt.conf should only be altered when the user makes a change.

I searched for similar bugs, or for previous reports of this bug, but I only found this:

https://github.com/hexchat/hexchat/issues/858

**Comment by xPaw** [comment]
There's definitely some bug within `chanopt_save_all` it self. I've been looking at `chanopt.conf` file while changing channel settings. After changing something, it rewrites the file with option for that channel only, all other channels are gone. However on client exit it writes the file again, with all previous channels.

**Comment by Arnavion** [comment]
Merged into #1134 since it has more discussion.
