### ISSUE TITLE
Garbage in Scrollback will crash HexChat

### ISSUE THREAD

**Issue by Olipro** [hexchat/hexchat#1036]
If a scrollback log file gets corrupted with garbage characters in any way, it will result in HexChat crashing.

Judging by the current format, it would probably be wise to switch to some sort of validated markup like XML or JSON so that invalid scrollback files can be discarded safely.

**Comment by PikalaxALT** [comment]
I'm also experiencing the scrollback.  Hexchat will suddenly crash, and then the next time I try to launch Hexchat, it will fail to load any scrollback and immediately crash to desktop.  The only way to stop HexChat from crashing is to delete all the scrollback files.

**Comment by TingPing** [comment]
Should be improved by 650bddcfd1399c875156cec8be37e331835ce129, reopen if can still crash.
