### ISSUE TITLE
EFnet Server List

### ISSUE THREAD

**Issue by dubkat** [hexchat/hexchat#1039]
The servers listed for EFnet are beyond ancient, and most of them are long gone.  I hearby provide you with the current list as of 2014-06-28.

irc.qeast.net for example, changed to irc.avalonworks.ca like a decade ago, and has since changed names twice since then. (currently teksavvy, listed below)

-- dubkat / EFnet Staff (efnet.port80.se / efnet.portlane.se / irc.teksavvy.ca)

-  **EFnet IRC Servers**
  -  *Round Robins*
    -  *IPv6 Only*
      - irc.ipv6.efnet.org
    -  *IPv4 & IPv6*
      - irc.efnet.org
  -  *Europe*
    - efnet.port80.se (v4 / v6)
    - efnet.portlane.se (v4 / v6)
    - irc.swepipe.se
    - irc.du.se
    - irc.homelien.no (v4 / v6)
    - irc.underworld.no (v4 / v6)
    - irc.efnet.fr
    - irc.inet.tele.dk (v4 / v6)
    - irc.efnet.pl
    - irc.ac.za (v4 / v6)
  -  *USA*
    - *East Coast*
      - irc.teksavvy.ca (v4 / v6)
      - irc.colosolutions.net
      - irc.servercentral.net
      - irc.choopa.net (v4 / v6)
      - irc.eversible.com
      - irc.umich.edu 
      - irc.paraphysics.net (v4 / v6)
    -  *West Coast*
      -  irc.arcti.ca
      - irc.mzima.net
      - irc.Prison.NET

Thanks!
Dan / dubkat

**Comment by DGMurdockIII** [comment]
please fix this in newer versons

**Comment by opcow** [comment]
irc.paraphysics.net doesn't seem to have any ipv6 addresses anymore.
