### ISSUE TITLE
"Looking up %U" upon startup

### ISSUE THREAD

**Issue by AJMJ2012** [hexchat/hexchat#104]
Each time I open HexChat, I get these messages.
- Looking up %U
- Unknown host. Maybe you misspelled it?

As well as this, all servers in the server list flagged to automatically connect on startup will not attempt a connection. It just does nothing.

Sorry if this has been reported before. I did do a search on "%U" and got nothing.

Downloaded from ppa:gwendal-lebihan-dev/hexchat-stable (http://ppa.launchpad.net/gwendal-lebihan-dev/hexchat-stable/ubuntu precise main) via apt-get.

Linux Mint 13 Maya
Linux linuxmint 3.2.0-30-generic #48-Ubuntu SMP Fri Aug 24 16:52:48 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

**Comment by slokhorst** [comment]
I ran into the same issue. I tracked it down to my desktop environment (Openbox), which has trouble parsing `io.github.Hexchat.desktop` when it tries to autostart it on boot. Notably this line:
```
Exec=hexchat --existing %U
```

It doesn't replace (or omit) the `%U` (Openbox uses [pyxdg](https://freedesktop.org/wiki/Software/pyxdg/) for this, which ["Does not check exec parameters"](https://cgit.freedesktop.org/xdg/pyxdg/tree/xdg/DesktopEntry.py)) and instead passes it on to HexChat, which obviously doesn't know what to do with it.

So this is mostly a fault in the program starting HexChat, although HexChat could implement a workaround by ignoring `%U` if it is passed as a command line argument.
