### ISSUE TITLE
Login/identify before auto-joining channels

### ISSUE THREAD

**Issue by garrettw** [hexchat/hexchat#1045]
I would like to see myself logged into NickServ _before_ HexChat starts joining all the channels I have saved.
For example, on Freenode, I would like to auto-join ##php, but that channel only lets registered users join, so currently HexChat joins all of my channels but that one, and _then_ identifies to NickServ, so I have to manually type in /join ##php every time.

**Comment by gim-** [comment]
Links provided by @ghost are dead, here is a new one for those who came here from Google just like me:
https://freenode.net/kb/answer/sasl
