### ISSUE TITLE
Hexchat fails to quit with Python3 enabled.

### ISSUE THREAD

**Issue by ShapeShifter499** [hexchat/hexchat#1065]
Hi,

Hexchat fails to quit for a unknown reason when Python3 is enabled at build. However if built with Python2 Hexchat has no issues.

My system is a Acer Chromebook C710 with a bios mod to run a full OS, ArchLinux.  I have "SysInfo, Python, Do At, Checksum, FiSHLiM" for the .so plugins and "NowPlaying" for the python script  and Hexchat exited just fine until I re-enabled the python.so (py3) plugin.

**Comment by ShapeShifter499** [comment]
No more issues so far, closing.

**Comment by TingPing** [comment]
I have encountered issues with dbus support (which nowplaying uses) causing these issues personally.

**Comment by ShapeShifter499** [comment]
Yea I stopped using the "Now Playing" script I mentioned above. Not using any "Now Playing" script in Hexchat now, I don't have any need for it.

**Comment by e-anima** [comment]
i also use TingPing with the latest hexchat and also have that problem.

**Comment by TingPing** [comment]
For what its worth I have re-written that plugin in Lua which avoids whatever issue python-dbus was having.

https://github.com/TingPing/plugins/blob/master/HexChat/nowplaying.lua
