### ISSUE TITLE
Cannot write czech characters via Caps-Lock

### ISSUE THREAD

**Issue by Grelek** [hexchat/hexchat#1102]
I found bug in chat textbox. When I want to write any of these uppercase czech letters - ĚŠČŘŽÝÁÍÉ - by turning on Caps-Lock and then pressing their key, it writes only lowercase version of them. You can find these letters under the F keys (0-9 keys in US layout).

**Comment by mcepl** [comment]
It would be probably useful to say which OS you are on (I suppose Windows, right)?

**Comment by Grelek** [comment]
Yes, I use HexChat on Windows. (Windows 7 Professional 64bit)

**Comment by TingPing** [comment]
There are many known input issues with Gtk on Windows and there isn't anything HexChat can do about that..
