### ISSUE TITLE
"Unknown host. Maybe you misspelled it?" everytime I start a computer

### ISSUE THREAD

**Issue by ghost** [hexchat/hexchat#1104]
Each time I start my computer and open HexChat, the very same thing happens no matter what version:
- Looking up [any server]?
- Disconnected ()
- Looking up [any server]
- Unknown host. Maybe you misspelled it?

This doesn't go away in any way. Not unless I re-install HexChat which then starts working.

What's the issue here? It didn't use to do this until I first time updated to 2.10 and won't go away when I re-install even the 2.9.4 version

**Comment by erm3nda** [comment]
This happends to me right now for first time. No matter how many times i do reinstall it. Internet is working, dns working. Actually using hexchat-2.12.4-4.

It worked once, so i don't really know what's happening with it.

**Comment by vince94** [comment]
This is happening to me too. I'm trying to connect to #botb 

 Cycling to next server in botb...
* Disconnected ()
* Looking up botb
* Unknown host. Maybe you misspelled it?

**Comment by TingPing** [comment]
> This is happening to me too. I'm trying to connect to #botb

That is a channel not a server. Connect to the network it is on in the network list then join that channel.
