### ISSUE TITLE
Cannot join channel before identification

### ISSUE THREAD

**Issue by fyrak1s** [hexchat/hexchat#1132]
I have recently set up hexchat and immediatly added three channels to autojoin.

The problem is, that only channels 1 and 2 get autojoint, not channel 3. So I have manually accessed channel 3 and tried to set it as autojoin again, but the autojoin checkbox was already set (and itt is in the autojoin list, too)... unsetting and setting it again did not help either.

**Comment by gklimm** [comment]
Autojoin should wait on NICKSERV authentification:
#postgresql-de :Cannot join channel (+r) - you need to be identified with services - see https://freenode.net/kb/answer/registration
I identify with NICKSERV but the autojoin-channel are joined before NICKSERV reply

Perhaps a parameter for waiting a couple of seconds could help?

**Comment by TingPing** [comment]
@gklimm 	*settings > advanced > autojoin delay*...

**Comment by Marenz** [comment]
May I suggest to the issue opener or anyone with according permissions to rename the title of this issue to `Cannot join channel before identification` or something along those lines to make finding this issue easier?
