### ISSUE TITLE
Modifying chanopts for a channel only saves that channel's chanopts to chanopts.conf until shutdown

### ISSUE THREAD

**Issue by xnite** [hexchat/hexchat#1134]
When making changes to client settings (Log channel to disk, beep on message, etc) the settings are not saved unless the client is shutdown cleanly. In other words, if I change a bunch of these settings and then shut down my computer 2 days later these settings are not kept. The current work around is to modify these settings and then shut the client down & reopen it, but these modifications should be stored persistently as soon as they are changed instead of during the exit routine.

**Comment by frowardd** [comment]
Hi, this bug still exists! 2.10.2 64bit, exactly as @Arnavion describes it above.

**Comment by xnite** [comment]
@frowardd I am also still experiencing this issue. No word on if it's being worked on or anything guys?

**Comment by TingPing** [comment]
@xnite There has been one chanopt related fix commited since the last release, but overall no. chanopts are too far broken.

**Comment by xnite** [comment]
@TingPing what about adding a command, a work around for now, to flush the chanopts from memory to disk?

**Comment by xPaw** [comment]
Same bug as #1033

**Comment by Strykar** [comment]
Issue still exists, I inadvertently opened a duplicate at https://github.com/hexchat/hexchat/issues/1597
