### ISSUE TITLE
Hexchat always crash on launch (windows 7 ulti 64bit)

### ISSUE THREAD

**Issue by Reimu08** [hexchat/hexchat#1165]
Hexchat always crash on me when I try to run it. actually it worked fine before but, I had to do a fresh install of windows 7 ever since that this always happen.

```
Problem signature:
  Problem Event Name:   APPCRASH
  Application Name: hexchat.exe
  Application Version:  2.10.1.0
  Application Timestamp:    53d6ab80
  Fault Module Name:    MSVCR120.dll
  Fault Module Version: 12.0.21005.1
  Fault Module Timestamp:   524f83ff
  Exception Code:   c000001d
  Exception Offset: 0000000000098b00
  OS Version:   6.1.7600.2.0.0.256.1
  Locale ID:    1033
  Additional Information 1: adfb
  Additional Information 2: adfb2b69ef457532f955f2bef0ee97a4
  Additional Information 3: 3cd2
  Additional Information 4: 3cd2d9bcba38b62f8d1b54e8a2cbf4b8
```

**Comment by massimilianoh** [comment]
I have the same problem with 64 bit and 32 bit versions. 

  Problem Event Name:	APPCRASH
  Application Name:	hexchat.exe
  Application Version:	2.10.2.0
  Application Timestamp:	5474c5e6
  Fault Module Name:	MSVCR120.dll
  Fault Module Version:	12.0.21005.1
  Fault Module Timestamp:	524f83ff
  Exception Code:	40000015
  Exception Offset:	0000000000074a46
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	dd56
  Additional Information 2:	dd565647958486bd671a4e6945fdca18
  Additional Information 3:	cdac
  Additional Information 4:	cdac18cedc25fd218de83fdd1ebf3aa2
