### ISSUE TITLE
No system tray in Unity

### ISSUE THREAD

**Issue by franleplant** [hexchat/hexchat#1170]
Hi!
     I have recently download HexChat from the [official ppa](https://launchpad.net/~gwendal-lebihan-dev/+archive/ubuntu/hexchat-stable), but I cant find the system tray option nor I can find additional plugins to download it.

Can you please provide help?
Thanks!
Fran

**Comment by Saphyel** [comment]
You can use preferences for install one package from newer or older repository. Tutorial here:
https://wiki.debian.org/AptPreferences#A.2Fetc.2Fapt.2Fpreferences

**Comment by AdnanHodzic** [comment]
hexchat-indicator doesn't work on 16.04. There's no way to put hexchat into system tray.

**Comment by TingPing** [comment]
#1235 is an issue for HexChat supporting it directly.
