### ISSUE TITLE
server_inline should replace invalid utf-8 sequences with replacement character instead of falling back to ISO-8859-1 for the whole line

### ISSUE THREAD

**Issue by rexmadgere** [hexchat/hexchat#1198]
Sometimes text came unreadable
![2014-11-02 00 16 46](https://cloud.githubusercontent.com/assets/9503811/4873317/90956d72-620c-11e4-9f7f-7a1c4227ffb8.png)

**Comment by Arnavion** [comment]
This is fixed now. All text sequences that can't be interpreted as valid in the server encoding will be replaced with the unicode replacement character � as part of the internal conversion to UTF-8.
