### ISSUE TITLE
Python plugin crashes if you try to reload a python script from within itself

### ISSUE THREAD

**Issue by SoniEx2** [hexchat/hexchat#1200]
plugin:
```python
__module_name__="crash"
__module_version__="1.0"
__module_description__="crash"

import hexchat

def crash(word, word_eol, userdata):
    hexchat.command("py reload crash")

hexchat.hook_command("crashreload", crash)
```

just do /crashreload

**Comment by remiscarlet** [comment]
Sorry, but could someone explain what exactly one means by "use a timer"? From what I understand, reloading a plugin via script should be possible assuming it's done via a "timer" but I'm not too sure what that means. Like, "time.sleep(1)"? I'm not sure how that would help, so I'm assuming I'm wrong on that assumption.
