### ISSUE TITLE
Hexchat will not reconnect if proxy is briefly unreachable

### ISSUE THREAD

**Issue by badon** [hexchat/hexchat#1212]
When connecting to an IRC server via a proxy, Hexchat can be configured to auto-reconnect if the connection to the IRC server is lost. However, if the connection to the proxy is lost, Hexchat will not attempt to auto-reconnect. See also:

https://github.com/hexchat/hexchat/issues/475

**Comment by Arnavion** [comment]
Duplicate of #849

This would be fixed by #600 (if ever).
