### ISSUE TITLE
Hexchat crashes after specific commands

### ISSUE THREAD

**Issue by komies** [hexchat/hexchat#1227]
Updated to 2.10.2 to see if this would fix my problem but it did not. Hexchat crashes when attempting to perform some specific types of / commands, most noticeably those related to query and nickserv's issue function. It does not crash when sending a message to a particular service, only when executing particular commands (particularly those that would open a new tab). For example:

no crash: /ns id password 
crash: /ns info username

Crash occurs during both aliased (/ns info) and non-aliased (/msg nickserv info) commands. Also occurs on attempts to /query username. Any ideas towards fixing this would be appreciated! 

On crash the error is simply 'Hexchat has stopped working' and has to be closed.

**Comment by Arnavion** [comment]
If this is still an issue, please reopen and post more info such as OS, any loaded plugins, which network(s) cause the crash, etc.
