### ISSUE TITLE
HexChat isn't correctly forcing new query windows.

### ISSUE THREAD

**Issue by Aiden880** [hexchat/hexchat#1228]
Regardless of:
![image](https://cloud.githubusercontent.com/assets/6422991/5269586/02f36146-7a5c-11e4-808a-813087d707fa.png)

This always happens:
![image](https://cloud.githubusercontent.com/assets/6422991/5269591/0998020e-7a5c-11e4-995f-5f4f911f3164.png)

In a random channel of the network the messages were sent on. I was hoping the upgrade would fix this; it did not.

**Comment by Arnavion** [comment]
Please reopen with above-requested info if this is still an issue.
