### ISSUE TITLE
HexChat doesn't suit OS X Yosemite style

### ISSUE THREAD

**Issue by ircer** [hexchat/hexchat#1248]
Hi

I downloaded HexChat on to my Mac but it looks so dated compared to everything else. The style looks nothing like other Apps.

Is it going to be updated soon? 

Please :-)

**Comment by vmoutoussamy** [comment]
Hi,
don't you have a plan to switch to Gtk3 ? Could this help us for this issue ?
As a heavy user of IRC, I have to admit that hexchat is ugly on Yosemite.
Regards

**Comment by TingPing** [comment]
@vmoutoussamy Gtk3 is a lot better on OSX but it actually 'fits in' less in that there is no Quartz theme though the default theme Adwaita looks good.

As for plans on switching... outlook isn't looking great.

**Comment by ircer** [comment]
:+1: I would £ for this

**Comment by Mikaela** [comment]
> ￼ I would £ for this

https://www.bountysource.com/issues/7265922-hexchat-doesn-t-suit-os-x-yosemite-style

**Comment by Karlheinzniebuhr** [comment]
+1 for this, the font is barely readable :/

**Comment by ircer** [comment]
Is it worth putting a bounty on this, or is it not possible?

**Comment by TingPing** [comment]
It is about as good as it will get.
