### ISSUE TITLE
Can't copy text from IRC [Windows]

### ISSUE THREAD

**Issue by Nentify** [hexchat/hexchat#1259]
I'm using Windows 8.1 and I can no longer copy text from the HexChat client. I have the 'automatically copy selected text' and tried the weird Ctrl +  Shift + C, but to no avail. It worked fine before one of the more recent updates.

**Comment by TingPing** [comment]
> It worked fine before one of the more recent updates.

Specifics help.

So you are saying with auto copy on and you just selecting text and doing nothing else, ctrl+v does not paste anything?

**Comment by Nentify** [comment]
Correct. I can't remember which update in particular though. I think it was the most recent one. If there's a list of old versions somewhere I could try them out. 
On 4 Jan 2015 14:11, TingPing <notifications@github.com> wrote:
It worked fine before one of the more recent updates.


Specifics help.

So you are saying with auto copy on and you just selecting text and doing nothing else, ctrl+v does not paste anything?

**Comment by Mikaela** [comment]
> If there's a list of old versions somewhere I could try them out.

* https://github.com/hexchat/hexchat/releases

**Comment by TingPing** [comment]
@Mikaela more specifically - https://dl.hexchat.net/hexchat/

**Comment by Nentify** [comment]
Hmm, can't copy from any versions. It must be something else causing HexChat to have issues. Thanks anyway!
