### ISSUE TITLE
Error "Download failed"

### ISSUE THREAD

**Issue by HGK-7** [hexchat/hexchat#1264]
http://i2.imageban.ru/out/2015/01/07/548ee157712788173d819d8abb9e1352.jpg
http://i4.imageban.ru/out/2015/01/07/4a262aa33fedc697b72019dd62f450c6.jpg
Status: Cannot connect
Even if various options disabled in the configuration installation, it is still an error

**Comment by TingPing** [comment]
It is trying to download the redist from here: https://dl.hexchat.net/misc/. You can install it manually.

**Comment by HGK-7** [comment]
All set in manually, it's still an this error, useless tries to download vcredist.exe

**Comment by TingPing** [comment]
If properly installed it will not try to download it. There is one for 32 and 64bit.

**Comment by Arnavion** [comment]
As TingPing said, if the redist is already installed then the installer will not try to download it.
