### ISSUE TITLE
Transparent Background feature doesn't work quite like xchat

### ISSUE THREAD

**Issue by Worm4real** [hexchat/hexchat#1270]
When I would use the Transparent Background feature in xchat it would give me a view of whatever my windows wallpaper is, but when I try to enable that feature in hexchat via /set text_transparent nothing happens. Not sure if it's my mistake in assuming these are the same feature or what. http://puu.sh/eCR8b/dd05de0f73.png

**Comment by TingPing** [comment]
Using ```/set``` rarely changes anything instantly. Use the preferences window.

It does behave different though as it is real transparency and it applies to the entire window now.

**Comment by Worm4real** [comment]
Right so the feature is just totally different(or it just worked in some really funky unintended way that I personally liked) from X-Chat? Is there any way to re-implement that as an addon or something like that?

**Comment by TingPing** [comment]
Text area only transparency will come back if #591 is ever merged. The hacky desktop only, per rgb transparency that only worked on like 2 desktops will certainly never return.
