### ISSUE TITLE
Hangs on calling python functions from gi.respository.*

### ISSUE THREAD

**Issue by dbanetto** [hexchat/hexchat#1281]
In the python console, or a python plugin, calling a function that is loaded from a typelib using (at least) `gi.repository` hangs hexchat.

To reproduce

``` python
>>> from gi.repository import Notify
>>> print(Notify)
<gi.module.DynamicModule 'Notify' from '/usr/lib/girepository-1.0/Notify-0.7.typelib'>
```

Importing from `gi.repository` works, however running anything from the modules hangs it

``` python
>>> print(Notify.Notification)
*hangs*
>>> help(Notify)
*hangs*
```

I have tested some of the modules provided by  `gi.repository` with the same result

Hexchat version: 2.10 and master
Python version: 2.7.9 (default, Dec 11 2014, 04:42:00) [GCC 4.9.2]

**Comment by TingPing** [comment]
Slightly off topic but use ```/tray -b``` to make custom notifications, there is no reason to import libnotify.

**Comment by Burrito-Bazooka** [comment]
Discussed some weeks ago in IRC, placed here so that people know. The line at 14:37:15 is the reason it doesn't work.

> D-27 14:18:55 Burrito> TingPing, here's a silly question that I think already the answer is 'no' to, but it's still worth asking: It's not possible to do all that glib business from Python, is it? To get the main thread to do things?
> D-27 14:19:14 Burrito> I mean, gtkwin_ptr looks very encouraging
> D-27 14:19:22 Burrito> but that's probably for other things
> D-27 14:19:37 TingPing> Burrito, sure, `from gi.repository import GLib`
> D-27 14:19:47 Burrito> as soon as I do that, HexChat hangs.
> D-27 14:19:57 Burrito> but that might be my system....
> D-27 14:21:05 Burrito> so I just assumed I was trying something that obviously wasn't possible
> D-27 14:21:20 TingPing> Burrito, hmm it does hang here
> D-27 14:21:20 Burrito> then went down the road of using timers
> D-27 14:21:40 TingPing> Burrito, would have to debug it further, it certainly isn't a technical limitation
> D-27 14:21:41 Burrito> and assumed that when you suggested to use GLib everywhere, you meant from C.
> D-27 14:22:48 Burrito> if I do '/py exec from gi.repository import GLib', the hang starts before the message even disappears from the inputbox
> **D-27 14:37:15 TingPing> "Python supports the creation of additional interpreters (using Py_NewInterpreter()), but mixing multiple interpreters and the PyGILState_*() API is unsupported."**
> D-27 14:37:22 TingPing> Burrito, hmm, that might be the problem ^
> D-27 14:37:38 TingPing> **gobject-introspection uses the PyGILState API**
> D-27 14:37:44 TingPing> **hexchat uses multiple interpreters**
> [irrelevant stuff]
> D-27 14:44:20 TingPing> Burrito, real shame, guess you'll just need to use another language like C or Lua
> D-27 14:44:38 Burrito> okay :c
> D-27 14:44:48 Burrito> I'm gonna use timers for this.
> D-27 14:45:06 Burrito> (and look at lua)
> D-27 14:45:11 TingPing> that ofc doesn't make the behavior any more defined

The moderately good news is people have taken note on the CPython project. I think:

* https://bugs.python.org/issue10915
* https://bugs.python.org/issue15751

**Comment by TingPing** [comment]
This was fixed in master.
