### ISSUE TITLE
Pushing new updates through chatwindow is susceptible to spoofing attacks

### ISSUE THREAD

**Issue by nidalR** [hexchat/hexchat#1282]
Currently, new updates are pushed through the chat window with a message from "Update Checker" containing the url for downloading a new update.

A user could be tricked by a malicious bot with the name "Update checker" or something similar into downloading and executing a binary file masquerading as the latest version of hexchat. The current practice of  pushing updates via the chat window encourages or conditions this user behaviour.

Solution would be to give a seperate dialog box or pop-up for update notifications

**Comment by TingPing** [comment]
It looks absolutely nothing like a normal message.. but I am for this for entirely different reasons. 

See https://github.com/hexchat/hexchat/tree/updater

**Comment by nidalR** [comment]
Well there are subtle differences but I wouldn't say "It looks absolutely nothing like a normal message". It is the differences are small enough that an unsuspecting user could be fooled. Also there are certain scenarios where old user messages have the same color scheme as the update checker. See the screenshot below : 
![hexchat bug report](https://cloud.githubusercontent.com/assets/1751316/6058276/cbe8338e-ad4b-11e4-8c7a-8f0aa8cacdef.png)

**Comment by TingPing** [comment]
Actually you are right, that is really close.
