### ISSUE TITLE
Single-character nicks don't highlight properly

### ISSUE THREAD

**Issue by 2mac** [hexchat/hexchat#1283]
When a user with a single-character nick mentions me, it is not highlighted. Version 2.10.1

Since this is a very strange issue that's probably hard to pin down, I'll also mention the detail that the single character is a capital Q.

**Comment by Fironet** [comment]
This isn't the case, single characters are fine. Q is ignored as the default settings are set to not highlight from typical network nicks such as Q, N, NickServ, etc. See *Preferences>Alerts>'Nick names not to highlight'* to change this if you like.
