### ISSUE TITLE
Add support for inline images (like Textual)

### ISSUE THREAD

**Issue by KC9YDN** [hexchat/hexchat#1285]

**Comment by umpc** [comment]
I would definitely use this. It's quickly becoming an unofficial standard of many modern clients.

**Comment by TingPing** [comment]
This will never happen. xtext (what we use to display text) is quite customized to displaying only text and it already does this poorly.

**Comment by KC9YDN** [comment]
If xtext is so bad, it's probably time to switch to something else.

**Comment by Arnavion** [comment]
Feel free to submit a patch with a replacement.

**Comment by KC9YDN** [comment]
Will you like that by 10pm UTC tomorrow?

**Comment by Arnavion** [comment]
It's the only way you'll get what you want, so it's up to you when you want to submit it.

**Comment by KC9YDN** [comment]
The thing is that normally developers strive to make their software the
very best.

On Thu, Feb 5, 2015 at 9:47 PM, Arnav Singh <notifications@github.com>
wrote:

> It's the only way you'll get what you want, so it's up to you when you
> want to submit it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hexchat/hexchat/issues/1285#issuecomment-73174443>.
>



-- 
*Ethan Best*

**Comment by TingPing** [comment]
@KC9YDN It is quite the technical challenge to replicate *all* behaviors of the current widget using something like a GtkTextView which supports images. You can't just guilt that into existence.

**Comment by astauffer** [comment]
@KC9YDN I switched over to Komanda for the inline images.

**Comment by Vastrix** [comment]
![;(](http://images-cdn.moviepilot.com/images/c_fill,h_300,w_500/t_mp_quality_gif/fehyydmkkgxyoijkhzoh/5-tear-jerker-moments-from-inside-out-so-much-sadness-468663.gif)

**Comment by KC9YDN** [comment]
@Vastrix, This is very old and the developers will not care what you have to say.

**Comment by Avamander** [comment]
But like, is this at least planned? I think if you'd at least add the ability to show images in the text box with a python plugin people would implement the rest themselves.

**Comment by Arnavion** [comment]
@Avamander You say that like "the ability to show images in the text box" is not the exact same thing that TingPing said above is impossible with xtext.

**Comment by Avamander** [comment]
@Arnavion Is there an issue open about supporting displaying images/video in the chat field? I searched but found only this.
