### ISSUE TITLE
Autocomplete channel name

### ISSUE THREAD

**Issue by s1390** [hexchat/hexchat#1286]
It would be nice if you could autocomplete a channel name as well, like you can with a nickname. So doing `#h` + `tab`, would give you: `#hexchat`.

**Comment by TingPing** [comment]
You already can.

**Comment by s1390** [comment]
Thanks for your reply, @TingPing. 
Could you please tell me how to? Pressing Tab after a #, won't work at all. I'm on Windows 7, and I asked a few guys with Linux the same question, and they aren't able to make it work either. We are all on the latest version.

**Comment by TingPing** [comment]
It works the exact same as nicks. So does typing a few more chars allow it to complete? To change this behavior see *Preferences > Input box > Nick completion amount*.

**Comment by s1390** [comment]
Thank you.
