### ISSUE TITLE
--disable-nls is ignored

### ISSUE THREAD

**Issue by LeoUnglaub** [hexchat/hexchat#1300]
Hey,
i am the Hexchat maintainer on Crux-Linux and noticed that even if compiled with `--disable-nls` the summary prints the following:

```
HexChat 2.10.2

GTK+ interface ........ : yes
Text interface ........ : no
Theme manager ......... : no

OpenSSL support ....... : yes
D-Bus support ......... : no
libnotify support ..... : yes
libcanberra support ... : no
Plugin interface ...... : yes
NLS/gettext ........... : yes
IPv6 support .......... : yes
MS Proxy NTLM (ISA) ... : no
libproxy support ...... : no

Perl .................. : no
Python ................ : no

Checksum .............. : yes
Do At ................. : no
FiSHLiM ............... : no
SysInfo ............... : no
```

Thanks and grretings
Leo

**Comment by TingPing** [comment]
Yes, it is not possible to disable NLS and this is on purpose. The `--disable-nls` flag is not added by us but by some m4 files we import. We could modify that and ship our own but I don't think that is necessary.

**Comment by TingPing** [comment]
To clarify it is not our choice but glib/gtk have a hard dep on it and I see little reason to work around that.

https://github.com/GNOME/glib/blob/71642ce766d73bb06f2cd33b4f585bafff315c7d/m4macros/glib-gettext.m4#L103

**Comment by TingPing** [comment]
See also: https://github.com/hexchat/hexchat/commit/c3c6b46230df853b51b0979c1c5a561517b000a0
