### ISSUE TITLE
GPL does not need to be agreed to in the installer

### ISSUE THREAD

**Issue by themusicgod1** [hexchat/hexchat#1301]
You are not required to agree to anything to merely use software which is licensed under the GPL.  It is an unnecessary restriction and gives users the wrong idea about what the GPL is.

https://www.gnu.org/philosophy/free-sw.html

**Comment by TingPing** [comment]
Should the license still be shown even if users don't need to agree to it?

**Comment by themusicgod1** [comment]
It doesn't have to be shown in full but I think it requires you to make mention that it can be shown if needed.

from the GPL:

> c) If the modified program normally reads commands interactively when run, you must cause it, when started running for such interactive use in the most ordinary way, to print or display an announcement including an appropriate copyright notice and a notice that there is no warranty (or else, saying that you provide a warranty) and that users may redistribute the program under these conditions, and telling the user how to view a copy of this License. (Exception: if the Program itself is interactive but does not normally print such an announcement, your work based on the Program is not required to print an announcement.)

**Comment by TingPing** [comment]
*Help > About > License* shows the license.

**Comment by Arnavion** [comment]
```irc
<Arnavion> >5. You are not required to accept this License, since you have not signed it. However, nothing else grants you permission to modify or distribute the Program or its derivative works. These actions are prohibited by law if you do not accept this License. Therefore, by modifying or distributing the Program (or any work based on the Program), you indicate your acceptance of this License to do so, and all its terms and conditions for copying, distributing or modifying the Program or works based on it.
<Arnavion>  
<Arnavion> Okay, well that makes it simple then

<Arnavion> Then again, there's also this in the FAQ   http://www.gnu.org/licenses/gpl-faq.html#ClickThrough
<Arnavion> >Some software packaging systems have a place which requires you to click through or otherwise indicate assent to the terms of the GPL. This is neither required nor forbidden. With or without a click through, the GPL's rules remain the same.
<Arnavion> >Merely agreeing to the GPL doesn't place any obligations on you. You are not required to agree to anything to merely use software which is licensed under the GPL. You only have obligations if you modify or distribute the software. If it really bothers you to click through the GPL, nothing stops you from hacking the GPLed software to bypass this.
<Arnavion> So basically even if you click Agree you're legally allowed to not agree to it unless you want to redistribute it

<Arnavion> Then again there's   http://tortoisesvn.tigris.org/ds/viewMessage.do?dsForumId=757&dsMessageId=2712850
<Arnavion> tl;dr "I agree" is maybe required for the No Warranty to apply
```

So:
1. Clicking "Agree" doesn't legally mean you agree to it.
1. Even if you don't agree to it, you legally implicitly agree to it if you redistribute HC.
1. Clicking "Agree" may or may not be required in a court of law to consider that you accepted we gave you no warranty for using HC.

**Comment by Stanzilla** [comment]
Make the agree button say "next" instead and all is good? :P

**Comment by Arnavion** [comment]
@Stanzilla You didn't read (3)

**Comment by Stanzilla** [comment]
Well ok :(
