### ISSUE TITLE
Make nickname autocompletion aware of the active chatters

### ISSUE THREAD

**Issue by Atilla** [hexchat/hexchat#1305]
Nickname autocompletion is one of the most useful things in the client, to the point of creating a mechanical habit of pressing the <tab> button. 

With a number of similar nicknames, this habit can often result in frequently referring to the wrong person, simply because their name happens to be first in alphabetical order. Keeping a small most-recently-chatted list per channel and using this to prioritize the completions can alleviate this problem to a good extent.

**Comment by bendem** [comment]
You can set the autocomplete sorting to `Last spoke order` in `Prefs > Input Box > Nick completion sorted` to do just that.

**Comment by Atilla** [comment]
And do I feel silly now... Thanks a bunch.
