### ISSUE TITLE
Howto: Prevent failure to find idp.iss when ISC is building a release install exe

### ISSUE THREAD

**Issue by JackTandy** [hexchat/hexchat#1311]
The Inno Download Plugin is included in hexchat.iss but there is no dir defined for this external include.

Therefore, the build process can fail to find and include idp.iss which results in error exit.

Solution: Locate where the IDP is installed and add its path to the top of hexchat.iss.tt like in the following example...
```
#pragma include __INCLUDE__ + ";C:\Program Files (x86)\Inno Download Plugin"
```

and all will be well again.

**Comment by TingPing** [comment]
The IDP installer has an option to globally include it.

**Comment by JackTandy** [comment]
Not from a fresh install and from the link you present on your pages, there is NO option

**Comment by TingPing** [comment]
I was not aware that the main installer had an option for it. Eitherway that does not matter, our docs link to an idp installer and this installer has this option (I believe by default).

**Comment by TingPing** [comment]
Upon testing the main inno installer does not bundle IDP at all.
