### ISSUE TITLE
Emoji Support

### ISSUE THREAD

**Issue by Dium** [hexchat/hexchat#1314]
I have the default alternative fonts in addition to me adding Segoi UI Symbol to view emojis, but I use Consolas as the main font.

I am not able to view emojis in Hexchat as of yet or still.

**Comment by TingPing** [comment]
Have you read http://hexchat.readthedocs.org/en/latest/tips.html#special-glyphs ?

Installing and enabling the fonts listed should cover most symbols.

**Comment by Dium** [comment]
I have, but I don't really understand playing around a little with the alternative fonts. I have the fonts installed but it still doesn't work. I'll have to try more again later.



On Wed, Mar 11, 2015 at 1:54 PM -0700, "TingPing" <notifications@github.com> wrote:
Have you read http://hexchat.readthedocs.org/en/latest/tips.html#special-glyphs ?

Installing and enabling the fonts listed should cover most symbols.

---

**Comment by Flashynuff** [comment]
Hey, try installing Android Emoji and adding that to your alternative fonts. You can find it here: https://android.googlesource.com/platform/frameworks/base.git/+/jb-release/data/fonts/AndroidEmoji.ttf

Works perfectly with just about every emoji I've seen, though the emojis are really small.

**Comment by Dium** [comment]
It's telling me that it's not a valid font file.

**Comment by TingPing** [comment]
Did you add it in the Alternate fonts setting **not** the main font?

**Comment by Dium** [comment]
I mean that I can't install it.

**Comment by tomek** [comment]
that link is wrong as it points to git log...

@Dium you should try adding "segoe ui emoji" to alternative font list, it should cover most of the glyphs

**Comment by Dium** [comment]
Yeah, I added Segoe UI Symbol to my list a while ago and it shows some now, but not all.

**Comment by tomek** [comment]
"segoe ui emoji" is a different font than "segoe ui symbol"

**Comment by Dium** [comment]
My bad. I did try that at one point but nothing happened. I assumed Microsoft included this font in Windows, but that isn't the case.

I've just obtained Segoe UI Emoji so I'll try that out.

**Comment by Dium** [comment]
Segoe UI Emoji seems to do the trick. Thanks, tomek.

**Comment by Arnavion** [comment]
It's included with Windows starting from 8.1

**Comment by Dium** [comment]
Oh I see. I upgraded to 8.1 from 8, so that must be why.

**Comment by Flashynuff** [comment]
"It's telling me that it's not a valid font file."

Hmm, yeah, you're right. That only seems to happen when I download the specific file. If I download the whole fonts directory and install it from there, it works fine. Weird
