### ISSUE TITLE
Wrong ZNC-buffer playback timestamps in FiSHLiM encrypted channels

### ISSUE THREAD

**Issue by iyx** [hexchat/hexchat#1319]
I'm not sure how server-time feature works exactly and if time-stamps are themselves crypted when using FiSHLiM, but time (timestamps) of connection is used for all buffered messages.

Before, in client without server-time capability, I have had timestamps appended in messages, using 'Append Timestamps' setting in ZNC configuration (instead of 'Prepend Timestamps', in order to get messages decrypted by FiSHLiM on buffer playback). 

With HexChat using server-time it seem not to matter whether I use Prepend or Append (or neither) in ZNC config, timestamps will not be prepended or appended to the message. Problem is that with wrong timestamps displayed, I have no way of knowing real timestamps this way..

**Comment by TingPing** [comment]
Fixed in https://github.com/hexchat/hexchat/commit/addefa9ef139af1d3a910336d471637a53d15502

You can get a development build here: https://dl.hexchat.net/hexchat/testing/
