### ISSUE TITLE
What unit of measure is the net_ping_timeout setting in

### ISSUE THREAD

**Issue by gene1wood** [hexchat/hexchat#1322]
[The Hexchat FAQ](http://hexchat.readthedocs.org/en/latest/faq.html#how-do-i-auto-reconnect-after-my-computer-wakes-up-from-being-in-sleep-hibernate-mode)  recommends using the `net_ping_timeout` setting.

It appears that the comparison is done between the response from the IRC server to the `PING` command and `time(0)`

https://github.com/hexchat/hexchat/blob/98fefcd162368cd3f7122a66a43d6248fb2ef29a/src/common/hexchat.c#L270

Is this milliseconds? Seconds?

I'll submit a PR to the documentation once this is known to add clarification to that FAQ item.

**Comment by Arnavion** [comment]
`time()` returns time in seconds.

**Comment by gene1wood** [comment]
Thanks! This is fixed in hexchat/documentation@dfb06ff
