### ISSUE TITLE
Add btrIRC to network list

### ISSUE THREAD

**Issue by AlphaT3ch** [hexchat/hexchat#1324]
Hello! I’m AlphaTech, an administrator of btrIRC. I was wondering if you could list our network on HexChat. Here’s our info

Server Site: http://btri.x10.bz
Server #1: irc.btri.x10.bz
Server #2: btrirc.zapto.org
Connection Ports: 6665, 6666, 6667, 7000 and 7070
SSL Ports: 6697, 8000, 8001 and 8002
Administrator: AlphaTech
Main Channel: #btri
My Email: alphatech@btri.x10.bz

**Comment by TingPing** [comment]
> Server Site: http://btri.x10.bz

```
You have been permanently banned from this board
Attempting to get around this in any way will result in worse things.

Reason: 
```

Off to a good start.

**Comment by AlphaT3ch** [comment]
I don't know about that; You shouldn't be banned unless you spammed us. We've banned a couple proxies also.

**Comment by AlphaT3ch** [comment]
We've resolved this issue and now hopefully can be featured in the networks list.

**Comment by TingPing** [comment]
Ok, I usually just update the network list before new releases.

**Comment by AlphaT3ch** [comment]
Okay, thank you so much!

**Comment by TingPing** [comment]
Seems the server didn't even last a year...
