### ISSUE TITLE
Bantype *!*@*domain

### ISSUE THREAD

**Issue by Mikaela** [hexchat/hexchat#1329]
Additinal bantype `*!*@*domain` would be useful in some situations like freenode's webchats.

* `*!*@IP` bans normal clients and WebChat
* `*!*@*IP` bans normal clients and KiwiIRC

Of course it's possible to set those bans manually, but it would be nice if HexChat could ban like that directly even if it's useful only with users who don't have reverse DNS.

**Comment by TingPing** [comment]
Looks like it already is - https://github.com/hexchat/hexchat/blob/master/src/common/outbound.c#L504

**Comment by Mikaela** [comment]
Oh, it's probably in git then. The one that I used is 2.10.2-1.

**Comment by TingPing** [comment]
Its probably been there for 10 years. If its not in the GUI just manually add it.

**Comment by TingPing** [comment]
(after checking it is in the default menu popup, but maybe not in yours though)

**Comment by Mikaela** [comment]
In the GUI menu I see:

```
*!*@*.host
*!*@domain
*!user@*.host
*!*user@domain
```

I also don't see any option for setting custom one.

**Comment by TingPing** [comment]
Ah it is just not very clear on how it handles IPs vs domains. The code I linked shows that for the first option if it is not an IP address it uses `*!*@*DOMAIN`.

**Comment by Mikaela** [comment]
So if I ban someone from 127.0.0.1 with it `*!*@*127.0.0.1` gets banned?

Thanks, I will use it.

**Comment by TingPing** [comment]
> So if I ban someone from 127.0.0.1 with it *!*@*127.0.0.1 gets banned?

No. If it is an IP it does `*!*@*.IP` as it shows.

You can hardcode an option for `*!*@*%h` if you want.

**Comment by Mikaela** [comment]
Confusng. I will do that hardcoding now and I also updated the issue too be more clear in case option like that is possible.
