### ISSUE TITLE
Crash after failed attempt to open log file

### ISSUE THREAD

**Issue by jobe1986** [hexchat/hexchat#1331]
OS: Windows 7 64bit
HexChat Version: 2.10.2

Basically it appears if logging is enabled and you do something that results in a new log file being created, if the new file cannot be created then hexchat crashes. In this case it was because the channel name was 200 chars long and the file system said the full path to the file was too long. Confirmed it was log opening that caused it by disabling logging and again joining the same channel name this time with no crash.

Sorry if this has already been reported and dealt with, I was unable to find an open or closed issue similar to this.

**Comment by Arnavion** [comment]
Fixed by https://github.com/hexchat/hexchat/commit/1d31671
