### ISSUE TITLE
Is there a way to utilize desktop notification (OSD)?

### ISSUE THREAD

**Issue by shouya** [hexchat/hexchat#1332]
For now hexchat has these built-in alert fashions:

* beeping
* blinking tray icon
* blinking status bar

I think desktop notification would be helpful as well. Since with which I will have less chance to miss important messages without having to peek at the tray area frequently. 

I didn't find such an option in the systems, is there such a way to utilize, e.g. a plugin? Or any plan to add this functionality? Thanks :)

**Comment by TingPing** [comment]
On what OS?

**Comment by shouya** [comment]
Sorry for missing that piece of info. I am on gentoo linux + xmonad.

**Comment by TingPing** [comment]
HexChat on linux has always supported notifications via libnotify. Build it with it and it will be in alerts.

**Comment by shouya** [comment]
Okay I'll check it up. Thank you.
