### ISSUE TITLE
Highlight an IRCop with special color.

### ISSUE THREAD

**Issue by Glossow** [hexchat/hexchat#1335]
Hello.
I want to make a suggestion for you to make it possible to highlight an IRCop with special color.
There is a possibility in HexChat to highlight users by special color who are "afk" at the moment.
There should be this possibility because if you will make a /whois ircop there will be an announcement *** user (~user@IP) did a /whois on you. There is no other way to see ircop. By the way there is this kind of opportunity/possibility to highlight by special color IRCop in KVIrc.

**Comment by TingPing** [comment]
https://github.com/TingPing/plugins/blob/master/HexChat/statuscolor.py

**Comment by Glossow** [comment]
You know what IRC Server Operator? And I mean the list of users.

**Comment by TingPing** [comment]
If the network doesn't give the oper a prefix then its a huge PITA to try and get that information.

**Comment by Mikaela** [comment]
The information might be in who, but I would be against using who-polling for that as away-notify finally kills it.

**Comment by TingPing** [comment]
Anyway sorry for closing this prematurely but eitherway this belongs in a script not in the core of HexChat imo. It is very network specific and likely uncommon.

**Comment by Glossow** [comment]
I use KVIrc 4 years. He correctly defines this parameter.

**Comment by wowaname** [comment]
/who gives operator status in the ninth field along with here/gone and channel op prefix.
