### ISSUE TITLE
dl.hexchat.net is completely inaccessible to users of Opera & Windows XP

### ISSUE THREAD

**Issue by Orvid** [hexchat/hexchat#1336]
So, I went to update my install of HexChat and found out that yet another site has fallen victim to the complete BS of CloudFlair's free SSL certificates.

Due to the use of ECDSA as the signature algorithm in the certificate, it is impossible for anyone using Opera Classic (12.17 & below) to connect to a server using one of these certificates. In the first example [here](https://community.centminmod.com/threads/cloudflare-universal-ssl-incompatible-with-winxp-internet-explorer-8-browsers.1577/) It doesn't actually realize this, but Opera classic does not support ECDSA regardless of the OS. This means that, in the first example, just over *7.5%* of the users of the site would no longer be able to connect if the only certificate available is ECDSA.

This is completely contrary to CloudFlare's claim, and continued assertion that Opera 8 is the minimum required version, even though they have been aware since October of last year that it does NOT work in Opera 8. This is because they have for some absurd reason decided that SNI is enough to handle support for older browsers, and, while, if you have OTHER certificates that are signed with older algorithms, that is true, Universal SSL does not provide any other certificates, rendering any site using their certificate complete inaccessible to users of older browsers.

For users of Opera Classic, we cannot connect at all, because SSL is being forced on the site.

There are other free SSL services out there that ARE actually compatible with older browsers, https://www.startssl.com/ being the one I usually use.

As a last note, sorry if this reads a bit like a rant, but I'm just a bit annoyed.

**Comment by Mikaela** [comment]
I believe this bug report is invalid as Windows XP went EOL 2014-04-08 and the latest version of Opera is 28.0.1750.48 **not** 12.17. You endanger your security by using EOL OS and browser, so you might want to upgrade as soon as possible.

If you are using old version of Opera because of the removed features like email, you might be interested in [Vivaldi](https://vivaldi.com/)

**Comment by TingPing** [comment]
If users cannot securely access our site then they should upgrade.

**Comment by Orvid** [comment]
There is a *lot* more than email that is removed in non-classic opera. There is a reason 12.17 claims it is up-to-date. I don't use opera for email, I use it for it's absurd number of other features.
 Opera 12.17 uses the Presto rendering engine, which uses significantly less memory than either webkit or gecko. (it's currently sitting at 1.5gb of memory) The non-classic version of opera uses webkit, which means 1 process per tab plus a few extra. This is a major problem for me because I _always_ have the task manager open to the process list on my second monitor, and I have ~45 tabs open in Opera at any one time, spread across 4 windows. I currently have about 100 processes running, using any browser based on webkit (including Vivaldi), would result in 150 processes, which is not in any way acceptable to me. 

Quite a few of the user scripts I use actively use functionality that simply is not available in other browsers, and only exist in opera because they were needed to be able to patch the functionality of sites that failed at browser-sniffing Opera.

Opera classic is the end of a product line, yes, but it is still supported in the same way any LTS release is supported, via security updates.

**Comment by TingPing** [comment]
If it is still supported then you should bother them about supporting modern TLS and ciphers.
