### ISSUE TITLE
Unicode issues with maximum length raw messages

### ISSUE THREAD

**Issue by Lunatrius** [hexchat/hexchat#1337]
shout 0.50.0
![](http://puu.sh/gSWNS/5fa6c82038.png)

HexChat 2.10.1
![](http://puu.sh/gSXjW.png)

Same message posted in a channel with a shorter channel name (the unicode characters aren't cut off)
![](http://puu.sh/gSXyv.png)

A shorter message that contains a cut off unicode character
![](http://puu.sh/gSXBz.png)

**Comment by TingPing** [comment]
Well it sure is better than previous versions!

**Comment by TingPing** [comment]
Oh I realize now that the first image is a different client. Update HexChat to the test build and this is fixed.
