### ISSUE TITLE
/DCC send command kills connection to server

### ISSUE THREAD

**Issue by edison23** [hexchat/hexchat#1340]
When I use `/dcc send <nick> <file>` it instantly kills connection to server (Hexchat doesnt recognize that and behaves similiarly as if I'd turned wifi off or something, just times out after some time).

**Comment by TingPing** [comment]
OS?

**Comment by edison23** [comment]
Ubuntu 14.04 LTS
HexChat 2.10.2

**Comment by edison23** [comment]
Ok, never mind, just happend to me with another client, so it's obviously not a hexchat related problem. I'm clueless though. Sorry for bothering you.

**Comment by TingPing** [comment]
Some terrible routers try do automatically do things when they detect DCC and fail.

**Comment by edison23** [comment]
thanks, I'll try to investigate that direction
