### ISSUE TITLE
DCC send multiple files

### ISSUE THREAD

**Issue by edison23** [hexchat/hexchat#1341]
When selecting more files to send, Hexchat opens multiple connections (each for one file) rather than queue the files and use one connection. This makes sending multiple files at once virtually impossible.

**Comment by TingPing** [comment]
Thats not how the DCC spec works.

**Comment by edison23** [comment]
ok, good to know, but - couldnt hexchat internally make sending the dcc commands sequential rather than paralel? would be very handy

**Comment by TingPing** [comment]
Well one option is to just not start multiple until you want them running.

**Comment by edison23** [comment]
well when you have 20 files 300 MB each and upload speed around 400 kb/s,
then this option is not really feasible.
