### ISSUE TITLE
Add 'Mark all read' feature

### ISSUE THREAD

**Issue by cindyker** [hexchat/hexchat#1342]
If you get a play back in most if not all of your channels all the channels will show that you have unread messages.. 
These are messages that in most cases I have already read, this causes me to have to click on each channel to clear the channel color to show true new messages.

A menu option that would just clear the new/unread messages from all channels would be awesome.

**Comment by TingPing** [comment]
A simple workaround is `allchan gui color 0`

**Comment by Farow** [comment]
And you can also add your own alias for that under `Settings -> User Commands`.

**Comment by Starhowl** [comment]
What does `/allchan gui color 0` do? Where is it documented? Is it a permanent setting and in case of _yes_, how to reset it to the original settings?

**Comment by DasBrain** [comment]
`/allchan` - executes a command in every channel. See `/help allchan`.
`/gui color 0` - changes the color of the current tab to all read. See `/help gui`.
