### ISSUE TITLE
Mode Button 'm' gets truncated

### ISSUE THREAD

**Issue by RichardHitt** [hexchat/hexchat#1354]
When mode buttons are displayed on a channel window the moderated-flag letter 'm' gets truncated.  In the attached image, channel #rbhtest2 shows the erroneous behavior and channel #rbhtest shows the corrected behavior.
![screenshot - 04212015 - 11 01 08 am](https://cloud.githubusercontent.com/assets/2191928/7259201/935879d8-e816-11e4-863e-2d31609fe591.png)

Notice that in the corrected window each letter's box width is proportional to its character width,  the default behavior for gtk_toggle_button_new_with_label().  In mg_create_flagbutton() the statement after it, gtk_widget_set_size_request(), causes the error by being too small for an 'm', and should be removed.  PULL request coming up.

**Comment by TingPing** [comment]
I think it looks cleaner when they are all the same size, that would mean finding the widest one and setting them all that size.
