### ISSUE TITLE
Client does not allow joining Channels that do not start with the '#'-prefix

### ISSUE THREAD

**Issue by skeleten** [hexchat/hexchat#1359]
HexChat version 2.10.1 on Windows 10.0.10041 (Preview)

According to the [RFC 2812](https://tools.ietf.org/html/rfc2812) [Section 1.3](https://tools.ietf.org/html/rfc2812#section-1.3), a  Channel may start with a prefix of &, #, +, !.
The HexChat client currently does ignore any attempt to connect to any channel that does not start with the #-prefix. While this covers almost all channels that should still be in use, any other channels are not accessible through the use of HexChat.

**Comment by TingPing** [comment]
It respects the prefixes the network claims to support. Do you have an example of a network where this is not true?

**Comment by Mikaela** [comment]
Works for me on IRCnet, `CHANTYPES=#&!+`.

**Comment by skeleten** [comment]
Seems like this was an mistake on my side, about the server configuration of the network I was using. Sorry for the false positive
