### ISSUE TITLE
HexChat crashes if sufficient Microsoft IME input is provided into an edit box containing certain WYSIWYG control code characters

### ISSUE THREAD

**Issue by StepS-** [hexchat/hexchat#1360]
Steps to reproduce:
- Add a Japanese IME to the system, but don't toggle it on yet
- In the text message input field of HexChat, right-click -> Input Methods -> Microsoft IME
- Make sure that "Render colors and attributes" in preferences is enabled.
- Into the input field, insert a whitespace, then the Bold control-code character (with Ctrl+B).
- Move the caret back to the beginning of the input field.
- Toggle the IME on and switch into an input mode that isn't "halfwidth alphanumeric" (e.g., with Alt+~ or by using the tray button).
- Start typing text with the IME.
  + On Windows 8.1, some corrupted characters (crosses inside rectangles) will show up, and a certain amount of button presses will lead to a crash.
  + On Windows 7, the crash upon trying to type with the IME is instant.

Video of the issue (Win7): https://www.youtube.com/watch?v=7Xm7DqGg1IA
Running Windows 8.1 x64 with 64-bit HexChat 2.10.2.

**Comment by TingPing** [comment]
So bold (or other attributes) is required? What is *preferences > input render attributes* set to?

**Comment by StepS-** [comment]
Yes, Bold has to be present in the input field, prefixed with a whitespace. The IME typing has to occur to the left side from that whitespace.
![image](https://cloud.githubusercontent.com/assets/5569139/7330009/c97e09ac-eaef-11e4-9bef-772579e3bb61.png)

**Comment by TingPing** [comment]
@StepS- Try it with that setting off.

**Comment by StepS-** [comment]
With "Render colors and attributes" off, the issue doesn't happen.
On my Windows 7 VM, the crash upon inputting with IME is instant (Windows 8.1 allowed me to input some broken characters before crashing).
Here's the video of the issue: https://www.youtube.com/watch?v=7Xm7DqGg1IA

**Comment by TingPing** [comment]
@StepS- One last test, turn off the render colors, but turn on spell check (ensuring that it works).

**Comment by Arnavion** [comment]
Can repro. Note that just enabling IME mode is not enough - it defaults to normal-width English chars which don't have the bug. I had to also switch to hiragana mode.

**Comment by StepS-** [comment]
> @StepS- One last test, turn off the render colors, but turn on spell check (ensuring that it works).
The crash doesn't happen, however I was able to produce those weird corrupted crosses-in-boxes by typing randomly and pressing space several times during typing (and continuing typing). They didn't lead to a crash on my Win7 VM.
![image](https://cloud.githubusercontent.com/assets/5569139/7330360/f155d116-eaf5-11e4-93d0-0898ef983712.png)

> Can repro. Note that just enabling IME mode is not enough - it defaults to normal-width English chars which don't have the bug. I had to also switch to hiragana mode.
Yeah, that was what I meant. Edited the first post (and added a video).

**Comment by Arnavion** [comment]
I'm unable to make it crash on 32-bit HC, and another person who can repro the glyphs (with Google's IME) is also unable to make it crash. Are you using 32-bit or 64-bit HC?

The glyphs only come up when the word is undecided, so if you continue to type until the IME decides to fix the word (leave it as kana or replace with kanji) the glyphs will go away.

**Comment by StepS-** [comment]
64-bit HexChat

**Comment by Arnavion** [comment]
I've not been able to get it to crash on either 32-bit HC or 64-bit, but I did trace the glyphs problem to pango's handling of attributes for pre-edit text in the GtkEntry widget. Try the build here - https://dl.hexchat.net/hexchat/testing/arnavion/HexChat%202.11.0%20x86.exe

This will disable rendering attributes while the textbox contains pre-edit text. As soon you press space / enter to finalize the characters, the attributes will be restored.

**Comment by StepS-** [comment]
For some reason, this build crashes immediately upon trying to create the main window (either when I press Connect in the list of networks, or if I enable "Skip network list on startup")

**Comment by Arnavion** [comment]
You must have something else that's causing the crashes. Use a clean config. (Rename %APPDATA%\HexChat to something else.)

**Comment by StepS-** [comment]
As said above, it was already using a clean config since I had installed it in "portable mode".

**Comment by StepS-** [comment]
Ok, found the reason of the startup crash. After looking at the stack trace from the minidump, I spotted a reference to libenchant.dll, which was the spellcheck library. I then checked my `%LOCALAPPDATA%\enchant` directory and found that it contained outdated (so probably no longer supported) spellcheck files, and even the portable build accessed that directory (and had spellcheck on by default). Deleting it fixed the crash.
Tested, and the IME crash no longer occurs, neither do the glyphs (same in my Win7 VM). So this issue can be closed. ありがとうございました！ :smile:

**Comment by TingPing** [comment]
What languages do you have enabled for spell check? The dictionaries we ship are a bit old at this point but that shouldn't cause a crash ofc.

**Comment by StepS-** [comment]
I don't use spell check in my main installation. And in the default config file (portable installation) I imagine it's set to "en_US".

**Comment by TingPing** [comment]
> edit: It'd be great to be able to redefine the path for dictionaries in the portable version, as that's what might happen when the app is not "fully portable".

The docs are pretty clear where they go for portable installs: http://hexchat.readthedocs.org/en/latest/tips.html#spell-check

Anyway I suspect it has absolutely nothing to do with the dictionaries but the exact same rendering crash you have both bold.

**Comment by StepS-** [comment]
>The docs are pretty clear where they go for portable installs

Thanks for that link!

>Anyway I suspect it has absolutely nothing to do with the dictionaries but the exact same rendering crash you have with bold.

The spellcheck crash I mentioned recently was an entirely different one. It happened when HexChat (2.11.0) tried to create the main window (where the chat and list of channels/servers appears). Simply deleting "enchant" fixed it. If I get it to happen again with a fresh setup, then I'll open an issue for that.

**Comment by TingPing** [comment]
>The spellcheck crash ("startup crash") I mentioned some posts above was an entirely different one. It happened when HexChat (2.11.0) tried to create the main window (where the chat and list of channels/servers appears). 

Ah. 2.11.0 on 8.1 now uses native Windows spell checking so if this issue didn't happen with 2.10.2 maybe that is related somehow, though they should not conflict..
