### ISSUE TITLE
sleep option to auto-join channel

### ISSUE THREAD

**Issue by joubertredrat** [hexchat/hexchat#1363]
Hi,
I saw that is possible to auth on network and autojoin in channel, but both is executed in same time, but, in protected channel doesn't work, channel only for registered users as example.

Then in this case /sleep can help on this as example.

/sleep 15 /join #channel1
/sleep 15 /join #channel2
/sleep 15 /join #channel3
/sleep 15 /join #channel4 

I think that is good idea to put option to delay between auth and join.

**Comment by TingPing** [comment]
Use SASL: https://hexchat.readthedocs.org/en/latest/faq.html#why-are-channels-joined-before-identifying

**Comment by joubertredrat** [comment]
@TingPing oh, this option exists! Thanks for the help
