### ISSUE TITLE
Large scrollback buffer takes too long to load

### ISSUE THREAD

**Issue by Atario** [hexchat/hexchat#1364]
I have my scrollback buffer set to 100000 lines; one channel I'm in currently has ~66000 lines in it (~8200KB).  HexChat takes over 30 minutes to finish loading it and stays unresponsive the whole time.  Bogs down the rest of the machine during this time too.  Verified the problem was the scrollback by temporarily renaming the file and joining the same channel, which happened instantly.

By comparison, Vim and Notepad++ load the same scrollback file in under a second; Notepad takes ~20 seconds.

**Comment by RichardHitt** [comment]
Hi, Atario

Thanks!  Your issue came at just the right time.  My current project 
will fix this issue, and I wonder if you are in a position to test it.  
If not, that's okay.  If so, are you able to build from the source tree?

Richard Hitt

**Comment by Atario** [comment]
I can test, but I'm not currently configured to build.  Could probably get there, if it's necessary.

**Comment by RichardHitt** [comment]
Thanks, tell me about your distro.  I myself usually use Fedora 21 64-bit and I'd gladly make you an rpm to test with.  But I've built for Windows as well.  Let me know what OS and Distro you are running, and I'll see what I can do.

**Comment by Atario** [comment]
I'm on Windows 7.

(I do have an Ubuntu Server 12.04 LTS file server I can use; not sure how helpful that would be, as there's no GUI…)

**Comment by RichardHitt** [comment]
Okay, have a look at http://rbh00.dyndns.org/~rbh00/9001 and install that hexchat package on your Windows 7 system, please.  I tested it with a russian-alphabet scrollback file of seventy-six thousand lines and it took about 2 sec to complete the /join command for that channel.  Let me know one way or the other what it does for you, please.

**Comment by Atario** [comment]
Ok, I installed it, then copied over my config folder from the normal installation.  Still took ~25 minutes to load the scrollback.

(It might be worth noting that I have my timestamp format set to "[%Y/%m/%d %H:%M:%S] ".  If I turn timestamps off, it loads without a notable delay…)

**Comment by TingPing** [comment]
> (It might be worth noting that I have my timestamp format set to "[%Y/%m/%d %H:%M:%S] ". If I turn timestamps off, it loads without a notable delay…)

Yea thats a rather important detail.. Can you test it with leaving the timestamp on but disabling *Preferences > Appearance > Indent nick names*.

**Comment by Atario** [comment]
Yeah, that also makes it load immediately.

(If you're going to have your fingers in that code, while you're in there, could you also have a look at https://github.com/hexchat/hexchat/issues/1325 ?)

**Comment by RichardHitt** [comment]
Atario, you need to increase your maximum text indent value.  It starts out at 256.  I suggest you try using a value of 300.  Use this command:
    /set text_max_indent 300
Then you will need to restart your hexchat app.  If any of your channels takes longer than say ten seconds to load, give a larger value, say, 400.

**Comment by Atario** [comment]
I went straight to 400 and it works ok now.  Thanks!

**Comment by RichardHitt** [comment]
You're very welcome, Atario.  Thanks for trying it so promptly, and thanks also for your feedback!
