### ISSUE TITLE
Spotify plugin not working

### ISSUE THREAD

**Issue by Numline1** [hexchat/hexchat#1366]
Hello, it seems that Spotify plugin from hexchat-addons repo is not working since recent major update to Spotify from few weeks ago.

Instead of current playing song, you only get
username is now listening to: emium

Thanks for your help!

**Comment by TingPing** [comment]
That has nothing to do with this Project, it is a third party plugin.

That said it gets the song info from the title, they changed that. There is nothing that we can do about that.

**Comment by Arnavion** [comment]
(You can try contacting @rahatarmanahmed to have it updated.)

**Comment by rahatarmanahmed** [comment]
@TingPing is right, there's nothing I can do to fix it. Thanks for letting me know, I added a warning to the plugin README about that.

**Comment by Numline1** [comment]
Thanks for your help guys, if it can't be fixed, it can't be fixed, I guess I'll look for another workaround.

**Comment by TingPing** [comment]
@Numline1 Scrobbling to lastfm and using a plugin for that should work well.

**Comment by rahatarmanahmed** [comment]
@Numline1 Some people [report](https://github.com/rahatarmanahmed/hcspotify/pull/1) that Spotify still has the song info in the window title, but changed the format so it's 10 characters off. I haven't seen my Spotify client do that, but I've [released a fix](https://github.com/rahatarmanahmed/hcspotify/releases/tag/0.2) anyway if it works for you.

**Comment by TingPing** [comment]
I think they removed it entirely, got complaints about that, then re-added in a different format...

**Comment by rahatarmanahmed** [comment]
Maybe, but I just freshly installed Spotify and my plugin still reports the window title as "Spotify Free".

**Comment by TingPing** [comment]
Oh, so I guess you should handle both Free and Premium titles?

**Comment by rahatarmanahmed** [comment]
I'm not sure if it has to do with having Spotify Premium or not, but since I don't, I can't really say how Spotify's window title is supposed to behave. Perhaps @Numline1 or someone else with Premium can test it.

**Comment by Numline1** [comment]
Hey guys. I just tested @rahatarmanahmed 's update, it seems to be working, thanks!

There are actually two things that seem to be the "title". First is application's title at the top of maxmized Spotify, as seen here - http://puu.sh/i7nFd/a75091276e.png

Second is the actual application title in taskbar - http://puu.sh/i7nJV/3e9216633b.jpg

I assume the plugin works with the one in the taskbar, however I see no offset there.

**Comment by rahatarmanahmed** [comment]
Maybe it's OS specific? What OS are you running @Numline1?

**Comment by Numline1** [comment]
Windows 8.1 Pro here.

**Comment by rahatarmanahmed** [comment]
I've got Windows 7, so maybe. I'll wait and see what the other guy says.

**Comment by rahatarmanahmed** [comment]
Got another report from someone who got it working running on Windows 8, so I'll assume it won't work on 7 and older.
