### ISSUE TITLE
Is gnome-common a requirement?

### ISSUE THREAD

**Issue by meuwe** [hexchat/hexchat#1369]
Is gnome-common a requirement? Because my distro did not list it as a requirement to compile it from source and gnome-common is not included in my distro, so it made me wonder about this?

thank you

**Comment by TingPing** [comment]
If you build from git head, No.
If you build from a stable tarball, No.
If you build from a git snapshot from a few months ago, Yes.

**Comment by meuwe** [comment]
I just tried two, what I'm assuming are stable tarballs;

https://dl.hexchat.net/hexchat/hexchat-2.10.2.tar.xz

https://github.com/hexchat/hexchat/archive/v2.10.2.tar.gz

Both of them are asking for gnome-common

**Comment by TingPing** [comment]
> https://dl.hexchat.net/hexchat/hexchat-2.10.2.tar.xz

This is the stable release, just run `./configure`

> https://github.com/hexchat/hexchat/archive/v2.10.2.tar.gz

This is not an official release.

**Comment by meuwe** [comment]
My apology I had ```sh autogen.sh``` by mistake in my compiling script. It appears to be compiling now ok.

But now it's not seeing my python-2.6.6 version.

The compile options are saying;

```Python ...... :no```

So I added to the configure options as;

```enable-python=python-2.6.6``` 

But it's not working...

**Comment by TingPing** [comment]
Because Python 2.6 is not supported.

**Comment by meuwe** [comment]
Oh crap, my distro only has this version... :(

**Comment by TingPing** [comment]
What distro?

**Comment by meuwe** [comment]
Slackware 13.37

**Comment by TingPing** [comment]
Lucky for you latest slackware has 2.7.

**Comment by TingPing** [comment]
Also http://slackbuilds.org/repository/14.1/network/hexchat/

**Comment by meuwe** [comment]
But I'm not using 14.1 I'm using 13.37...

This is my VM image of Slackware I use as a guest OS that I wanted to install hexchat on. It has xchat at the moment.

I use 14.1 as my Host OS also, that has hexchat too, but, I would like to use it on this VM image as well...
