### ISSUE TITLE
Colored Events is affected by input

### ISSUE THREAD

**Issue by mossarelli** [hexchat/hexchat#1377]
I use the event "Your Message" with special characters and colors to make sure I can easily find myself in the list because my nick and message gets the color green.

The text: %B%C9┌$1┘:$t%O%C9$2%O
This way my nickname shows up as green, there's two little corners and the rest of my message is green. Problem is, if the first character of my message is any number, that number affects the color of the message and it is omitted in the message. So writing: "8chan" shows up as "chan" on my end and in the log as well:
May 20 01:21:54 ┌Username┘:	chan is the last...

Is there something I missed or is this a bug? Thanks for your help.

**Comment by Arnavion** [comment]
%C09

**Comment by mossarelli** [comment]
Thank you so much! I will remember this.
Much love to ye.
