### ISSUE TITLE
Input bar disappears after having used RDP

### ISSUE THREAD

**Issue by meisme** [hexchat/hexchat#1384]
If I leave Hexchat running on my computer while I access it through Windows' Remote Desktop, when I disconnect again the input bar - that is the place where you type commands and messages - disappears (along with the nick and voice/op indicator). There's just nothing below the main window.  It seems to happen 100 % of the time. I'm using the latest version, according to the update checker.

**Comment by TingPing** [comment]
Gtk over RDP is extremely broken in numerous ways. You can try reporting these upstream though gtk2 is not really heavily developed any longer I wouldn't expect much.
