### ISSUE TITLE
Highlighting Hindi characters makes highlighted text go across screen making it unable to copy etc

### ISSUE THREAD

**Issue by Saga1234** [hexchat/hexchat#1388]
![hindi](https://cloud.githubusercontent.com/assets/12719558/7944422/669ef710-0962-11e5-9557-27f6bc0a9979.PNG)
![hindi2](https://cloud.githubusercontent.com/assets/12719558/7944424/67abc7d2-0962-11e5-8b18-1af444e85143.PNG)

(Both are the exact same message)

HexChat 2.10.2
x64
Windows 7 SP1

**Comment by TingPing** [comment]
Duplicate of #692
