### ISSUE TITLE
An option to disable the "Now talking on..." and the "Topic for #channel..." messages

### ISSUE THREAD

**Issue by AaronMcHale** [hexchat/hexchat#1390]
It would be nice to have config options to disable the following from being printed in chat every time the channel is opened:

    * Now talking on #channel
    * Topic for #channel is: This is a channel
    * Topic for #dev set by ChanServ (Thu Apr 16 03:36:36 2015)

Thanks
Aaron

**Comment by 666threesixes666** [comment]
settings > text events
scroll down to:
Topic %C22*%O$tTopic for %C22$1%C is: $2%O
change to 
Topic 

scroll down to:
Topic Creation %C22*%O$tTopic for %C22$1%C set by %C26$2%C (%C24$3%O)
change to
Topic Creation

scroll down to:
You Join %C19*%O$tNow talking on %C22$2%O
change to
You Join 

there are supposedly methods to disable this via scripts or plugins but idk where the repo is and its annoying to the point where ill full on blast the feature away from the program.

**Comment by AaronMcHale** [comment]
Hi, sorry about the late reply, that seemed to work for me, thanks.
