### ISSUE TITLE
Indicator icon dosen't work on Pantheon

### ISSUE THREAD

**Issue by bil-elmoussaoui** [hexchat/hexchat#1394]
Pantheon is based on Ubuntu, as you can see here [elementary OS](www.elementary.io)
The indicator icon is not working, all other indicators works fine!

**Comment by TingPing** [comment]
Duplicate of #1235

**Comment by bil-elmoussaoui** [comment]
Well, it's not the same distro, nothing is the same! KDE have a different library to show/hide indicators.

**Comment by TingPing** [comment]
Well the title is very different but the solution for both is to add Appindicator support.
