### ISSUE TITLE
Help Message for /close is Confusing

### ISSUE THREAD

**Issue by Havvy** [hexchat/hexchat#1397]
When doing `/help close`, I get the following response:

`Usage: CLOSE [-m], Closes the current window/tab or all queries`

That has to be the most confusing help message I've seen in years. Expand it out to a few sentences to explain the nuances.

**Comment by TingPing** [comment]
It's hardly that confusing, it close a tab or [with the only optional arg shown] all queries.

**Comment by Havvy** [comment]
`Usage: CLOSE [-m], Closes the current tab, closing the window if this is the only open tab. With the "-m" flag, closes all queries.`

The terseness is only helpful if you already know what it means. By expanding it out into two sentences, you can still be succinct in description, but helpful to those who are looking it up for the first time.

**Comment by TingPing** [comment]
That looks good.
