### ISSUE TITLE
Options spawning on a different monitor

### ISSUE THREAD

**Issue by Stanzilla** [hexchat/hexchat#1401]
In a multi monitor setup, Hexchat options window and dialogs spawn always on display 1, not the one where Hexchat actually is. Would probably make more sense to always spawn it on top of the Hexchat window.

**Comment by Arnavion** [comment]
That's not what it does, but anyway it was fixed already. Use a test build.

**Comment by TingPing** [comment]
Duplicate of #1007 (already fixed as mentioned)
