### ISSUE TITLE
Make channel tree font separately configurable (so you can make it smaller)

### ISSUE THREAD

**Issue by wm4** [hexchat/hexchat#1402]
Currently, changing the font in the hexchat preferences changes both the channel message view and the channel switcher tree. This is quite impractical, because I want a larger font for the channel view (for readability), but a smaller one for the channel tree (so I can see the full list of channels without scrolling).

The "Smaller text" option in the channel switcher preferences is not helpful at all. Even though the text becomes a bit smaller, the vertical space the tree items take up is the same. In addition to this fundamental flaw, it also makes the font smaller by a fixed amount, which is not configurable enough.

I didn't have this problem in xchat, where the channel tree was rendered more compactly for some reason. It probably used the GTK system font, and the vertical padding was smaller too.

**Comment by TingPing** [comment]
*Preferences > User list > Use Text box font* (Yes I know its an odd location for chan tree related setting)

**Comment by wm4** [comment]
Odd indeed. This works great for me and fixes the issue for me. (My system font happens to be small enough.)
