### ISSUE TITLE
Make channel switcher a list instead of a tree

### ISSUE THREAD

**Issue by wm4** [hexchat/hexchat#1403]
The channel tree has a parent item for each network. This wastes vertical space. It also prevents rearranging channels in a way that would mix networks.

It would be nice if there was a way that simply omits the network, or maybe prefixes the channel name with the network name.

**Comment by TingPing** [comment]
That sounds like the job of an overly complex plugin. It makes no sense at all to mix and match channels from different networks.

**Comment by wm4** [comment]
>It makes no sense at all to mix and match channels from different networks.

It does. After all grouping by network and then sorting alphabetically is pretty arbitrary. (I know you can change channel position within networks, but it's not persistent across restarts.)

I'd prefer grouping channels logically, instead of by physical network.

**Comment by TingPing** [comment]
> I know you can change channel position within networks, but it's not persistent across restarts.

It can be. Disable sorting in prefs and then join order is how it shows up. You can change join order in the network list with shift+up/down.
