### ISSUE TITLE
Docked Window Size/Position not persisted

### ISSUE THREAD

**Issue by MrGadget1024** [hexchat/hexchat#1406]
Seems to be a minor bug with remembering window size/shape when docking hexchat to sides of screen... for example if I drag the window to the side of the screen, it docks and fills half the screen (fine), but if I then minimize and restore, it reverts to whatever size/shape/position it was before I did that.
Normal resizing / moving seems to be remembered correctly through minimize > restore
Same bug occurs if I drag window edge to screen edge that triggers a width or height "docking".

version is 2.11.0 on win 7 x64

**Comment by TingPing** [comment]
You said this did not happen in 2.10.2?

**Comment by MrGadget1024** [comment]
I can no longer reproduce this issue in 2.12.4 on Win7. Snapping the window to the right and then exiting, or minimizing and then exiting from the tray, and restarting HexChat correctly positions the window snapped to the right as it should.
