### ISSUE TITLE
Hungarian translation is wrong

### ISSUE THREAD

**Issue by 0xcaca0** [hexchat/hexchat#1409]
https://github.com/hexchat/hexchat/blob/master/po/hu.po#L4643-L4645
In Hungarian this says "Use a proxy server", just helped a very confused Hungarian user set up hexchat on Tor.
According to the user, it should say "Ne használjon proxy kiszolgálót"

**Comment by bendem** [comment]
Hexchat uses transifex to handle translation: https://www.transifex.com/projects/p/hexchat/

**Comment by gabre** [comment]
I am the mentioned user. The translation is wrong. I have requested to join the translator group.
