### ISSUE TITLE
Missing IRC networks

### ISSUE THREAD

**Issue by anonsubmitter** [hexchat/hexchat#1412]
Here are some IRC networks I noticed are missing from HexChat's network list:

Chat Hispano: http://www.chathispano.com/
IdleChat: http://idlechat.net/
Mibbit: https://search.mibbit.com/channels/Mibbit
Pirate IRC Network: http://pirateirc.net/
PurpleSurge: http://www.purplesurge.com/
SystemNET: http://www.systemnet.info/

**Comment by TingPing** [comment]
The goal is not to put every network in existence on the list.

**Comment by anonsubmitter** [comment]
Ok, I guess that at least rules out the Pirate IRC Network since it's a quite small and limited IRC network. What do you you think of the other IRC networks? Chat Hispano is the largest Spanish IRC network and Mibbit is quite large as well.

**Comment by TingPing** [comment]
I believe hispano was not added by the previous developer because it blocked entire countries (where he happened to live) so he never added it.

**Comment by anonsubmitter** [comment]
Ah, ok. I don't have any personal experience with that IRC network so I was unaware of that.

**Comment by Mikaela** [comment]
From what I have understood, the policy is that network operators ask for their network be added and as far as I am aware, at least PirateIRC had no interest to that.
