### ISSUE TITLE
SYSINFO doesn't see my second gpu so it doesn't report SLI

### ISSUE THREAD

**Issue by t00tie** [hexchat/hexchat#1420]
May I complain about my first world problems? 

/SYSINFO doesn't see my second gpu so it doesn't report SLI

obviously a very high priority "Bug"

** SysInfo ** Client: HexChat 2.10.2 (x64) ** OS: Microsoft Windows 7 Ultimate  ** CPU: Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (2.00 GHz) ** RAM: 32718 MB Total (27547 MB Free) ** VGA: NVIDIA GeForce GTX 980M ** Uptime: 135.07 Hours **

**Comment by Arnavion** [comment]
Atleast you're honest about it.

Anyway it's already fixed in master. Whatever is the next release will show all GPU names separated by commas.

**Comment by TingPing** [comment]
You can grab a new build here: https://dl.hexchat.net/hexchat/testing/
