### ISSUE TITLE
python34.dll missing

### ISSUE THREAD

**Issue by Hink1** [hexchat/hexchat#1421]
I am not quite sure why but this error seems to have persisted across multiple instances of installing the latest HexChat client with the python script package.  Is there a way I can build the dll file on my own?

**Comment by TingPing** [comment]
Run the HexChat installer, select the Python plugin, upon completion the Python installer will show up, install that with the default options.

**Comment by Hink1** [comment]
I fully ran the installer, installing Python resources and the error persists yet the dll file does exists.
![github 1](https://cloud.githubusercontent.com/assets/12993584/8608996/79a492ba-266e-11e5-80ee-ed57873e728a.PNG)

**Comment by TingPing** [comment]
In the Python installer there is an "Install for all users" option, it should have been checked by default but make sure it is.

**Comment by Hink1** [comment]
Installing it for all users fixed the error, thank you.

**Comment by Arnavion** [comment]
If C:\Python34 is not in your PATH, you cannot expect HC to be able to load it.
