### ISSUE TITLE
Windows build OpenSSL stupidly out of date

### ISSUE THREAD

**Issue by funkydude** [hexchat/hexchat#1422]
It would be nice to see a new release, or at least a new Windows build with the latest OpenSSL.

**Comment by TingPing** [comment]
Versions are tracked here: https://github.com/hexchat/gtk-win32/issues/10
Builds are uploaded here: https://dl.hexchat.net/hexchat/testing

**Comment by funkydude** [comment]
Thanks for the link to the dev version. Unfortunately that is also several versions out of date.

That being said, security fixes should not be restricted to development builds, especially when the development timeline for HexChat is so long.

**Comment by TingPing** [comment]
> Thanks for the link to the dev version. Unfortunately that is also several versions out of date.

If one version is several. d was released pretty recently so it will be updated soon enough.

> That being said, security fixes should not be restricted to development builds, especially when the development timeline for HexChat is so long.

Would be ideal yes.

**Comment by funkydude** [comment]
It's not one version. It's bundling version 1.0.2.3 of ssleay32.dll which is version 1.0.2c

**Comment by TingPing** [comment]
>It's not one version. It's bundling version 1.0.2.3 of ssleay32.dll which is version 1.0.2c

Correct and the latest is 1.0.2d, It has been a while since school but I think d is one after c.

**Comment by funkydude** [comment]
I guess I misread it for 1.0.1.3, thanks for the attitude though.

**Comment by funkydude** [comment]
This isn't resolved until there's a stable release without a vulnerable OpenSSL.
