### ISSUE TITLE
Chat Graphical Smileys/Icons

### ISSUE THREAD

**Issue by RyzaJr** [hexchat/hexchat#1432]
I know this is supported in the official version, but that is no longer updated.

I humbly request this eventually be supported in HexChat. It makes IRC clients more streaming-friendly with simplistic and good-looking chat logs.

Hopefully this hasn't been requested a million times before, and there's some obvious answer somewhere that I haven't found as to why this hasn't been implemented yet.

**Comment by TingPing** [comment]
Hmm, I don't actually see an issue over it but it has been asked a lot. The answer is always that this is pretty unlikely to happen.

**Comment by RyzaJr** [comment]
Ah, I see. Thanks for the reply. May I ask why it is unlikely?

If I were able to code it myself, I'd do so but unfortunately I'm not a programmer.

**Comment by TingPing** [comment]
xtext is the custom widget used to draw the textbox, it is a rather large, complex, and buggy widget which is not fun or easy to extend. So some developer must be so invested in this feature they would suffer through that.

**Comment by RichardHitt** [comment]
xtext is mine, and buggy it is not.  Large it is.  Complex it is. Robust 
it is.  Known bugs have fixes, and there are few of them. Unfortunately, 
hexchat bug fixes are apparently no longer being accepted.

Ryza jr.  I'd be happy to discuss with you the details of emoticons and 
their varying possibilities, and how xtext could be changed to make use 
of them.  I have already done some work along those lines, see issue 
#546, and you may wish to get involved only as a tester of my 
non-mainstream work.  Once xtext is liberated from the 
fixed-pixel-height-per-line scenario then variable-height emoticons 
become a possibility.  (As it is, Unicode has itself defined some 
emoticon-like characters, but they are imho unsatisfactory in the extreme.)

If you could help with testing a non-mainstream version of hexchat, let 
me know your Operating System and version (Linux preferred, but Windows 
possible).

Richard Hitt

**Comment by RyzaJr** [comment]
Hey RichardHitt,

Yeah, I'd like to help with testing your HexChat builds. I do use Windows 7 Professional 64 bit, but I have used Linux before but not much. I'm thinking about dual-booting it again for fun so I might be able to give it a go on there as well.

**Comment by RichardHitt** [comment]
Hi, Ryza

Let's take our dialog about this offline then, since it's non-mainline 
hexchat.  My email address is rbh00 at-sign netcom.com.  Send me email 
there from your ow n email account, not github, and I'll tell you what 
I've done so far and point you to an installable of it from last 
January.  It offers "paragraph spacing", like mIRC does, but I confess 
it is a long way from what I dream of in the way of emoji.

Richard

**Comment by Stanzilla** [comment]
`Unfortunately,
hexchat bug fixes are apparently no longer being accepted.`

Eh, really?

**Comment by TingPing** [comment]
So the Gtk stack recently added support for colored emoji:
![screenshot from 2017-10-23 05-43-28](https://user-images.githubusercontent.com/798838/31882546-2187013c-b7b5-11e7-9d49-5ba80a16a945.png)

(No idea when this will trickle down to the Windows releases but you can use this on Fedora 27 today).
