### ISSUE TITLE
Poor performances on Windows 10

### ISSUE THREAD

**Issue by TheShayy** [hexchat/hexchat#1436]
I was using Hexchat on Windows 7 before the upgrade, and it was juste fine
Since I upgraded, the interface is really very slow, sometimes unresponsive, and connection with the server keeps resetting (Ping timeout, my bouncer can't ping me for a while)
Hexchat is the only one being slowed since the upgrade, so I think it is not Windows' fault

EDIT: Btw, this is off-topic, but why don't you look at Windows' kernel version directly to detect W10? Even if it is a temp solution, it might be better than a ugly "Windows 8" in CTCP VERSION reply :s

**Comment by TingPing** [comment]
Works fine for me. As for version reply use a test build: https://dl.hexchat.net/hexchat/testing.

**Comment by DoctorWho11** [comment]
util.c needs to be modified to support windows 10 using IsWindows10OrGreater() and then compiled against the windows 10 SDK.

**Comment by TheShayy** [comment]
Ok I found the problem
F-Secure's DeepGuard is slowing down Hexchat on W10
The test build is saying Windows 8.1
