### ISSUE TITLE
irc:// links not opening with hexchat

### ISSUE THREAD

**Issue by b818283** [hexchat/hexchat#1437]
how do I associate irc:// links with hexchat in Win10x64?

Thanks

**Comment by Stanzilla** [comment]
http://www.howtogeek.com/223144/how-to-set-your-default-apps-in-windows-10/

Use the "by protocol" link in the settings.

**Comment by b818283** [comment]
Thank you for replying.  I only have two options:  Keep using this app: Google Chrome or  Other Options:  Look for other apps in the Store:  There are mo options to choose, or browse to the Hexchat executable.  Thanks.

**Comment by TingPing** [comment]
The hexchat installer should always change it for you.

**Comment by reconman** [comment]
I have the same problem. HKEY_LOCAL_MACHINE\SOFTWARE\Classes\irc\shell\open\command is set to open HexChat but it's not an option for irc URLs.

**Comment by NoxNebula** [comment]
same as @reconman.

**Comment by TingPing** [comment]
Merge with #1277

**Comment by mrandreastoth** [comment]
I'm having this issue on Windows 10 Build 17677.rs_prerelease.189520-0940. Windows 10 simply won't list HexChat as an option for IRC. Similarly, when I manually associate IRC with HexChat in Firefox Developer Edition, it won't stick.

**Comment by bingoxo** [comment]
still nothing ?
