### ISSUE TITLE
[Win10 bug] Clicking on checkboxes in Preferences doesn't work

### ISSUE THREAD

**Issue by stephenfournier** [hexchat/hexchat#1443]
Demo of the bug here:

![](http://zippy.gfycat.com/DimpledDisgustingBedbug.gif)

The problem started occurring after upgrading to Windows 10.

**Comment by tomek** [comment]
I can't reproduce it on my win10 using windows test build. Could you check it yourself - download test build from here: https://dl.hexchat.net/hexchat/testing/

**Comment by stephenfournier** [comment]
Downloaded the x64 test build from the link your provided. Still having the same issue unfortunately.

**Comment by stephenfournier** [comment]
I moved the Hexchat folder from AppData and Program Files, and then installed the x64 test build of Hexchat, but still having the same problem.

Found some more info on the problem though. When I move the cursor out of the preferences window, then move it back in, it will allow me to check the checkbox. Once I check the checkbox, I need to perform this again. Notice I have to do the same thing with the cancel button too.

![](http://zippy.gfycat.com/DeadRadiantBushsqueaker.gif)

**Comment by Arnavion** [comment]
What about with the 32-bit build?

**Comment by Mikaela** [comment]
In case you are interested, I had this happen with Dropbox settings some days ago and I just remembered this issue and thought I could say it here that it's not only HexChat. Today it worked without issues, but I am not sure if it has updated itself or anything.

**Comment by stephenfournier** [comment]
seems to be fixed

**Comment by TingPing** [comment]
@stephenfournier What did it? Windows update?

**Comment by stephenfournier** [comment]
@TingPing Most likely.
