### ISSUE TITLE
[Win10 bug] Mouse-wheel can control chat channel scrollbar only after the Title bar has been clicked

### ISSUE THREAD

**Issue by stephenfournier** [hexchat/hexchat#1444]
In order for the scrollbar in a chat channel to be able to be controlled using the mouse wheel, you must first click on the Title bar in Hexchat: ![](http://puu.sh/jqAEZ/1e40d62742.png)

If control is on the chat channel, you aren't able to use the mouse-wheel to control the chat channel scrollbar.

This problem first starting occurring after upgrading to Windows 10.

**Comment by tomek** [comment]
Like in #1443 - I can't reproduce it on my win10 using windows test build. Could you check it yourself - download test build from here: https://dl.hexchat.net/hexchat/testing/

**Comment by stephenfournier** [comment]
Downloaded the x64 test build from the link your provided. Still having the same issue unfortunately.

**Comment by Arnavion** [comment]
What about with the 32-bit build?

**Comment by stephenfournier** [comment]
seems to be fixed
