### ISSUE TITLE
hexchat indicator broken and unable to minimize to tray on ubuntu 15.04

### ISSUE THREAD

**Issue by tristan-k** [hexchat/hexchat#1447]
I'm using `Ubuntu 15.04 64bit` with `HexChat 2.10.2` and installed the `xchat-indicator 0.3.11-0ubuntu7` package. I followed the [workaround for the bug](https://github.com/cheshire-mouse/hexchat-indicator#known-problems) which starts a new instance when clicking on the messaging menu indicator, but it still wont resume the state of hexchat. Just to be clear: I want to close the app window so its gone from the task switcher and bring it back with clicking on the indicator.  Can someone confirm this behaviour or provide a solution?

I also noticed that there is no option available to minimize hexchat to the tray. The [FAQ](https://hexchat.readthedocs.org/en/latest/faq.html#how-do-i-minimize-hexchat-to-the-system-tray-notification-area) says  `On both Unix and Windows there is an included tray plugin. To enable minimizing to tray on exit go to Settings ‣ Preferences ‣ Alerts.` But there is no such option.

![hexchat preferences_022](https://cloud.githubusercontent.com/assets/732025/9195992/5f8e311a-4027-11e5-9de5-8c2ae6dea22d.png)

Also see my report [here](https://github.com/cheshire-mouse/hexchat-indicator/issues/3).

**Comment by TingPing** [comment]
That plugin is a third party project. As for indicators not being supported natively see #1235

**Comment by tristan-k** [comment]
Whats about the missing option to minimize to tray?

**Comment by TingPing** [comment]
> As for indicators not being supported natively see #1235
