### ISSUE TITLE
User nick always red

### ISSUE THREAD

**Issue by CandiceJoy** [hexchat/hexchat#1453]
My user nick in the text box is always red, even though my user color in the userlist is clearly green.  You could either not assign red to any other user and always have the local user colored red, or you could make the user's nick in the text box show their proper user color when that feature is enabled.

**Comment by TingPing** [comment]
Your nick is not colored with that setting the red is just a part of your theme. The user list doesn't have knowledge of your theme to mimic that color and the colors are fixed they are not dynamic to be able to avoid whatever your theme is set to (which again it has no knowledge of anyway).
