### ISSUE TITLE
Crashes on Windows 10

### ISSUE THREAD

**Issue by Krahazik** [hexchat/hexchat#1455]
Trying to connect to a IRC server on windows 10 the client crashes and closes abruptly.

**Comment by Poorchop** [comment]
It would probably help if you could provide a little more information. What architecture? Using any scripts? Did this work in a previous version of Windows for you? Was this a fresh HexChat install? Maybe try to debug and see if you can get any helpful information.

**Comment by jackpoz** [comment]
Connecting to irc.rizon.net on Windows 10 x64 using HexChat 2.10.2 x64 works fine

**Comment by Borkason** [comment]
I haven’t had a single crash, either.

**Comment by SamuelMarks** [comment]
Same issue for me. Changing to the x86 version fixed the problem.

(I am on x64 Windows)

**Comment by SamuelMarks** [comment]
Ahhh, I thought that might be it.

Reinstalled the x64 version without the Python 2.7 bindings. It all works now.

**Comment by TimothyBramlett** [comment]
@SamuelMarks Thanks!  I had the exact same issue and reinstalling without the Python 2.7 bindings solved it for me as well!
