### ISSUE TITLE
Doesn't handle channel url numeric starting with :

### ISSUE THREAD

**Issue by fred0r** [hexchat/hexchat#1460]
Joining a Freenode-Chan shows a wrong Channel-Url:

```
--- Topic for #znc is www.znc.in | ZNC 1.6.1: http://wiki.znc.in/ChangeLog/1.6.1 | http://znc.in/nightly | Debian stable: 1.4 is 1.5 year old | 1.2 is 2 years old | 1.0 is 3 years old | Debian oldstable: 0.206 is 3.5 years old | don't randomly PM people | http://blog.max-mehl.com/2014/i-love-znc-because-ilovefs/
--- Topic for #znc set by jpnurmi at Tue Aug 04 22:14:33 2015
Channel #znc url: ttp://znc.in
```
Irc-Client: Hexchat (Windows Testing Build 9664b1b)

I also reported it initially to znc, because one of the maintainers told me that is looks like a znc-bug (https://github.com/znc/znc/issues/1045) - but then i was told in #hexchat to submit it also here.

**Comment by TingPing** [comment]
Simple change to check for `':'` here: https://github.com/hexchat/hexchat/blob/9664b1b7e3040b7388ecd8c2de46919502f310af/src/common/proto-irc.c#L682

Seems pretty reasonable to do.

**Comment by DarthGandalf** [comment]
I see the same pattern for numerics 330, 332 at that file... Maybe there are more like it.

**Comment by TingPing** [comment]
Yea it is sloppily done all over I'm sure. =\

**Comment by fred0r** [comment]
It also happens on every 'whois' - but as the proto-irc.c is mentioned i think the future fix will repair that also,

**Comment by fred0r** [comment]
thx
