### ISSUE TITLE
Strange problem with Glibc v2.22

### ISSUE THREAD

**Issue by davem-13** [hexchat/hexchat#1461]
Hello, im using manjaro linux, and im trying to compile latest hexchat git from AUR (i tried with the binary package from manjaro repos ---> the same issue) and that is what i get:

" hexchat[23216]: segfault at 4 ip b692c9d0 sp bf8e77c0 error 6 in libc-2.22.so[b687e000+1b3000] "

that is in the logs in /var/log -- i cant find something else related there, and occuring when im trying open it normally. 
When im issuing this: hexchat -n (without plugins) the client starting without that nasty issue (gui always)

During the compillation i havent see something bad, and the compilation is successfull always

GLIBC: 2.22
GCC: 5.2.0
 
what else i can provide and how , for helping you?

**Comment by TingPing** [comment]
Build hexchat with debugging. `./configure --enable-debug` and then run it under gdb:
`gdb ./src/fe-gtk/hexchat`, type `r` for it to run and crash, type `bt full` for backtrace and pastebin it.
