### ISSUE TITLE
Installer fails to download files

### ISSUE THREAD

**Issue by The-Hink** [hexchat/hexchat#1467]
For some reason I am no longer able to install HexChat.

![image](https://cloud.githubusercontent.com/assets/12993584/9623431/4aa12e2c-510e-11e5-817a-07e981d80ca0.png)

**Comment by TingPing** [comment]
For whatever reason you can't connect to https://dl.hexchat.net/, something on your end probably.

**Comment by Hink1** [comment]
That I know.  Is there something common on the users' side that would cause this?

**Comment by folbo** [comment]
Friend got the same issue, unable to connect when downloading vcredist.exe http://puu.sh/k1M5d/22ea1820dc.png

**Comment by TingPing** [comment]
Sadly the error message is useless and I wouldn't know where to get more detailed logs.
