### ISSUE TITLE
Portable setup setting

### ISSUE THREAD

**Issue by jackpoz** [hexchat/hexchat#1474]
Running "HexChat 2.10.2 x86.exe" asks if the Portable Mode should be enabled but then it shows the feature is disabled if the folder selected 2 "Next >" before isn't a portable drive. This is an installation bug, either always allow Portable setup or don't even show the option if the drive is not portable.

![silly config](https://cloud.githubusercontent.com/assets/1153754/9746625/592737e6-5679-11e5-9819-0f2929918e94.jpg)

**Comment by TingPing** [comment]
You are trying to install into `C:\Program Files\HexChat`. This path is not user writable and as such would require Admin to run a 'portable' install in that folder. So many users have done this over the years not understanding what portable mode is for we had to add a check to prevent this. If you select a sane place to install it everything should work fine.

**Comment by jackpoz** [comment]
> You are trying to install into C:\Program Files\HexChat. This path is not user writable and as such would require Admin to run a 'portable' install in that folder

This comment should be added to the installer so one knows which path are/aren't supported for a Portable installation. According to what you said a path like C:\HexChat would work, even if that's not a portable drive.

**Comment by SeinopSys** [comment]
Agree with @jackpoz, I forgot to change the install path to where I usually install the app and this message confused me. I use portable install to keep the app & my configs on a 2nd drive in case my primary drive needs formatting for a reinstall, which technically isn't a "portable drive".
