### ISSUE TITLE
PortableApps version of HexChat

### ISSUE THREAD

**Issue by Trucido** [hexchat/hexchat#1480]
First off, yes I know HexChat has a portable install mode, but [PortableApps](http://portableapps.com) is a great platform to install and conveniently auto update all apps while keeping them self contained and portable across multiple OS installs, or multiple computers. For example on a local install I use %USERPROFILE%\Bin\PortableApps\ for all my PortableApps programs but similarly they could be stored on a removable drive to use on any computer. PortableApps also has the convenience of a start-menu-like launcher.

I think HexChat would make a great addition to the PortableApps library, and would make updating it much simpler too. HexChat already has a portable install mode, so it should be fairly easy to package into the .paf.exe format.

There's already a request open for 2 years here: http://portableapps.com/node/36103
and a test release here: http://portableapps.com/node/44464

This would mean a maintainer would be required, but perhaps some automated method could be devised to package and publish the PortableApps version on every release? (After it's accepted into the PortableApps main repositories)

More info on creating PortableApps here: http://portableapps.com/development

Thanks for reading, and a big thank you to all developers involved for continuing the development and improvement of one of the best IRC clients :)

**Comment by berrythesoftwarecodeprogrammar** [comment]
might be cool. the devs here seem to hate portable mode tho lol even tho it works fine and ive used xchat/hexchat like that for years

**Comment by Trucido** [comment]
Yeah so have I, I've still got a theme from nearly 10 years ago :) 

Anyways, technically HexChat wouldn't even need to be installed in "portable" mode, the PortableApps platform can automatically redirect %APPDATA% stuff to the appropriate portable location without the app even needing to know, sort of like a symlink/junction or virtual filesystem

Typically the directory hierarchy of a PortableApp would consist of something like this:

PortableApps
&nbsp;└── HexChatPortable
       &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── App
       &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;│&nbsp;&nbsp;&nbsp;&nbsp;       └── (program files and stuff go here, including the real HexChat.exe)
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── Data 
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;│&nbsp;&nbsp;&nbsp;&nbsp;    └── (all %APPDATA% files get redirected here by the wrapper)
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── Other 
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;│&nbsp;&nbsp;&nbsp;&nbsp;        └── (licensing and help documents)
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;└── HexChatPortable.exe ( PortableApps wrapper that runs the real program )

**Comment by TingPing** [comment]
I don't think anybody from this project has interest in maintaining anything for PortableApps but they are of course free to redistribute this project if they wish. So I'd suggest one of you perhaps pushing them for it.

**Comment by Poorchop** [comment]
Shouldn't this be left open then or closed as wontfix?

**Comment by TingPing** [comment]
>Shouldn't this be left open then or closed as wontfix?

I don't consider it a HexChat issue. "Will HexChat be added to PortableApps?" is a question for PortableApps not HexChat.

**Comment by Trucido** [comment]
I don't think the PortableApps team actually maintains many packages themselves, just the open source platform. It's usually up to app developers or volunteers to provide the packages.

Figured it was worth a try and might be easier if the app authors hooked some automated build in with their releases rather than an outside maintainer but I understand it's additional work only a low percentage of users might benefit from.

Thanks for the consideration, I don't have the time to be s maintainer anymore so maybe someone will pick this one up eventually.
