### ISSUE TITLE
Publish on Mac App Store

### ISSUE THREAD

**Issue by mcandre** [hexchat/hexchat#1482]
Thanks for porting Hexchat to Mac OS X! Us Mac users appreciate a great IRC client!

Could we please publish Hexchat on the Mac App Store to make it easier to install?

**Comment by TingPing** [comment]
This will never ever happen.

- Various dependencies and hexchat need to be modified to fit the guidelines
- HexChat is pretty bad on OSX
- Doesn't that technically violate the GPL2 license?
- I don't think a non-native Gtk UI would even pass their initial review
- Somebody has to actually support it
