### ISSUE TITLE
HTTP links truncated at # on double-click (with Chrome as default browser)

### ISSUE THREAD

**Issue by gbasood** [hexchat/hexchat#1484]
HTTP URLs in the chat log will be truncated on double-clicking to open.
For example, double-clicking:
`https://github.com/hexchat/hexchat/pull/1466/files#diff-68f7ee3118c7c29437b54c75e628af14L4676`
will instead open ~~your default browser~~ and direct it to:
`https://github.com/hexchat/hexchat/pull/1466/files`

However, right-clicking and using URL handlers seems to work just fine.

A little bit more testing shows that this only happens with Chrome as the default browser.

**Comment by TingPing** [comment]
Does `/url https://github.com/hexchat/hexchat/pull/1466/files#diff-68f7ee3118c7c29437b54c75e628af14L4676` have the same behavior?

I don't think there really is a ton we can do to change the behavior outside of HexChat, we just pass on the link.

**Comment by Stanzilla** [comment]
That's a bug in Chrome, it's fixed in the Dev Channel.
