### ISSUE TITLE
Tree view spacing (gui_tweaks)

### ISSUE THREAD

**Issue by malenki** [hexchat/hexchat#1493]
Hi,
recently I realised that Xchat had a tiny feature hexchat is missing. 
The switch ["gui_tweaks = 32"](https://xchatdata.net/Using/SetVariables#gui_tweaks) in xchat.conf enabled a smaller treeview/userlist row spacing. This is useful when visiting several networks with several channels and having only a small display. 
It would be nice if this feature could be re-invented (or I get pointed to the hexchat counterpart).

Screenshots of Xchat to compare (first "gui_tweaks = 34" set, second without this line):
![2015-09-27_230710_scrot_xchat_tab_space](https://cloud.githubusercontent.com/assets/188565/10169683/88428922-66d2-11e5-9205-a06021f78e1c.png) ![2015-09-29_174501_scrot_xchat_tab_space](https://cloud.githubusercontent.com/assets/188565/10169686/8cbcd408-66d2-11e5-90de-673ba5995052.png)

**Comment by TingPing** [comment]
Just moved to a sane place - *Preferences > Advanced > Display lists in compact mode*

**Comment by malenki** [comment]
Thanks for pointing and the speedy reply!
(Sometimes I forget the GUI over some config files… :) )

**Comment by TingPing** [comment]
No problem, a lot of configs were renamed and split to have better names with less flags and easier to add to the preferences window.
