### ISSUE TITLE
How to auth before joining rooms?

### ISSUE THREAD

**Issue by brylie** [hexchat/hexchat#1496]
I want to auto-join several rooms, but some require that I be identified by NickServ before joining. How can I automatically authenticate with NickServ before joining rooms?

**Comment by TingPing** [comment]
Use SASL as your login type in the network list, (this is already the default for networks like freenode), for a step by step see https://freenode.net/sasl/sasl-hexchat.shtml

**Comment by brylie** [comment]
Thanks. I overlooked the password field, perhaps not understanding that it would identify with NickServ.

**Comment by Poorchop** [comment]
There's also a join delay option for networks that don't support SASL or CertFP and require auth via NickServ. Preferences > Chatting > Auto join delay and increase as necessary.
