### ISSUE TITLE
Download links do not work.

### ISSUE THREAD

**Issue by mkunz7** [hexchat/hexchat#1497]
https://hexchat.github.io/downloads.html

Most the links are broken.

**Comment by TingPing** [comment]
What error do you get navigating to https://dl.hexchat.net ? I imagine you are using an outdated browser.

**Comment by mkunz7** [comment]
Net::ERR_CERT_COMMON_NAME_INVALID
Followed by:
404 There isn't a GitHub Pages site here

Tested in FF latest and Chrome Latest
wget complains about tls as well

**Comment by mkunz7** [comment]
root@mybox:~/wget/wget-1.16.3# gnutls-cli -d 5 dl.hexchat.net -p 443
Resolving 'dl.hexchat.net'...
Connecting to '2400:cb00:2048:1::681b:8489:443'...
|<4>| REC[0xe83690]: Allocating epoch #0
|<2>| ASSERT: gnutls_constate.c:695
|<4>| REC[0xe83690]: Allocating epoch #1
|<3>| HSK[0xe83690]: Keeping ciphersuite: DHE_RSA_AES_128_CBC_SHA1
|<3>| HSK[0xe83690]: Keeping ciphersuite: DHE_RSA_AES_128_CBC_SHA256
|<3>| HSK[0xe83690]: Keeping ciphersuite: DHE_RSA_CAMELLIA_128_CBC_SHA1
|<3>| HSK[0xe83690]: Keeping ciphersuite: DHE_RSA_AES_256_CBC_SHA1
|<3>| HSK[0xe83690]: Keeping ciphersuite: DHE_RSA_AES_256_CBC_SHA256
|<3>| HSK[0xe83690]: Keeping ciphersuite: DHE_RSA_CAMELLIA_256_CBC_SHA1
|<3>| HSK[0xe83690]: Keeping ciphersuite: DHE_RSA_3DES_EDE_CBC_SHA1
|<3>| HSK[0xe83690]: Keeping ciphersuite: DHE_DSS_AES_128_CBC_SHA1
|<3>| HSK[0xe83690]: Keeping ciphersuite: DHE_DSS_AES_128_CBC_SHA256
|<3>| HSK[0xe83690]: Keeping ciphersuite: DHE_DSS_CAMELLIA_128_CBC_SHA1
|<3>| HSK[0xe83690]: Keeping ciphersuite: DHE_DSS_AES_256_CBC_SHA1
|<3>| HSK[0xe83690]: Keeping ciphersuite: DHE_DSS_AES_256_CBC_SHA256
|<3>| HSK[0xe83690]: Keeping ciphersuite: DHE_DSS_CAMELLIA_256_CBC_SHA1
|<3>| HSK[0xe83690]: Keeping ciphersuite: DHE_DSS_3DES_EDE_CBC_SHA1
|<3>| HSK[0xe83690]: Keeping ciphersuite: DHE_DSS_ARCFOUR_SHA1
|<3>| HSK[0xe83690]: Keeping ciphersuite: RSA_AES_128_CBC_SHA1
|<3>| HSK[0xe83690]: Keeping ciphersuite: RSA_AES_128_CBC_SHA256
|<3>| HSK[0xe83690]: Keeping ciphersuite: RSA_CAMELLIA_128_CBC_SHA1
|<3>| HSK[0xe83690]: Keeping ciphersuite: RSA_AES_256_CBC_SHA1
|<3>| HSK[0xe83690]: Keeping ciphersuite: RSA_AES_256_CBC_SHA256
|<3>| HSK[0xe83690]: Keeping ciphersuite: RSA_CAMELLIA_256_CBC_SHA1
|<3>| HSK[0xe83690]: Keeping ciphersuite: RSA_3DES_EDE_CBC_SHA1
|<3>| HSK[0xe83690]: Keeping ciphersuite: RSA_ARCFOUR_SHA1
|<3>| HSK[0xe83690]: Keeping ciphersuite: RSA_ARCFOUR_MD5
|<2>| EXT[0xe83690]: Sending extension SERVER NAME (19 bytes)
|<2>| EXT[0xe83690]: Sending extension SAFE RENEGOTIATION (1 bytes)
|<2>| EXT[0xe83690]: Sending extension SESSION TICKET (0 bytes)
|<2>| EXT[SIGA]: sent signature algo (4.2) DSA-SHA256
|<2>| EXT[SIGA]: sent signature algo (4.1) RSA-SHA256
|<2>| EXT[SIGA]: sent signature algo (2.1) RSA-SHA1
|<2>| EXT[SIGA]: sent signature algo (2.2) DSA-SHA1
|<2>| EXT[0xe83690]: Sending extension SIGNATURE ALGORITHMS (10 bytes)
|<3>| HSK[0xe83690]: CLIENT HELLO was sent [139 bytes]
|<4>| REC[0xe83690]: Sending Packet[0] Handshake(22) with length: 139
|<4>| REC[0xe83690]: Sent Packet[1] Handshake(22) with length: 144
|<4>| REC[0xe83690]: Expected Packet[0] Handshake(22) with length: 1
|<4>| REC[0xe83690]: Received Packet[0] Alert(21) with length: 2
|<4>| REC[0xe83690]: Decrypted Packet[0] Alert(21) with length: 2
|<4>| REC[0xe83690]: Alert[2|40] - Handshake failed - was received
|<2>| ASSERT: gnutls_record.c:726
|<2>| ASSERT: gnutls_record.c:1122
|<2>| ASSERT: gnutls_handshake.c:2762
*** Fatal error: A TLS fatal alert has been received.
*** Received alert [40]: Handshake failed
|<4>| REC: Sending Alert[2|80] - Internal error
|<4>| REC[0xe83690]: Sending Packet[1] Alert(21) with length: 2
|<4>| REC[0xe83690]: Sent Packet[2] Alert(21) with length: 7
*** Handshake has failed
GnuTLS error: A TLS fatal alert has been received.
|<4>| REC[0xe83690]: Epoch #0 freed
|<4>| REC[0xe83690]: Epoch #1 freed
root@mybox:~/wget/wget-1.16.3# gnutls-cli --version
gnutls-cli (GnuTLS) 2.12.20
Packaged by Debian (2.12.20-8+deb7u3)

**Comment by TingPing** [comment]
Your build of gnutls does not support any cipher that the server does, it requires ECDSA.

**Comment by mkunz7** [comment]
Curl was able to grab the file. Updating gnutls made it so gnutls-cli worked. We should implement a mirror for those of use without tls v1.2 or enable other ciphers. My desktop was failing because of a proxy.

**Comment by TingPing** [comment]
Well anybody is free to mirror the tarballs (they are even signed) but ECDSA is common enough that I won't be changing it (and anything old enough to not have it probably can't build hexchat anyway).

**Comment by mkunz7** [comment]
Some proxies don't support tlsv1.2. Current settings don't allow fallback. Your common user isn't going to want to compile from the source off of github when they could just grab the binary. Do we really need a tls1.2 only level of security? Just my 2cents.

**Comment by TingPing** [comment]
Your common user doesn't use an insecure proxy. It should work fine on any supported platform.
