### ISSUE TITLE
Text doesn't have a linebreak once it reaches the margin

### ISSUE THREAD

**Issue by Naththo** [hexchat/hexchat#1499]
Maximized:
![https://i.imgur.com/ceJqcW9.png](https://i.imgur.com/ceJqcW9.png)

Resized:
![https://i.imgur.com/H9uAzmH.png](https://i.imgur.com/H9uAzmH.png)

Using HexChat 2.11.0 on Windows 10.

**Comment by RichardHitt** [comment]
Hi Nathan, could you please provide a step-by-step procedure for reproducing this problem?  Thanks.  Maybe provide two step-by-step procedures, please, one for "Maximized: and one for "Resized".

**Comment by Naththo** [comment]
There is no step by step procedure. If I, for example send a long message which should go to a new line, it doesn't.

For example, if I send the following string it goes underneath the userlist rather than to a new line.
`Vivamus vitae tellus eu ipsum luctus feugiat ut sed velit. Sed rutrum facilisis dui. In nec rhoncus turpis. Nulla id varius nibh. Vestibulum tristique consectetur lectus ac lobortis. Curabitur risus enim, pellentesque eu pretium eget, imperdiet quis tellus. Mauris fringilla velit non neque pharetra hendrerit. Suspendisse pulvinar leo nulla.`

![https://i.imgur.com/gkLcGaq.png](https://i.imgur.com/gkLcGaq.png)

It is literally just sending a string which is longer than the width of the main container.

**Comment by Naththo** [comment]
So I just tried the `Classic` theme and that works fine. So I guess it's something to do with the theme. Any ideas?

**Comment by Naththo** [comment]
Weird. I just reverted it to the theme I was using and it now works. I guess this can be closed since I don't really know how to reproduce this.

**Comment by Naththo** [comment]
So it appears the issue I had was having one single %H in the text event.

I was using `%O< %C20$3$1 %O>%H%O%C30$t$2%O` and after I removed the %H it was sorted.
