### ISSUE TITLE
Hexchat not starting as intended when run by an external application (Windows, portable mode)

### ISSUE THREAD

**Issue by akvgergo** [hexchat/hexchat#1500]
I assigned hexchat.exe to one of the macro keys on my keyboard for conveniency, but whenever I try to start the application this way, instead of loading the configs from the installation folder, it will always try to load it from \appdata\roaming\hexchat. Is there some kind of starting parameter/argument that I need to specify if I want to start the application this way?

Using win 8.1 and version 2.10.2

**Comment by TingPing** [comment]
The `portable-mode` file must exist in the CWD when launched.

**Comment by akvgergo** [comment]
That empty file in my installation directory? Because that's there.

**Comment by TingPing** [comment]
The problem is whatever tool is launching it has the wrong CWD.

**Comment by akvgergo** [comment]
It's a standard macro manager, and I've tried starting it using both the .exe in the CWD and the desktop shortcut. Are you sure it's not on the applications end? If you're sure, then worst case scenario, I just reinstall with portable mode off. Not like I'm using it anyway :P

**Comment by TingPing** [comment]
@akvgergo Pretty sure that was the cause and my patch fixes it. @tomek should be uploading a new build for you to test if you wish.

> Not like I'm using it anyway :P

Bad user!

**Comment by akvgergo** [comment]
I just like to have the application and the configs in one place :V. Anyway, Thank you for the quick response :D

**Comment by tomek** [comment]
@akvgergo https://dl.hexchat.net/hexchat/testing/tomek/issue1500/ you can check the build from this dir, proper test build will be uploaded later (in https://dl.hexchat.net/hexchat/testing/)

**Comment by akvgergo** [comment]
Yep, that fixed it. Thank you very much :ↄ
