### ISSUE TITLE
Please release a new version of hex chat

### ISSUE THREAD

**Issue by paladox** [hexchat/hexchat#1503]
Please release a new version of hexchat since last release was in November last year.

And it keeps freezing and closing on windows when the internet goes down.

Please release a new version for windows.

**Comment by TingPing** [comment]
> And it keeps freezing and closing on windows when the internet goes down.

Duplicate of #600 (note its not fixed in any new release).

**Comment by paladox** [comment]
But would be nice to have an update since its been a year. and this seems to be the best irc client for windows.

**Comment by tomek** [comment]
you can always use test build: https://dl.hexchat.net/hexchat/testing/ (yes they are fine and you can use them daily)

**Comment by paladox** [comment]
@TingPing I have tested the daily release of hexchat and seems to fix the frequent closing errors after disconnecting from the internet.

**Comment by TingPing** [comment]
The crash is a timing issue so it is not necessarily reliably reproducible and a lot of changes can make it appear more or less commonly.

**Comment by paladox** [comment]
Well it seems it dosent crash after network crashes. The application is still running for me when normally it would have crashed.
