### ISSUE TITLE
Crash on Hexchat startup

### ISSUE THREAD

**Issue by Suitaloo** [hexchat/hexchat#1508]
So my computer bluescreened when trying to start up hexchat, and I think that may have caused some issues with the client. Here's some details about the crash.

```
 Problem Event Name:	BEX
  Application Name:	hexchat.exe
  Application Version:	2.10.2.0
  Application Timestamp:	5474c5cc
  Fault Module Name:	hexchat.exe
  Fault Module Version:	2.10.2.0
  Fault Module Timestamp:	5474c5cc
  Exception Offset:	0005b4ad
  Exception Code:	c0000409
  Exception Data:	00000000
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1033
  Additional Information 1:	3098
  Additional Information 2:	30988ec824310fbb4ea4b6594542ef4c
  Additional Information 3:	1702
  Additional Information 4:	170289b3b29d3a4a4212d1b8c9f41533
```

I might just try re-installing it, if that doesn't work, I guess I'll go back to kiwi until it gets fixed. I tried re-installing it and it still crashes. Just something I thought should be included.

**Comment by TingPing** [comment]
Maybe the bluescreen corrupted a config file in *%appdata%\HexChat*, maybe try deleting the scrollback folder there.

**Comment by Suitaloo** [comment]
I deleted the scrollback folder, it still crashes. I looked through the folder though and all it contained were logs of conversations. No config files.

**Comment by TingPing** [comment]
That doesn't make sense, did you use portable mode?

**Comment by Suitaloo** [comment]
I don't think I did, but I did do a fresh install and it didn't fix the problem, so maybe that could be the reason that there were no config files for some reason. Wouldn't explain why there were chat logs though, considering I uninstalled then reinstalled. All that was in the folder was a folder that said "freenode" and then the logs inside of that folder, if that helps. The bluescreen happened while loading up hexchat as well, so that might have fucked something up.

**Comment by TingPing** [comment]
If you use portable mode there is a config folder where you installed it.

**Comment by Suitaloo** [comment]
I don't think I'm using portable mode... How can I tell if I'm using it or not?

**Comment by TingPing** [comment]
A `portable-mode` file exists where you installed hexchat.

**Comment by Suitaloo** [comment]
There is no portable mode file

**Comment by TingPing** [comment]
so you have no config files at all a fresh reinstall doesn't fix anything. I have no idea.

**Comment by Suitaloo** [comment]
Then wouldn't the issue arise from the lack of config files?

**Comment by TingPing** [comment]
No, hexchat can run totally fine without configs, normally it would write them on start but even if writing them failed everything is fine.

**Comment by Suitaloo** [comment]
Well, are the config files CONF files? Because if so, they're just flat out in the roaming folder, things like hexchat.conf or addon_update_checker.conf

**Comment by TingPing** [comment]
So it is *%appdata%\hexchat.conf*? I am not sure how that would be possible.

**Comment by Suitaloo** [comment]
I honestly have no idea either, but they're there, and guessing by the fact that you have no idea how that's possible, I take it the config files being in the wrong location might have something to do with it? Just spitballing.

**Comment by TingPing** [comment]
Config files just being in weird places shouldn't cause any crash, try deleting them in case they are corrupt.

**Comment by Suitaloo** [comment]
All of them or just single ones?

**Comment by TingPing** [comment]
Might as well do all.

**Comment by Suitaloo** [comment]
And it worked! Thanks man!

**Comment by TingPing** [comment]
Great but do they still get created in the wrong place?
