### ISSUE TITLE
Add a /log command

### ISSUE THREAD

**Issue by Justinzobel** [hexchat/hexchat#1515]
with options 

/log on (start logging current channel/pm)
/log off (obvious)
/log file (open log file with xdg-open)

**Comment by TingPing** [comment]
> /log on (start logging current channel/pm)
> /log off (obvious)

`/chanopt text_logging on`

> /log file (open log file with xdg-open)

https://github.com/Farow/hexchat-scripts/blob/master/viewlog.pl
