### ISSUE TITLE
[Request] Delay command

### ISSUE THREAD

**Issue by VasVadum** [hexchat/hexchat#1516]
I checked the servlist.conf file to get this for you so you can see what I currently use.

> C=nickserv identify --nope--
> C=ghost Vas --nope--
> C=nick Vas
> C=ECHO #chan1 #chan2 #chan3 #chan4 #chan5 #chan6 
> C=ECHO http://hexchat.readthedocs.org/en/latest/appearance.html (For later)
> C=mode Vas +px
> C=join #chan7,#chan8,#chan9

The problem is, I need a delay because for some reason, mode happens before my nick fully sets.  I don't know why.  It's odd.

What I'd like to be able to do, is add "DELAY" like "ECHO".  Echo is client side, yes?  So if DELAY is hit, then the client will stop there and wait before running next command.

Here's an example of what I'd do with delay:
> C=nickserv identify --nope--
> C=ghost Vas --nope--
> C=DELAY 1
> C=nick Vas
> C=DELAY 1
> C=mode Vas +px
> C=ECHO #chan1 #chan2 #chan3 #chan4 #chan5 #chan6 
> C=ECHO http://hexchat.readthedocs.org/en/latest/appearance.html (For later)
> C=join #chan7,#chan8,#chan9

DELAY 1, 1 second.  DELAY 5, 5 seconds.  etc.  Do you think you guys can add this to the client at all?  or is there already a method for this?

**Comment by berrythesoftwarecodeprogrammar** [comment]
/timer

```
Usage: TIMER [-refnum <num>] [-repeat <num>] <seconds> <command>
       TIMER [-quiet] -delete <num>
```
TIMER 1 nick Vas
TIMER 2 mode Vas +px
(after one second and after 2 seconds from typing TIMER)
