### ISSUE TITLE
adding a ctcp reply adds an 'auto replace' instead

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [hexchat/hexchat#1518]
hexchat 2.11.0
win 7 x64

when i add a ctcp reply and press save it doesnt get saved to ctcp replies, i open auto replace and see it there instead

**Comment by revmischa** [comment]
+1 i'm seeing this as well

**Comment by Arnavion** [comment]
Does it also happen with 32-bit HC?

**Comment by berrythesoftwarecodeprogrammar** [comment]
i cant run 32bit HC.
```
The program can't start because VCRUNTIME140.dll is missing from your computer. Try reinstalling the program to fix this problem. 
```

**Comment by berrythesoftwarecodeprogrammar** [comment]
doesnt happen on 32bit

**Comment by Arnavion** [comment]
Now try with latest 64-bit HC.

**Comment by berrythesoftwarecodeprogrammar** [comment]
which do you mean? where do i get it? i dont see any updates in here https://dl.hexchat.net/hexchat/testing/

**Comment by Arnavion** [comment]
HexChat-2.11.0-x64-1d8dd50.exe ...

**Comment by berrythesoftwarecodeprogrammar** [comment]
oh sorry, the modified dates arent changed in the directory listing

**Comment by berrythesoftwarecodeprogrammar** [comment]
yep that fixed it
