### ISSUE TITLE
Client related issues.

### ISSUE THREAD

**Issue by VasVadum** [hexchat/hexchat#1521]
I have two or three issues with the client.  I think I'll combine the startup commands here too, as I don't want to flood the place with a bunch of issues.  Unless you prefer that then I can split this up.

EDIT: Please let me know if you want me to split this up, and will do so right away (as soon as I find out)

-1. When I've lost connection, auto join has a channel we'll call #Chan8 in it as well as my start up commands also trying to rejoin that channel.
The issue here is that while I'm in channels
#Chan1, #Chan2, #Chan3, #Chan4, #Chan5, #Chan6, #Chan7, #Chan8, #Chan9, #Chan10 
And lose connection, I auto reconnect to all of them just fine.  Except #Chan8, while Chan2, 6, and 8 are in both auto join and /join 2,6,8 on start commands, Chan8 starts a new window with the logging reset to it's previously opened status ignoring all the stuff in the old one where the old one becomes (#Chan8) and stays that way while somewhere else in my list of connected channels, #Chan8 is sitting right there.  I had an instance where I had 5 (#Chan8) sitting there with a 6th working one.  This is getting very bothersome, it's really screwing up my logs big time for that channel.

-2. I have two channels set to "beep on message" but sometimes, others suddenly set themselves to beep on message without any warning, and start beeping on message.  I have no clue why or which channel it is either.  I would like you to add a ♪ before the # on channels with beep on message turned on.  But also stop channels that shouldn't have it from randomly being assigned.  It often happens with that channel above in issue 1, I think that it might even be the only one it's happened on thus far.

-3. I run some commands on startup, but one ALWAYS fails if I have just started the client up.

C=nickserv identify PasswordHere
C=ghost Vas PasswordHere
C=timer 2 nick Vas
C=ECHO #steam #TechFurs #ChanDisguised #ChanDisguised #ChanDisguised #floofdragons
C=ECHO http://hexchat.readthedocs.org/en/latest/appearance.html (note to self)
C=join #Chan2,#Chan8,#Chan6
C=timer 3 mode Vas +px

I've tried other combinations of this, but mode ALWAYS fails, no matter what.  Even before I used timer.  Before I used timer, everything else was flawless and perfect, mode is the only one that can't execute properly.  it claims no user with that name exists.  As a note, I used the same Chan2 8, and 6 examples from the first two issues so you see where Chan8 is in the join command.  :P 

This issue only appears to happen on first start, After all commands have been run, and auto joins have executed (the list of 20 J items below the C= items), /mode then works properly and each reconnect after.

**Comment by VasVadum** [comment]
I figured out why Mode is broken.  Your IRC client forces /nick changes to not be able to happen till the END of the join list.  I want my commands run in PROPER ORDER.  The same damn order I run them in.

-Notice- {from NickServ} Password accepted - you are now recognized. (Idenfiied)
-Notice- {from NickServ} Nick VasVadum isn't currently in use. (Ghosted)
-Notice- {from NickServ} Nick Vas isn't currently in use.(Ghosted)
»» Vas_Vadum sets mode +p Vas_Vadum (mode change)
»» FurNet :No such nick/channel (mode change)
»» FurNet :No such nick/channel (mode change)
»» You are now known as VasVadum (nick change)
»» You are now known as Vas (nick change)

-------------------------------------------------------------------------------------------------
This is how I have my commands set up to run.

C=nickserv identify PasswordHere
C=ghost VasVadum PasswordHere
C=ghost Vas PasswordHere
C=timer 3 nick VasVadum
C=timer 3 nick Vas
C=ECHO #steam #TechFurs #Nupe #Nupe #Nupe #floofdragons
C=ECHO http://hexchat.readthedocs.org/en/latest/appearance.html
C=mode Vas_Vadum +px
C=mode VasVadum +px
C=mode Vas +px
C=join #Nupe,#Nupe,#Nupe
J= +13 more
J=#Starcraft
J= +5 more

-------------------------------------------------------------------------------------------------
This is how your client appears to run it:

C=nickserv identify PasswordHere
C=ghost VasVadum PasswordHere
C=ghost Vas PasswordHere
C=ECHO #steam #TechFurs #Nupe #Nupe #Nupe #floofdragons
C=ECHO http://hexchat.readthedocs.org/en/latest/appearance.html
C=mode Vas_Vadum +px
C=mode VasVadum +px
C=mode Vas +px
C=join #Nupe,#Nupe,#Nupe
J= +13 more
J=#Starcraft
J= +5 more
C=timer 3 nick VasVadum
C=timer 3 nick Vas

**Comment by Arnavion** [comment]
You're running commands in the middle with `timer 3` and then getting surprised when they run after the commands that follow them?

In any case even if you removed the use of timer, the commands would still be sent in close succession, so it's possible the server will drop them. If you want a complicated set of order-dependent commands then either use progressively larger timers or write a script.

**Comment by VasVadum** [comment]
Oh, ok, so I was misinformed on #1516 as to what timer does when I asked for a sleep command that pauses the entire line of commands following that line.  Yes I figured this out just now, don't close this damn thing, there were two more issues there!  Oh fine, I'll re-make two more issues with those two issues.

**Comment by Arnavion** [comment]
Correct.

**Comment by Mikaela** [comment]
I am not sure how relevant to this issue this is, but

> C=timer 3 mode Vas +px

Why do you hardcode nick which is bound to fail while HexChat should provide you `umode` command? I think there might also be some variable containing the current nick which would work with `mode`.

**Comment by VasVadum** [comment]
....  Would have been nice had someone actually told me /umode +p works.  I've been told by most everyone to use /mode Username +p, no one even in the tech/irc support channels had said /umode exists.

**Comment by TingPing** [comment]
`/help -l` will tell you every single command in hexchat, also if you hover over the *Connect Commands* area it will show variables you can use for similar things.

**Comment by VasVadum** [comment]
Hah, /umode doesn't work on startup either.  I get a different message though.
»» Vas_Vadum :No such nick/channel
Where as it is normally;
»» furnet :No such nick/channel
How hilarious is that.  :P I mean, wow.  Mode and umode can't be run on startup.  That's funny.

**Comment by TingPing** [comment]
It has to be ran after registration but otherwise should be fine.

**Comment by VasVadum** [comment]
You can see that it is run after identified and nick changes.  This is my newest and most current command list.

> C=nickserv identify PasswordHere
> C=ghost VasVadum PasswordHere
> C=ghost Vas PasswordHere
> C=nick VasVadum
> C=nick Vas
> C=ECHO #steam #TechFurs #Nupe #Nupe #Nupe #floofdragons
> C=ECHO http://hexchat.readthedocs.org/en/latest/appearance.html
> C=umode +px (fails 70% of the times I tried reconnecting the last 10 times)
> C=join #Nupe,#Nupe,#Nupe
> C=timer 1 umode +px (now added these as a backup)
> C=timer 2 umode +px
> C=timer 3 umode +px
> J=(19 channels here)

**Comment by TingPing** [comment]
Makes sense, if you call umode the second after you send a nick there is a delay between that and it replying 'you have a new nick'.

**Comment by VasVadum** [comment]
timer doesn't solve this.  Timer delays the command, but takes the name used during the delay start.  So all 4 umodes in that example use the same old name, timer just delays them to run at different times.  Proof;

> -Notice- {from NickServ} Password accepted - you are now recognized. (Identify)
> -Notice- {from NickServ} Nick VasVadum isn't currently in use. (Ghosted)
> -Notice- {from NickServ} Nick Vas isn't currently in use. (Ghosted)
> »» You are now known as VasVadum
> »» You are now known as Vas
> »» Vas_Vadum :No such nick/channel (Nodelay) (joincommand)
> »» Vas_Vadum :No such nick/channel (1 second delay)
> »» Vas_Vadum :No such nick/channel (autojoin channels) (2 second delay)
> »» Vas_Vadum :No such nick/channel (3 second delay)
> »» Vas sets mode +p Vas (manually run after all else failed)

So, even if I use timers, it doesn't help.  I now need to change all of them to mode all of my names 3 seconds after my nick change.  Without the ability to slow down commands sent to the network, I can't make them run correctly.  Shouldn't there already be a delay commands option in the client for networks that don't like you running a bunch on starting?  I mean, in the settings.  A delay between each command run?  It is already a known issue that some services don't let you send a bunch of commands after all and instead of queing you up, the commands get ignored/deleted.  I figured, if this is such a major problem, people by now would have added a solution to their IRC clients.  I guess not.  Timer doesn't quite fit that with this client and how it works because you have to disable other features of the client to make timer work.

**Comment by berrythesoftwarecodeprogrammar** [comment]
lol

**Comment by VasVadum** [comment]
I added /umode +p 10 times to my command list which is executed like 2 seconds apart each time.  All it does is fail each time.  Here's the raw log of a few tries, and my manual try after that.

&lt;&lt; MODE FurNet Vas +px
&gt;&gt; :lynx.furnet.org 401 Vas FurNet :No such nick/channel
&lt;&lt; MODE FurNet Vas +px
&gt;&gt; :lynx.furnet.org 401 Vas FurNet :No such nick/channel
&lt;&lt; MODE Vas +p
&gt;&gt; :Vas MODE Vas :+p
