### ISSUE TITLE
Auto Join fails to re-join one channel in particular.

### ISSUE THREAD

**Issue by VasVadum** [hexchat/hexchat#1522]
When I've lost connection, auto join has a channel we'll call #Chan8 in it as well as my start up commands also trying to rejoin that channel.
The issue here is that while I'm in channels
#Chan1, #Chan2, #Chan3, #Chan4, #Chan5, #Chan6, #Chan7, #Chan8, #Chan9, #Chan10
And lose connection, I auto reconnect to all of them just fine. Except #Chan8, while Chan2, 6, and 8 are in both auto join and /join 2,6,8 on start commands, Chan8 starts a new window with the logging reset to it's previously opened status ignoring all the stuff in the old one where the old one becomes (#Chan8) and stays that way while somewhere else in my list of connected channels, #Chan8 is sitting right there. I had an instance where I had 5 (#Chan8) sitting there with a 6th working one. This is getting very bothersome, it's really screwing up my logs big time for that channel.

I won't be saying the channel name publicly.

**Comment by TingPing** [comment]
Does the channel require authentication? What does *Window > Raw Log* look like?

**Comment by VasVadum** [comment]
The three channels I have in auto join and /join 1,2,3 are all the same on authentication rules.  The other two work, while this one that doesn't for some reason doesn't.

I'll have to check this and see.  I will edit this in a minute, I'm going to toggle my phone's tether a few times and watch.
