### ISSUE TITLE
Milliseconds in timestamps

### ISSUE THREAD

**Issue by Sanqui** [hexchat/hexchat#1530]
It doesn't appear that Hexchat supports logging fractions of seconds in timestamps.  It would be great if a new formatting code could be added for that.

Python supports `%f` for microseconds, and http://strftime.net/ suggests `%L` for milliseconds (and `%3`, `%6`, `%9` for milli, micro, nano, respectively).  I have no preference.

**Comment by TingPing** [comment]
HexChat just uses your OSes `strftime()` and it is up to them on what they support.

**Comment by Sanqui** [comment]
Is there any system which supports fractions of seconds in `strftime()`?  Is it possible or common to extend this function in any of these?  I'd consider this a feature missing from HexChat and not from my OS.

**Comment by TingPing** [comment]
I don't think so, the data passed to `strftime()` doesn't store anything more specific than seconds. This is entirely useless in an IRC client considering network latency and everything.

**Comment by Sanqui** [comment]
In most cases, probably, but I'm in an IRC channel with over 5000 people in it and often over 10 messages a second.  I'd like to log milliseconds for posterity, and also to identify bot messages, which often appear all at the same time.
So, with a legitimate use case, I believe this is a feature missing from HexChat.

**Comment by TingPing** [comment]
> In most cases, probably, but I'm in an IRC channel with over 5000 people in it and often over 10 messages a second.

The time you receive a message is irrelevant due to network latency in every step of the process.

> I believe this is a feature missing from HexChat.

One would need to switch from `time_t` everywhere messages are passed around and implement some custom formatting. It won't happen.

**Comment by Sanqui** [comment]
>The time you receive a message is irrelevant due to network latency in every step of the process.
That doesn't mean it's irrelevant.  What would the point of supporting timestamps at all, then?  I am interested in logging the exact time HexChat receives the message.  

It's a shame if it cannot reasonably be implemented.  However I believe this is a legitimate feature which HexChat is lacking, and it's limiting what it can be used for.

**Comment by TingPing** [comment]
> That doesn't mean it's irrelevant. What would be the point of supporting timestamps at all, then? 

Thankfully network latency is below hours, minutes, and usually seconds.

Go ahead and work up a patch for it, can't say it will be welcomed but if it isn't terrible who knows.

**Comment by Farow** [comment]
Just write a simple logging script either in Python or Perl.

**Comment by Mikaela** [comment]
HexChat supports server-time and usually that means that HexChat uses the timestamp which the server gives so messages appear in the correct order.

On bouncer side, ZNC 1.7.x-git does this even if some people don't like it (https://github.com/znc/znc/issues/1144).

**Comment by Farow** [comment]
Do messages ever come in the wrong order from the server?
