### ISSUE TITLE
FR: Open a new tab when you send a private message

### ISSUE THREAD

**Issue by mdmower** [hexchat/hexchat#1539]
HexChat 2.10.2
Ubuntu 15.10 x64

I would appreciate a new setting:
* _Open a new tab when you **send** a private message_

If I intend to send a few PMs in a row to a user, it's nice to not have to repeat `/msg username ...` each time, and instead I can type that once and then switch to the new tab to send subsequent messages. As it stands now, I have to wait for a reply or be in the same channel as the user to open a dialog window.

**Comment by TingPing** [comment]
`/query nick message` ?

**Comment by mdmower** [comment]
Thank you TingPing. I learned something new.
