### ISSUE TITLE
Update hexchat to support date formats in comments

### ISSUE THREAD

**Issue by paladox** [hexchat/hexchat#1547]
Hi currently in hexchat it shows the time that the comments were submitted. But it doesn't show the date with the time. Since if it was yesterday it would show the time as if it was today and you woulden know which date or day it was submitted at.

**Comment by TingPing** [comment]
*Preferences > Settings > Appearance > Timestamp format*

See the possible formatting here: https://msdn.microsoft.com/en-us/library/fe06s4ak.aspx
