### ISSUE TITLE
Make channel tree area scrollable

### ISSUE THREAD

**Issue by txt-file** [hexchat/hexchat#1548]
### Steps to reproduce
* open so many chats that you get a scroll bar in the channel switcher tree view

### Expected behaviour
* whole view reacts to scrolling with mouse wheel

### Actual behaviour
* mouse wheel scrolling only reacts if the mouse cursor is over the scroll bar

### System config
* debian wheezy amd64
* hexchat: 2.10.0-1~bpo70+1

**Comment by TingPing** [comment]
This was fixed a year and half ago, get your distro to update - https://github.com/hexchat/hexchat/commit/a918ec2236eef4a24396eec7a89e6b8bdc0ee533

**Comment by txt-file** [comment]
That's great.

BTW: Thanks for this great irc client.
