### ISSUE TITLE
Server password with spaces is passed incorrectly

### ISSUE THREAD

**Issue by Lartza** [hexchat/hexchat#1550]
PASS parameter with spaces should be prefixed with : as per the RFC.
Otherwise the server doesn't recognize the password as a single parameter.
Current behaviour:
`<< PASS test password`
Expected:
`<< PASS :test password`

(For reference znc/znc#1188)

**Comment by Arnavion** [comment]
I worry about servers out there that don't strip the leading colon, so maybe better to only prefix it if the pass contains a space instead of unconditionally.

**Comment by Lartza** [comment]
That shouldn't happen though, since the first colon should always start the last parameter. Should be a bug that needs to be fixed in the server that case. Would be nice if someone could check how many irc daemons fail with always sending a colon.

**Comment by Lartza** [comment]
Apparently enough that this has been an issue to someone
martynsmith/node-irc#87
So probably should check for spaces before prefixing
