### ISSUE TITLE
Hexchat stay connected after network disconnect and reconnect

### ISSUE THREAD

**Issue by takaizu91** [hexchat/hexchat#1551]
This issue is a bit weird, whenever I have problem with the network (disconnect and stuff), other app/software disconnect and reconnect just fine but hexchat seems still connected, without new incoming chat from irc. It just sit there idle until I figured out my irc was already disconnected hours later and need to restart hexchat again to work porperly.

Is this some kind of known bug or it's only happen on my system? Not that problematic but more towards annoying since I didn't get any irc update and missing up some important conversation

**Comment by Arnavion** [comment]
[`/set net_ping_timeout 60`](https://github.com/hexchat/documentation/blob/master/settings.rst#list-of-settings) or similar value. Without constantly sending data it is impossible for an application or OS to know if the TCP connection is still valid.
