### ISSUE TITLE
Hexchat error with latest nightly build for windows

### ISSUE THREAD

**Issue by paladox** [hexchat/hexchat#1552]
Hi when I open hexchat on windows using the latest nightly hexchat release I am getting this error

LIST :This command could not be completed because it has been used recently, and is rate-limited.

when clicking on list of channels in the server drop down menu.

Please could this be fixed.

I am using windows 10.

**Comment by KindOne-** [comment]
IRC networks like freenode rate limit the ```/list``` command, so that is why you are seeing the ```LIST :This command could not be completed because it has been used recently, and is rate-limited.```

https://github.com/freenode/ircd-seven/blob/master/src/messages.tab#L287

**Comment by paladox** [comment]
I never got that message before until today.

**Comment by KindOne-** [comment]
Not an issue in hexchat. you just so happened to issue a ```/list``` command when the server load was high. Various commands on the IRCd are rate limited.

**Comment by Arnavion** [comment]
Probably because they're getting DDOSed currently.
