### ISSUE TITLE
Alt codes don't work

### ISSUE THREAD

**Issue by NekomataReece** [hexchat/hexchat#1557]
Heyo. I've just started using HexChat, but I cannot type anything using ALT+____ which worked fine on the other IRC I used to use. Help is appreciated.

-Thanks!

**Comment by nayuki** [comment]
HexChat uses GTK for its widgets, which behave somewhat differently from native Windows widgets.

Typing Windows' Alt+numeric codes is not supported. But as an alternative you can press Ctrl+Shift+U and type the hexadecimal Unicode code point for the character. For example, 'é' is 00E9.

**Comment by Arnavion** [comment]
Try as I might, I cannot get that to work on Windows. Works on Linux though.

**Comment by Arnavion** [comment]
Okay, Ctrl-Shift-U only works when input mode (right-click on the textbox) is set to "Simple".
