### ISSUE TITLE
Crashes when Win8.1 wake up (from suspend mode)

### ISSUE THREAD

**Issue by mzalazar** [hexchat/hexchat#1564]
I have win8.1 and when i push power button (it was in stand by mode) and my desktop is restored, then a window tell me that this program stops functioning :(

**Comment by TingPing** [comment]
Duplicate of #600

**Comment by paladox** [comment]
I noticed that under the chat bar that is on the right the users that are avalible to chat there is a green bar when you reconnect or lose connection that will load until it is fully green then it crashes.
