### ISSUE TITLE
SASL AUTHENTICATE does not work with a prefix

### ISSUE THREAD

**Issue by DanielOaks** [hexchat/hexchat#1566]
When an `AUTHENTICATE` message is sent from the server and it includes a prefix, it is not seen as a SASL message. This causes a hang when trying to authenticate with our server ([mammon](https://github.com/mammon-ircd/mammon)).

RFC1459 specifies that prefixes are an optional part of messages, and the `SASL` specification does not prohibit prefixes on this specific message.

This is caused by the handling of the `AUTHENTICATE` message [here](https://github.com/hexchat/hexchat/blob/78486b49d5b688ba5054631b849f8959846cf07b/src/common/proto-irc.c#L1338).

Here's an example log:
```
C: AUTHENTICATE PLAIN
S: :irc.dereferenced.org AUTHENTICATE +
```

Please note that if the `server-time` capability is activated, we also send the `time` tag on this message, as such:
```
C: AUTHENTICATE PLAIN
S: @time=2015-12-14T04:13:27.000Z :irc.dereferenced.org AUTHENTICATE +
```

**Comment by TingPing** [comment]
So as mentioned this in theory applies to every message we handle in `process_named_servermsg()` so it has just been wrong for decades.
