### ISSUE TITLE
My HexChat keeps crashing?

### ISSUE THREAD

**Issue by GTAXL** [hexchat/hexchat#1567]
http://pik.gtaxl.net/14_12_15_22_15_29.png

http://pastebin.com/9p2u2Swk

[22:22:47] Update Checker You have the latest version of HexChat installed!

I have Windows 7 Ultimate 64-bit SP1.

I also have HexChat installed as 64-bit.. 16GB RAM.

**Comment by TingPing** [comment]
You can try out a newer build here: https://dl.hexchat.net/hexchat/testing/

Otherwise you'll have to include more information. Have you tried Safe Mode? Does a specific network or plugin cause it?, etc
