### ISSUE TITLE
HexChat crashes with no info after updating to python 2.7.11

### ISSUE THREAD

**Issue by b0nk** [hexchat/hexchat#1568]
I open hexchat and when I press Connect after I select the server the program crashes. Using hexchat 2.10.2
I tried re-installing it. and also tried the x64 builds in the testing directory and got the same thing happens

Windows 7 Home Premium x64.

How can I get more info about the crash?

**Comment by b0nk** [comment]
OK problem solved. You need to set the system variables PYTHONPATH and PYTHONHOME to the root of the python installation.

**Comment by TingPing** [comment]
This seems to be the upstream issue over it: https://bugs.python.org/issue25824

Hopefully this is fixed in another bugfix release soon, until then the workaround mentioned above or just staying on 2.7.10 will work.

**Comment by Arnavion** [comment]
Since I was asked recently, HC cannot do anything to prevent this because Python calls `exit(1)` because of that bad regkey (something a library should never do).

**Comment by vBm** [comment]
Had the same issue and also danced around it by setting `%PYTHONPATH%`

**Comment by Unperceivable** [comment]
This workaround allows me to connect but returns the error that  "hcpython2.dll': %1 is not a valid Win32 application" despite re-installation. Other threads suggest that this is due to a mismatch between python and hexchat bit versions but they are both 64-bit.

**Comment by Arnavion** [comment]
1. Make sure you set both PYTHONPATH and PYTHONHOME
1. Make sure you don't have any other Python version in PATH
1. Try with 2.7.10 or earlier in case you're using 2.7.11 or 2.7.12 (I'm not sure the bugfix is in .12 or not)

**Comment by wolfy1339** [comment]
It is fixed in 2.7.12 according to the changelog
