### ISSUE TITLE
Weird one-character nickname notifications

### ISSUE THREAD

**Issue by alekratz** [hexchat/hexchat#1571]
There are some nicknames which are one character and really weird, but still valid. Specifically, the \ (backslash)and | (vertical bar) nicknames cause odd behavior. When using *either* nickname, and either the backslash *or* vertical bar is entered, it gives a notification; regardless of what your actual nickname. This is not intended behavior to the best of my knowledge.

**Comment by TingPing** [comment]
From the [IRC spec](https://tools.ietf.org/html/rfc1459):

>   Because of IRC's scandanavian origin, the characters {}| are
   considered to be the lower case equivalents of the characters []\,
   respectively. This is a critical issue when determining the
   equivalence of two nicknames.

**Comment by alekratz** [comment]
Ah, interesting. Thanks for the follow-up.
