### ISSUE TITLE
Option to disable middle-click closing of channels

### ISSUE THREAD

**Issue by Grinnz** [hexchat/hexchat#1575]
I frequently accidentally close channels by middle-click, I would like an option to disable this keybinding as I have no need to close channels with a mouse button.

**Comment by KindOne-** [comment]
Its been git for a while now. 74ff67acd3a51253c4941bc7322af346d408f47b 

#1232 

You can try out a newer build here: https://dl.hexchat.net/hexchat/testing/

**Comment by Grinnz** [comment]
Thank you!
