### ISSUE TITLE
hexchat does not see hunspell help debuging

### ISSUE THREAD

**Issue by mogorman** [hexchat/hexchat#1576]
Hi.  I am a nixos user and their version of the package seems to not connect with the spell checking code in hexchat.  Can anyone tell me how to go about debugging to see where the disconnect is?  I have a feeling its a path issue, or environment variable one.  but I am having trouble finding where / how hexchat is looking for spell check support

**Comment by TingPing** [comment]
HexChat uses the enchant library for spell checking, it is the one that actually finds and loads any dictionaries all HexChat does is set a language code which is configurable in preferences > input box.

**Comment by mogorman** [comment]
so enchant is included and linked from what i can tell.  I guess I should start looking at it then?

**Comment by TingPing** [comment]
hexchat doesn't actually link to enchant it is [loaded at runtime](https://github.com/hexchat/hexchat/blob/master/src/fe-gtk/sexy-spell-entry.c#L157-L205), that might be where your issue is at.

**Comment by mogorman** [comment]
that seems to be it from inotify.  just have to figure out now why the path is wrong

**Comment by mogorman** [comment]
i was able to fix the issue and send them a pr.  thank you for your help @TingPing
