### ISSUE TITLE
hexchat AppArmor profile for better security

### ISSUE THREAD

**Issue by adrelanos** [hexchat/hexchat#1577]
There is an AppArmor profile for XChat.
https://github.com/Whonix/apparmor-profile-xchat

It's been created/maintained by @troubadoour. We likely could port it to hexchat.

Would you be interested to ship it in official [hexchat git](https://github.com/hexchat/hexchat)?

**Comment by TingPing** [comment]
I think it would be better off to give this to Canonical (or whoever else uses apparmor) directly honestly, I certainly don't use a system with AppArmor and would be worse off maintaining it than them.

**Comment by adrelanos** [comment]
That would be Debian.

**Comment by TingPing** [comment]
Even better since Debian's changes would trickle down.
