### ISSUE TITLE
Hexchat simply won't open

### ISSUE THREAD

**Issue by Brugriff** [hexchat/hexchat#1582]
One day, about a month ago, Hexchat just stopped opening. I'd click the shortcut, I'd run the .exe and nothing would happen. I've reinstalled it twice now and it's still not working. I've tried both x86 and x64 versions of 2.10.2 (the version I was running when I ran into this issues) and still nothing is happening.

How can I fix this?

**Comment by TingPing** [comment]
Does the Safe Mode shortcut work? If so try removing the *%appdata%\HexChat\scrollback* folder.

**Comment by Brugriff** [comment]
Safemode does not work.

**Comment by TingPing** [comment]
Well it is almost surely something in that config folder so you can just rename it entirely to test.

**Comment by Brugriff** [comment]
What do you mean? Rename what, exactly?

**Comment by TingPing** [comment]
Like *%appdata%\HexChat* to *%appdata%\HexChat-backup*, then HexChat will make new configs.

**Comment by Brugriff** [comment]
That fixed it, thanks!

**Comment by TingPing** [comment]
Well you can track down what changed to help future people.
