### ISSUE TITLE
Opening the context menu on the channel list (tree) should focus the entry clicked on

### ISSUE THREAD

**Issue by FichteFoll** [hexchat/hexchat#1583]
Normal applications auto-focus the element that a context menu was opened on via right mouse click, but hexchat does not. At least not in the channel list/tree view. It does happen for the userlist however.

This is on Windows 7 using some test build from May.

**Comment by TingPing** [comment]
That sounds rather annoying, there are many times you just wan to do something to another tab without focusing it.

**Comment by Arnavion** [comment]
Applications aren't consistent about whether right-clicking a tab focuses it or not. IE, Chrome and Konsole don't switch to the tab. VS and Notepad++ do.

As for HC, you could argue for consistency between the user list and channel list / tree but I don't think such consistency really matters. The context menu *does* have the name of the channel at the top, so it's also not ambiguous which channel the context menu is open for.

**Comment by FichteFoll** [comment]
As @Arnavion mentions, it is not uncommon practice to focus both the tab item and the tab when right-clicking it, but it's inconsistent among software. FireFox follows the webbrowser trend in that it doesn't focus, whereas Sublime Text follows the text editor trend and does focus. It is certainly not clear in which section hexchat belongs.

However, there are also ways for improvement even without focussing the tab.
Basically, there are the following options:

- Focus the tab when using context menu on it
- Don't focus the tab. This option has three sub-options:
  - A secondary selection in a different color (I'm unsure if supported)
  - Highlight the clicked tab item but do not focus the channel tab when it's right-clicked. When the menu is closed, highlight the original active tab item again. Might be inconsistent with how the active channel is represented in the list.
  - Current behavior (don't change tab item highlight)

Ideally, there would be a setting to toggle between the two main options.

**Comment by Arnavion** [comment]
>It is certainly not clear in which section hexchat belongs.

HC belongs in the section of "if it ain't broke don't fix it."

>Ideally, there would be a setting to toggle between the two main options.

No, not at all "ideally." This is a silly thing to add an option for.

As I said the context menu already tells you which channel it's for. There's no pressing need to clarify it further.
