### ISSUE TITLE
Oper message commands not working properly

### ISSUE THREAD

**Issue by rscs** [hexchat/hexchat#1590]
/chatops Testing 1,2,3 ... this is a test
/globops Testing 1,2,3 ... this is a test
/locops Testing 1,2,3 ... this is a test

Each of these commands just transmits the word "testing" and not the complete message.

* *** Global -- from xp1: Testing
* *** LocOps -- from xp1: Testing
* *** ChatOps -- from xp1: Testing

In order to send the complete message, I have to prefix the message with a colon:

/chatops :Testing 1,2,3 ... this is a test
/globops :Testing 1,2,3 ... this is a test
/locops :Testing 1,2,3 ... this is a test

* *** ChatOps -- from xp1: Testing 1,2,3 ... this is a test
* *** Global -- from xp1: Testing 1,2,3 ... this is a test
* *** LocOps -- from xp1: Testing 1,2,3 ... this is a test

I know the colon prefix is part of the RFC, but the client should automatically add it so the user does not have to remember to.

**Comment by TingPing** [comment]
None of these are client commands, you are just sending raw messages to the server. You can manually add them in *Settings > User commands* and you would set it to something like `chatops :&2`.

**Comment by rscs** [comment]
Thank you for the quick response! This has solved it!
