### ISSUE TITLE
Hexchat closes immediately after opening

### ISSUE THREAD

**Issue by MoltenCheese** [hexchat/hexchat#1592]
Whenever I try opening Hexchat, it says, "* Can't open log file(s) for writing. Check the permissions on C:\Users\kin\AppData\Roaming\HexChat\logs\" and then closes by itself.

I've tried uninstalling and then re-installing Hexchat, but this still keeps on happening every time. When I checked "C:\Users\kin\AppData\Roaming\HexChat\logs\", I found nothing in the folder.

I use Hexchat 2.10.2 x64 on a Windows 7 computer. There are no viruses/dysfunctions on my computer, and I don't understand what the problem is.

Please help!

**Comment by TingPing** [comment]
Well closing on failing to open logs has been fixed, grab a new version here: https://dl.hexchat.net/hexchat/testing/

As to why it can't open the logs I don't know.

**Comment by MoltenCheese** [comment]
It's working now. Thank you very much, TingPing!
