### ISSUE TITLE
No alerts (pings) on select channels

### ISSUE THREAD

**Issue by uyscuti-wiki** [hexchat/hexchat#1593]
Alerts (pings) on highlighted messages aren't working on select channels (in my case, 2 of the 24 channels I'm in).

**Comment by TingPing** [comment]
Does `/chanopt` in those channels say anything if off?

**Comment by uyscuti-wiki** [comment]
Yes `alert_beep` was OFF! Turned it on using `/chanopt alert_beep ON`
Thanks for the help :)

**Comment by uyscuti-wiki** [comment]
`alert_beep..........: ON `
` alert_taskbar.......: {unset}`
 `alert_tray..........: {unset}`
 `text_hidejoinpart...: {unset}`
 `text_logging........: {unset}`
 `text_scrollback.....: {unset}`
 `text_strip..........: {unset}`

Unfortunately turning that on, pings me on every single message :(

**Comment by TingPing** [comment]
`/chanopt alert_beep 2` will go back to unset.

**Comment by uyscuti-wiki** [comment]
Yep, that worked. Many thanks.
