### ISSUE TITLE
Addition to the python API

### ISSUE THREAD

**Issue by ajloveslily14** [hexchat/hexchat#1595]
an addition to the python api that lets you get names bye server. You can get the global one with hexchat.get_prefs("irc_nick1") however if you  have different nicks on different servers and change your nick to  hexchat.get_prefs("irc_nick1") then its the same everywhere.

**Comment by TingPing** [comment]
`hexchat.get_info('nick')` can return your current nick name, though being able to get all configured nicks in the network list is another possibility.
