### ISSUE TITLE
HexChat Does Not Recognize Cyrillic Characters

### ISSUE THREAD

**Issue by pretodor** [hexchat/hexchat#1596]
Hi guys,

I am running Linux Mint 17.2. Even though the 'Character set' is set to UTF-8 for the IRC network I am using, whenever somebody starts writing with Cyrillic characters HexChat returns them like so:
íå ìîæå äà áúäå ñèãóðåí ñúì ÷å ñâúðøèõ îòçàä

I would appreciate if you could look into this.

Regards,
Todor

**Comment by TingPing** [comment]
Sounds like the other users aren't using UTF-8.

**Comment by pretodor** [comment]
The thing is they do not have problems seeing each other's messages. Only I am left scratching my head trying to figure out what they are writing.

Also, I find it hard to believe **every one of them** not to be using UTF-8 which leads me to think the problem is coming from me.

**Comment by Arnavion** [comment]
What TingPing said. Of course they won't have trouble seeing each other's messages if they're all using the same non-UTF8 encoding.

If you don't believe it, join #hexchat on FreeNode and have him paste Cyrillic to you.

**Comment by pretodor** [comment]
I just did that. Everything worked fine as you suspected. Thanks for the help, @TingPing and @Arnavion . I will go right now and try to resolve the issue from the other end i.e. by asking the other users to change their encoding to UTF-8.
