### ISSUE TITLE
HexChat doesn't load perl plugin at startup or manually

### ISSUE THREAD

**Issue by rweiss55** [hexchat/hexchat#1599]
I have placed the dccautomanage plugin's perl file in %APPDATA%\HexChat, but the client does not list it in the list of plugins loaded at startup. I installed perl from the HexChat site and it's folder is in PATH. I have tried to load the plugin through HexChat --> Load plugin or script..., but it gives this error:

"Unknown file type %AppData%\Roaming\HexChat\addons\dccautomanage.pl. Maybe you need to install the Perl or Python plugin?
 Usage: LOAD [-e] <file>, loads a plugin or script"

I have also tried `LOAD -e dccautomanage` but this gives:

"Cannot access C:\Users\Rob\AppData\Roaming\HexChat\dccautomanage.pl
 No such file or directory"

I'm out of ideas and not really sure what the issue here is.

**Comment by TingPing** [comment]
You also must install the Perl plugin from HexChat's installer.

**Comment by rweiss55** [comment]
Thank you, that worked. When I read "On Windows - Select the plugins in the installer. - Install the language linked on our downloads page" on the HexChat FAQ page, I thought you had to do one or the other. I didn't realize that you needed to do both. It's working now.
