### ISSUE TITLE
[win10] hexchat crashing

### ISSUE THREAD

**Issue by esdf** [hexchat/hexchat#1601]
So I've downloaded the x64 build of hexchat and installed it. the server select window pops up, but after I try to connect to any server the client crashes. when I close the server window, the client crashes as well. basically, I can't use Hexchat on Win 10.

edit: just tried x86 build, it works properly. so please fix your x64 build.

**Comment by TingPing** [comment]
Did you install the Python plugin? If so what version of Python do you have installed?

**Comment by esdf** [comment]
I alraedy have a python installation, 2.7.11

**Comment by TingPing** [comment]
Duplicate of #1568
