### ISSUE TITLE
DCC: If file exists, rename new file instead of overwriting

### ISSUE THREAD

**Issue by Vlek** [hexchat/hexchat#1604]
When downloading files through DCC, if there is already a file in the downloads folder with the same name, then that item is overwritten. There ought to be an option to select whether overwriting is okay, or whether one should be asked to rename the new download. A decent option would be to have hexchat append a "(1)" at the end of duplicate filenames automatically.

**Comment by TingPing** [comment]
It already should do this, it appends `.<number>` to the end.

**Comment by Arnavion** [comment]
If the existing file on disk is smaller than the target size, it's assumed to be a partial download and the download is resumed from that position and appended to the file.

If the existing file is the same size or bigger, then a new file with a suffix like TingPing says is created.

If you've set it to prompt you for every download then you're already in full control of choosing a new target file.
