### ISSUE TITLE
Each line of pasted text is interpreted as a command when it begins with a slash

### ISSUE THREAD

**Issue by Ketsuban** [hexchat/hexchat#1606]
Sometimes I want to paste some text from my console to IRC. Sometimes a line of that text begins with a slash, because it's a path. For example:
```
thomas@klinklang:~$ which rustfmt
/home/thomas/.multirust/toolchains/stable/cargo/bin/rustfmt
```
When I paste this, I get only the first line, and a terse error message `* HOME/THOMAS/.MULTIRUST/TOOLCHAINS/STABLE/CARGO/BIN/RUSTFMT :Unknown command` in the status window.

What are the odds someone pasting more than one line of text into their IRC client is intending to execute commands? I'd wager the odds are low compared to people who want to give a path, so the preferable behaviour would be treating this as text without needing to escape the opening slash.

**Comment by TingPing** [comment]
There was an old hack to ignore file paths that could be improved, otherwise there isn't much that can be done.

**Comment by Arnavion** [comment]
And then someone who *does* want to paste multiple lines including a nickserv command (as dumb as it is) will see it sent as cleartext to whichever tab they're looking at.

Multiple lines or not, you have to remember to escape the opening slash if you're not typing a command.
