### ISSUE TITLE
Hexchat OpenSuSe Tumbleweed no sound

### ISSUE THREAD

**Issue by abetterfish** [hexchat/hexchat#1620]
Pretty much the title. No sounds are ever playing.

**Comment by TingPing** [comment]
HexChat uses libcanberra for sounds so you need to track that down on its end. A simple test would be to run the command `canberra-gtk-play --id='message-new-instant'`. Often your DE will provide volume settings specific to 'sound effects' or similar so ensure that isn't muted.

**Comment by Arnavion** [comment]
Works for me on Tumbleweed (20160222). Not only does it beep, it also beeps when the system volume is muted...
