### ISSUE TITLE
Rendering/highlight problems with fonts that use ligatures

### ISSUE THREAD

**Issue by dmlloyd** [hexchat/hexchat#1621]
That is, fonts that use an OpenType feature to automatically substitute character sequences with ligatured equivalents, where the ligature's width does not equal the width of the sum of the original characters.  The expected result is that the ligature will take up the space that it should; the actual result is that extra space is added to the end of each "chunk" after the ligature, and also, when you highlight text containing ligatures, rather than partially highlighting ligature components when you scroll over them, the ligature appears and disappears (being replaced by its constituent letters) depending on what direction you highlight in.

Other OpenType features may or may not work sensibly; here's a link with some more info:

http://ilovetypography.com/OpenType/opentype-features.html

I'd say either explicitly disable these features, or make them work correctly.

**Comment by TingPing** [comment]
Well as far as rendering goes that is purely up to Pango, we just throw it a line and say render it. The highlighting bug is probably a similar problem to #692

**Comment by Arnavion** [comment]
Merged into #692
