### ISSUE TITLE
Sysinfo: Add support for ARM

### ISSUE THREAD

**Issue by astravexton** [hexchat/hexchat#1624]
Running 2.10.2 on an ARM architecture `/sysinfo cpu` shows garbled text `CPU: 0 x ™™¹?˜&[T¹@ ((¶) @ -0MHz w/ unknown L2 Cache **`

/proc/cpuinfo output

```
Processor   : ARMv7 Processor rev 0 (v7l)
processor   : 0
BogoMIPS    : 13.52

processor   : 1
BogoMIPS    : 13.52

processor   : 2
BogoMIPS    : 13.52

processor   : 3
BogoMIPS    : 13.52

Features    : swp half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 
CPU implementer : 0x51
CPU architecture: 7
CPU variant : 0x1
CPU part    : 0x06f
CPU revision    : 0

Hardware    : UNKNOWN
Revision    : 0003
Serial      : 0000000000000000
```

**Comment by TingPing** [comment]
Looks like the [parse function](https://github.com/hexchat/hexchat/blob/78486b49d5b688ba5054631b849f8959846cf07b/plugins/sysinfo/unix/parse.c#L38-L108) doesn't handle arm at all. So obviously supporting it would be the ideal solution but it should probably return failure on un-handled archs anyway.

**Comment by TingPing** [comment]
You can verify that commit fixes the corruption, so now this issue becomes to add support for arm.
