### ISSUE TITLE
auto-replace fails if shift+space is pressed

### ISSUE THREAD

**Issue by zmike** [hexchat/hexchat#1625]
If spacebar is pressed, auto-replace will function as expected. If shift+spacebar is pressed, however, it will not work. This is annoying because sometimes if I am typing something like `NULL` I will release shift while pressing space after.

**Comment by TingPing** [comment]
I believe that is on purpose, as a way to avoid it. You can manually add this in *Settings > Keyboard Shortctuts* though.

**Comment by Arnavion** [comment]
Correct.

**Comment by zmike** [comment]
Ah, okay. Thanks for the tip.
