### ISSUE TITLE
Use existing python installation

### ISSUE THREAD

**Issue by flip111** [hexchat/hexchat#1627]
During the installation of hexchat (win64) i cancelled the installation of python because i already have that exact version installed. However now my python scripts do not run, how can i point hexchat to use the existing python installation?

**Comment by TingPing** [comment]
Beyond being the same version it has to be the same bitness also. If it is that means the `pythonXX.dll` is not in `PATH` and HexChat cannot find it so you can manually modify that or reinstall Python with "Install for all users" checked.

**Comment by flip111** [comment]
Well i have in path `C:\Users\flip101\AppData\Local\Continuum\Anaconda3` there is `python34.dll`. Installed `Anaconda3-2.3.0-Windows-x86_64` with python 3.4.3. How can i make sure python is loaded or not? I try to install this plugin https://github.com/Xesyto/Hexchat-DeadKeyFix By the way my hexchat is also 64bits `https://dl.hexchat.net/hexchat/HexChat%202.10.2%20x64.exe`

**Comment by TingPing** [comment]
> How can i make sure python is loaded or not?

*Window > Plugins and Scripts*

**Comment by flip111** [comment]
It only lists hcupd.dll and hcpython3.dll so i guess it's not finding the right pythonXX.dll ?

**Comment by TingPing** [comment]
> hcpython3.dll

**Comment by flip111** [comment]
Hey the error was in something very silly ... i just installed hexchat on a fresh windows installation and i didn't have "hide file extensions for known filetypes" turned off. so the file was actually placed as `DeadKeyFix-3.py.txt`. So after i removed the `.txt` it worked fine.

Just wondering though ... while searching for python dll on my system i noticed that quite a few programs come with their own dll like libreoffice and deluge. Perhaps it would be a good idea for hexchat to also include just the python dll?

**Comment by TingPing** [comment]
> Just wondering though ... while searching for python dll on my system i noticed that quite a few programs come with their own dll like libreoffice and deluge. Perhaps it would be a good idea for hexchat to also include just the python dll?

We only bundle the minimum that we have to which leaves bug/security fix releases up to the official Python builds.
