### ISSUE TITLE
Autoreconnecting to a server might reset your charset to UTF-8 (2.11.0)

### ISSUE THREAD

**Issue by StepS-** [hexchat/hexchat#1628]
At some point in 2.11.0, a bug was introduced that makes HexChat reset any custom charset selection to UTF-8 after auto-reconnecting to a server twice (from my tests), e.g. due to network drops. Thus you have to perform /charset manually to fix it.

**Comment by TingPing** [comment]
Introduced in 5749c53484369515c4e6df4a4730b1f34fab82b4 by always setting encoding in `server_set_defaults()` which is called on `server_connect()`.
