### ISSUE TITLE
Windows installer: Deletes logs and preferences on update

### ISSUE THREAD

**Issue by gralamin** [hexchat/hexchat#1630]
This morning the update checker found the newer version, so I ran the update. Unfortunately, it seems this process deleted the roaming appdata folder all logs and preferences are stored in on windows. As a result, the entire application had to be reconfigured, and I lost the sections of my logs I hadn't backed up.

Installing updates should instead preserve this folder, so users don't lose anything.

**Comment by JetCrusherTorpedo** [comment]
I had the portable version installed, and I installed the new version over the top of the old version. All preferences saved. I'm wondering if this is the correct way to update the portable version?

**Comment by Arnavion** [comment]
@gralamin Locally built installer didn't remove it for me, and there haven't been any changes in that regard, so it's strange. What OS and version of HC did you have before? 2.10.2 or a test build? x86 or x64 ?

@JetCrusherTorpedo Considering OP is talking about the AppData config directory getting deleted, they weren't using portable mode.

**Comment by gralamin** [comment]
@Arnavion I am running Windows 10 x64, and I had installed hexchat on windows 7. Previous build isn't certain, I don't have the installer sitting around any more so I can't tell for sure, but I believe it was 2.10.2

**Comment by TingPing** [comment]
The installer doesn't even have knowledge of where HexChat stores its configs, it certainly doesn't go deleting random things in *%appdata%*.

> I had the portable version installed, and I installed the new version over the top of the old version. All preferences saved. I'm wondering if this is the correct way to update the portable version?

@JetCrusherTorpedo This is unrelated but. NO. This leaves the possibility of mixing libs from two releases because there is no uninstaller to remove the old ones.

**Comment by gralamin** [comment]
Ran a few experiments:
*  I created a backup of my appdata, and tried to installing 2.12.0 overtop itself. This didn't delete anything.
* Uninstalling and reinstalling 2.10.2 does not lose the data. I confirmed this is the correct folder.
* Updating to 2.12.0 does not lose the data.

I now suspect it has something to do with installing it in Windows 7 then upgrading to windows 10, but I have no idea what.  I would not be opposed to closing this based on the difficulty in reproducing the issue.

**Comment by TingPing** [comment]
> I now suspect it has something to do with installing it in Windows 7 then upgrading to windows 10, but I have no idea what. I would not be opposed to closing this based on the difficulty in reproducing the issue.

Yea I am very confident nothing on hexchats end purposefully deleted anything so its likely to be an external problem of some sort...
