### ISSUE TITLE
 AutoLoad failed for: /usr/local/lib/hexchat/plugins/python.so

### ISSUE THREAD

**Issue by Brand3n** [hexchat/hexchat#1632]
I recently compiled the newer version (2.12), and when I started it up, it gave me this error:

`AutoLoad failed for: /usr/local/lib/hexchat/plugins/python.so`
`/usr/local/lib/hexchat/plugins/python.so: undefined symbol: _Py_ZeroStruct`

It connected to my IRC networks just fine, but when I go to 'Plugins and scripts' python isn't loaded. When I try to load it manually, it gives me the same "undefined symbol" error.

I'm using Linux Mint 17.3 (Ubuntu 14.04 base)

**Comment by Arnavion** [comment]
Make sure the python you're compiling against and the python you're linking to at runtime are the same version.

**Comment by Brand3n** [comment]
Output from configure, and python version: [http://pastebin.com/HUjXvB46](url)

**Comment by TingPing** [comment]
That's not anything useful from configure.. pastebin `config.log`

**Comment by Brand3n** [comment]
http://pastebin.com/HUjXvB46 (Same link, edited to be config.log)

**Comment by TingPing** [comment]
Just throwing a guess out there but mind trying this patch: https://paste.fedoraproject.org/338757/14578884/

**Comment by TingPing** [comment]
Oh duh I see the problem, so the m4 script broke "API" and renamed PYTHON_LDFLAGS to PYTHON_LIBS, your version is the older one and uses the former, we expect the latter, renaming that will fix it.
