### ISSUE TITLE
Connecting to a ZNC server with HexChat 2.12.0 triggers heuristic quarantine with Kaspersky Internet Security 16.0.0.614(e)

### ISSUE THREAD

**Issue by Donpedro13** [hexchat/hexchat#1633]
As the title says, when i connect to my ZNC server using the newest HexChat client, it triggers the heuristic protecton of KIS (Trojan.Win32.Generic) and it puts the exe in quarantine. If i connect to any other network, everything works fine. Unfortunately, I can't try other ZNC servers besides my own.

hexchat.exe passes file scan, the quarantine is triggered shortly right after i connect to my server.

![hexchat_kis_problem](https://cloud.githubusercontent.com/assets/2521782/13728270/4a8bc61c-e912-11e5-89d3-0d182d7f97f9.png)

I'm on Windows 10, using the 2.12.0 x64 build downloaded from [the downloads page](https://hexchat.github.io/downloads.html)

I know it's most likely a false positives, just wanted to make sure you know about this. I've reverted back to version 2.10.2, which is unafffected.

**Comment by TingPing** [comment]
This is not Kaspersky's bug tracker.

**Comment by Arnavion** [comment]
And https://encrypted.google.com/search?q=kaspersky+report+false+alarm will point you to said bug tracker.

**Comment by NeatNit** [comment]
I contacted Kaspersky about this, after it happened to me for the third time. After a bit of back and forth, I got this response, which I felt is worth putting here:

> Dear customer,
> 
> I appreciate the patience you have shown. My apologies for the delay in getting back to you.
> 
> We've just received a reply from our Virus Analysts with the latest update.
> 
> There was a False Detection. It will be fixed with soonest updates. If you are software developer of this application you can add you app in WhiteList of Kaspersky. To apply to Kaspersky White List program please refer to: http://www.kaspersky.com/partners/whitelist
> 
> Thank you for contacting us and have a nice day!

**Comment by TingPing** [comment]
> To apply to Kaspersky White List program please refer to: http://www.kaspersky.com/partners/whitelist

Broken link, nice.

@tomek Since you handle the Windows releases you can sign up here if you want: http://www.kasperskypartners.com/et.cfm?eid=register

At the end of the day I honestly don't care though, Kaspersky makes this problem for its users and that isn't our fault.

**Comment by NeatNit** [comment]
Huh? The link works for me.

**Comment by Arnavion** [comment]
Broken for me too. Keeps redirecting to http://usa.kaspersky.com/

**Comment by Arnavion** [comment]
I assume the correct link is http://whitelist.kaspersky.com/whitelist_program -> http://whitelist.kaspersky.com/program_registration

@TingPing Don't know if your partners link is the same thing in the end...
