### ISSUE TITLE
Matrix integration

### ISSUE THREAD

**Issue by fladd** [hexchat/hexchat#1638]
It would be great if HexChat could access the Matrix network (matrix.org).

An easy interface for IRC client to do so is available here: http://pto.im/

**Comment by Arnavion** [comment]
If it exposes the Matrix network as an ircd, what does HC need to do differently?

**Comment by fladd** [comment]
Integrate it?

**Comment by TingPing** [comment]
Repeating words doesn't suddenly clarify anything. The point of http://pto.im is to bridge existing irc clients to matrix so the question is what else do you expect HexChat to do?

**Comment by fladd** [comment]
I am sorry for the confusion. I was motivated by people in the Matrix HQ room to point you to PTO. I assumed it is software to be included in IRC clients to enable easy access to the Matrix network. I now understand that PTO is basically an IRC server to which clients can connect.

So, just forget about PTO.

The request stays the same, though: Support for the Matrix network in HexChat.

**Comment by TingPing** [comment]
Ok then I will just say that HexChat will not be becoming a multi-protocol client any time soon so bridge solutions like PTO are your best bet.

**Comment by fladd** [comment]
Fair enough...
