### ISSUE TITLE
2.12.0 gtk changes

### ISSUE THREAD

**Issue by miwu** [hexchat/hexchat#1639]
Has something significant changed with how Hexchat uses gtk? Since updating to 2.12.0, there are now borders everywhere there weren't before and it looks very strange.

**Comment by Arnavion** [comment]
There's not much point in asking that without telling us what OS you're talking about...

**Comment by miwu** [comment]
Right, sorry - Windows 10 x64. Still functioning perfectly on OS X El Capitan and Debian 8.

**Comment by Arnavion** [comment]
Portable mode or properly installed?

**Comment by miwu** [comment]
Portable, but I've tried a "fresh" install the proper way and it hasn't changed anything. If it's relevant, I'm attempting to use [this](https://gist.github.com/miwu/e47bbca5a9947264d571) gtkrc, and borders that were hidden in 2.10.0 are no longer.

**Comment by Arnavion** [comment]
Oh if it's a custom GTK theme then it's a different matter.

2.12.0 uses GTK 2.24.30 compared to 2.10.2's 2.24.25. I guess something changed between those versions and you need to update your theme for it.

**Comment by miwu** [comment]
Oh, I see - I'll look into it. Thanks!
