### ISSUE TITLE
mIRC colors should actually match mIRC

### ISSUE THREAD

**Issue by someperson** [hexchat/hexchat#1640]
HexChat's "mIRC Colors" by default do not match the actual colors used by mIRC. This can cause problems with some color combinations, which are easily readable with mIRC's palette, but much more difficult to read with HexChat's default settings.

Since HexChat is supporting mIRC's standard here, I think it's reasonable for it to implement the colors defined in that standard, which are documented [here](http://www.mirc.com/colors.html).

![palettes](https://cloud.githubusercontent.com/assets/376450/13733800/4853fd30-e965-11e5-869c-b66cbc721422.png)

**Comment by Arnavion** [comment]
>standard

That word doesn't mean what you think it means.

If you want the colors to be precisely equal to mIRC's then use the mIRC theme. Even the "standard" document you linked mentions that clients are free to have different colors.

HC's default colors seem to have a general muted theme to them, and I'm open to giving them slightly more contrast. But your justification ("must match mIRC") is invalid and your examples (blue on blue, red on red, and dark pink on dark teal) are unconvincing.

**Comment by someperson** [comment]
mIRC is the de facto standard for colors on IRC. It is telling that the setting in HexChat is literally called "mIRC colors". I am not arguing that the colors must be exactly identical to the ones used in mIRC, but I think they should at least behave similarly. Namely, if a combination of colors results in readable text on mIRC, it should be equally readable in HexChat. The simplest way to ensure that text always displays as intended is to simply match the colors suggested in the standard.

Also note that I am not suggesting changing any colors used for the interface. This makes switching to the mIRC theme not a proper solution to this problem, since this changes far more than just the mIRC colors.

**Comment by Arnavion** [comment]
>mIRC is the de facto standard for colors on IRC

> It is telling that the setting in HexChat is literally called "mIRC colors"

Again, mIRC does not get to decide the RGB values of each color, and no other client is under some obligation to use the same values as it.

>I am not arguing that the colors must be exactly identical to the ones used in mIRC

![image](https://cloud.githubusercontent.com/assets/1096010/13734944/a88e917e-e960-11e5-8f3c-22cf4259524a.png)

![image](https://cloud.githubusercontent.com/assets/1096010/13734948/b9576d32-e960-11e5-96f1-bbd8649d42e5.png)

>but I think they should at least behave similarly

Which they already do. Red is red. Green is green.

>Namely, if a combination of colors results in readable text on mIRC,

Which your examples aren't, as I already said.

---

So if you want the colors to be the same as mIRC, which your current PR does, the change is not welcome.

If you want to make them have more contrast, then as I already said I'm open to it.

**Comment by someperson** [comment]
Now I am confused. The colors used by mIRC are somehow not acceptable, but other colors that "have more contrast" than the current ones in HexChat would be. Under what criteria is one okay but not the other?

And to my eyes, the examples I posted are perfectly readable with mIRC's palette, but difficult to read with HexChat's default palette. It is examples like this that have actually come up while chatting that prompted me to bring up this issue.

**Comment by Arnavion** [comment]
>The colors used by mIRC are somehow not acceptable, but other colors that "have more contrast" than the current ones in HexChat would be. Under what criteria is one okay but not the other?

I guess in your universe there are only two shades of red, the one used by mIRC and the one used by HC. I'm glad I don't live in such a universe.

>And to my eyes, the examples I posted are perfectly readable with mIRC's palette

Congratulations? To me they're not.

**Comment by someperson** [comment]
> I guess in your universe there are only two shades of red, the one used by mIRC and the one used by HC. I'm glad I don't live in such a universe.

My point is that changing the colors to "have more contrast" would necessitate changing the shade of red used in HexChat. What makes some shades acceptable over others?

**Comment by Arnavion** [comment]
Let's see. I have one value was chosen to be dark but is maybe too dark. I have another value that's brighter but undesirable. How could I take these two values and come up with a happy compromise...

Maybe I could pick a value in between that is still dark to maintain the original intent, yet bright enough to be readable? Nah, math's too hard. Let's go shopping.

**Comment by hxe** [comment]
i think this is a good request. the colors 0-15 should match mIRC colours as they are used for art and other purposes which should look the same for users across different clients. 16+ should be used for internal purposes and themes.

themes can easily override these settings and they do. so one could easily just change their colors.conf to be
```
color_0 = ffff ffff ffff
color_1 = 0000 0000 0000
color_2 = 0000 0000 7f7f
color_3 = 0000 9393 0000
color_4 = ffff 0000 0000
color_5 = 7f7f 0000 0000
color_6 = 9c9c 0000 9c9c
color_7 = fcfc 7f7f 0000
color_8 = ffff ffff 0000
color_9 = 0000 fcfc 0000
color_10 = 0000 9393 9393
color_11 = 0000 ffff ffff
color_12 = 0000 0000 fcfc
color_13 = ffff 0000 ffff
color_14 = 7f7f 7f7f 7f7f
color_15 = d2d2 d2d2 d2d2
```
im not sure if op NEEDS the defaults to be like that, but i dont see anything wrong with that idea and think its a good one

**Comment by TingPing** [comment]
*cough* https://hexchat.github.io/themes.html *cough*
