### ISSUE TITLE
Windows build says '.\plugins\hcpython3.dll': The specified module could not be found.'

### ISSUE THREAD

**Issue by Diablo-D3** [hexchat/hexchat#1644]
Windows build says '.\plugins\hcpython3.dll': The specified module could not be found.'

Normally wouldn't be an issue, but all the ZNC HexChat scripts are in Python.

Broke on 2.12.0, was working fine on 2.10.2. Installer upgraded to new version of Python, may be related?

**Comment by TingPing** [comment]
You have to reboot after installing Python 3.5.

**Comment by turtlehunter** [comment]
Can confirm. Working fine in previous versions, reinstalled python, rebooted and still appear. Fix was using Python2 instead of 3

Also, tried compiling from source and it has a lot of errorss in the python implementation

**Comment by Arnavion** [comment]
@Diablo-D3 Note that the error text in the message comes from Windows but the DLL name comes from HC. That is, if the loader can't find any dependent DLLs like python35.dll it will print the same error. So check if that's the case.

**Comment by Diablo-D3** [comment]
@TingPing @Arnavion Rebooting fixed it.
