### ISSUE TITLE
Entry Point Not Found after updating to v2.12.0

### ISSUE THREAD

**Issue by srifqi** [hexchat/hexchat#1645]
After updating to lastest version (v2.12.0) I get this message:

![error message](https://cloud.githubusercontent.com/assets/4017302/13781780/1d538f04-eaf7-11e5-9323-42a70437dd96.png)

I'm on Windows 7 32-bit and here is some of installed programs:
![list of some Microsoft apps](https://cloud.githubusercontent.com/assets/4017302/13781924/9cbec6aa-eaf7-11e5-8e84-cfa58e36db3d.png)

Also, it worked well on v2.10.2. So, what's wrong?

**Comment by TingPing** [comment]
As mentioned on IRC you only installed the 32bit redist and used 64bit hexchat.
