### ISSUE TITLE
Security: Kaspersky detects 2.12.0 as Trojan

### ISSUE THREAD

**Issue by sa7mon** [hexchat/hexchat#1646]
Updated HexChat to 2.12.0 today and immediately Kaspersky (Internet Security) alerted me and deleted 

`C:\Program Files\hexchat.exe`
and
`C:\Users\user\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\Taskbar\HexChat.lnk`

Detected as PDM:Trojan.Win32.Generic

![hexchat2](https://cloud.githubusercontent.com/assets/3712226/13800526/ffdd1156-eaf7-11e5-8c5d-6acb17f6874a.PNG)

Hopefully it's just a false positive? I rolled back to 2.10 for now.

**Comment by GranoblasticMan** [comment]
I'm not sure why your Kaspersky is flagging it; according to VirusTotal.com, it's showing ZERO out of 56 engines detect anything: https://www.virustotal.com/en/file/3a3edc3e8b173ba348817af0a70ae84761b9d36c4d113bcecade3c912ddcb8b3/analysis/1458100735/

**Comment by Arnavion** [comment]
Search for existing issues before opening new ones.

Duplicate of #1633
