### ISSUE TITLE
[SOLVED] Upgraded to 2.12.0: Connection failed. Error: Mauvais descripteur de fichier

### ISSUE THREAD

**Issue by BenoitMartin2** [hexchat/hexchat#1649]
Hi,

HexChat can't connect anymore to my servers.
Build 2.12.0
OS : ArchLinux 4.4.5-1

**Comment by BenoitMartin2** [comment]
It's ok resetting the proxy to defaults param.
```
net_proxy_auth = 0
net_proxy_host = 
net_proxy_pass = 
net_proxy_port = 0
net_proxy_type = 0 
```

**Comment by TingPing** [comment]
So.. you just had bogus proxy settings?

**Comment by BenoitMartin2** [comment]
Yep, couldn't just use my "old" config file cause of this. had to remove it, reload HexChat and it ran.
