### ISSUE TITLE
HexChat UTF-8 Support Problem

### ISSUE THREAD

**Issue by HeckFin52** [hexchat/hexchat#1654]
Ah yeah, HexChat does not support UTF-8, makes Japanese, Chinese, Korean and Arabic not able to show.
Hope HexChat can add character settings in program

**Comment by TingPing** [comment]
You need to be more clear, what do the characters look like? Lego blocks?

**Comment by AGCaesar** [comment]
I just encountered an UTF-8 problem as well.
http://i.imgur.com/Yb7hQ5A.png
The user with the broken special characters used CTCP reply from Briza: VERSION Miranda NG 0.95.4 build #13028 (IRC v.0.11.0.3), (c) 2003-2014 J.Persson, G.Hazan.  So this might be Miranda NGs fault, but everyone else in the channel was perfectly able to see the ö ä ü and ß ....

**Comment by Arnavion** [comment]
@AGCaesar Your issue is likely to be #1636 not this one.

This one is likely to be user using a font that doesn't have unicode glyphs, as TingPing alluded.
