### ISSUE TITLE
Continuous crashing on Windows

### ISSUE THREAD

**Issue by PokeAcer549** [hexchat/hexchat#1655]
Whenever I try to start HexChat, it freezes and crashes on EFNet (not SSL), before joining my channels. This occurs on x86 and x64, and I have only spellchecker installed for plugins. No interpreters which was causing my issue before.

**Comment by TingPing** [comment]
Try removing any old scrollback files: `%appdata%\HexChat\scrollback`.

**Comment by PokeAcer549** [comment]
That actually fixed it, thanks!
