### ISSUE TITLE
Hexchat python support

### ISSUE THREAD

**Issue by Announcement** [hexchat/hexchat#1660]
*Hexchat* currently supports **Python**.

During the installer it makes me choose `2.7` or `3.5`
... I have both installed and want it to support _both_ at the same time please.

~ Windows (7)

**Comment by TingPing** [comment]
You can't have both, for one they have conflicting symbols, for two how could hexchat cleanly expose that to the user, the `/py` command can only work for one plugin.

**Comment by vgturtle127** [comment]
@Announcement @TingPing Why would support of both versions be useful? I always just use the latest version. I too have both installed, but I don't ever use more than one for any application.

I'm just curious as to your reasoning for wanting both, really. :smile:

**Comment by TingPing** [comment]
@vgturtle127 Some scripts just don't support Python 3.

**Comment by vgturtle127** [comment]
@TingPing That makes sense, older scripts would naturally not have the features that Python 3 might have.
