### ISSUE TITLE
HexChat 2.12.0 - code pages

### ISSUE THREAD

**Issue by smaragdus** [hexchat/hexchat#1662]
HexChat version 2.12.0 can no longer be used with servers which use code pages, quotation from change log:
"remove “IRC” encoding, replaced with UTF-8"
 which means that non-Unicode characters are not displayed properly, screen-shots below:
 - channel list - http://s20.postimg.org/6vp8ave19/Hex_Chat_2.png
 - channel - http://s20.postimg.org/g4rekzmx9/Hex_Chat_2.png
This problem does not occur in HexChat version 2.10.2 which uses mixed encoding. The latest version is useless to me and I have to revert to the previous one. So I cannot regard the removal of IRC encoding as an improvement.

**Comment by Arnavion** [comment]
Change your network settings to use the correct encoding instead of utf-8.

**Comment by smaragdus** [comment]
@Arnavion
Many thanks, problem seems solved.
