### ISSUE TITLE
non RFC compliant servers and ISON

### ISSUE THREAD

**Issue by ajloveslily14** [hexchat/hexchat#1664]
If you join a server, and it is not RFC compliant, hexchat keeps sending ISON (name of friend) even though it is getting no response. Perhaps make it so it tries x amount of times(maybe set in settings or using the /set command) and then stops if it gets no reply.

**Comment by TingPing** [comment]
As I mentioned on IRC you can limit which networks a user in the friends list applies to e.g. `/notify -n freenode,gimpnet bob` to easily avoid this issue.

**Comment by ajloveslily14** [comment]
Issue closed then i guess :+1:
