### ISSUE TITLE
Turn off chanview highlighting for join/parts.

### ISSUE THREAD

**Issue by justinabrahms** [hexchat/hexchat#1667]
I find it to be a bit maddening to have channels highlight when people join/part. I'd love to turn that off. I don't know gtk well enough to grok where to do that, but I think it's somewhere around  https://github.com/hexchat/hexchat/blob/78486b49d5b688ba5054631b849f8959846cf07b/src/fe-gtk/chanview.c#L476

Having an option to turn off highlighting for join/parts would make me very happy. I'd still want to know when people are talking to me or talking in general. This could even piggy back on the "turn off join/part notifications" thing, which I've already selected.

**Comment by TingPing** [comment]
*Preferences > Colors > New data*. Change it to black (normal text color).
