### ISSUE TITLE
Issue with log file line breaks

### ISSUE THREAD

**Issue by Nezumi-chan** [hexchat/hexchat#1675]
I'm not entirely sure what happened, but from about March 15th, log files are not displaying proper line breaks in Windows Notepad. They do in Wordpad, but that doesn't want to open log files while Hexchat is active. Not sure if it's something I did, or what, or why. Anyone have any help?

**Comment by TingPing** [comment]
HexChat now only uses unix line endings so you should use a text editor that can handle that. I honestly didn't even know an editor existed that couldn't before this.

**Comment by Nezumi-chan** [comment]
That could be it. Not sure why it suddenly stopped working, unless there was an update I forgot about, but... sounds about right, Notepad++ seems to do it well.

**Comment by TingPing** [comment]
Yea you forgot about 2.12.0 releasing :P. Anyway I don't really consider this a problem, sorry about the inconvenience though.

**Comment by Arnavion** [comment]
Yes regular Notepad can't handle LF endings.
