### ISSUE TITLE
Remove EFnet servers that aren't responding from the Network List

### ISSUE THREAD

**Issue by anonsubmitter** [hexchat/hexchat#1677]
Every EFnet server I've been connected to via HexChat's Network List has not responded and after a long redirection process I've finally been redirected to irc.efnet.org, which works perfectly but isn't even listed in the Network List. Could you remove all of the not responding EFnet servers from the Network List and replace them with irc.efnet.org and set it as the first and default server?

**Comment by TingPing** [comment]
I presume you are on an outdated server list from hexchat as i recently updated it. but this discussion already happened in #1039
