### ISSUE TITLE
2.9.6 version don't sends away message.

### ISSUE THREAD

**Issue by Wibol** [hexchat/hexchat#1692]
The away_show_message line is missing in hexchat.conf and its Preferences window option. I tried to add it manualy while Hexchat is closed, but at starup the line disappears again.

Thanks.

**Comment by TingPing** [comment]
Yes it was removed; Use third party scripts for such functionality such as: [awayannonce.py](https://github.com/hexchat/hexchat-addons/blob/master/python/awayannounce/awayanounce.py)
