### ISSUE TITLE
File choosers crash on 2.12.1

### ISSUE THREAD

**Issue by ylzhan** [hexchat/hexchat#1694]
Hello,

I just updated HexChat (2.12.1).

Problem:
1. Ask a file via dcc
2. Select a folder
3. After clicking on "OK" when selecting the destination folder, the program crashes with a "has stopped working" error. 

Info : 
Portable Mode: No
Build Type: x64
OS: Microsoft Windows 10 Family (x64)

Thanks.

**Comment by TingPing** [comment]
Just to confirm this happens on every file chooser? *Window > Plugins > Load* ?

**Comment by ylzhan** [comment]
@TingPing 

Yes. I tried "Window > Plugins > Load" and I have the same crash.

**Comment by chadj** [comment]
Also crashes for me when selecting an audio file under Chatting > Sounds in the preferences

**Comment by Liastre** [comment]
Same on Windows 7x64.

**Comment by belstgut** [comment]
I can confirm.

HexChat 2.12.1
Build: x64
OS: Win 10 Pro N

**Comment by Velyndra** [comment]
Can confirm, crashes on XDCC file transfer and default location change. Reverting to 2.12.0 causes no crash

Windows 10 Pro x64

**Comment by TingPing** [comment]
Yes yes we know just replying it does isn't useful.

**Comment by Liastre** [comment]
Well since that bug become known, I guess it would be better to add label _known_ or something like that, doesn't it? :)

**Comment by belstgut** [comment]
Normaly when someone reports a bug devs want to know if it is reproducible. So you can label it confirmed or so.

**Comment by TingPing** [comment]
@belstgut I understand, it is just that this crash was brought up a lot since the release and I am pretty salty nobody discovered it before release...

**Comment by Arnavion** [comment]
Fixed by https://github.com/hexchat/gtk-win32/commit/a4cd425

**Comment by TingPing** [comment]
New build with the fix is linked on [downloads](http://hexchat.github.io/downloads.html).
