### ISSUE TITLE
Feature Request: Minimize download XDCC bar

### ISSUE THREAD

**Issue by silveringking** [hexchat/hexchat#1696]
Hi I want to do a feature request, when you're downloading via xdcc with hexchat, a pop up bar appears on the channel and I want to be able to minimize it so I can resume chatting and I don't have to open 2 instances of hexchat at same time.

Is that possible? I think more people may have the same problem.

Thank you so much!

**Comment by TingPing** [comment]
Just close the dialog? Tranfsers don't stop and you can re-open it with *Window > File Transfers*.

**Comment by Poorchop** [comment]
It might also help to have utilities open in tabs. I use XDCC a bunch and it's much neater and lets you resume chatting without having to close the downloads.
