### ISSUE TITLE
Upgrade to 2.12.1, immediately crashes

### ISSUE THREAD

**Issue by zuluintl** [hexchat/hexchat#1701]
Upon any connection to any server, the program completely crashes: HexChat IRC Client has stopped working.

Windows 10 Pro Version 1511 (OS Build 10584.218)

IPv6 tunnel to the router. Crashes on IPv6 or on IPv4 to any EFNet server.

Completely removed all HexChat files and directories and installed fresh, and problem remains.

**Comment by Arnavion** [comment]
Try without the python plugins.

**Comment by ziddey** [comment]
Disable the identd server :(

**Comment by TingPing** [comment]
@ziddey Identd crash was fixed in 2.12.1-2 which was a rebuild. All new downloads link to that.

**Comment by djivad** [comment]
2.12.1-2 fixed it. Thanks!

**Comment by ziddey** [comment]
Thanks. Didn't realize there was a newer version.
