### ISSUE TITLE
Show an indicator at the top of a channel when a channel is scrolled up.

### ISSUE THREAD

**Issue by madprops** [hexchat/hexchat#1703]
Very often it happens that the channel chat is scrolled upwards and you not realize it easily (only way is checking the scrollbar) and sometimes even respond to old messages.

Something similar to that.

I think it is a useful visual feedback.

Obviously it can be optional and maybe be off by default. And maybe there could be options to control the colors and height.

Make it translucent on hover so you can read what's below it. And make it scroll to the bottom when clicked.

**Comment by madprops** [comment]
Actually it would be better to have it on the bottom (top of the input box)

**Comment by madprops** [comment]
Discord does this http://i.imgur.com/lRvXMJS.jpg

**Comment by TingPing** [comment]
Gtk3 easily provides a shadow if a window is scrolled up or down if that move ever happens.
