### ISSUE TITLE
Wrong right click context menu appears if username contains a full stop

### ISSUE THREAD

**Issue by emukidid** [hexchat/hexchat#1706]
If you right click a user normally you get the context menu to "Open Dialog Window", etc. 

If the user you've right clicked has a full stop character '.' in their name, the right click menu displayed is for a URL instead - this only happens when you do it from the text pane. The workaround is to scroll down the users list to find the user and right click from there.

**Comment by TingPing** [comment]
Well on normal networks `.` is invalid in the nick but in the case that a nick is also a URL it seems reasonable to show preference to the nick match.
