### ISSUE TITLE
Up/Down keyboard in channel tree

### ISSUE THREAD

**Issue by vlakoff** [hexchat/hexchat#1708]
I'm viewing the channels as a tree (default setting). I was expecting my keyboard up/down keys to switch channels when I have focus on this window section, but it's not the case.

Current alternatives:
* click on the channel,
* enable "scroll mouse-wheel to change tabs" setting then… use the mouse wheel.

Expected:
* Keyboard up/down should switch channels, when mouse is over the channel tree or it has been clicked inside to explicitly take focus on it. (your pick)

**Comment by Arnavion** [comment]
<kbd>Ctrl</kbd>-<kbd>PgUp</kbd>/<kbd>PgDn</kbd> are global shortcuts.

**Comment by TingPing** [comment]
Also configurable in *Settings > Keyboard Shortcuts*.
