### ISSUE TITLE
Modern/Material design?

### ISSUE THREAD

**Issue by thenoncoder** [hexchat/hexchat#1710]
The current design looks as old as the irc procotol itself is.

**Comment by TingPing** [comment]
HexChat's theme is provided by Gtk2, so look around and find Material design focused Gtk2 themes.

Some Google results:

- https://github.com/nana-4/Flat-Plat
- https://snwh.org/paper/theme

If HexChat ever makes it to Gtk3 we can do some fancier things out of the box and have more theme-ability with CSS but until then that is what you get.

**Comment by thenoncoder** [comment]
Any ETAs on out of the box support?

**Comment by Poorchop** [comment]
@thenoncoder see #1707 and [here](https://github.com/hexchat/hexchat/milestones/3.0.0)
