### ISSUE TITLE
Silent failing on invalid nick name selection

### ISSUE THREAD

**Issue by CubeTheThird** [hexchat/hexchat#1715]
This issue had been plaguing me for months, and I finally found the problem.
Previously, the selection for 1st 2nd and 3rd choice nick names was case sensitive, however it is now case insensitive. As my first and second choice were the same, only differing in capitalization, the servlist.conf file would refuse to save, as this is configured in the same dialog as the nick names. Strangely enough the hexchat.conf file had no issues. Because the name was previously set, and wasn't being modified, there was no indication or notification that the name was invalid, until attempting to modify it.

**Comment by TingPing** [comment]
> Previously, the selection for 1st 2nd and 3rd choice nick names was case sensitive, however it is now case insensitive. 

IRC is case insensitive, a few versions ago it just didn't care at all but I got tired of users not understanding you need unique nicks.

>  Because the name was previously set, and wasn't being modified, there was no indication or notification that the name was invalid, until attempting to modify it.

Looks pretty clear to me: http://i.imgur.com/exdgYha.png

I admit we could make it more verbose that it won't save, but the error icon is a pretty big indication there is an error.

**Comment by TingPing** [comment]
Oh I understand what you mean, it was a previous config...
