### ISSUE TITLE
Broken update due to portable mode no longer working

### ISSUE THREAD

**Issue by amivit** [hexchat/hexchat#1717]
I have Hexchat installed in portable-mode to my Dropbox, so regardless of where I open the client, my settings are staying the same. 

However for some silly reason, one of you contributors decided to hardcode the impossibility of installing hexchat in portable mode, unless it is on a thumb-drive. 

2.10.2 is fine, but I can no longer update as I get this stupid popup http://i.imgur.com/UcZy1iE.png

I'm sure I could trick this hardcoded detection by installing it to a thumbdrive, and then moving the files to my Dropbox again. However that seems silly, then I'd rather just go back to mIRC.

Could you please reconsider this game-breaking change?

**Comment by TingPing** [comment]
Sounds like you never actually set the dir to your Dropbox, it only checks for Program Files.

**Comment by amivit** [comment]
I think you were right, I must have messed up but I was sure I had the correct folder selected. Portable mode does indeed work. My apologies
