### ISSUE TITLE
Hexchat immediately crashes after saving text file

### ISSUE THREAD

**Issue by badon** [hexchat/hexchat#1720]
Hexchat immediately crashes after saving a text file. I tested this with the channel list on freenode, and with the raw log. The file is saved, but apparently Hexchat crashes immediately after it is saved.

**Comment by TingPing** [comment]
Make sure you have 2.12.1-2 from hexchat.github.io

**Comment by badon** [comment]
I have 2.12.1, and the updater says that is the latest version. Sorry, I forgot to mention my version.

**Comment by TingPing** [comment]
The updater doesn't understand the version 2.12.1-2. So I will say it again. Make sure you have 2.12.1-2 from https://hexchat.github.io

**Comment by badon** [comment]
I'm sorry, I missed the dash two part of the version you were speaking of. I tested 2.12.1-2 and I have been unable to trigger the bug again, so it appears to be fixed. Thanks!
