### ISSUE TITLE
Clicking URLs produces "Google Chrome is unresposive" notice

### ISSUE THREAD

**Issue by thebigl1** [hexchat/hexchat#1721]
I don't know what exactly caused it, but now whenever I simply left-click a URL in a channel, it pops up a notice saying "Google Chrome is unresponsive. Relaunch now?" with Yes/No buttons, and clicking Yes doesn't do anything at all. I can't find any settings to adjust. The only thing I can think of that may have caused this is having used CCleaner to clear out junk data.

**Comment by TingPing** [comment]
HexChat just gives it a URL, Chrome issues at that point should probably be reported to them.

**Comment by thebigl1** [comment]
Alright. Sorry for the confusion, you could probably go ahead and delete this.
