### ISSUE TITLE
Need help with python3 selenium webdirver code

### ISSUE THREAD

**Issue by nasiru825** [hexchat/hexchat#1726]
I am trying to test out selenium webdriver for python3.5 and i keep getting a error i already downloaded pip
MY CODE-
`from selenium import webdriver
from selenium.webdriver.common.keys import keys
driver= webdriver.FireFox()

driver.get("http://www.python.org")`

ERROR MESSAGE-
> Traceback (most recent call last):
  File "C:\Users\nasir_000\OneDrive\Documents\selenium.py", line 1, in <module>
    from selenium import webdriver
  File "C:\Users\nasir_000\OneDrive\Documents\selenium.py", line 1, in <module>
    from selenium import webdriver
ImportError: cannot import name 'webdriver'

**Comment by TingPing** [comment]
This is not a forum to discuss using Python.

**Comment by nasiru825** [comment]
What  Is It For THEN

**Comment by TingPing** [comment]
Surprisingly, HexChat.

**Comment by Poorchop** [comment]
@nasiru825 HexChat is an IRC client. You use it to connect to IRC networks, where you can join channels that are more appropriate for asking your question.

Look at [this](https://hexchat.readthedocs.io/en/latest/getting_started.html) if you need help understanding how to use HexChat to connect to a network. You'll want to connect to freenode and then join #selenium, and possibly #python as well. Be prepared to wait a long time for help.
