### ISSUE TITLE
Does not start after 30/05/2016 Windows 10 update

### ISSUE THREAD

**Issue by Gustavo6046** [hexchat/hexchat#1733]
Hello again. I tried to run this program after a LOOOONG update, however it doesn't run like the other programs.

Double-checked the registry folder of Python and it's as it should be.

Tried reinstalling it, didn't work.

Didn't find anything relevant in the search.

Thanks.
Gustavo

Oh, and the gspawn-win32-helper-console (which I though would help) I found gives this:
http://puu.sh/paBYd/d8544cfc73.png
Which means it's not receiving enough arguments.
If only Hexchat gave a error log...

Trying to open HexChat from console is immediate, but no output comes and a ghost process is leaved. HexChat still doesn't work even terminating this ghost process!

**Comment by Arnavion** [comment]
Try without the python plugin.

>Oh, and the gspawn-win32-helper-console (which I though would help) I found gives this:

You're not supposed to run it.

**Comment by Gustavo6046** [comment]
Nevermind, was fixed after a common restart.
