### ISSUE TITLE
Auto-Replacements do not work until saved

### ISSUE THREAD

**Issue by LordAkkarin** [hexchat/hexchat#1737]
I just noticed that auto-replacements do not seem to work out of the box until the auto-replace window was opened at least once and saved (this does not seem to apply to default entries however).

For instance a replacement like "(lenny)" to "( ͡° ͜ʖ ͡°)" will not take effect immediately after opening the application.

**Comment by TingPing** [comment]
How are you adding the replacement then?

**Comment by LordAkkarin** [comment]
It's not about adding it. They straight up just don't work when you save them and re-start the client until you open the window and hit save again.

Anyways: While trying to reproduce it on another machine it seems to be more of a random occurrence. ... weird one tbh

**Comment by TingPing** [comment]
What hexchat versions?

**Comment by LordAkkarin** [comment]
Version 2.12.1 (should be latest. I just downloaded it).

I'm not seeing things, am I?
![2016-05-31_11-12-31](https://cloud.githubusercontent.com/assets/297893/15669455/bfed46b4-2720-11e6-8e56-a0cdb7b0f3a5.gif)

**Comment by TingPing** [comment]
The same replacement string seems to work consistently here.

**Comment by Poorchop** [comment]
Are you using any scripts? It's working fine here too.

**Comment by LordAkkarin** [comment]
Nope. There's no scripts installed in my client at the moment.

It almost seems like HexChat isn't really capable of keeping up with me as it seems to work consistently when typing at about half speed.

**Comment by TingPing** [comment]
None of the logic is asynchronous, the second the key is pressed hexchat checks for replacements.

**Comment by Arnavion** [comment]
I'm going to guess that when you type at full speed, you press <kbd>Shift</kbd>-<kbd>Space</kbd> instead of <kbd>Space</kbd> which suppresses auto-replace by design.

**Comment by Arnavion** [comment]
Feel free to reopen if that's not the explanation.
