### ISSUE TITLE
Hexchat Crashes When Selecting Custom Sound

### ISSUE THREAD

**Issue by whispy** [hexchat/hexchat#1739]
The Hexchat client (2.12.1 x64) crashes whenever I try to select a custom sound via `Preferences > Sound`. It is easily reproducible for me and will crash regardless of either the file I select (though all have been .wav files) or the event highlighted in the left column. 

I've checked the app crash dump and it says the Fault Module Name is `gobject-2.0.dll`. Not sure if that helps or not. Let me know if you need more info or testing.

I'm running Windows 8.1.

**Comment by whispy** [comment]
I found a workaround — if I manually enter the file's path into the `Sound file:` text field and then hit `ok`, I can set the sound without the client crashing. However, the crash error still exists when a file is selected via the `Browse...` file dialog.

**Comment by TingPing** [comment]
Please re-install the latest version linked here, this was fixed: http://hexchat.github.io/downloads.html
