### ISSUE TITLE
User list size breaks when maximizing window with query selected

### ISSUE THREAD

**Issue by SonicFreak94** [hexchat/hexchat#1741]
I'm running HexChat 2.12.1 x64 on Windows 10.

If the window is maximized or restored with a query focused (or really anything without a user list; works on server tabs as well), the user list will either be tiny or way too large depending on whether it was a maximize or restore that happened.

I recorded a short video to illustrate the problem: [here](https://youtu.be/U9iLvnP2gpo).

**Comment by Arnavion** [comment]
Duplicate of #808
