### ISSUE TITLE
Colour lines like usernames

### ISSUE THREAD

**Issue by pr0letariat** [hexchat/hexchat#1745]
This issue is similar to this one:

https://github.com/hexchat/hexchat/issues/1378

Although I don't understand the solutions given, could someone please explain how to accomplish this?

I would like to have lines highlighted like usernames, this is especially useful when speaking one to one with someone at length to differentiate who said what.

**Comment by TingPing** [comment]
Then just ask for clarification on that issue...

Anyway my comment was pretty clear I think: https://github.com/hexchat/hexchat/issues/1378#issuecomment-104363364
