### ISSUE TITLE
DCC GET <nick> command behaviour

### ISSUE THREAD

**Issue by marlowww** [hexchat/hexchat#1746]
When you accept DCC SEND Offer with command `DCC GET <nick>`, files are always saved as new with `<.number>` ending. It varies from manual accepting behaviour. When you start downloading file which exists and you manually accept it, download is resumed and appended to existing file, when existing file on disk is smaller than the target size, otherwise it is appended with `<.number>`. I don't know how to accept file and resume it (append download) in Python script, because of this strange behaviour.

**Comment by Arnavion** [comment]
Seems `dcc_get_nick` should call `update_is_resumable` like the other functions do.

**Comment by marlowww** [comment]
Added Pull Request, which should fix this unexpected behaviour. #1747
