### ISSUE TITLE
Start hexchat minimized

### ISSUE THREAD

**Issue by abhigenie92** [hexchat/hexchat#1748]
How do I start hexchat minimized?
I am using kubuntu 16.04, kde 5.6.4. I have added hexchat in the program to start-up automatically.

Below are the settings I have.
![image](https://cloud.githubusercontent.com/assets/12474640/16108062/4b0b43b4-33be-11e6-945d-d8e0fdae1de7.png)

**Comment by TingPing** [comment]
Since you found #1451 I'll assume you understand that you can call `hexchat --minimize=1`

**Comment by orschiro** [comment]
Is `hexchat --minimize=1` still supported? 

I just tried it but it's still showing a window on Linux Mint 18.3.

![image](https://user-images.githubusercontent.com/170947/33605760-516dd3ee-d9bb-11e7-9087-936b909c80f2.png)

![image](https://user-images.githubusercontent.com/170947/33605778-616bd1d8-d9bb-11e7-9840-9ff0abd0c760.png)

**Comment by orschiro** [comment]
Sorry for bothering! Found the working solution for me with `hexchat --minimize=2` to directly minimize to tray. :-)
