### ISSUE TITLE
Conditional nickname colours

### ISSUE THREAD

**Issue by gdude2002** [hexchat/hexchat#1749]
Something I miss from mIRC is the nick colour functionality of its address book. Using this, it's easy to assign specific colours to user nicks based on various criteria. For example:

* Red nicknames for users with the `@` prefix
* Blue nicknames for users with `bot` in their ident
* Green nicknames for users that haven't sent a message within the last 10 minutes

There was a bunch of options that I can't remember right now.

---

It seems that while you _could_ write a script to eat the message events and output them yourself (which is really quite hacky), there doesn't appear to be a way to change the colour that's shown in the user list. This would be a core part of such a feature.

**Comment by gdude2002** [comment]
Grabbed a screenshot of the options window for your nick colour setting.

![](https://dl.dropboxusercontent.com/u/1547120/ShareX/2016/June/mirc_2016-06-16_11-08-56.png)

(`$$me` is used to refer to yourself; this is how you set your own nick colour in mIRC)

**Comment by Arnavion** [comment]
https://github.com/hexchat/hexchat-addons/tree/master/python/nicenicks

**Comment by gdude2002** [comment]
Yes, I've seen this. It doesn't solve this issue.

Did you read the ticket? I mentioned this approach, and pointed out that it
was kind of hacky. Additionally, this does not change the colour of the
user in the user list, it only supports setting permanent colours per nick
and falls back to cycling colours, and does not take prefix or other
criteria into account.

I do not believe hexchat provides an API to change a nick's colour in the
user list, from a look over how the colour for that is retrieved. Being
able to hook that would fix the other concerns in my ticket.

**Comment by TingPing** [comment]
> I do not believe hexchat provides an API to change a nick's colour in the
user list

The scripting API is very detached from the UI. A script can directly modify the Gtk window itself and accomplish what you want but it isn't pretty.

>  Additionally, this does not change the colour of the
user in the user list, it only supports setting permanent colours per nick
and falls back to cycling colours, and does not take prefix or other
criteria into account.

Fairly easy modifications. For example: [statuscolor.py](https://github.com/TingPing/plugins/blob/master/HexChat/duplicates/statuscolor.py)

**Comment by gdude2002** [comment]
Yeah, I agree that those would be fairly trivial changes overall. I was
mostly just annoyed at the immediate ticket close.

Yeah, I don't think one would want to mess with the UI directly either - I
noticed that the text utils has a method for grabbing the colour of a nick,
which the user list (among other things) uses - that's what I'd like to
hook. I'd do it myself and submit a PR, but I'm inexperienced with C/++..

**Comment by TingPing** [comment]
Well your original comment didn't propose any API additions. I think it is fairly safe to say the built in feature of far more advanced coloring options will not happen though.
