### ISSUE TITLE
Installation on Windows hangs

### ISSUE THREAD

**Issue by jeena** [hexchat/hexchat#1751]
I had everything on default and after a while the installation just stopps and hangs, I can't even exit the program, I just hear the sound that it's not possible to click the X to close.

![hexchat-problem](https://cloud.githubusercontent.com/assets/151764/16170738/78c94440-355d-11e6-89d7-acd2dcf12f2f.png)

**Comment by TingPing** [comment]
You can try installing the redist directly and see what happens. (It's on the download page)

**Comment by jeena** [comment]
Ok, now I installed it first and then reinstalled Hexchat and it works! Thanks for the tip!
