### ISSUE TITLE
Windows: SSL23_GET_SERVER_HELLO:unknown protocol

### ISSUE THREAD

**Issue by jeena** [hexchat/hexchat#1752]
I use Hexchat on Linux and Windows with the znc bouncer. On Linux everything works well, but when I use the exact same settings as on Linux, the Windows version shows this error:

    * Looking up irc.jeena.net
    * Connecting to jeena.net (89.238.65.41:6667)
    * Connection failed ((336031996) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol)

![hexchat-problem-1](https://cloud.githubusercontent.com/assets/151764/16172971/ead82ab6-3593-11e6-85c6-142da90a3503.png)

**Comment by TingPing** [comment]
You are connecting to a non-ssl port with ssl.

**Comment by jeena** [comment]
HexChat 2.12.1 and I will need to check on Linux which znc version I use.

**Comment by TingPing** [comment]
2.12.1 only uses TLS 1.0+ (but this should apply to the linux version also..)

**Comment by jeena** [comment]
Sadly nothing is outdated, I just compiled znc from the master branch which makes it ZNC 1.7.x-git-611-b7309cd and HexChat 2.12.1 just downloaded from the website.

**Comment by tomek** [comment]
@jeena you should try test build from here: https://dl.hexchat.net/hexchat/testing/ as i'm able to connect to your server (on win10)

```
* Looking up irc.jeena.net
* Connecting to jeena.net (2a00:1828:2000:774::3:6667)
* * Certification info:
*   Subject:
*     CN=Jeena
*   Issuer:
*     CN=Jeena
*   Public key algorithm: rsaEncryption (2048 bits)
*   Sign algorithm sha256WithRSAEncryption
*   Valid since Feb  1 20:27:41 2016 GM to Jan 29 20:27:41 2026 GM
* * Cipher info:
*   Version: TLSv1/SSLv3, cipher ECDHE-RSA-AES128-GCM-SHA256 (128 bits)
* * Verify E: self signed certificate.? (18) -- Ignored
* Connected. Now logging in.```

**Comment by jeena** [comment]
And yes, on Linux I'm also using HexChat 2.12.1

Ah cool I'll try that.

**Comment by jeena** [comment]
Hm, no it doesn't work with the testing version either, so it's something about my setup it doesn't like. I had this other problem earlier today, might those be related? https://github.com/hexchat/hexchat/issues/1751

**Comment by jeena** [comment]
It seems that I have big problems with SSL on my windows installation and it isn't about HexChat at all because many other programs have similar problems, so I'll close this bug.
