### ISSUE TITLE
[Windows] Crash occurs at ToastNotificationManager::CreateToastNotifier when connecting server

### ISSUE THREAD

**Issue by fujii** [hexchat/hexchat#1755]
1) Start HexChat
2) Network List
3) Connect
4) Crash

Unhandled exception at 0x00007FFFC83498FE (ucrtbase.dll) in hexchat.exe: Fatal program exit requested.

callstack:

~~~
ucrtbase.dll!00007fffc83498fe()	Unknown
ucrtbase.dll!00007fffc8349036()	Unknown
hexchat.exe!__scrt_unhandled_exception_filter(_EXCEPTION_POINTERS * const pointers) Line 75	C++
KernelBase.dll!00007fffc9df7e2e()	Unknown
ntdll.dll!00007fffccbed958()	Unknown
ntdll.dll!00007fffccbd5ac6()	Unknown
ntdll.dll!00007fffccbe9a9d()	Unknown
ntdll.dll!00007fffccb74f29()	Unknown
ntdll.dll!00007fffccb76bd4()	Unknown
KernelBase.dll!00007fffc9da1f08()	Unknown
vcruntime140.dll!00007fffc59b4582()	Unknown
vccorlib140.dll!00007fffae99bae5()	Unknown
[External Code]	
hcnotifications-winrt.dll!Windows::UI::Notifications::IToastNotificationManagerStatics::CreateToastNotifier(Platform::String ^ __param0)	C++
hcnotifications-winrt.dll!Windows::UI::Notifications::ToastNotificationManager::CreateToastNotifier(Platform::String ^ __param0)	C++
hcnotifications-winrt.dll!notification_backend_init() Line 80	C++
hexchat.exe!notification_plugin_init(_hexchat_plugin * plugin_handle, char * * plugin_name, char * * plugin_desc, char * * plugin_version, char * arg) Line 179	C
hexchat.exe!plugin_add(session * sess, char * filename, void * handle, void * init_func, void * deinit_func, char * arg, int) Line 294	C
hexchat.exe!fe_idle(void * data) Line 387	C
glib-2.0.dll!000002557e70a0f7()	Unknown
glib-2.0.dll!000002557e70b0ea()	Unknown
glib-2.0.dll!000002557e70b5e0()	Unknown
gtk-win32-2.0.dll!00007fff9b69cd5f()	Unknown
hexchat.exe!main(int argc, char * * argv) Line 1097	C
[External Code]	
~~~

It does not crash if if I remove hcnotifications-winrt.dll.

**Comment by fujii** [comment]
Unfortunately, it still happens.
How to reopen?

**Comment by Arnavion** [comment]
You built master with that change?

**Comment by fujii** [comment]
Yes, I did.
But, after rebooting Windows, I can not reprocude original problem even with unmodified v2.12.1.
This crash began one day suddenly as other mentioned https://github.com/hexchat/hexchat/issues/1588#issuecomment-195464199
I will try agin if it will happen again with v2.12.1.
Please keep this bug closed. Thank you.

**Comment by Arnavion** [comment]
With unmodified 2.12.1 you should get mojibake in the toast notifications even if it doesn't crash.

**Comment by dragonble** [comment]
Hi, I have the same issue and hexchat still crash if I don't delete hcnotifications-winrt.dll 

System : Windows 8.1
Hexchat build: 2.12.1 unmodified and basic install

**Comment by learn-more** [comment]
I will take a look at this.

**Comment by xaxxon** [comment]
Do you want me to reboot and see if the problem goes away or not reboot to make sure I can reproduce the problem for a potential fix?

**Comment by learn-more** [comment]
It probably wont be today, but if you can hold off rebooting until later this week that would help verifying a potential fix.

**Comment by xaxxon** [comment]
I'll see what windows will let me do.

**Comment by xaxxon** [comment]
Error loading notifications-winrt

err 0x803e0105: the notification platform is unavailable.

The notification platform is unavailable.

**Comment by learn-more** [comment]
Thanks!

This is WPN_E_PLATFORM_UNAVAILABLE, I will investigate how to handle / work around this.

**Comment by learn-more** [comment]
@xaxxon Can you re-test with https://ci.appveyor.com/project/TingPing/hexchat/build/1.0.52 ?
This is a nicer implementation, that does not slam a message box in your face :)

**Comment by xaxxon** [comment]
My power went out so my computer rebooted.   I saw no messages anywhere.

Also, I noticed that I had turned off notifications in my windows 10
control panel, but was previously unable to even pull up the control panels
settings window for "notifications and actions".  Now it pulls up just
fine, since the reboot.
