### ISSUE TITLE
missing dll after installing the latest hexchat

### ISSUE THREAD

**Issue by ambicoder** [hexchat/hexchat#1757]
I installed the latest hexchat but on launching it a get a message that a dll file is missing:
![capture](https://cloud.githubusercontent.com/assets/3075234/16254543/b54479a0-3849-11e6-9b8e-686ebfe3cd4e.PNG)

As you can see from the image snapshot this dll seems not to be related with VC redistributable as other similar issues mention here.

What should I do to fix the issue?

**Comment by Arnavion** [comment]
>seems not to be related

It is.
