### ISSUE TITLE
Auto-Load of Plugins not working

### ISSUE THREAD

**Issue by Ttech** [hexchat/hexchat#176]
When I setup HexChat plugins are loaded from ./.config/hexchat from the Plugins menu. However they do not seem to auto load anymore like what would happen in XChat.

Manually loading the plugins works fine, but is a bit difficult if you startup and close HexChat with any frequency. 

Tested on two different systems ArchLinux using package and Ubuntu using package from the site.

**Comment by platta** [comment]
Sorry to comment on such an old thread, but it's pretty high in search results and both links above no longer point to the actual documentation. It's here now: https://hexchat.readthedocs.io/en/latest/faq.html#how-do-i-auto-load-scripts-at-startup
