### ISSUE TITLE
Support for --existing command-line option?

### ISSUE THREAD

**Issue by ThomasWeber** [hexchat/hexchat#1777]
I am using HexChat on Windows and am attempting to join a server and channel using the command-line using a client that is already ruinning, but having a few problems. When I try to use the command line:

hexchat.exe --existing --url="IRC://irc.chat.twitch.tv/channelname"

I get a message that it isn't supported. Has this feature not been imported from XChat?

Thanks!

**Comment by TingPing** [comment]
It only works on Unix where we have DBus. This is mentioned in #252
