### ISSUE TITLE
GtkEntry doesn't understand astral plane characters entered via Win10 touch keyboard

### ISSUE THREAD

**Issue by Scrxtchy** [hexchat/hexchat#1778]
![](http://jesusfuck.me/di/FOR9/16-07-24-15-02-30.gif)

Input seems to like ones from 1995, which are mixed into blocks such as 'Symbols' 'Dingbats' and 'Enclosed CJK Letters and Months' etc. all with a code on the lower side of unicode.

My attempts to 'type' any character from range 1F300 - 1F5FF return ill results.

Currently the only way these can be input is by using the clipboard

The osd-keyboard used in this issue is the windows 10 touch keyboard
Can be enabled on any desktop machine from the taskbar's context menu
![](http://jesusfuck.me/di/60AD/16-07-24-15-19-05.png)

**Comment by Arnavion** [comment]
For astral plane characters, Windows sends two VK_PACKET messges with the corresponding utf-16 bytes of the character. The code in `gdk_event_translate` converts these one at a time, so the first one is ignored because it's incomplete and the second one is ignored because it's invalid.

**Comment by Arnavion** [comment]
Upstream bug at https://bugzilla.gnome.org/show_bug.cgi?id=769126

**Comment by TingPing** [comment]
Merged upstream: gnome/gtk@b7c92fb1fb31fbdb70348587dc326142f4f615b3
