### ISSUE TITLE
emit_print when same hook_print is active causes freeze

### ISSUE THREAD

**Issue by Beliaar** [hexchat/hexchat#1782]
When I hook a text event using hook_print and then calling a emit_print with the same event anywhere - even outside of the script - hexchat will freeze/become unresponsive.

Example:

```python
import hexchat

__module_name__ = 'test'
__module_description__ = 'test'
__module_version__ = '-1'

def channel_msg_cb(word, word_eol, userdata):
    return

hexchat.hook_print("Channel Message", channel_msg_cb)
```
then using `/py console`
```python
hexchat.emit_print("Channel Message", "Nick", "Message")
```

Windows 10 x64 1511 Build: 10586.494
Hexchat x64 2.12.1-2

**Comment by TingPing** [comment]
Can't reproduce and doesn't even make sense. It would make sense if you emit the event from within `channel_msg_cb` is that your original problem?

**Comment by Beliaar** [comment]
Nope, I'd know how to handle that case. And it does not freeze if I comment out the line with the hook. I unloaded all other scripts too. Not sure what I could do on my side to figure it out.

**Comment by Beliaar** [comment]
This seems to be some problem with Python. Using similar code with Lua this problem does not exist.

I just tried reinstalling an 64 Bit python 2.7 (newest version), but now hexchat refuses to run at all.

**Comment by Beliaar** [comment]
Hmm,it works with a 3.5 of python. I guess I just convert the scripts. I leave whether to close this issue to you.

**Comment by TingPing** [comment]
> primary python version installed back then.

Python 2.7.11 has a broken installer but they fixed that in 2.7.12

**Comment by Beliaar** [comment]
Oh, and, for some reason I downloaded 2.7.11, I'll try that, just for testing, but will probably stay with 3.x anyway.

**Comment by Beliaar** [comment]
Ok, works with 2.7.12. Thanks.
