### ISSUE TITLE
[Feature Request] Keyboard Shortcut for Repositioning Channels when Viewed as Tabs

### ISSUE THREAD

**Issue by pretodor** [hexchat/hexchat#1783]
At the moment you can reposition the open channels when they are viewed as a tree by pressing `ctrl+shift+pgup/pgdn` but this is not possible when they are viewed as tabs (You can switch between the 2 layouts from `View > Channel Switcher`).

**Comment by TingPing** [comment]
By default *Alt+Left* and *Alt+Right*. See also: *Settings > Keyboard Shortcuts*.
