### ISSUE TITLE
Links are openend in Chrome regardless of URL handler

### ISSUE THREAD

**Issue by PureTryOut** [hexchat/hexchat#1786]
My url handler is set to `!firefox -new-window %s`. However, when actually clicking on a link, it opens it in Google Chrome instead. I actually want it to be Firefox, as Chrome is only my backup browser. Running the command `firefox -new-window %s` directly in a terminal correctly opens the link in Firefox.

Running Arch Linux and Hexchat version 2.12.1.

**Comment by TingPing** [comment]
URL handlers are entirely about the right click menu and have nothing to do with the default opener.

See the docs on how to change default opener: http://hexchat.readthedocs.io/en/latest/faq.html#how-do-i-change-what-browser-is-opened

**Comment by PureTryOut** [comment]
Even though it also occured in the right click menu, your link did fix it, so not a Hexchat bug. Thanks and sorry for bothering you with this!
