### ISSUE TITLE
HexChat crashes when I try to disable autojoin via right click on the channel name.

### ISSUE THREAD

**Issue by robert-groensfeld** [hexchat/hexchat#1792]
This only happens with the channel #HorribleSubs on irc.rizon.net

- Autojoin is still set when I restart the program
- The program disappears from the list of active processes
- HexChat version: 2.9.6
- Linux kernel: Linux 3.19.0-66-generic
- Linux distribution: Ubuntu 14.04.4 LTS

**Comment by TingPing** [comment]
Please try a more recent version: https://launchpad.net/~gwendal-lebihan-dev/+archive/ubuntu/hexchat-stable

**Comment by robert-groensfeld** [comment]
Fixed in HexChat version 2.12.0
