### ISSUE TITLE
Channels - Favorites menu??

### ISSUE THREAD

**Issue by Beast141** [hexchat/hexchat#1798]
Im not sure if this feature exists because i have been sitting hours searching for atleast a decent addon or why hexchat doesnt have just a simple menu of 'favorites' BESIDES the favorites under the server settings that autojoins.

I mean theres plenty of channels that users want to enter without auto-joining and without re-downloading the whole server channel list everytime.

This is the only script i could find but its for XChat and when i tried to load it on HexChat, it didnt really work.  https://sites.google.com/site/fookmarks/
This is the script list i found it from: http://xchat.org/cgi-bin/disp.pl

If there is such a feature of a 'favorites' menu where one could add channels and visit only from time to time then please tell me, alternatively could the script above be set to work with HexChat? Can someone re-test it?

**Comment by TingPing** [comment]
https://github.com/TingPing/plugins/blob/master/HexChat/bookmarks.py

**Comment by Beast141** [comment]
Ah thank you TingPing - it works well!  Can you tell me howcome this is not in this list?
https://github.com/hexchat/hexchat-addons
or am i missing something?

**Comment by TingPing** [comment]
There are dozens of repos full of HexChat scripts and there are XChat scripts dating back over a decade, it isn't possible for them to all be in one place.
