### ISSUE TITLE
should identify to nickserv before auto joining channels

### ISSUE THREAD

**Issue by roidayan** [hexchat/hexchat#1799]
some channels may be restricted so only identified users can join.
hexchat needs to first identify to nickserv and wait a reply that we are identified (or wait 2 seconds) before auto joining channels.

... :Cannot join channel (+r) - you need to be identified with services

**Comment by TingPing** [comment]
Use SASL for login method.

See also: http://hexchat.readthedocs.io/en/latest/faq.html#why-are-channels-joined-before-identifying
