### ISSUE TITLE
Compiling: macro AX_APPEND_COMPILE_FLAGS is not defined

### ISSUE THREAD

**Issue by kernelpanic3** [hexchat/hexchat#1803]
Attempting to run autoconf on Kubuntu 16.04 to compile a freshly obtained dev version produces:

```
configure.ac:19: error: macro AX_APPEND_COMPILE_FLAGS is not defined. Is autoconf-archive installed?
configure.ac:17: HEX_CHECK_MACRO is expanded from...
configure.ac:19: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
```

...but autoconf-archive is indeed installed. This was already [reported on the AUR](https://aur.archlinux.org/packages/hexchat-git/?comments=all) and said to be fixed...

Thanks for a great client!

**Comment by TingPing** [comment]
It is certainly in Ubuntus package..: http://packages.ubuntu.com/xenial/all/autoconf-archive/filelist

**Comment by kernelpanic3** [comment]
That produces:
```
configure.ac:45: warning: macro 'AM_GLIB_GNU_GETTEXT' not found in library
configure.ac:196: warning: macro 'AM_PATH_GLIB_2_0' not found in library
aclocal: installing 'm4/ax_append_compile_flags.m4' from '/usr/share/aclocal/ax_append_compile_flags.m4'
aclocal: installing 'm4/ax_append_flag.m4' from '/usr/share/aclocal/ax_append_flag.m4'
aclocal: installing 'm4/ax_append_link_flags.m4' from '/usr/share/aclocal/ax_append_link_flags.m4'
aclocal: installing 'm4/ax_check_compile_flag.m4' from '/usr/share/aclocal/ax_check_compile_flag.m4'
aclocal: installing 'm4/ax_check_link_flag.m4' from '/usr/share/aclocal/ax_check_link_flag.m4'
aclocal: installing 'm4/ax_perl_ext_flags.m4' from '/usr/share/aclocal/ax_perl_ext_flags.m4'
aclocal: installing 'm4/ax_require_defined.m4' from '/usr/share/aclocal/ax_require_defined.m4'
aclocal: installing 'm4/pkg.m4' from '/usr/share/aclocal/pkg.m4'
aclocal: installing 'm4/intltool.m4' from '/usr/share/aclocal/intltool.m4'
aclocal: installing 'm4/nls.m4' from '/usr/share/aclocal/nls.m4'
configure.ac:45: warning: macro 'AM_GLIB_GNU_GETTEXT' not found in library
configure.ac:196: warning: macro 'AM_PATH_GLIB_2_0' not found in library
configure.ac:45: error: possibly undefined macro: AM_GLIB_GNU_GETTEXT
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:68: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:196: error: possibly undefined macro: AM_PATH_GLIB_2_0
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

**Comment by TingPing** [comment]
Great, new errors, those would be provided by one of the glib packages. I suggest checking out the docs for a possible list: http://hexchat.readthedocs.io/en/latest/building.html#unix

**Comment by kernelpanic3** [comment]
Hmm. `apt-get build-dep hexchat` didn't change the errors in the slightest...but `libluajit-5.1-dev` on top of that cleared everything up. It's still a pretty confusing error - maybe, if it's possible, something more specific could be given?

**Comment by TingPing** [comment]
>  It's pretty confusing to have glib errors because a luajit dev package is missing - if it's possible, perhaps that should be changed?

That makes absolutely no sense nor can I reproduce it.

**Comment by kernelpanic3** [comment]
Weird. Now I can't either, though the original autoconf macro error is still present.

**Comment by fayadr** [comment]
Same problem here on Ubuntu 16.04. I tried to build for the first time hexchat following the build recommandations on http://hexchat.readthedocs.io/fr/latest/building.html and got the same error : 
```
configure.ac:19: error: macro AX_APPEND_COMPILE_FLAGS is not defined. Is autoconf-archive installed?
configure.ac:17: HEX_CHECK_MACRO is expanded from...
configure.ac:19: the top level.
```
Regarding the guide, i don't miss any dependencies.
