### ISSUE TITLE
Python3 - %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by ThePsionic** [hexchat/hexchat#1805]
I'm currently unable to load any Python add-ons as the Python plugin will not load with the message "%1 is not a valid Win32 application". What can I try and do to fix this?

**Comment by TingPing** [comment]
Normal debugging steps: Install Python (correct version/bitness) with the option to add to PATH/install for all users. Possibly reboot. ???

**Comment by ThePsionic** [comment]
Thanks. I never knew there was a 64-bit release of Python - turns out you gotta dig pretty deep to find it.
