### ISSUE TITLE
Autoload module?

### ISSUE THREAD

**Issue by itsabear** [hexchat/hexchat#1812]
Hi, I place "script.py" in ~/.config/hexchat/addons/

The script working fine with *py load script.py*

However, it didn't autoload everytime I open hexcat?

Is there a way to fix this?

**Comment by TingPing** [comment]
This is the correct directory, how are you starting hexchat?

**Comment by itsabear** [comment]
Either by `hexchat` in shell, or clicked hexchat in the menu. (in Ubuntu)

**Comment by TingPing** [comment]
Well then it is certainly trying to autoload, I'm not sure there is an easy way to debug why the python plugin is failing though.

**Comment by itsabear** [comment]
I think it's my code problem. I think the module actually starts "before" IRC joining. The module should be executed as soon after joined a server. That's why. Well, closing this. Thanks.
