### ISSUE TITLE
ctrl + 'char' shortcut problem

### ISSUE THREAD

**Issue by rowboatrubadub** [hexchat/hexchat#1814]
When I am in a certain chat room, I try to autocomplete a user's nick, and instead of simply completing the nick and letting me finish typing as it should, it does something unexpected.  Instead, the shortcut lists out the users nicks who are currently in the chat room to me.  It only does this with the letter 's'.  So ctrl + 's' lists out usernames that start with s instead of completing a nick.  Only in one room in particular though.  I assumed it was something normal that I didn't know how to change the settings for but I thought I would let you know.

hexchat 2.12.1
not portable
Microsoft windows 10 home (x64)

**Comment by Arnavion** [comment]
It prints the list if there's more than a certain number of nicks that would match the filter. That's by design.

**Comment by TingPing** [comment]
This is configurable in *Preferences > Input box > Nick completion amount*
