### ISSUE TITLE
linux client is creating new folders in scrollback folder instead of using the existing ones

### ISSUE THREAD

**Issue by H4ndl3** [hexchat/hexchat#1826]
I moved my HexChat config folder to a location that is available from both my windows client and my linux client. I specified the directory via the `-d` directive and everything seems to be working quite smoothly, except for the scrollback logs: the linux client created new folders in the scrollback folder for the networks I'm using, instead of using the existing ones. They have the same name but at the end there seems to be some unicode sign. `ls` lists the folders as `network@bouncer?` and in the file explorer they show up as `network@bouncer ` (blank at the end). When I open the folder there is some form of box with numbers in it at the end of the folder name in the title of the file explorer.

So HexChat seems to create new folders with some kind of unicode sign at the end instead of using the existing ones with the same name, minus the sign at the end.

**Comment by TingPing** [comment]
You need to run `dos2unix` on all config files when moving from Windows. See #834

**Comment by H4ndl3** [comment]
@TingPing so there is no way to use the same config folder for Windows and Linux? :/

**Comment by TingPing** [comment]
That will never be fully possible as some files reference paths and log names vary by platform. But yea the line endings are the biggest pain for that atm.
