### ISSUE TITLE
Consider Adding DigitalAddiction to the default network list

### ISSUE THREAD

**Issue by RohanOne** [hexchat/hexchat#1829]
Hi there, Im from DigitalAddiction, a budding tech community and we have our own irc server. We're looking for potential members of our community and we were wondering if you can add our IRC to your default network list.  Our main site is at digitaladdiction.info and our irc server is at irc.digitaladdiction.info

**Comment by mB-PiBox** [comment]
This isn't an 'Issue'
1 There is an IRC channel for #HexChat on freenode that you could have asked this is, doubt it would have been granted but again github isn't the place for posting Ad Requests.
2. lets hope that the people in your #web channel are not the ones that "setup" digitaladdiction.info using a free Wordpress Theme; which is horribly modified by the way.

**Comment by RohanOne** [comment]
1. The reason i asked here instead of freenode is because github is DESIGNED to be a place to post suggestions as well as issues and at least on github the suggestion will be processed and dealt with instead of IGNORED by the 30+ members of the chan who sit and lurk, or worse being told off to post the issue on github because THIS IS WHERE YOU POST ISSUES AND SUGGESTIONS

2. This wasnt an ad request. DA is a strictly not for profit community and we arent asking for free advertisement, we simply wanted to be added to the EXISTING list of networks which, may i say, consist of several dead networks anyway

3. This unhelpful, dismissive, attitude of yours is the EXACT reason we created DA; so that people like YOU wont shout down people who are genuinely looking for help with an issue

4. I mentioned that we are a BUDDING community which means that not all of our infrastructure is in place, so im SORRY if the site wasnt designed to YOUR standards your highness! What does the design of the site has anything to do with this issue anyway? Furthermore, whats wrong with using a free wordpress theme?

**Comment by TingPing** [comment]
The issue tracker is the ideal place for this.
