### ISSUE TITLE
GTK text input box not applying system themes properly

### ISSUE THREAD

**Issue by anthonyryan1** [hexchat/hexchat#1832]
Dark GTK themes seem to be having trouble properly applying themes to the "SexySpellEntry" box, in the sense that they are only able to half theme it.

[Looking at what one theme did](https://github.com/horst3180/arc-theme/commit/2b1a290469ad575432d51ba8107e878537b3178b#diff-d78bbe2e9363b58a24d3cf9ffe80a2f2R80), they had to add styling rules specifically for HexChat. If possible I think it would be optimal to replace "SexySpellEntry" with a more standard GTK widget that's more likely to be themed properly by default, rather than requiring every theme that exist have an element added just for HexChat.

Just for reference I'm having the issue shown in this screenshot with Adwaita dark.
![screenshot from 2016-10-06 22-59-54](https://cloud.githubusercontent.com/assets/543852/19177593/9eed4308-8c18-11e6-8e4b-0215229745dd.png)

**Comment by TingPing** [comment]
This was fixed by 91df075d62606ee295932f1dfefc98187b5ce839. You can just disable prefs > input > use text box color until you get that though.
