### ISSUE TITLE
Hexchat 2.12.2 on windows x64 crashes on startup while autojoining channels

### ISSUE THREAD

**Issue by Victorsueca** [hexchat/hexchat#1836]
I have hexchat setup to autojoin on startup 3 networks and a total of 12 channels, while in 2.12.1-2 it loads fine, on 2.12.2 it crashes.

**Comment by Thibaut120094** [comment]
I have the same problem, disabled Kaspersky Internet Security and it loads fine.

Do you have any antivirus/security software enabled?

**Comment by TingPing** [comment]
Probably some corrupt scrollback file. You can delete %appdata%\HexChat\scrollback as a test.

**Comment by Thibaut120094** [comment]
> Probably some corrupt scrollback file. You can delete %appdata%\HexChat\scrollback as a test.
Doesn't work, it still crashes.

**Comment by Victorsueca** [comment]
I have Kaspersky Total Security, but after disabling it still crashes, deleting the scrollback files doesn't help either. Downgraded to 2.12.1-2 and works fine.

**Comment by Arnavion** [comment]
IIRC HC had to get whitelisted with them for the previous release too.

It's probably fucked the binaries when they were installed. Disabling it after the fact may not help.

**Comment by TingPing** [comment]
Yea was mentioned in #1633. Considering all 3 of you use Kaspersky seems like the problem.

**Comment by Victorsueca** [comment]
Manually adding it to the whitelist, ignoring the antivirus warnings and reinstalling hexchat seems to have fixed it.
