### ISSUE TITLE
Spanish language

### ISSUE THREAD

**Issue by solohtml** [hexchat/hexchat#1842]
When I change Hexchat (Windows 7 Ultimate amd64) x64 to Spanish, at restart it crashes and I need to edit hexchat configuration manually to delete language selection.
Is any problem with Spanish translation or just is it a general languages selection problem?
![captura](https://cloud.githubusercontent.com/assets/3239523/19312064/ce1130f8-9088-11e6-88ec-7aba7043cf7d.PNG)
![captura2](https://cloud.githubusercontent.com/assets/3239523/19312217/61952686-9089-11e6-8f41-acdf4ba88841.PNG)

**Comment by TingPing** [comment]
This was fixed here: https://github.com/hexchat/hexchat/commit/bb8f0beabe25823fb2ea6190af58de98b4a4b05a and ensured it can't happen in the future here: https://github.com/hexchat/hexchat/commit/2a81b98e7bcad05bf54d9c423f68df6492ae4326

Not uploaded yet but you can grab a newer build here soon: https://dl.hexchat.net/hexchat/testing/

**Comment by TingPing** [comment]
You can grab a new build at https://dl.hexchat.net/hexchat/testing btw
