### ISSUE TITLE
Color emoji support on Windows 8/10

### ISSUE THREAD

**Issue by vaguerant** [hexchat/hexchat#1843]
As far as I can tell, HexChat currently only supports black and white emoji on Windows, at least when using the Microsoft-bundled "Segoe UI Emoji" font. My (layperson) understanding is that this font uses COLR and CPAL tables to fill outlines with full color designs, so anything which supports those is able to display the full color emoji and where those are unsupported, only the outlines are displayed. Thus, setting the font in HexChat is not enough to display full color emoji; HexChat shows black and white outlines.

I know there's some kickback against emoji in general, let alone in full color, so were this to be implemented I would perhaps suggest that it be optional whether a user wishes to see emoji in full color or the fallback outlines.

**Comment by TingPing** [comment]
This is an upstream Pango/Cairo issue. As I understand it cairo supports this in some capacity (might require patches still) but pango does not. If you google around you can find some discussions on the mailinglists.

As such I'll just be closing this as this project really isn't the starting point to getting this feature implemented and you would be better off prodding the Pango folks.

**Comment by vaguerant** [comment]
Thanks, TingPing. Apologies for my failure to realize the hierarchy.

For anyone who finds this issue, you may wish to follow [this Pango issue](https://bugzilla.gnome.org/show_bug.cgi?id=763186) for updates.

**Comment by Znuff** [comment]
Any new status on this?

Pango seems to have been brought up2date with the required patches (as per the issue linked), so in theory hexchat should be good to go with colored svg fonts soon?

**Comment by TingPing** [comment]
Pango/Cairo did land support for them but I have not tested it on Windows.

> good to go with colored svg fonts soon?

The SVG format is not supported though.

**Comment by matelich** [comment]
Can this be reopened since the upstream work is done?

**Comment by TingPing** [comment]
@matelich I don't use Windows but I think it just works.

As mentioned SVG formats are not supported but color emoji, such as Noto Emoji, work fine.

**Comment by matelich** [comment]
@TingPing No luck with Noto Color Emoji. Tried to attach a screenshot, but its not working. I still get monochrome emoji (and things generally are not rendering very nicely).

Additionally, the font picker shows the hex boxes even for abc's.
[ 0 0 ]
[ 6 1 ]

**Comment by TingPing** [comment]
That is unfortunate.

I still believe it is not something actionable for HexChat. Font rendering is entirely handled by the Pango library.

**Comment by matelich** [comment]
I guess I wasn't positive a release had been made with the latest Pango
stuff.

**Comment by TingPing** [comment]
Yes this work all happened about 4 years ago in Pango. On the Linux backend for Pango color emoji work very well in HexChat.

The problem seems to be on the Windows backend for Pango. I don't expect anything needs to change on HexChat's part.
