### ISSUE TITLE
Setup gives portable mode error.

### ISSUE THREAD

**Issue by thegreatestminer** [hexchat/hexchat#1844]
EDIT: Whoops, didn't add a description.

Basically I want to install HexChat onto my flash drive but it gives the error when I try to enable portable mode in the installer.
![image](https://cloud.githubusercontent.com/assets/19188146/19399314/e9666dcc-921e-11e6-950f-16a241d4d98e.png)

Is this because the computer I am running has HexChat installed so it detects that and disables it? Should I uninstall HexChat and then try again?

**Comment by TingPing** [comment]
Stop installing portable things to locations where your user can't even write.

**Comment by beresnyak** [comment]
I confirm this bug. The x64 version of the installer does not give the option to choose install location and when "portable" option is chosen it returns an error. Currently it is not feasible to produce portable version of HexChat with x64 Windows installer. The TingPing's comment is misleading and irrelevant. The issue should be opened.

**Comment by TingPing** [comment]
It forbids installing in `Program Files` because it will be broken there.

If you choose another path and it works open a new bug.

**Comment by beresnyak** [comment]
Did you read what I wrote? It does not give you a choice of install location. I guess I'll have to open a new bug.

**Comment by justingoldberg** [comment]
The solution is use the 32-bit version, plus you can run both versions side by side.

**Comment by Metroid-Prime** [comment]
Something to note that if someone is installing this in Sandboxie, it will give the same error (even though my Sandboxie is on D drive).
