### ISSUE TITLE
HexChat won't accept nick with underscore

### ISSUE THREAD

**Issue by TheRealPear** [hexchat/hexchat#1845]
Hey all, so I installed HexChat today and I managed to login with esper.net but then HexChat starts to spam my chat log saying that it only accept "alphanumeric" nickname even though the underscore (_) work fine on other IRC client I use.

Thank you for reading this and hopefully you can fix this problem for me.

**Comment by TingPing** [comment]
HexChat does absolutely no validation of nickname so this is the network giving you this message.

With that said I connected to EsperNet and changed my nick with no issues.

**Comment by TheRealPear** [comment]
@TingPing 
Weird, I connected to esper.net before with my nick that have underscore and it never gave me any error, only the problem occur everytime I use HexChat

**Comment by philwyett-hemi** [comment]
I cannot reproduce this issue on any platform with hexchat.

**Comment by TheRealPear** [comment]
@philwyett-hemi , set your nickname as a username with underscore with the esper.net server setting on HexChat's Network List. It seem like it only happen on Esper.net though.

**Comment by TingPing** [comment]
What is the exact server on espernet?

**Comment by philwyett-hemi** [comment]
Connected to irc.esper.net with my normal nick that I use on Freenode.

See screenshot.
![screenshot from 2016-10-27 23-36-36](https://cloud.githubusercontent.com/assets/22780155/19788115/849821bc-9c9e-11e6-89fd-c7909eaee104.png)

**Comment by TingPing** [comment]
The server tab prints the specific server in the MOTD.

**Comment by TheRealPear** [comment]
Actually, the nick with underscore work if I put anything in front of the underscore but it only give me this error 

> (* *** Your username is invalid. Please make sure that your username contains only alphanumeric characters.)

 when I use my nick without anything in front of the underscore.

**Comment by philwyett-hemi** [comment]
@TheRealPear Indeed, the use of underscores as a nick prefix is forbidden by this server. This is not an issue of hexchat, but an irc.esper.net decision.

@TingPing This should be mark as not a bug.

![screenshot from 2016-10-28 00-44-42](https://cloud.githubusercontent.com/assets/22780155/19789496/ff48f3b0-9ca7-11e6-9a78-3638fe905793.png)

**Comment by TheRealPear** [comment]
But the only thing is that my nickname work fine on other IRC client such as mIRC, esper.net's webchat, IRCCloud. I moved to HexChat because it was better. I only found a workaround for this but it will show the message everytime I startup my HexChat.

**Comment by philwyett-hemi** [comment]
As a note. I have files a ticket with esper.net about not allowing an underscore prefix. I will post info if I get a response.

**Comment by Arnavion** [comment]
Is that a hyphen in front of the username in the screenshot? Is that the problem?

**Comment by philwyett-hemi** [comment]
@Arnavion The tilde is a prefix if their ircd cannot handshake with a host ident server.

[https://esper.net/ircd.php#ircd-usermodes](https://esper.net/ircd.php#ircd-usermodes)

**Comment by philwyett-hemi** [comment]
@Arnavion I am curious too. All bar mirc are web based. I will test mirc when I get the Win 10 ISO downloaded.

Other clients such as xchat also fail with underscore prefix nicks.

![screenshot_centos_7_ws_x86_64_clone_2016-10-28_02 21 06](https://cloud.githubusercontent.com/assets/22780155/19791083/ca5d25d2-9cb5-11e6-8924-ef5198c09edb.png)

**Comment by philwyett-hemi** [comment]
Below is the response from Esper.

`Message:

Hello,

Per RFC 1459 (the document that describes the IRC protocol), nicknames must begin with a letter:

<nick> ::= <letter> { <letter> | <number> | <special> }

You can find the full document here: [https://tools.ietf.org/html/rfc1459#section-9.2.1](https://tools.ietf.org/html/rfc1459#section-9.2.1)

Any IRC daemon that permits a nickname that doesn't start with a letter is not compliant with IRC protocol.

Thanks,

mr_flea
EsperNet Server Administrator`

Also see: [https://tools.ietf.org/html/rfc1459#section-2.3.1](https://tools.ietf.org/html/rfc1459#section-2.3.1)

Regards

Phil

**Comment by TingPing** [comment]
Oh it sounds like you are confusing *nickname* and *username*, so in other clients you probably only set the former?

**Comment by philwyett-hemi** [comment]
@TingPing This is their answer and interpretation of the RFC, not mine.

What needs to be taken from all the info is:

- Not a hexchat issue.
- Other software also see error.
- Esper.net IRCd does not allow underscore prefix on nicks.

**Comment by TingPing** [comment]
No I am referring to @TheRealPear, EsperNet doesn't care if your nick starts with _ they care if your username does.

**Comment by philwyett-hemi** [comment]
@TingPing That is true. I have just tested and indeed it only errors if the username has an underscore prefix. The nick can, which seems to go against what the Esper admin quoted me. I will forward this info back to them. Many thanks.
