### ISSUE TITLE
New recommendations（新的建议）

### ISSUE THREAD

**Issue by ELE-Clouds** [hexchat/hexchat#1847]
Because there may be people in different languages in IRC, switching the translation software back and forth can affect communication. I hope to be able to join the simultaneous translation function, with the translation plug-in recommended several outstanding as the default, the other can be their own definition.
------------------以上翻译来自谷歌翻译------------------------
由于IRC中可能存在使用不同语言的人，但不断来回切换翻译软件会影响交流效果。希望能够加入同步翻译功能，用翻译插件推荐几个优秀的作为默认，其它的可以自己定义。

**Comment by TingPing** [comment]
I'm confused, are you talking about a plugin? If so why are you opening an issue here? HexChat itself will never support translation directly as it depends upon third party services typically.

**Comment by ELE-Clouds** [comment]
Oh. I'm sorry, thank you! I understand.
