### ISSUE TITLE
nick autocompletion is triggered without pressing [TAB]

### ISSUE THREAD

**Issue by zetok** [hexchat/hexchat#1850]
OS: Gentoo amd64
Hexchat: 2.10.2

Reproducible: Always

https://github.com/qTox/qtox-irc-logs/blob/f33964e71b5499a72409a97f2f5f0712563f5dd0/2016/09/%23qtox_20160923.log.txt#L111,L115

Steps to reproduce:
1. Have `rerumnovarum` in an IRC channel
2. Write `re: foo; bar`, that should do I think?
3. Press enter pinging `rerumnovarum`, since Hexchat makes message to be `rerumnovarum: foo; bar`

Any other info that I could supply?

**Comment by TingPing** [comment]
`/set completion_auto off`. Note that this does *not* default on.

**Comment by zetok** [comment]
>Note that this does not default on.

Hmm, I didn't set that option though, and I haven't seen it in Settings.. Makes me wonder if that's a leftover from old XChat config I've renamed years ago -.-

Thanks, next time I'll make sure to look in hexchat.conf.

**Comment by TingPing** [comment]
At one point it was in *Preferences > Input box*. In the current release it was removed from that dialog because its a pretty weird setting that only gets enabled on accident.
