### ISSUE TITLE
Hexchat does not notice a change in time zone (Windows)

### ISSUE THREAD

**Issue by tombii** [hexchat/hexchat#1851]
I started HexChat 2.12.1 while I was traveling in GMT+11. Then I put my computer to sleep and back in GMT+2, I changed the Windows time zone setting. I opened the network list in Hexchat (since I had been disconnected) and reconnected to my IRC network.
Messages however are still displayed in GMT+11 in the chat window (time stamps enabled).

![hexchat](https://cloud.githubusercontent.com/assets/6607822/19600333/d05a920a-97a4-11e6-8b33-32e9bd72d054.png)

**Comment by flotwig** [comment]
Can verify that this is an issue. If you leave HexChat running while moving across timezones, timezones will be stuck in the timezone you started HexChat with until you restart it.

**Comment by TingPing** [comment]
@learn-more Is there something special applications would do on Windows to avoid this?

https://github.com/hexchat/hexchat/blob/07f1fc60dac480d3e4ca8e98ec1c0e08c050676d/src/common/text.c#L636

**Comment by learn-more** [comment]
@TingPing There is [WM_TIMECHANGE](https://msdn.microsoft.com/en-us/library/windows/desktop/ms725498(v=vs.85).aspx)

**Comment by TingPing** [comment]
So why doesn't `localtime()` respect that?

**Comment by Arnavion** [comment]
Windows CRT's localtime caches the timezone and doesn't reset it. The user has to do it manually by calling `_tzset`.

`WM_TIMECHANGE` is a window message; the CRT itself has nothing to do with it. HC could of course use that message to call `_tzset` if GTK lets you receive it.

**Comment by learn-more** [comment]
i'll add a pull request for that soon.
