### ISSUE TITLE
Vector-based emoji support

### ISSUE THREAD

**Issue by nicholatian** [hexchat/hexchat#1854]
Twitter has apparently [open-sourced their emoji set](https://blog.twitter.com/2014/open-sourcing-twitter-emoji-for-everyone) for everyone. Having support for this in HexChat would be really helpful for those of us who use it, and even for those who don’t, it still brings about a more pleasant viewing experience on the client.

I have a collection of auto-replace functions in my HexChat config for typing emoji, but as it stands right now they only come up as black-and-white glyph outlines. Having them coloured using scalable vector graphics would be great to have. Thanks!

**Comment by vaguerant** [comment]
This is probably a duplicate of #1843, where it was explained that this is an upstream issue.

**Comment by nicholatian** [comment]
AFAIK that issue talked of colouring for otherwise text-based emojis. What I’m suggesting is that SVG graphics, hopefully Twitter-based ones, be inserted in place of the emojis by the client.

**Comment by TingPing** [comment]
If it is related to fonts in anyway then it has nothing to do with this project and is an upstream issue for Pango.

**Comment by vaguerant** [comment]
Those font/text-based emoji in question **are** vector graphics. Given fonts with vector emoji already exist, it seems unnecessarily convoluted for HexChat to implement a separate method of displaying vector graphics outside of the font system.

**Comment by nicholatian** [comment]
Nothing’s happened in several months, so I guess this issue is in the deadpool. Thanks anyways~
