### ISSUE TITLE
Provide App bundle for OSX

### ISSUE THREAD

**Issue by philicious** [hexchat/hexchat#1858]
Please provide an app bundle for OSX like for earlier versions https://dl.hexchat.net/hexchat/osx/

Install via Homebrew is working but its not straightforward / userfriendly for average Joe.
Secondly the homebrew version always has an ugly terminal window open along Hexchat window.

**Comment by TingPing** [comment]
I won't be doing this:

- I no longer use OSX
- The OSX version is awful and I don't really want to promote it or suggest people use it
- Homebrew (and other repos) will do a better job maintaining dependencies anyway

**Comment by idnow-philicious** [comment]
oh ok so MacOS isnt supported officially ?

PS: to me, OSX version looks&feels the same as on Windows or Linux

Is there some wiki page that would hint me the steps for doing such a HexChat bundle ?

**Comment by philicious** [comment]
oh ok so MacOS isnt supported officially ?

PS: to me, OSX version looks&feels the same as on Windows or Linux

Is there some wiki page that would hint me the steps for doing such a HexChat bundle ?

**Comment by TingPing** [comment]
OSX is largely unsupported yes.

> Is there some wiki page that would hint me the steps for doing such a HexChat bundle ?

https://github.com/hexchat/hexchat/tree/master/osx

**Comment by zkl94** [comment]
if it is unsupported, then please update the feature description "Cross-platform on Windows, OS X, and Unix-like OSes" on https://hexchat.github.io/ to add some kind of warning. It is very misleading for OS X users.

**Comment by TingPing** [comment]
@zkl94 Updated.

**Comment by worc** [comment]
it doesn't look like it was updated? it's still misleading, and moreso these days after apple stopped calling in osx and moved on to calling it macos. it's hard to tell if the animus against osx applies to more recent releases.

**Comment by TingPing** [comment]
It says:

> Cross-platform on Windows and Unix-like OSes

Seems fine to me, no longer mentions OSX.

**Comment by philicious** [comment]
yep, its fine

**Comment by worc** [comment]
i guess it's misleading because the popular idea is that osx and macos are both unix-like.

**Comment by philicious** [comment]
@worc btw there is some work going in #1931 for an unofficial Hexchat build. I did that for older Hexchat versions. however since the build system got changed, there needs to be some more work put into it.
