### ISSUE TITLE
HexChat 2.12.3 lose logs

### ISSUE THREAD

**Issue by nemysis** [hexchat/hexchat#1860]
Please revert Windows little Names and use normal GNU/Linux big and little Names.

Or make in menu an Option to use Windows or GNU/Linux Names and one Tool to change between these Settings and convert automatically Names for Server, channel and user.

Users  than I with many Servers and Channels not have Time to make this self.
I not wish to come to IRC with HexChat 2.12.3.

**Comment by TingPing** [comment]
http://stackoverflow.com/questions/152514/how-to-rename-all-folders-and-files-to-lowercase-on-linux
