### ISSUE TITLE
Connect without autojoins?

### ISSUE THREAD

**Issue by Tanath** [hexchat/hexchat#1861]
There doesn't seem to be a way that I can find to connect to a server without autojoining channels. I'm troubleshooting sasl authentication over tor and need to connect once without tor, but autojoining my channels would defeat the purpose of tor. I have about 100 channels so manually removing and readding is out of the question. Is there something I've missed, or a solution for this?

**Comment by TingPing** [comment]
There is no quick toggle for all autojoins; The two best methods for this would either be to make a new temporary network to figure this all out or to backup your `servlist.conf` file and just remove the autojoins and restore it when complete.

**Comment by Tanath** [comment]
Thanks, I was just in the process of figuring this out. I think backing up `servlist.conf` is easiest. A toggle would be really nice though. When you have a lot of channels for a server sometimes you only want to connect to fewer channels, or none ( eg. for troubleshooting, or a short time). Reconnections would be spammy for those channels otherwise.
