### ISSUE TITLE
PPA is (still) far behind

### ISSUE THREAD

**Issue by kernelpanic3** [hexchat/hexchat#1863]
It would be nice if the Ubuntu/Debian PPA could be updated, or an alternate one arranged. I don't find the idea of having to build from source repeatedly very appealing, and the one source with anything newer than 2.12.0 has a broken binary (and is still only 2.12.1)...

I realize the PPA's maintainer is busy, but this is rather absurd.

**Comment by TingPing** [comment]
The Debian packager is looking for a new maintainer.
