### ISSUE TITLE
Highlights should be more strict about punctuation

### ISSUE THREAD

**Issue by daemhan** [hexchat/hexchat#1864]
On an IRC network that I own, I use the nick "g", and for some reason, highlight alerts me on a lot of 'false positives'. 

For instance:
B.I.G., g;laring [someone typoed], g'morning, g'night, and several others like this will highlight me. It seems that it should work that only when the letter is preceded and followed by a space that I should be highlighted. We have other people who use single-character nicks as well. One of whom uses "Y", and she has mentioned that she has the same issue when people say 'y'all'. This does not happen when the letter is included in a regular word. Big, glaring, good morning, and good night, for instance, do not trigger it.

It's not a huge issue, but it can be a bit annoying when looking for highlights only to find that it was a false positive. This has been happening for 3 years now, since I started using the single character as a nick, so I'm assuming that it was a small bug previously as well.

**Comment by TingPing** [comment]
As I see the current behavior is ideal. `TingPing's` is a valid highlight. Sure it could go a step further and understand `'s` is special but this seems unecessary simply to workaround the specific nick of `g` being used in `g'night`. An easier alternative would be to write a script for you personally that handles that situation.

**Comment by daemhan** [comment]
It applies to all single character nicks as we just tested, but we figured out that how HexChat is handling that is better than other clients, which seem to use *nick*, and a script would probably break other things, since it would also remove highlights if people pasted something any of us using the single letters had said. Unless it were 'fixed' to only highlight _g_ [or whatever other single character], and then we'd all have to altar textsettings to use < nick > or whatever <>|{}|.., etc. we customised with. Interestingly, if the single character is ` or |, it's not affected from what we can tell.

Had not thought of that aspect. I'll go ahead and close this, because it's frankly something that -could- be fixed, either with the client itself or with a script, but getting all the parameters together to account for any little anomaly it is just way too much work for a minor annoyance. Thanks for the reply!

**Comment by TingPing** [comment]
>  and then we'd all have to altar textsettings to use < nick > or whatever <>|{}|.., etc.

Highlighting is at a lower layer than text events so these don't matter.

Really though this script isn't too hard (untested ofc):

```python
def on_highlight(word, word_eol, userdata):
  words = word[1].split()
  nick = hexchat.get_info('nick')
  nicklen = len(nick)

  # Allow exact matches with a few exceptions
  for w in words:
    if hexchat.nickcmp(w[:nicklen], nick) == 0:
      if len(w) != nicklen and not w.endswith((',', '.', ':', "'s")):
        hexchat.emit_print('Channel Message', *word)
        return hexchat.EAT_ALL
      return

hexchat.hook_print('Channel Msg Hilight', on_highlight, priority=hexchat.PRI_HIGH)
