### ISSUE TITLE
IRC client keeps disconencting from irc bouncer

### ISSUE THREAD

**Issue by paladox** [hexchat/hexchat#1867]
Hi when I go into the background and open another application, irc client seems to not send me irc notifications so I tried a whois call and then that triggers it to disconnect me and reconnect me to my irc bouncer.

This happened recently as it was working before.

I am unsure if this problem started in hexchat 2.12.2 or 2.12.3 but one of those is the cause.

And may be related to patch  https://github.com/hexchat/hexchat/commit/e7101ebcae9ab846faa19511d374cd331f5ce684

**Comment by paladox** [comment]
It may be caused by https://github.com/hexchat/hexchat/commit/6b2cc1d28b67dd352c4be775ba214ca864cc5500 And https://github.com/hexchat/hexchat/commit/215a164e57c7eb19beca503be2da1f50660ffb82 And https://github.com/hexchat/hexchat/commit/bcbe42dd7a4b7bca0e699c3e52f2c9bf7b37deba

This may have been caused by one of those patches doing power saving. Power saving should be an option since that may be causing this.

**Comment by TingPing** [comment]
Since you keep replying to #1866 clearly this is a duplicate.
