### ISSUE TITLE
please relicense doat away from WTFPL, or make it not part of the default build

### ISSUE THREAD

**Issue by marcmerlin** [hexchat/hexchat#1869]
Howdy, Sorry to bother you with this, but WTFPL is not a real license and while some people think it's fun to use it, it's actually causing the derived works (hexchat here) to be tainted with a bad license. Hexchat has just been removed from our software repository at work sadly just because of this one plugin.
Sure, we could rebuild without it and maintain a fork, but not really worth or time.
https://en.wikipedia.org/w/index.php?title=WTFPL&oldid=712812819#Effectiveness_as_license_or_waiver
https://en.wikipedia.org/w/index.php?title=WTFPL&oldid=712812819#Characteristics
I realize it's not the main license of hexchat (good), hence my suggestion to ensure your end product (a package in a distribution) is not tainted with WTFPL

**Comment by TingPing** [comment]
I agree it is a license I would rather not have but:

> Hexchat has just been removed from our software repository at work sadly just because of this one plugin.
Sure, we could rebuild without it and maintain a fork, but not really worth or time.

Really...

**Comment by TingPing** [comment]
So here is a commit killing the plugin: https://github.com/hexchat/hexchat/commit/faa6ab758dd4290656f89746ef9cce7a04ddd2d1

This actually does nothing to your situation though, you still have to make a new package.

**Comment by marcmerlin** [comment]
1) thanks for your answer.
2) you're right it's not hard to rebuild, but if you have thousands of internal users and 5-10k debian packages in use, we don't really have the time to do custom work them, especially less essential ones
3) your change does help somewhat though because if we have an internal user who decides to do a rebuild of your package, your change now will hopefully land into the next version of the distro without extra work, making re-adding the package by default much easier.
So thanks for the change and your reply.

**Comment by TingPing** [comment]
Unless somebody does the work to backport this then it could be multiple years before you even see it...

**Comment by marcmerlin** [comment]
I understand, but as I said, if upstream is fixed, it's more of an incentive for someone on our side to fix it too since we know we won't have to keep the fork forever.
Thanks for your quick change, I appreciate it.
