### ISSUE TITLE
Highlights in PMs doesn't work

### ISSUE THREAD

**Issue by slushpuppy** [hexchat/hexchat#1871]
When someone PMs me, the PM shows default orange

However if someone highlights and PMs me, the tab just shows black

Hexchat 2.12.3, win64

**Comment by TingPing** [comment]
Works as expected here. What is the color set to in *Preferences > Colors > Highlight* ?

**Comment by slushpuppy** [comment]
@TingPing The default orange. Try this:

/msg <your nick> <your nick>, it will show up like this->

http://i.imgur.com/vIGcBwK.png

**Comment by TingPing** [comment]
So your problem is messaging yourself doesn't count as a highlight. That honestly sounds fine to me...

**Comment by slushpuppy** [comment]
@TingPing No, it is 2 different nicks private messaging each other. 

Try it yourself, have someone in the channel pm you with your name only.

**Comment by TingPing** [comment]
Ah, seems this was a side effect of 03767ee0f98262220eb13a2fcb1f2fe0963cba3d

**Comment by slushpuppy** [comment]
@TingPing Appreciated, thanks man!
