### ISSUE TITLE
option to sort channels by activity

### ISSUE THREAD

**Issue by pabs3** [hexchat/hexchat#1873]
It would be useful if there were an option to sort the channel list by the amount of activity in the channel since the last marker line. I would personally like if the channels were *not* grouped by the network, since that would interfere with activity sorting.

I would suggest a calculation something like this for the activity ratings: 1 point for joins/parts, 5 points for notices, 10 points for messages, 15 points for messages with configured highlights and 20 points for messages directed at the user with "nick[,:] example message here".

This would be very useful for focussing on which backlog to read first, especially for people who are on a lot of channels that are mostly inactive.

**Comment by TingPing** [comment]
This information is already sort of exposed via the <kbd>Ctrl</kbd>+<kbd>`</kbd> binding. In theory somebody could hook that up to sorting.

**Comment by Arnavion** [comment]
Won't the tab list / tree list jump around like crazy? Even if you run it on a low-frequency timer it would still jump around as you were looking at it / mousing over it / cycling through it with the keyboard.

**Comment by TingPing** [comment]
Yea it would be pretty awful.

**Comment by pabs3** [comment]
I can't find any info about the Ctrl+` shortcut, got a link to the docs/code for that?

For me, I don't think there would be much jumping around.

You could put the sorting behind a keystroke to avoid that though.

**Comment by TingPing** [comment]
The only docs are `Settings > Keyboard shortcuts`

**Comment by pabs3** [comment]
Ah, it looks like you meant Alt instead of Ctrl. That and Ctrl+Shift+m
(which is not listed) looks very useful.

Now I just need to figure out how to migrate my XChat setup.

**Comment by pabs3** [comment]
Just tried the shortcut in HexChat 2.12.0 from Debian and the 'auto' option does not work as advertised in the help text, it just focuses the tab bar and then cycles focus through the tab buttons. It doesn't switch tabs until you press Space and doesn't cycle according to activity.

**Comment by TingPing** [comment]
Ah sorry yes Alt.

> That and Ctrl+Shift+m (which is not listed) looks very useful.

There are two types of shortcuts, the customizable kind and the menubar kind. This is in Window where you can see its binding.

> it just focuses the tab bar and then cycles focus through the tab buttons. It doesn't switch tabs until you press Space and doesn't cycle according to activity.

The input box has to be focused for any of those shortcuts to work, I don't use tab buttons but it sounds like they are stealing focus which should never happen.

**Comment by pabs3** [comment]
Woops, I was pressing Ctrl+Tab instead. I customised it to Ctrl+` because GNOME uses Alt+` for window switching. I guess that is a good alternative to the sorting that I suggested. You can close this issue now, sorry for the noise.

Is there any way for jumping to the marker line to be the default when you switch to a new tab?

**Comment by TingPing** [comment]
> Is there any way for jumping to the marker line to be the default when you switch to a new tab?

Nope.
