### ISSUE TITLE
How do you downloaded the latest compiled version of hexchat?

### ISSUE THREAD

**Issue by slushpuppy** [hexchat/hexchat#1874]
https://dl.hexchat.net/hexchat/testing/

I am getting my exes from here, but they don't appear to fix the issue I am having regarding highlighted nicknames in PM

**Comment by TingPing** [comment]
@tomek Just needs to upload the newer build.

**Comment by slushpuppy** [comment]
@TingPing Thanks a ton!

**Comment by tomek** [comment]
@slushpuppy new build 13f6d92 is up

**Comment by slushpuppy** [comment]
thanks alot @TingPing @tomek
