### ISSUE TITLE
"Unknown host. Maybe you misspelled it?"

### ISSUE THREAD

**Issue by HelloBats** [hexchat/hexchat#1887]
As of yesterday afternoon, Hexchat is giving me an error that states "Unknown host. Maybe you misspelled it?" when attempting to connect to any IRC network. When I run nslookup from a command prompt, it returns a ip address for the servers consistent with other people I checked with.

**Comment by 0thread** [comment]
Happened several times to me and my acquaintances as well, but was not possible to reproduce when needed.

**Comment by HelloBats** [comment]
I was running Windows 10. Strangely, it was fixed after restarting twice, the issue persisted after the first restart.

**Comment by barjac** [comment]
I was seeing this error in Linux for months when hexchat was in autostart in plasma5. After killing the autostarted instance of hexchat and re-starting there was no further problem. It seemed that there was a timing issue during startup. This has now been fixed by recent system updates - possibly systemd, but only guessing.

**Comment by slester** [comment]
I'm getting this error in Linux only for `chat.freenode.net`. `host` and `dig` reveal proper IP lookups, and I can connect to `irc.mozilla.org` perfectly fine, but I'm getting the following on loop, even after closing all instances of Hexchat and reopening it:

```* Looking up chat.freenode.net
* Unknown host. Maybe you misspelled it?```

**Comment by smt923** [comment]
I realize this is old but this may shed some light on some people's issues, for me I had copied over my settings from a windows install to a linux install, what I didn't realize is the different line endings were messing up the server information, so if you're sure it's not a network/dns issue on your end, try converting/cleaning up erroneous line endings for your platform in your settings
