### ISSUE TITLE
Autocorrection of 'the' can not be disabled?

### ISSUE THREAD

**Issue by kakobrekla** [hexchat/hexchat#1888]
Hi,

in my native language we often use 'teh' which gets autocorrected to 'the'. I tried to play with dictionaries and adding the word to ignore, however I am unable to disable this.  I also tried joining user 'teh' to the chan, yet autocorrection keeps getting in the way.

Is there any way to alleviate this pain?

**Comment by kakobrekla** [comment]
This explains it:

https://github.com/hexchat/hexchat/blob/master/src/common/hexchat.c#L734

I hope you realize how insane this is? Please to remove it.

**Comment by kakobrekla** [comment]
Update, noticed

https://github.com/hexchat/hexchat/blob/master/src/common/hexchat.c#L958

and so created empty 'replace.conf' which made the problem go away.

**Comment by TingPing** [comment]
*Settings > Auto Replace*

**Comment by kakobrekla** [comment]
Auto replace will not disable it!

**Comment by TingPing** [comment]
You simply click *Delete* and *Save* in that dialog.
