### ISSUE TITLE
Upstream 2.12.4 tarball is "broken" on OpenBSD

### ISSUE THREAD

**Issue by n0la** [hexchat/hexchat#1897]
The upstream tarball was created with:

```shell
autoreconf --install --symlink
```

Which means that most files in the ```m4``` are installed as symlinks to ```/usr/share/automake```. This breaks build on OpenBSD as those symlinks are now broken. Please fix your tarball by **not** adding the ```--symlink``` option on autoreconf.

**Comment by TingPing** [comment]
Sorry about that, will try to remember that next time: I've uploaded a new tarball here (as to not break hashes for other distros): https://dl.hexchat.net/hexchat/hexchat-2.12.4-repack.tar.xz

**Comment by n0la** [comment]
The repacked tarball does fix this issue. Thanks.
