### ISSUE TITLE
Hexchat 2.12.4 detected as Trojan/GdSda.A by Panda Free Antivirus

### ISSUE THREAD

**Issue by lifebaka** [hexchat/hexchat#1901]
Just downloaded the newest version, and was getting it flagged as a virus repeatedly.  Not using portable mode, am on the x86 build, using Windows 10 Home (x64).

**Comment by TingPing** [comment]
I wrote a blog post about this common complaint: https://hexchat.github.io/news/hexchat-and-antivirus.html

TL;DR: It is a false positive, whitelist hexchat or wait.
