### ISSUE TITLE
Theme manager relies upon current directory to detect portable-mode

### ISSUE THREAD

**Issue by z0rti** [hexchat/hexchat#1902]
Using: HexChat 2.12.4
hexchat.exe works as expected, using HexChat\config\ folder
thememan.exe complains:
"HexChat installation not found! Check your %APPDATA%/HexChat folder"

**Comment by TingPing** [comment]
How are you launching it?

**Comment by z0rti** [comment]
I launched it with a path "c:\Program Files\HexChat\thememan.exe"
Doubleclick in explorer does work, though...

**Comment by TingPing** [comment]
Yea it relies upon the CWD to find the `portable-mode` file.
