### ISSUE TITLE
All icons have disappeared

### ISSUE THREAD

**Issue by hariharan-m** [hexchat/hexchat#1905]
The Tray Icon, User Mode icons, Network Icons have disappeared. Have rebuilt hexchat from source but still the problem persists. Im on Arch Linux.

**Comment by TingPing** [comment]
`gdk-pixbuf2` update caused this, reported upstream:

- https://bugs.archlinux.org/task/52168
- https://bugzilla.gnome.org/show_bug.cgi?id=776105

**Comment by hariharan-m** [comment]
Downgrading the gdk-pixbuf2 package to the previous version (2.36.0) fixed it. Thank you.

**Comment by TingPing** [comment]
This was fixed upstream.

**Comment by darkcircle** [comment]
I have also met this problem ... and I'm using gentoo distribution .... so...
should I rebuild hexchat with latest version of gdk-pixbuf?

**Comment by TingPing** [comment]
@darkcircle Just having any gdk-pixbuf version other than the one broken release will do.

**Comment by darkcircle** [comment]
@TingPing  OMG ... I saw now. sorry for late and thank you so much!!!!!!!!
