### ISSUE TITLE
Unable to install to a network drive on Windows 8.1

### ISSUE THREAD

**Issue by YuGiOhJCJ** [hexchat/hexchat#1906]
Hello,
I am unable to install HexChat 2.12.4 x64 to a network drive, on Windows 8.1

I set this destination location:
```
Z:\Users\yugiohjcj\Desktop\software\HexChat
```

Then I get an error:
```
The drive or UNC share you selected does not exist or is not accessible.
Please select another.
```

How to solve that please?
Why don't you provide a version without installer to avoid this issue?

Thank you.
Best regards.

<img src="http://yugiohjcj.free.fr/hexchat-network-drive-windows.png"/>

**Comment by learn-more** [comment]
If the network drive is mapped as regular user (which it probably is, if you can see it in explorer) that means the installer running as admin cannot see it.

To verify this is the case, open a command prompt (cmd) as admin, and try to navigate to the Z: drive.

**Comment by YuGiOhJCJ** [comment]
Indeed, my network drive is mapped as regular user so the administrator cannot see it:
````
C:\Windows\system32>Z:
The system cannot find the drive specified.
````

So, installing HexChat on a network drive requires to mount my network drive as administrator?
If you know how to do that and if it is safe, please give me instructions because I want to try.
I still think you should provide a version without installer to avoid this issue.
Take example on Minetest if you need: https://github.com/minetest/minetest/releases
It's easy: You extract then you run.

**Comment by learn-more** [comment]
How do you map the network drive usually?
Repeat the same steps from an administrator process,
or try one of the workaround described here: https://support.microsoft.com/en-us/help/3035277/mapped-drives-are-not-available-from-an-elevated-prompt-when-uac-is-configured-to-prompt-for-credentials-in-windows

As an alternative, try installing to the full UNC path as alternative (\\server\\directory).

**Comment by YuGiOhJCJ** [comment]
In order to map the network drive, I usually do it from my graphical user interface:
- I do a double click on my "Network" icon on the desktop
- I do a click on my remote machine in the network
- I do a right click on my remote directory
- I select "Map network drive..."
- In the "Map Network Drive" window, I select the drive letter (here "Z:")
- I check the "Reconnect at sign-in" box
- I uncheck the "Connect using different credentials" box
- I do a click on the "Finish" button

Repeating these steps as an administrator is not possible for me because I don't know how to be administrator in the graphical user interface.

Hopefully, I know how to be administrator through the command line.
So, in the administrator command prompt, I can list the network drives:
```
C:\Windows\system32>net use
New connections will be remembered.

There are no entries in the list.
```
As you can see, network drives mapped by the user are not visible here.

So, I map from the command line as administrator:
```
C:\Windows\system32>net use z: \\laptop\windows
The command completed successfully.
```

Then I check if the map is done correctly:
```
C:\Windows\system32>net use
New connections will be remembered.


Status       Local     Remote                    Network

-------------------------------------------------------------------------------
OK           Z:        \\laptop\windows          Microsoft Windows Network
The command completed successfully.
```

It seems it is.
So, I launch the installer on my desktop and it works!
I am able to install to the Z: network drive.
However, when I reboot my machine, the network drives mapped by the administrator is not anymore mapped:
```
C:\Windows\system32>net use
New connections will be remembered.

There are no entries in the list.
```
But it does not matter because now hexchat is installed and works fine as a user!

Problem solved.
Thanks.

**Comment by learn-more** [comment]
For future reference:

- Open task manager (RMB on task bar, task manager)
- Kill all instances of explorer
- In task manager -> File -> New task
- enter 'explorer.exe'
- Check the box 'Run as administrator'
- Press 'OK'
- Apply the mapping as usual
- Kill explorer again
- Start a new instance of explorer, this time not as admin

Your way is probably simpler :)
