### ISSUE TITLE
Website licence

### ISSUE THREAD

**Issue by anowlcalledjosh** [hexchat/hexchat#1907]
Is the hexchat website under a FOSS licence? I'd like to use some of the CSS to style [/r/hexchat](https://reddit.com/r/hexchat), but it's not clear whether I'm allowed to. The [Modernist](https://github.com/orderedlist/modernist) theme it's based on is under CC BY-SA 3.0; can I assume that, being a derivative of the Modernist theme, all the CSS from https://hexchat.github.io is also under CC BY-SA 3.0 (unless otherwise noted, e.g. normalize.css)? It would be nice to get confirmation of this.

**Comment by TingPing** [comment]
>  The Modernist theme it's based on is under CC BY-SA 3.0

Correct.

> can I assume that, being a derivative of the Modernist theme, all the CSS from https://hexchat.github.io is also under CC BY-SA 3.0

As per the license itself, https://creativecommons.org/licenses/by-sa/3.0/, yes:

> ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.

**Comment by TingPing** [comment]
On a side-note, do we really need a subreddit? /r/irc is not active enough for questions to be a problem and I myself respond there.

**Comment by anowlcalledjosh** [comment]
You have a point. I'm happy to make a post directing people towards /r/irc and disable submissions to /r/hexchat if you'd like.
