### ISSUE TITLE
Use SQLite instead of simple scrollback files

### ISSUE THREAD

**Issue by MicroDroid** [hexchat/hexchat#1908]
HexChat badly lags when you connect to a bouncer and your bouncer streams an `n` number of channels joins, it forces your disk to seek to also seek `n` times to read the scrollbacks and retrieve them

How about using SQLite for this? That would work way better, because technically it's a scrollback database

**Comment by TingPing** [comment]
What evidence do you have that reading the disk is the bottleneck?

I'd imagine if you change *Prefs > Chan Switcher > Focus new tabs* to be *Never*. The client will be responsive during connection.

**Comment by jwshields** [comment]
I have my bouncer set to send 100 lines of scrollback upon connect. I join about 20 networks and 250 channels and hexchat lags a bit, but this is just because of the mass of data being sent, not something that I would really say is a fault of Hexchat.

Non-issue imo.

**Comment by MicroDroid** [comment]
@TingPing During channel joins, the disk activity goes to around 80-100% and the whole UI hangs with the mouse cursor spinning. The CPU usage was dead-low too so I thought it isn't the UI thread locking or something.

Though, that held false, when I set the `Focus new tabs` to `Never` the UI actually did way better, even though the disk usage was the same

**Comment by TingPing** [comment]
Honestly I'm not sure why one would want both ZNC and client side scrollback anyway.

**Comment by MicroDroid** [comment]
@TingPing Because each have their own time frame?

**Comment by jwshields** [comment]
I disable hexchat scrollback so that it doesn't show logs from last time i connected, but I use ZNC scrollback to show me recent activities, i dunno
