### ISSUE TITLE
Auto reclaim ghost nickname after disconnected

### ISSUE THREAD

**Issue by 00cpxxx** [hexchat/hexchat#1910]
Hi, all. Thanks for the wonderful project. I believe this issue must have been posted but I cannot find anything similar using the same way I use to describe this.

It is possible to configure 4 nicknames, the first is the main one and it is registered in the nickserv. When I'm disconnected hexchat smartly reconnects to the network using the second nick. What I would like is for it to watch the nick list until my ghost is disconnected due to ping timeout and then rename myself to my main nick and identify myself.

If no channels are joined it would be possible to achieve the same using whois command with regular intervals.

Thanks in advance and sorry if it is a double post.

**Comment by TingPing** [comment]
There is this script that can do this: https://github.com/Poorchop/hexchat-scripts/blob/master/Arnavion-scripts/autoidentify.py

**Comment by boussouira** [comment]
You can release your nickname using: `/msg NickServ release <nickname> <pass>`

**Comment by 00cpxxx** [comment]
Thanks for both answers, they do are palliative solutions, but what about integrating them? After connecting and checking that the first nick is unavailable and if a password is configured hexchat could auto release the nick and switch back to it much faster.

**Comment by TingPing** [comment]
Maybe, the one problem is that nickserv features aren't exactly standardized and can't be assumed to be supported.

**Comment by 00cpxxx** [comment]
I understand that but issuing a wrong command won't have any harmful effect too. I have cloned the source code and will dig a bit.

**Comment by Mikaela** [comment]
> I understand that but issuing a wrong command won't have any harmful effect too.

Enough wrong commands and the services will ignore you. The network operators will also complain if HexChat users start spamming invalid commands every restart.

**Comment by 00cpxxx** [comment]
No problem, we can still monitor PART messages until our ghost disconnects from any channel we are in and then change back to main nick and identify.

**Comment by TingPing** [comment]
I really hate `nickserv` and I hate workaround around its quirks so I'm not sure I want that in the core rather than a script.

**Comment by 00cpxxx** [comment]
No problem, I already solved my problem. Thanks.
