### ISSUE TITLE
Timestamp color not changing

### ISSUE THREAD

**Issue by wadie** [hexchat/hexchat#1913]
Hi,

I'm adding the following timestamp code

`%C18[%H:%M:%S] %O`

Which should make the timestamp appear in blue, based on what I saw in the Text Events.
Using Hexchat on Ubuntu.

**Comment by TingPing** [comment]
Timestamps have to be the raw irc characters not the hexchat format strings.

**Comment by wadie** [comment]
The raw IRC characters show as strings, no colors at all..
