### ISSUE TITLE
Feature request: webcam functionality

### ISSUE THREAD

**Issue by linuxscripts** [hexchat/hexchat#1914]
I wanted to request webcam functionality for Hexchat, either using FFmpeg or MJPGstreamer. 
Perhaps RTMP might be needed (https://obsproject.com/forum/resources/how-to-set-up-your-own-private-rtmp-server-using-nginx.50/ )

You could allow to have a channel OP stream his webcam footage, and make it available (only in the current chatroom), to all people in the chatroom (guests). If there is more than 1 OP in the chatroom, the person that was OP the first would get the streaming privilege, but upon leaving the room or de-opping himself, the person that then becomes OP will get the streaming privilege.

This feature should make the software usable as a (light-weight) videoconferencing software (which are in short supply for linux, andare often quite heavy on resources (see http://openmeetings.apache.org/installation.html ). IRC also all ready has the ability to make chatrooms private (see https://botbot.me/how-to-setup-irc-channel/ ), so that would be an additional advantage (then usable for say company meetings, ...).

**Comment by TingPing** [comment]
HexChat has no interest in becoming a video chat platform nor would it be trivial to duct-tape onto IRC and get other clients on board anyway.
