### ISSUE TITLE
Feature request: profile functionality

### ISSUE THREAD

**Issue by linuxscripts** [hexchat/hexchat#1915]
In addition to the webcam functionality, there was one other feature I wanted to request:

this other functionality is profile information.
At present, prety much the only information available of people on IRC is the nickname, and the IP or SSL (available via whois command). A more extensive profile would improve the system. To do so, a txt
file could be created by the hexchat program which can be transferred and loaded if people right-click on a user in a chatroom and click on "profile". The program can make the file by letting users type in the info in a "Profile" tab under the Preferences window.

Things the profile should be able to show:
Nickname:
Real name:
Birthdate:
Sex:
Location:
Website:
Remarks:
Avatar:

The avatar should allow for any image (in jpg or png format), up to a resolution of say 1024x768. This, as in regular chatting, the image isn't transferred so doesn't slow down anything, so there's no reason
why a full size image shouldn't be usable. When shown to the users requesting the user info, the size of the image can be set to a certain size (so the image doesn't fill the screen but is still high in detail)

**Comment by TingPing** [comment]
Probably best to leave this to a script. You could just add CTCP replies for your custom info and then your script can display them however you wish. kvirc already has their avatar system I believe but it isn't anything I have interest in.
