### ISSUE TITLE
Can't connect DCC CHAT connect fails every time? Doesn't open chat at all.

### ISSUE THREAD

**Issue by Truanifan** [hexchat/hexchat#1928]
Okay, I'm very IRC dumb so if I get something wrong or have trouble describing my problem accurately, I'm sorry. Please bear with me.

My issue is that I can't seem to get the DCC Chat session(?) to connect and open the chat in a new tab. I type the whole "/ctcp somename blah blah blah" thing to initiate the chat, see "Received a DCC CHAT offer from somename", click Accept, but it just hangs. After a few seconds it tells me: »» DCC CHAT connect attempt to somename failed (err=Connection timed out). It's happened every single time so far.

Is this a problem with my HexChat settings? I never had this problem before so I don't know what to do.

Thanks in advance for any advice.

**Comment by TingPing** [comment]
Probably have to set up port forwarding: http://hexchat.readthedocs.io/en/latest/faq.html#why-doesn-t-dcc-send-work-behind-a-router

DCC is fairly awful and I wouldn't recommend it, especially for CHAT it serves no purpose. It is inherently insecure as it doesn't support any encryption and is a PITA to use. Just use the bundled `fishlim` plugin or an `otr` plugin if you want a private chat.

**Comment by Truanifan** [comment]
My problem was fixed. Thank you for your help. Sadly, the DCC thing is the only way the other person has it set up to share files and such. Otherwise I'd heed your advice. For future I'll read up on the plugins you mentioned. Thanks again for your help!
