### ISSUE TITLE
Hexchat on MacOS

### ISSUE THREAD

**Issue by philicious** [hexchat/hexchat#1931]
hi @TingPing 

from one of our last conversations I know that MacOS isnt officially supported anymore.
So I'm trying to jhbuild and bundle it on my own.
I'm following https://hexchat.readthedocs.io/en/latest/building.html#os-x

Building HexChat under jhbuild worked and runs fine. Also your modified `gtk-quartz-engine` and `xamarin-gtk-theme`

However, when bundling, I get some warnings 
```
('Warning, library not available in any prefix:', '/usr/local/opt/freetype/lib/libfreetype.6.dylib')
('Warning, library not available in any prefix:', '/usr/local/opt/harfbuzz/lib/libharfbuzz.0.dylib')
('Warning, library not available in any prefix:', '/usr/local/opt/fontconfig/lib/libfontconfig.1.dylib')
```
and the bundle crashes with
```Dyld Error Message:
  Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /usr/local/opt/freetype/lib/libfreetype.6.dylib
  Reason: Incompatible library version: libfreetype.6.dylib requires version 44.0.0 or later, but libpng16.16.dylib provides version 34.0.0
```
and the 3 libs are indeed the only ones not loaded from the bundle, which seems wrong
```
       0x10bdd0000 -        0x10be38ff3 +libharfbuzz.0.dylib (0) <EEFD96F7-D24B-352F-9013-B05662148ACB> /usr/local/opt/harfbuzz/lib/libharfbuzz.0.dylib
       0x10be4f000 -        0x10be7cff7 +libfontconfig.1.dylib (0) <F7DD767D-B9D5-3F40-8A69-DD864B1C9124> /usr/local/opt/fontconfig/lib/libfontconfig.1.dylib
       0x10be8c000 -        0x10bf02fff +libfreetype.6.dylib (0) <69B2D432-70C4-3D22-9D6E-3244629C00B5> /usr/local/opt/freetype/lib/libfreetype.6.dylib
```

Now I'm wondering if that link from above is missing some info that you might know adhoc.

I did 
```
jhbuild bootstrap
jhbuild build meta-gtk-osx-bootstrap meta-gtk-osx-core
```
maybe I need additional things like freetype, fontconfig, harfbuzz there ? Or meta-gtk-osx-freetype ?

I'd appreciate some hints before spending more time. Thanks in advance !

**Comment by TingPing** [comment]
> So I'm trying to jhbuild and bundle it on my own.

Based upon those errors you aren't using jhbuild at all and are just building against homebrew.

**Comment by philicious** [comment]
@TingPing well I'm building in a `jhbuild shell` but I do have homebrew on same machine and already figured that it pulls in deps on/from that for some unknown reason.

**Comment by TingPing** [comment]
Jhbuild probably found libs at build time and linked to them, you really have to work in a clean environment if you want to use it.

**Comment by philicious** [comment]
ok. yep. I also thought about a separate user account w/o homebrew for doing this. but I wanted to make sure I'm not missing anything obvious that you might know and that docs is missing.

so I really dont need to `jhbuild build.. ` anything else than `meta-gtk-osx-bootstrap meta-gtk-osx-core` ? 

btw I did an `otool -L` on `~/gtk/inst/lib/*.dylib` and its these here that depend on the 3 wrong libs
```
libpangocairo-1.0.0.dylib
libpangocairo-1.0.dylib
libpangoft2-1.0.0.dylib
libpangoft2-1.0.dylib
```
maybe that rings some old bell ?

**Comment by TingPing** [comment]
> ok. yep. I also thought about a separate user account w/o homebrew for doing this. 

That doesn't help `/usr` containing libs, you need to unlink homebrew.

> so I really dont need to jhbuild build.. anything else than meta-gtk-osx-bootstrap meta-gtk-osx-core ?

It has been years and was always messy.. maybe?

**Comment by philicious** [comment]
@TingPing hehe ok then. I'll play around then and see what helps. thanks 👍  . 
I'll update this issue if it eventually worked out

**Comment by philicious** [comment]
I was able to build a HexChat.app bundle now , anyone stumbling over this issue, grab it here https://github.com/philicious/hexchat/releases/tag/2.12.4

@TingPing here are my complete build notes, maybe you wanna update https://hexchat.readthedocs.io/en/latest/building.html#os-x 
```
# install prerequisites
brew install openssl lua

# install GTK for OSx build env
download https://git.gnome.org/browse/gtk-osx/plain/gtk-osx-build-setup.sh
sh ./gtk-osx-build-setup.sh
jhbuild bootstrap
jhbuild build meta-gtk-osx-bootstrap meta-gtk-osx-freetype meta-gtk-osx-core

# setup build env for HexChat
jhbuild shell
export OPENSSL_LIBS="-L/usr/local/opt/openssl/lib -lssl -lcrypto"
export OPENSSL_CFLAGS="-I/usr/local/opt/openssl/include"
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/opt/openssl/lib/pkgconfig

# build hexchat https://github.com/philicious/hexchat/commits/build-on-osx
cd hexchat
./autogen.sh --prefix=$JHBUILD_PREFIX
make && make install

# build the native Quartz engine for GTK https://github.com/TingPing/gtk-quartz-engine/tree/mono
cd gtk-quartz-engine
./autogen.sh --prefix=$JHBUILD_PREFIX
make && make install

# build gtk osx-like theme https://github.com/mono/xamarin-gtk-theme
cd xamarin-gtk-theme
./autogen.sh --prefix=$JHBUILD_PREFIX
make && make install

# build spellchecker lib https://github.com/AbiWord/enchant
cd enchant  (checkout v1.6.1)
./autogen.sh --prefix=$JHBUILD_PREFIX --disable-ispell --disable-myspell --disable-aspell --enable-applespell
make && make install

# make the HexChat.app bundle
cd hexchat/osx
./makebundle.sh
```

PS: the wrong deps on homebrew libs were because `meta-gtk-osx-freetype` was missing from jhbuild. Besides that I only had to do a little patch and also update the bundle config file. see my branch if you are curious

**Comment by Halfwalker** [comment]
I know it's been a long time, but does anyone have a bundle for High Sierra 10.13.3 ?  The 2.12.4 from @philicious above doesn't work under HS ...  I can provide a fail report if interested.

**Comment by philicious** [comment]
@Halfwalker did you try my instructions for building ? I still havent updatend from Sierra and so didnt try to build XChat again

**Comment by Halfwalker** [comment]
No, not yet.  I was hoping to piggy-back off someone else :) . I'm new to Mac, so fumbling around a bit ...

**Comment by Halfwalker** [comment]
Starting to poke around with building locally.  One thing I noticed - no more autogen.sh ...  what now ?

**Comment by philicious** [comment]
@Halfwalker had a quick look, seems they changed the build system to `meson`, so my build instructions are outdated. 
however as `meson` seems to generally work on OSX (http://mesonbuild.com/Creating-OSX-packages.html) I'm confident Hexchat can still be build for OSX 

As there are no official docs, one has to figure stuff out themselves and might also need to read/understand/patch code. 
I remember from when I did the same which lead to my instructions above. It costs some hours.

I will give it a shot in like 2 weeks. Moving appartments right now and then 1 week holidays.

**Comment by Halfwalker** [comment]
Very cool - looking forward.  Now, learning Mac (coming from Linux/Gnome).

**Comment by TingPing** [comment]
Meson should make it easier over all to build on OSX but it does mean the OSX specific checks were left behind with the port and need to be re-done. This isn't *hard* work but it is still work that needs to be done and I'd accept any patches towards that or answer any questions.

**Comment by caronni** [comment]
@TingPing, thanks for linking the two issues. Looks like Homebrew is a bit conflicted in regards to GUI apps. There is https://caskroom.github.io/, but that seems to be only for pre-built binaries... And then there is things like macvim, git-cola and many others, which are clearly GUI based, but still in Homebrew. Hexchat would fit the bill?
 
@philicious Have a look at my build steps in #2173, seems to have me gotten a mostly working build using meson/ninja. However, no idea how to make an app after that, getting hung up on missing pieces (e.g. charset.alias).

**Comment by philicious** [comment]
@caronni did you see http://mesonbuild.com/Creating-OSX-packages.html on how to make an app bundle ?

**Comment by burdges** [comment]
I'll report that hexchat seemingly builds fine on macOS High Sierra using MacPorts with all gtk related ports set `+quartz`.. in the sense that it produces a binary that runs but..

If you just do `port install hexchat +quartz` then `meson-install` and `/opt/local/bin/ninja install` fail:
```
:debug:destroot Executing org.macports.destroot (hexchat)
:debug:destroot Environment: 
:debug:destroot CC_PRINT_OPTIONS='YES'
:debug:destroot CC_PRINT_OPTIONS_FILE='/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_irc_hexchat/hexchat/work/.CC_PRINT_OPTIONS'
:debug:destroot CPATH='/opt/local/include'
:debug:destroot DESTDIR='/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_irc_hexchat/hexchat/work/destroot'
:debug:destroot LIBRARY_PATH='/opt/local/lib'
:debug:destroot MACOSX_DEPLOYMENT_TARGET='10.13'
:info:destroot Executing:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_irc_hexchat/hexchat/work/build" && /opt/local/bin/ninja install 
:debug:destroot system:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_irc_hexchat/hexchat/work/build" && /opt/local/bin/ninja install 
:info:destroot [0/1] Installing files.
:info:destroot Installing src/fe-gtk/hexchat to /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_irc_hexchat/hexchat/work/destroot/opt/local/bin/hexchat
:info:destroot Installing plugins/checksum/checksum.dylib to /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_irc_hexchat/hexchat/work/destroot/opt/local/lib/hexchat/plugins/checksum.dylib
:info:destroot Installing plugins/fishlim/fishlim.dylib to /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_irc_hexchat/hexchat/work/destroot/opt/local/lib/hexchat/plugins/fishlim.dylib
:info:destroot Installing plugins/sysinfo/sysinfo.dylib to /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_irc_hexchat/hexchat/work/destroot/opt/local/lib/hexchat/plugins/sysinfo.dylib
:info:destroot Installing data/misc/io.github.Hexchat.appdata.xml to /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_irc_hexchat/hexchat/work/destroot/opt/local/share/metainfo/io.github.Hexchat.appdata.xml
:info:destroot Traceback (most recent call last):
:info:destroot   File "/opt/local/bin/meson", line 26, in <module>
:info:destroot     sys.exit(main())
:info:destroot   File "/opt/local/bin/meson", line 23, in main
:info:destroot     return mesonmain.run(sys.argv[1:], launcher)
:info:destroot   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 308, in run
:info:destroot     sys.exit(run_script_command(args[1:]))
:info:destroot   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 257, in run_script_command
:info:destroot     return cmdfunc(cmdargs)
:info:destroot   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mesonbuild/scripts/meson_install.py", line 390, in run
:info:destroot     do_install(datafilename)
:info:destroot   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mesonbuild/scripts/meson_install.py", line 216, in do_install
:info:destroot     install_targets(d)
:info:destroot   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mesonbuild/scripts/meson_install.py", line 371, in install_targets
:info:destroot     depfixer.fix_rpath(outname, install_rpath, False)
:info:destroot   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mesonbuild/scripts/depfixer.py", line 391, in fix_rpath
:info:destroot     fix_darwin(fname, new_rpath)
:info:destroot   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mesonbuild/scripts/depfixer.py", line 376, in fix_darwin
:info:destroot     subprocess.check_call(['install_name_tool', '-add_rpath', new_rpath, fname])
:info:destroot   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 286, in check_call
:info:destroot     retcode = call(*popenargs, **kwargs)
:info:destroot   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 267, in call
:info:destroot     with Popen(*popenargs, **kwargs) as p:
:info:destroot   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
:info:destroot     restore_signals, start_new_session)
:info:destroot   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1275, in _execute_child
:info:destroot     restore_signals, start_new_session, preexec_fn)
:info:destroot TypeError: expected str, bytes or os.PathLike object, not NoneType
:info:destroot FAILED: meson-install 
:info:destroot /opt/local/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 /opt/local/bin/meson --internal install /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_irc_hexchat/hexchat/work/build/meson-private/install.dat
:info:destroot ninja: build stopped: subcommand failed.
:info:destroot Command failed:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_irc_hexchat/hexchat/work/build" && /opt/local/bin/ninja install 
:info:destroot Exit code: 1
:error:destroot Failed to destroot hexchat: command execution failed
:debug:destroot Error code: CHILDSTATUS 95166 1
:debug:destroot Backtrace: command execution failed
:debug:destroot     while executing
:debug:destroot "system {*}$notty {*}$nice $fullcmdstring"
:debug:destroot     invoked from within
:debug:destroot "command_exec destroot"
:debug:destroot     (procedure "portdestroot::destroot_main" line 2)
:debug:destroot     invoked from within
:debug:destroot "$procedure $targetname"
:error:destroot See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_irc_hexchat/hexchat/main.log for details.
```

I could manually install the `hexchat` binary, and related files, into `/usr/local/`, but I'm suspicious this may simply be a meson bug that may resolve itself.  

p.s.  There are good reasons both MacPorts and Fink abandoned the "tight integration" path taken by Homebrew.  There are minor hiccups in keeping MacPorts set `+quartz`, rather than taking the easy `+x11` route, but mostly things work, and even nasties like GIMP and Inkscape work.

**Comment by philicious** [comment]
@caronni /cc @TingPing 
I finally got around playing with this and I got a working app bundle now. steps so far involve
```
# setup build env 
brew install git python3 meson ninja gtk pkg-config libproxy libcanberra dbus-glib libnotify luajit gettext
export PATH="/usr/local/opt/gettext/bin:$PATH"
export PKG_CONFIG_PATH=/usr/local/Cellar/openssl/1.0.2o_1/lib/pkgconfig/
export CPPFLAGS=-I/usr/local/opt/openssl/include 
export LDFLAGS=-L/usr/local/opt/openssl/lib
# add to meson.build
if host_machine.system() == 'darwin'
  install_data('osx/hexchat.icns',
  install_dir : 'Contents/Resources')

  install_data('osx/Info.plist.in',
  rename: 'Info.plist',
  install_dir : 'Contents')
endif

# configure build
meson build --prefix=/tmp/hexchat.app --buildtype=release --bindir=Contents/MacOS -libdir=Contents/Resources/lib
# fix wrongly generated buildfile, removing "-pagezero_size 10000 -image_base 100000000"
sed -i'' -e s/-pagezero.*-llua/-llua/g build/build.ninja
# build 
ninja -C build install
# ignore the errors at the end, caused by meson_post_install.py. this file needs a simple fix for not running the desktop and mime cache updaters on OSX where they are obsolete.
```
now you will have a working hexchat.app bundle in /tmp/ , however it is not fully self-contained yet and will only run on machines having gtk etc stuff installed via homebrew.
Need to enhance the meson.build with a `add_install_script(..)`. that script will take care of copying all required dependencies into the bundle and modifying the main executables library search path. this is not to complicated but will take a little time to get all deps and deps of deps covered.

I'm not an expert with meson build system, so @TingPing do you know by chance if meson can handle installing of deps ? 

earlier this was achieved by running `gtk-mac-bundler osx/hexchat.bundle`. however this only works with jhbuild build env, now its meson.

when I'm done, I'll wrap the steps up in a `osx/build_osx.sh` and PR with the few required patches to files.

**Comment by TingPing** [comment]
> I'm not an expert with meson build system, so @TingPing do you know by chance if meson can handle installing of deps ?

Well the method you say of just running a script is probably the best you can do in that case. `gtk-mac-bundler` still should work though.

>   install_data('osx/Info.plist.in',
  rename: 'Info.plist',
  install_dir : 'Contents')

This should be `configure_file()` as it sets `VERSION`

**Comment by philicious** [comment]
@TingPing ah ye `configure_file()` sounds great with auto-replacing the version placeholders in Info.plist 👍 

I'll give gtk-mac-bundler a try

**Comment by Snuupy** [comment]
@philicious do you have any updated build instructions?

I'm trying to follow https://github.com/hexchat/hexchat/issues/1931#issuecomment-390948491 but I get the following error:

```
(py2) SnuBook-Pro:hexchat brianlee$ meson build
The Meson build system
Version: 0.49.2
Source dir: /Users/brianlee/Downloads/Hexchat/hexchat
Build dir: /Users/brianlee/Downloads/Hexchat/hexchat/build
Build type: native build
Project name: hexchat
Project version: 2.14.2
Appending LDFLAGS from environment: '-L/usr/local/opt/openssl/lib'
Appending CPPFLAGS from environment: '-I/usr/local/opt/openssl/include'
Native C compiler: cc (clang 10.0.0 "Apple LLVM version 10.0.0 (clang-1000.10.44.4)")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/local/bin/pkg-config (0.29.2)
Dependency gio-2.0 found: YES 2.58.3
Dependency gmodule-2.0 found: YES 2.58.3
Dependency openssl found: YES 1.0.2q
Checking for function "memrchr" : NO
Has header "strings.h" : YES
Checking for function "X509_get_signature_nid" with dependency openssl: YES
Checking for function "SSL_CTX_get_ssl_method" with dependency openssl: YES
Checking for function "DH_set0_pqg" with dependency openssl: NO
Checking for function "DH_get0_key" with dependency openssl: NO
Checking for function "DH_set0_key" with dependency openssl: NO
^[Checking for function "ERR_remove_thread_state" with dependency openssl: YES
Checking for function "ASN1_STRING_get0_data" with dependency openssl: NO
Configuring config.h using configuration
Compiler for C supports arguments -pipe: YES
Compiler for C supports arguments -fPIE: YES
Compiler for C supports arguments -funsigned-char: YES
^[Compiler for C supports arguments -Wno-conversion: YES
Compiler for C supports arguments -Wno-pointer-sign: YES
Compiler for C supports arguments -Wno-padded: YES
Compiler for C supports arguments -Wno-unused-parameter: YES
Compiler for C supports arguments -Wno-missing-prototypes: YES
Compiler for C supports arguments -Winline: YES
Compiler for C supports arguments -Wstrict-prototypes: YES
Compiler for C supports arguments -Werror=implicit-function-declaration: YES
Compiler for C supports arguments -Werror=pointer-arith: YES
Compiler for C supports arguments -Werror=init-self: YES
Compiler for C supports arguments -Werror=format-security -Werror=format=1: NO
Compiler for C supports arguments -Werror=missing-include-dirs: YES
Compiler for C supports arguments -Werror=date-time: YES
Compiler for C supports arguments -fstack-protector-strong: YES
WARNING: Project targetting '>= 0.40.0' but tried to use feature introduced in '0.46.0': compiler.has_link_argument
WARNING: Project targetting '>= 0.40.0' but tried to use feature introduced in '0.46.0': compiler.has_multi_link_argument
Compiler for C supports link arguments -Wl,-z,relro: NO
Compiler for C supports link arguments -Wl,-z,now: NO
Compiler for C supports link arguments -Wl,--dynamicbase: NO
Compiler for C supports link arguments -Wl,--nxcompat: NO
Program make-te.py found: YES (/Users/brianlee/Downloads/Hexchat/hexchat/src/common/make-te.py)
Dependency libproxy-1.0 found: YES 0.4.15
Dependency libcanberra found: YES 0.30
Dependency dbus-glib-1 found: YES 0.110
Configuring org.hexchat.service.service using configuration
Program dbus-binding-tool found: YES (/usr/local/bin/dbus-binding-tool)
Dependency gtk+-2.0 found: YES 2.24.32
Dependency libnotify found: YES 0.7.7
Found CMake: NO
Dependency iso-codes found: NO (tried pkgconfig, cmake and framework)
WARNING: Use the 'pie' kwarg instead of passing '-fpie' manually to 'hexchat'
Dependency luajit found: YES 2.0.5
Program generate_header.py found: YES (/Users/brianlee/Downloads/Hexchat/hexchat/plugins/perl/generate_header.py)
Program perl found: YES (/usr/local/bin/perl)

plugins/perl/meson.build:76:2: ERROR:  Problem encountered: found perl not suitable for plugin
```

I have perl 5.28.1 installed through homebrew.

**Comment by SamuelMarks** [comment]
Nice work @Snuupy! - Can you upload it somewhere, e.g.: fork this repo, then upload it to the /releases?

**Comment by Snuupy** [comment]
> Nice work @Snuupy! - Can you upload it somewhere, e.g.: fork this repo, then upload it to the /releases?

Unfortunately no, I removed all the work as it was not worth using because of the DPI issues. Everything was basically blurry because of it.

**Comment by SamuelMarks** [comment]
Darn, will stick to this old XChat-Azure build then. Might move to irssi, Riot, or similar soon. 

Found this yesterday also: https://volt-app.com

**Comment by zeamp** [comment]
I am also using XChat-Azure after failing to properly build HexChat from source on macOS Ventura.

**Comment by zeamp** [comment]
After installing the latest HexChat 2.16.1 (Windows 10 x64) under WINE/CrossOver, HexChat crashes under load.

I assume the DPI/blurry text issue persists in HexChat macOS builds in 2023-2024?
