### ISSUE TITLE
Shift-up/down doesn't move network entries

### ISSUE THREAD

**Issue by nattofriends** [hexchat/hexchat#1938]
On Windows and Hexchat 2.12.4, Shift-up/down no longer moves networks up or down,

**Comment by tomek** [comment]
I just checked - on win10x64 + HexChat x64 - Network List: ```shift+arrow up/down``` works fine, in Network/Channel Tree ```ctrl+shitf+page up/down``` also works as intended

**Comment by nattofriends** [comment]
In-tree stuff seems to work, but network list doesn't.

**Comment by TingPing** [comment]
Do you have `Show favorites only` ticked?

**Comment by nattofriends** [comment]
Yes, I have it checked.

**Comment by TingPing** [comment]
Well there you go, uncheck it.

**Comment by nattofriends** [comment]
I would have thought that it would work when the show favorites only checkbox is checked as well.
