### ISSUE TITLE
Hexchat do not format meta-formatted text: bold, italic, underline

### ISSUE THREAD

**Issue by slacknk** [hexchat/hexchat#1945]
Hexchat do not format meta-formatted text: 

- \*bold\*
- \_underline\_
- \/italic\/

**Comment by TingPing** [comment]
HexChat uses [mirc codes](http://www.mirc.com/colors.html) for formatting. For convience it provides keybindings such as <kbd>Ctrl+k</kbd>, <kbd>Ctrl+i</kbd>, <kbd>Ctrl+u</kbd>, etc.

**Comment by slacknk** [comment]
**TingPing** , but one moment,
incoming messages, not freaking outgoing

**Comment by TingPing** [comment]
Ok, well other users will have to use mirc codes which is the most ubiquitous standard for IRC formatting.

Somebody could write a script that converts those into mirc codes similar to this: https://github.com/MicroDroid/hexchat-plugins/blob/master/plugins/markdown.py
