### ISSUE TITLE
Reduce file size of hexchat snap

### ISSUE THREAD

**Issue by extraymond** [hexchat/hexchat#1946]
By using ubuntu-app-platform snap as dependency, it may be able to shrink the size of hexchat snap to a relative small size.

**Comment by TingPing** [comment]
Please submit a PR to https://github.com/TingPing/hexchat-snap

**Comment by TingPing** [comment]
At a glance based upon this post: https://insights.ubuntu.com/2016/12/08/using-the-ubuntu-app-platform-content-interface-in-app-snaps/

It is only useful for Qt/QML applications.
