### ISSUE TITLE
Color symbols in user list

### ISSUE THREAD

**Issue by melt7777** [hexchat/hexchat#1947]
This is a feature request for improvement:

Existing behaviour: The userlist shows color-coded circles to the left of each users name depending on their  mode (op, voice, etc.)

Desired behaviour: The userlist shows color-coded symbols to the left of each users name depending on their mode (@ for op, + for voice. etc)

Example: The userlist in MIRC client shows the symbols in the userlist.

Best choice: Toggle this new behavior as another Appearance preference.  Would settle for direct replacement.

Thank you and have a great day!

**Comment by TingPing** [comment]
*Preferences > Userlist > Show icons*

**Comment by melt7777** [comment]
Thank you for the immediate response. This is good, and will meet our needs. Feature request would be then: Can we have the symbols color coded like the circle icons were?

**Comment by melt7777** [comment]
Closed, no longer require this feature
