### ISSUE TITLE
Sometimes the scrollbar does not stay at the bottom when returning to a tab

### ISSUE THREAD

**Issue by rodri** [hexchat/hexchat#1948]
This patch, applicable to git master, solves an annoying bug that causes that, when a tab (channel or private) is left with the scrollbar at the bottom, and some new text arrives, and then we select again that tab, sometimes the scrollbar is not completely down and there is hidden text and we have to scroll manually to the bottom.

```diff -Naur hexchat-2.12.4/src/fe-gtk/xtext.c hexchat-2.12.4-fix/src/fe-gtk/xtext.c
--- hexchat-2.12.4/src/fe-gtk/xtext.c	2016-07-05 21:46:48.000000000 +0200
+++ hexchat-2.12.4-fix/src/fe-gtk/xtext.c	2017-02-11 12:35:37.011291906 +0100
@@ -4962,6 +4962,14 @@
 	dontscroll (buf);	/* force scrolling off */
 	xtext->adj->value = buf->old_value;
 	xtext->adj->upper = buf->num_lines;
+
+	/* if the scrollbar was down, keep it down */
+	if (xtext->buffer->scrollbar_down && xtext->adj->value <
+		xtext->adj->upper - xtext->adj->page_size)
+	{
+		xtext->adj->value = xtext->adj->upper - xtext->adj->page_size;
+	}
+


 	if (xtext->adj->upper == 0)
 		xtext->adj->upper = 1;
 	/* sanity check */
```
[scrollbar_down.patch.txt](https://github.com/hexchat/hexchat/files/768484/scrollbar_down.patch.txt)

**Comment by TingPing** [comment]
Ideally submit a PR: https://help.github.com/articles/creating-a-pull-request/

At the very least post a `git` formatted patch with authorship and commit info.

**Comment by rodri** [comment]
Ok. Pull Request created:
https://github.com/hexchat/hexchat/pull/1949
