### ISSUE TITLE
theme manager will not run on windows

### ISSUE THREAD

**Issue by rjshaver** [hexchat/hexchat#1951]
I did a fresh install on windows.  I did a complete install doing all possible options.  It went through the install with Perl and Python.  I tried to run the theme manager from the start menu.  I immediately get the error:  HexChat Installation not found!  Check your %APPDATA%\HexChat folder.  I do not have an environment variable by that name.  I also looked in my installation folder  c:\Program Files\HexChat\ and the thememan.exe file is there.  I will want to change the theme if I am to use hexchat.  Can you find the error or a workaround?  Thanks.

FYI, in case it affects how theme manager runs.
With python, I did not add to my the python directory to my path.  I have py installed and it is set up as default to run python3.6.

**Comment by Arnavion** [comment]
Probably need to run HC once first so that it creates the appdata directory.

**Comment by rjshaver** [comment]
OK.  Thanks.  I thought I was supposed to run theme-manager when hexchat was not running so I exited the program.  It run while hexchat is running.

**Comment by rjshaver** [comment]
I get the manager running while hexchat is running and can load themes, but cannot apply them.  I shut down HC, but it will not apply.  It keeps saying that HC must be closed; Do you wish to continue?  I keep trying.

**Comment by rjshaver** [comment]
Sorry, I figured it out.  It may have been changing it but I could not see anything where it worked or not.  I have it working now.  Thanks so much for your assistance.
