### ISSUE TITLE
Use cmake instead of make

### ISSUE THREAD

**Issue by rogersachan** [hexchat/hexchat#1954]
cmake is cross-platform, so it would benefit all.

**Comment by TingPing** [comment]
If I switch to any build system it will be [Meson](http://mesonbuild.com). Not sure how much I feel like doing so though.

**Comment by rogersachan** [comment]
But now IDEs are adding built in support for it, like VS2017 now with the introduction of the cmake server.






On Tue, Feb 21, 2017 at 8:53 PM -0500, "TingPing" <notifications@github.com> wrote:












If I switch to any build system it will be Meson. Not sure how much I feel like doing so though.

**Comment by rogersachan** [comment]
Does meson have an exposable server?






On Wed, Feb 22, 2017 at 12:12 PM -0500, "Roger" <notifications@github.com> wrote:










But now IDEs are adding built in support for it, like VS2017 now with the introduction of the cmake server.













On Tue, Feb 21, 2017 at 8:53 PM -0500, "TingPing" <notifications@github.com> wrote:

























If I switch to any build system it will be Meson. Not sure how much I feel like doing so though.

**Comment by TingPing** [comment]
It doesn't have a server but it can be just as easily integrated. Gnome-Builder is the only IDE with integration atm I believe.

**Comment by Arnavion** [comment]
IDE integration is not a driving feature anyway. Having fewer build files trumps it.

**Comment by TingPing** [comment]
@Arnavion One reason I never bothered with moving forward with Meson is I imagined you wouldn't be interested in replacing the VS files with it. It also means adding it to gtk-win32 ofc.

**Comment by Arnavion** [comment]
You imagined incorrectly. I have no reason to want to preserve VS project files either. What I care about is minimizing effort. If there's a single set of build files for all OSes, then that reduces effort.

Same goes for gtk-win32.

**Comment by TingPing** [comment]
Well anyway I'll close this but for anybody interested here is a basic meson build (no plugins yet): https://github.com/hexchat/hexchat/compare/wip/meson

I'll work on testing on Windows at some point.
