### ISSUE TITLE
Shift+Ins does not paste primary selection

### ISSUE THREAD

**Issue by Massimo-B** [hexchat/hexchat#1962]
This is Linux, Xfce window manager.
CTRL+v and Shift+Ins both paste the same secondary clipboard ignoring the primary.
This should be hexchat related, as many other Gtk applications are using Shift+Ins as primary paste. Then the Window Manager and X can't fix that if an application overwrites that behaviour.

**Comment by Massimo-B** [comment]
After discussion on #hexchat I have to admit that different applications are doing it differently:

Terminator, Palemoon are using Shift+Ins as primary.

Firefox, Libreoffice, hexchat are using both for secondary.  I'm not insisting on that Shift+Ins. But there is no convention or guideline and not even a single shortcut doing the primary paste. Things must work without a pointer device that I like to avoid as much as possible.
X and the Window Manager have no chance to change that behaviour if applications can overwrite it.

You could but I have never seen it, make that an option.
You could act differently when using CTRL+v for secondary and Shift+Ins for primary because:
* People that don't know about the difference usually use CTRL+v.
* People that are using clipboard managers still can enable the "sync clipboards" feature for not using separate clipboards.
* People that are not using clipboard managers but are using the primary usually use middle click and still can use that.
* There is no reason to have 2 shortcuts for the secondary clipboard but no shortcut for the primary.

**Comment by TingPing** [comment]
HexChat uses a standard Gtk entry, so what keybindings it has for pasting it up to them.

**Comment by TingPing** [comment]
Also shift+ins works here anyway...
