### ISSUE TITLE
Show special icon for inactive chanops

### ISSUE THREAD

**Issue by KeyboardPerson** [hexchat/hexchat#1963]
"Inactive ops" means ops who currently have not activated their op powers. This would sit alongside the normal op icon which is displayed for currently active ops.

This can be toggle-able for those who may wish to disable it.

An additional idea, a toggle to optionally display those op icons directly in the chat log would also be nice to have.

Thanks!

**Comment by TingPing** [comment]
The concept of "inactive ops" is not really a standard part of IRC. Some networks let you request the list of ops, usually that can be disabled on a per channel basis, and even then it can't cover every situation. I don't really think this makes sense to be a core hexchat feature.

**Comment by KeyboardPerson** [comment]
It could be a toggle-able feature, like I said, for those people who don't wish to use it or if the network they're on doesn't support it.

However, if this may not be added as a core feature, is there a way to script this somehow?

**Comment by TingPing** [comment]
Scripts can't easy fiddle with icons, but they could print whatever in chat.

**Comment by KeyboardPerson** [comment]
:( Wish there was icon support. Maybe later on there might be.
