### ISSUE TITLE
Auto-reconnect name collision/race

### ISSUE THREAD

**Issue by OrangeDog** [hexchat/hexchat#1967]
Whenever hexchat reconnects it always switches to my secondary username, because the first is in use (presumably by me).
Having to `/nick` back to my preferred name every time is annoying.
```
[10:18:26] <name1> blah blah blah
[13:50:44] * Disconnected (No such device or address)
[13:51:23] * name1 is already in use. Retrying with name2...
/nick name1
[14:20:38] * You are now known as name1
```

**Comment by TingPing** [comment]
The nick being in use is out of HexChats control of course. You can use a script such as this one to automatically ghost and change back to a preferred nick after connection though: https://github.com/Poorchop/hexchat-scripts/blob/master/Arnavion-scripts/autoidentify.py

**Comment by OrangeDog** [comment]
Thanks, I'll see if that script solves the problem.
I thought there might be a possibility that a rearrangement of the reconnect process would ensure the server releases the nick before hexchat tries to take it again.

**Comment by TingPing** [comment]
The only action hexchat could take is just waiting an arbitrary amount of time, we have no knowledge of what the servers policies might be.

**Comment by OrangeDog** [comment]
Workaround is now here
https://github.com/Poorchop/Arnavion-scripts/blob/master/autoidentify.py
