### ISSUE TITLE
Changing GTK appearance Question/Issue

### ISSUE THREAD

**Issue by JordanGS** [hexchat/hexchat#1972]
First i installed Hexchat with the theme manager, then i uninstalled it and installed it without the theme manager, in both cases it doesn't work.

I followed the instructions outlined [here](https://hexchat.readthedocs.io/en/latest/appearance.html#theming)

```
    Create the directory <installdir>\share\themes\vertex\gtk-2.0
    Extract contents of vertex-gtk\gtk-2.0-dark\ into this directory.
    Create an empty file at <installdir>\etc\gtk-2.0\gtkrc (with no file extension!)
    Edit it and add gtk-theme-name = "vertex"
```

As you can see from the screenshot below, i believe i followed the instructions properly.

![desktop](https://cloud.githubusercontent.com/assets/17622264/23883901/218c6c28-0840-11e7-85d5-2e0ec4a5bb53.png)

However, the theme is not applied. In fact it looks like Windows 98 theme since it doesn't even use the W10 theme anymore. Any advice would be appreciated.

I used the latest version of HexChat 64-bit and the latest vertex release.

**Comment by TingPing** [comment]
You place the files in a hexchat installation, your screenshots are of the source directory.

**Comment by JordanGS** [comment]
@TingPing My installation directory is `C:\Development\HexChat`, my screenshots are of the installation directory as well and the guide says to place them into the installation directory. The two paths in the screenshots are

C:\Development\HexChat\share\themes\vertex\gtk-2.0

and

C:\Development\HexChat\etc\gtk-2.0

is that wrong?

**Comment by mB-PiBox** [comment]
Because your directory structure is incorrect.
and I see no "gtkrc" file.

The files from common/gtk-2.0 should be in the themes\vertex\gtk-2.0 folder

You just extracted the whole github zip into the folder. It doesn't work like that.

**Comment by TingPing** [comment]
Ah, I was confusing the development files for hexchats, but those are certainly some projects development files and as mentioned not a gtkrc file.

**Comment by TingPing** [comment]
The real theme is in the common/gtk-2.0 directory.

**Comment by JordanGS** [comment]
@mB-PiBox Yes i did, my bad. Thanks! :)

**Comment by TingPing** [comment]
I'll update the docs as the directory layout seems to have changed.
