### ISSUE TITLE
FiSHLiM Key Exchange not working with other clients

### ISSUE THREAD

**Issue by eimmot** [hexchat/hexchat#1974]
Works fine for hexchat <-> hexchat,
hexchat <-> irssi  key exchange fails, console displays error:

**SSL_read: error:05066064:Diffie-Hellman routines:compute_key:no private value**

The keys seem to go through, but they get corrupted or something. Haven't tested against other clients only irssi

**Comment by TingPing** [comment]
For reference: https://github.com/falsovsky/FiSH-irssi/blob/master/src/DH1080.c

Just a guess would be a base64 issue, as otherwise the files are nearly identical.
