### ISSUE TITLE
Autojoin Delay not working as expected

### ISSUE THREAD

**Issue by eimmot** [hexchat/hexchat#1976]
Currently, if no connect command is set on the server, autojoin delay is ignored. Setting a connect command will make it work as expected, it should work without one set.

https://github.com/hexchat/hexchat/blob/241dd69b081779a77718763561a779cdffcaf11f/src/common/inbound.c#L1590

**Comment by TingPing** [comment]
If nothing has to be done why wait?

**Comment by eimmot** [comment]
Lol I agree, somebody else complained about it not working, they might have a background script? Who knows

**Comment by TingPing** [comment]
The best workaround for scripts is probably just to put the scripts command in connect commands. Bit ugly but I think it is better than in the common case just sitting there for no reason.
