### ISSUE TITLE
SASL authentication fails on Windows every time (but works on Linux)

### ISSUE THREAD

**Issue by beatrix-bodo** [hexchat/hexchat#1988]
Hi,
I have a registered nickname and my server settings are configured properly (I sincerely hope so), but SASL authentication fails on Windows so I have to identify myself to NickServ every single time.
However it works fine on Linux.

**Comment by learn-more** [comment]
Set authentication mode to NickServ, if you have to identify to NickServ?

**Comment by mB-PiBox** [comment]
Works fine one the 2 Windows installs I have... one on desktop other on surface pro 4

**Comment by mB-PiBox** [comment]
Make sure certs are correctly named and generated

**Comment by beatrix-bodo** [comment]
Well that fixed it @learn-more, I feel kinda stupid now :D I just thought it worked the opposite way (it asks for the kind of auth that I set) and also didn't understand why it works on Ubuntu and why it doesn't on Windows with the same settings.
But it's fine now so thanks!

**Comment by TingPing** [comment]
SASL is the type of auth you want on freenode. If it fails your username is probably wrong.

**Comment by beatrix-bodo** [comment]
@TingPing My username and password should be fine, I've been using the same ones for about a year and there are no typos either. Besides I have the same config (same username and password with SASL auth) on Linux and it works so my login info seems correct.

**Comment by TingPing** [comment]
Just to clarify, username is a different setting than nickname, seriously just triple check those values and you will surely find the mistake. Anyway obviously nothing about auth is platform specific and it has continually worked for everybody for half a decade.

**Comment by beatrix-bodo** [comment]
Yeah I'm sure I goofed, sorry for opening an issue for this and thanks for the help!
