### ISSUE TITLE
Scrollback Goutputstream reported repeatedly as ScrInject.B Trojan by Nod32

### ISSUE THREAD

**Issue by ZexaronS** [hexchat/hexchat#1992]
Before I reported this I checked and it only happens on freenode.

Path is scrollback\freenode\.goutputstream-XXXXXX
everytime there's a random ID on those chars, happens every 5-15 seconds and temporairly freezes the program. 

I'm talking with freenode staff as we speak to determine on which end is this coming from, or some false positive.

**Comment by TingPing** [comment]
Just whitelist the scrollback/log directories. People posting malicious javascript doesn't apply to hexchat.

**Comment by ZexaronS** [comment]
oh
