### ISSUE TITLE
Freenode + Tor + SASL = working or not?

### ISSUE THREAD

**Issue by GGGunrunner** [hexchat/hexchat#1996]
Hello everyone!

I tried my best to follow the instructions on how to use SASL with Freenode hidden service.
Not quite sure if SASL is loaded at all on Hexchat startup.

Created a cert - YES
Selected SASL EXTERNAL (cert) - YES
Put Freenode.pem in ~/.config/hexchat/ and ~/.config/hexchat/certs (just in case) - YES
Added the hash to NickServ - YES

Now the output:

```
* *** Couldn't look up your hostname
* Capabilities supported: account-notify extended-join identify-msg multi-prefix sasl
* Capabilities requested: account-notify extended-join identify-msg multi-prefix 
* Capabilities acknowledged: account-notify extended-join identify-msg multi-prefix 
* *** Notice -- You need to identify via SASL to use this server
* Closing Link: gateway/tor-sasl/account (SASL access only)
* Disconnected (Remote host closed socket)
```

Does SASL need to be manually enabled somewhere, or what could be the problem?

**Comment by TingPing** [comment]
>  Put Freenode.pem in ~/.config/hexchat/ and ~/.config/hexchat/certs (just in case) - YES

The name of the file is probably wrong, it must match exactly the network list name including case.

**Comment by GGGunrunner** [comment]
Fixed.

Hexchat was running under another user creds. Totally my bad.

Although, if Hexchat is unable to find .pem file - "File not found" message would be nice :-)

**Comment by TingPing** [comment]
hexchat always tries to open `$network.pem` so always erroring would be a bit annoying.
