### ISSUE TITLE
HexChat won't start, no error message.

### ISSUE THREAD

**Issue by deadalnix** [hexchat/hexchat#1999]
HexChat won't start on my win10 machine. I get no error message or anything, nothing happens. Trying to launch HexChat via command line do not prompt anything on the standard output.

I tried to uninstall and reinstall HexChat, and to remove the %APPDATA%\HexChat folder, but nothing seems to work.

I'm not sure what is going on, or even how to get any information about what is going on.

**Comment by TingPing** [comment]
Does the "Safe mode" hexchat launcher work?

**Comment by deadalnix** [comment]
Hi @TingPing .

The same thing happen when launching the safe mode. And by the same thing, i mean literally nothing, the program quit immediately, no error message, no window opened, nothing.

**Comment by deadalnix** [comment]
Ok I have a crash dump file. Who should I send that to ?

**Comment by learn-more** [comment]
Are you able to attach it here?

**Comment by deadalnix** [comment]
I have no idea how to attach files to github issues. Is that a thing ?

**Comment by TingPing** [comment]
> Attach files by dragging & dropping, , or pasting from the clipboard.

**Comment by deadalnix** [comment]
[hexchat.crashdump.zip](https://github.com/hexchat/hexchat/files/988017/hexchat.crashdump.zip)

**Comment by learn-more** [comment]
It's an assert in cairo.dll,
@TingPing : are there symbol files for releases somewhere?

**Comment by TingPing** [comment]
> @TingPing : are there symbol files for releases somewhere?

@tomek: are there symbol files for releases somewhere?

**Comment by tomek** [comment]
https://dl.hexchat.net/hexchat/pdbs/

**Comment by deadalnix** [comment]
Hi everybody.

After a round of windows update, HexChat is back to work. It looks like the problem was on windows's side and not on yours.

**Comment by learn-more** [comment]
It was this assertion:
https://bugs.launchpad.net/ubuntu/+source/cairo/+bug/1476736

**Comment by ProjectRevoTPP** [comment]
Having this issue after the Windows Creators Update. Safe mode doesn't work, tried a reinstall of hex chat, same thing.

**Comment by chibill** [comment]
I am having the same problem after a windows update... Reinstalling does not seem to fix the problem.

**Comment by parkrrr** [comment]
I have the same behavior on Windows 10, but mine chokes on python:
```ntdll!NtTerminateProcess+0x14
ntdll!RtlExitUserProcess+0xbf
KERNEL32!ExitProcess+0xa
MSVCR90!get_pgmptr+0x257
python27!PyErr_Print+0x3d
python27!Py_InitializeEx+0x362
hcpython2!hexchat_plugin_init+0xbf
hexchat!plugin_add+0x298 [f:\git\hexchat\src\common\plugin.c @ 294]
hexchat!plugin_load+0xa7 [f:\git\hexchat\src\common\plugin.c @ 411]
hexchat!plugin_auto_load_cb+0x1f [f:\git\hexchat\src\common\plugin.c @ 421]
hexchat!for_files+0x22f [f:\git\hexchat\src\common\util.c @ 654]
hexchat!plugin_auto_load+0xe7 [f:\git\hexchat\src\common\plugin.c @ 461]
hexchat!irc_init+0x77 [f:\git\hexchat\src\common\hexchat.c @ 453]
hexchat!new_ircwindow+0x8e [f:\git\hexchat\src\common\hexchat.c @ 548]
hexchat!servlist_auto_connect+0x5f [f:\git\hexchat\src\common\servlist.c @ 531]
hexchat!xchat_auto_connect+0x9 [f:\git\hexchat\src\common\hexchat.c @ 806]
glib_2_0!g_main_dispatch+0x147 [c:\gtk-build\build\x64\glib\glib\gmain.c @ 3156]
glib_2_0!g_main_context_iterate+0x1fa [c:\gtk-build\build\x64\glib\glib\gmain.c @ 3842]
glib_2_0!g_main_loop_run+0x160 [c:\gtk-build\build\x64\glib\glib\gmain.c @ 4036]
gtk_win32_2_0!gtk_main+0xaf [c:\gtk-build\build\x64\gtk\gtk\gtkmain.c @ 1269]
```

**Comment by learn-more** [comment]
@parkrrr : Does this build help? https://github.com/hexchat/hexchat/pull/1987

**Comment by parkrrr** [comment]
@learn-more Unfortunately, no.

**Comment by learn-more** [comment]
as a workaround, you can remove python2 plugin.

**Comment by chibill** [comment]
Any fix for us who are not using the python plugin and have this problem still?

**Comment by chibill** [comment]
how do I get a crash dump?

**Comment by learn-more** [comment]
See https://github.com/hexchat/hexchat/issues/1734#issuecomment-290981232

**Comment by chibill** [comment]
That fails to do anything.
`C:\Program Files\HexChat>run_procdump.bat

C:\Program Files\HexChat>procdump.exe -accepteula -e 1 -x C:\Program Files\HexChat\ hexchat.exe

ProcDump v8.2 - Sysinternals process dump utility
Copyright (C) 2009-2016 Mark Russinovich and Andrew Richards
Sysinternals - www.sysinternals.com


The directory does not exist: C:\Program


C:\Program Files\HexChat>`

**Comment by chibill** [comment]
Crash dump from my install.

**Comment by chibill** [comment]
Crash dump is at https://minecraft16.ml/hexchat.exe_170523_142159.zip (github would not upload it...)

**Comment by learn-more** [comment]
Thanks!

@TingPing 
It breaks on `buf[len-1] = 0;	/* remove the trailing \n */`
inside servlist_load, with an out of range exception.
possibly len is 0?

**Comment by learn-more** [comment]
@chibill you can try the build from https://ci.appveyor.com/project/TingPing/hexchat/build/1.0.62 when it is done building.

**Comment by chibill** [comment]
That fixed it but it cleared all my networks.... (Does not even have the default ones...)

**Comment by learn-more** [comment]
`%appdata%\hexchat\servlist.conf`

Please be carefull when uploading, (if it is not empty), there are passwords in there!
(Please redact those)

**Comment by chibill** [comment]
Yeah... Installing the new version cleared out my old servlist.conf......

So it only has the one entry I just added to get back onto my ZNC Server.
