### ISSUE TITLE
Are you sure you want to quit?

### ISSUE THREAD

**Issue by Szprot** [hexchat/hexchat#2000]
![68747470733a2f2f692e696d6775722e636f6d2f737949447734582e706e67](https://cloud.githubusercontent.com/assets/23389103/25787545/3cca6f78-339a-11e7-97b4-656c1e9832b7.png)

I accidentally selected "Don't ask next time."

How do I get the prompt back

**Comment by TingPing** [comment]
`/set gui_quit_dialog on`
