### ISSUE TITLE
How to use hexchat on mac osx

### ISSUE THREAD

**Issue by congzhangzh** [hexchat/hexchat#2003]
Hi,

I want to use hexchat on mac osx,
but the mac osx port is no longer maintained.
Can you bring it back or how can I give a hand:)

Tks,
Cong

**Comment by TingPing** [comment]
It just isn't worth the maintenance, use a native client like Textual is my advice.

**Comment by congzhangzh** [comment]
tks, I just want give gtk on mac os a try:)
