### ISSUE TITLE
Hex chat freezes and reconnects to servers and rooms

### ISSUE THREAD

**Issue by Chen-pan** [hexchat/hexchat#2008]
Hexchat freezes when closing either the window or tab, after the /list command. I am running Windows.

Details:
HexChat 2.12.4
Portable Mode:No
Build Type: x64
OS:Microsoft Windows 10 Pro (x64)

**Comment by learn-more** [comment]
@Chenthu can you please follow the steps outlined here? https://github.com/hexchat/hexchat/issues/1734#issuecomment-290981232

**Comment by Chen-pan** [comment]
@learn-more sorry, i was busy. I couldn't respond in time. Could you close this?
