### ISSUE TITLE
HexChat crashes when calling emit_print("Channel Message")

### ISSUE THREAD

**Issue by Fulgen301** [hexchat/hexchat#2014]
[Python] If I call `hexchat.emit_print` with only one argument, e.g. `hexchat.emit_print("Channel Message")`, HexChat crashes.

**Comment by TingPing** [comment]
Works fine here, what HexChat version, what Python version, what platform, etc?

**Comment by Fulgen301** [comment]
Version: 2.12.4 (development snapshot from the 11th of June), Python 3.6.0:41df79263a11, Windows 10 Home x64

**Comment by TingPing** [comment]
Is `/py exec hexchat.emit_print("Generic Message")` enough to cause the issue for you, or is a script causing it? If so post the script.

**Comment by Fulgen301** [comment]
With Generic Message, it does not crash, however, if executing `/py exec hexchat.emit_print("Channel Message")`, it crashes.

**Comment by TingPing** [comment]
What scripts do you have loaded?

**Comment by Fulgen301** [comment]
None, while testing.

**Comment by Fulgen301** [comment]
@maxmitti found out that it only crashes if "Colored nick names" are activated.
Stack trace:
`Stack trace of thread 1174:
#0  0x0000561ba2d689d0 text_color_of (hexchat)`
