### ISSUE TITLE
Hexchat doesnt work with certain url (unicode charactors)

### ISSUE THREAD

**Issue by rredford** [hexchat/hexchat#2016]
It ignores certain like dotted U in this url (only known example to me, guy who shared link is from germany)

http://www.bünting.com/html/drehzahltabelle.htm

It ignores everything before ü so clicking it gets me nting.com/html/drehzahltabelle.htm

**Comment by TingPing** [comment]
Works fine here, are you on a really old version?

**Comment by rredford** [comment]
Not sure. mine is HexChat 2.9.6

**Comment by TingPing** [comment]
Yes that is very old, upgrade to 2.10.4 and it will work fine. Some packages are mentioned on the website: (https://hexchat.github.io)

**Comment by rredford** [comment]
Thanks. I thought I added repo for hexchat but guess not.
