### ISSUE TITLE
Click on URL opens blank browser window

### ISSUE THREAD

**Issue by regebro** [hexchat/hexchat#2019]
I have the issue that "Open URL in Browser" just opens a new blank window. With a URL handler it works.
I use v2.10.2 on Ubunty 16.04, with Chrome. Somebody had the same problem in issue #660, and it magically went away, so it's probably config. Any hint where to look would be appreciated.

**Comment by TingPing** [comment]
Your browsers desktop file is invalid, exactly as the linked issue discusses. So find the desktop file for your browser, look at its *Exec* line and fix it.

**Comment by regebro** [comment]
The linked issue does not discuss anything like that. I can't see anything wrong with my desktop file.

**Comment by TingPing** [comment]
What is the contents of your desktop file?

**Comment by regebro** [comment]
[google-chrome.txt](https://github.com/hexchat/hexchat/files/1109922/google-chrome.txt)

**Comment by regebro** [comment]
Penny dropped! There is another config in ~/.local/share/applications, and that one is wrong.

Thanks for the help!
