### ISSUE TITLE
Crash when loosing connection

### ISSUE THREAD

**Issue by funkydude** [hexchat/hexchat#2020]
Windows 10 64bit, 2.12.4 64bit

When loosing internet, HexChat prints the "Disconnected (No such device or address)" followed by crashing.

`Unhandled exception at 0x00007FFABC7D2208 (ucrtbase.dll) in hexchat.exe: An invalid parameter was passed to a function that considers invalid parameters fatal.`

**Comment by TingPing** [comment]
Duplicate of #600
