### ISSUE TITLE
URL Handlers doesnt accept valid input

### ISSUE THREAD

**Issue by bozonius** [hexchat/hexchat#2032]
I tried to use the GUI to add a URL handler for my environment.  I have multiple firefox sessions running and I only want to open a tab in one of them.  I enter the string as per the documentation page, with the leading "!", the whole path to my script (which works in Thunderbird btw for opening ff links), followed by "%s" -- I thought I had done this correctly, and saved it.

When I would return to the same dialog, my entry was gone, replaced by "(null)".  I tried this several times, even copy-pasting the path from the command shell after checking that that string does in fact give the correct path.

I eventually went out to the command shell, found the "urlhandlers.conf" file under .config, and entered the exact same information as I did in the dialog before.  Voila!  It works now.  I can select my firefox option from right-click on any link, and it properly opens the link in my desired ff session, in a new tab.

I am on Devuan 1.0, running under VirtualBox 5.1.26, with latest updates, using XFCE.  

Some diagnostic messages would be helpful, but probably fixing this would be more effective.  Please let me know if you need more info.

**Comment by bozonius** [comment]
I would also like to add that I found adding URL handlers at the command prompt to be rather exasperating.   And maybe the goal is to get all of this fixed so a user need not go through this.   However, this might be good info anyway, so here it is.

When I first fire up hexchat, I notice that the URL handler file is not automatically created (maybe it is the VERY first time it is run, but I had already run the program many times before).   Now what I needed to do was get a "snapshot" of the urlhandler.conf file because I wasn't sure what it was supposed to look like.  So I renamed it and let hexchat re-create it.  But the only way to nudge hexchat to do this was to go into the url handler dialog and hit save, which creates the example link.  Then I had a template to work from.

I guess if all other things worked to spec, this message might be rather moot.  But perhaps it might be useful, idk, in finding a fix for the initial issue, that the GUI dialog box does not accept my input, even though it is identical to what I enter manually as a work-around.

**Comment by TingPing** [comment]
Hit enter after editing a field for it to apply.

**Comment by bozonius** [comment]
TingPing: The problem is that if I leave the dialog and come back to it, my changes are gone.

**Comment by TingPing** [comment]
Yes you must always hit enter to apply edits.

**Comment by bozonius** [comment]
TingPing:  That isn't the problem.  I've tried this many times; it just doesn't work.  And that's no matter how hard I hit the enter key.

**Comment by TingPing** [comment]
To be clear:

- Open Dialog
- Click into a cell to edit it and insert text
- Hit enter for that cell to apply
- Press the save button on the dialog

Are you saying after that it is still unsaved?

**Comment by bozonius** [comment]
That was precisely what I was saying, yes.  I know it sounds incredibly unbelievable, but there appears to be a bug.  And the bug is NOT in my keyboard I assure you.

My guess is that it may have something to do with the particular environment I am running the program in.  It is XFCE on Devuan 1.0 (Debian Jessie without systemd) in a Virtualbox VM.   Perhaps you are unable to reproduce this exact scenario, which may be why you find this report so improbable.

**Comment by bozonius** [comment]
Since first reporting this, I rebooted the VM and I see that the interface is now working.  I had noticed that a firefox session did not fully load (before the reboot), so this may be related to an X11 problem or a communications issue in the VM guest, but idk.

If I can reproduce this again, I will re-open this bug.
