### ISSUE TITLE
Add natively support for the SASL ECDSA-NIST256P-CHALLENGE mechanism

### ISSUE THREAD

**Issue by chinkung** [hexchat/hexchat#2037]
Please add support for the SASL ECDSA-NIST256P-CHALLENGE mechanism.

Documentation: 
https://www.alphachat.net/sasl.xhtml
https://wdtz.org/freenode-sasl-upgrade-irssi-howto.html
https://github.com/atheme/ecdsatool

**Comment by TingPing** [comment]
As far as I know the the ircv3 group no longer recommends usage of `ECDSA-NIST256P-CHALLENGE` (I can get back to you on the details).  On top of that is it non-trivial to implement and not very valuable as you should always be using TLS anyway.  So HexChat will not be supporting it.

If you still want to use it here is a simple script that uses `ecdsatool`: https://github.com/TingPing/plugins/blob/master/HexChat/ecdsa.py
