### ISSUE TITLE
Offers non-functioning minimize to tray option when the app window is closed

### ISSUE THREAD

**Issue by allanday** [hexchat/hexchat#2045]
The following dialog is always shown when the Hexchat window is closed:

![screenshot from 2017-08-30 10-56-50](https://user-images.githubusercontent.com/213068/29866970-041c4020-8d72-11e7-9d07-02dec4b24c1d.png)

In a lot of cases, the system tray will not be enabled, so there's nothing to minimize to. This will also be an issue with GNOME from version 3.26, which won't display status icons by default.

One solution might be to only show the "minimize to tray" button when the status icon is enabled and visible.

**Comment by TingPing** [comment]
@allanday Well aware of the problem, one issue though is GNOME-Shell exposes no reasonable way to query the version number so we can react accordingly, we already hard-code other DEs like Unity/Elementary.

**Comment by csoriano1618** [comment]
Hey, just an idea, is it not "gnome-shell --version" good enough? How do you expect to query the version? with a DBUS call or so?

**Comment by TingPing** [comment]
> Just an idea, is it not "gnome-shell --version" good enough? 

That might be sufficient but I would prefer just reading an env var with that information.

> with a DBUS call or so?

A DBus interface does exist but I don't want to use that because its far more complex to implement and it pokes another large hole in Flatpak sandboxes.

**Comment by TingPing** [comment]
EDIT: Oh and duh `gnome-shell --version` doesn't work in Flatpak at all ofc.

**Comment by allanday** [comment]
I'm not sure whether they're interesting, but I thought of a couple of other ways to resolve this issue:

 1. Remove the minimize to tray button from the close dialog and make left-clicking on the status icon minimize/restore to the tray. This is the same behaviour as Slack and Rocket.Chat and seems quite neat.
 2. Only show the minimize to tray button if the system tray is enabled, and disable it by default. This is less ideal, since it would mean that the system tray option would be available in situations where it isn't useful. At the same time, in most cases someone will only enable the system tray icon if the tray is available.

**Comment by TingPing** [comment]
@allanday I believe we worked out a solution and the option should no longer be shown or used on GNOME 3.26.
