### ISSUE TITLE
"Looking up" but never connecting

### ISSUE THREAD

**Issue by hThoreau** [hexchat/hexchat#2048]
Hi.

I'm trying to use Hexchat to connect to OFTC. Sadly, it is failing to do so and not providing me with much information on why that is the case. For example, this is the `server.log`:
```
**** BEGIN LOGGING AT Mon Sep  4 21:08:27 2017

Sep 04 21:08:27 *	Looking up irc.oftc.net
Sep 04 21:37:56 *	Stopped previous connection attempt (76)
Sep 04 21:38:01 *	Looking up irc.oftc.net
**** BEGIN LOGGING AT Mon Sep  4 21:45:03 2017

Sep 04 21:45:03 *	Looking up irc.oftc.net
**** ENDING LOGGING AT Mon Sep  4 22:14:56 2017
```

How should I proceed on troubleshooting this issue?

**Comment by ivan** [comment]
Maybe `dig -t A irc.oftc.net`, and if it hangs, figure out why you're not getting a response; perhaps bad nameservers in `/etc/resolv.conf`. (`dig -t A irc.oftc.net @NAMESERVER_IP` to query a specific nameserver.)

**Comment by hThoreau** [comment]
Hi, it was a problem related to my Subgraph OS "metaproxy". That has been fixed. Sorry for almost forgetting I've opened this issue.
