### ISSUE TITLE
No sound on Ubuntu Zesty

### ISSUE THREAD

**Issue by MatejKovacic** [hexchat/hexchat#2051]
I am using Hexchat 2.12.4 on Ubuntu 17.04 and there are no sound notifications when I receive a private message.

I have checked Settings - Preferences - Sounds and for "Private Message" and "Private Message to Dialog" a sound "receive.wav" is set. This file points to "/home/matej/.config/hexchat/sounds" directory and there is a file in it. And I can plan it.

I went to System settings - Sound, and when I select Applications tab, and receive a message, I can see Hexchat appears double times (while sound plays), but sound power is set to zero. Unfortunately this receive sound is played quite quickly, but I tried to move a sound power slider to right... It moves, but the next time it is set to zero again and there is no sound.

**Comment by TingPing** [comment]
Not sure how it looks in Unity but there should be an option for "Sound Effect" volume or such in the control center.

**Comment by MatejKovacic** [comment]
Well... yes. I feel ashamed. :-)

And a little bit angry, because Ubuntu is constantly making some stupid changes...
