### ISSUE TITLE
Translation error on it_po

### ISSUE THREAD

**Issue by microcluster** [hexchat/hexchat#2053]
Hi, i'm new on GitHub.
I have noticed a translation error on a Hexchat window command. You can find it at the link below
https://github.com/hexchat/hexchat/blob/d99cd18fb9e97c4ec264ad7a72bf7e2ba9a6dfa2/po/it.po#L4293
here the code
```
#: ../src/fe-gtk/menu.c:1794
msgid "_Join a Channel..."
msgstr "E_tra in un canale..."
```
you should correct "E_tra" with "Entra" 

Thanks
Best regards

**Comment by TingPing** [comment]
Translations are all handled here: https://www.transifex.com/hexchat/hexchat/
