### ISSUE TITLE
Configuration of CTRL+W shortcut

### ISSUE THREAD

**Issue by Massimo-B** [hexchat/hexchat#2057]
Hi, please make the CTRL+W shortcut a configuration item.
By default in hexchat that does close a tab. However on many other editors, shells and environments I use that to delete a word and often close my tab by mistake.

Suggestion: Make the current default an option in the shortcut editor, showing the default CTRL+W to action "Close Window". I one deletes that it falls back to the editor, readline or linedit default to close the last word.

Hexchat for me is more like a shell or editor, typing an awful lot of text, than some other browser similars using the "Close window" default.

**Comment by Massimo-B** [comment]
Ok, as discussed in #hexchat this seems to be already done: https://github.com/hexchat/hexchat/commit/30a223a6cb8ee36139eeee75026fa72212b6f806

**Comment by Znuff** [comment]
Well, ok, thanks a lot.

How the hell do I put this back on?

**Comment by TingPing** [comment]
@Znuff *Run command* > `/close`

**Comment by kopax** [comment]
Hi, I also look for a faster way to close discussion and channel, I was used to <kbd>CTRL</kbd>+<kbd>CLICK</kbd> and all the option I have are way slower, using <kbd>CTRL</kbd>+<kbd>W</kbd> would be a satisfying solution for me, is there a way to get a faster shortcut ?
