### ISSUE TITLE
URLs copied from browser with special chars are broken

### ISSUE THREAD

**Issue by NoXPhasma** [hexchat/hexchat#2061]
When I post any URLs copied from the Browser with special chars, which get converted by the Browser are converted to color code and break the URL.

Here's an example, actual URL:
```https://de.wikipedia.org/wiki/María```
From the Browser converted URL:
```https://de.wikipedia.org/wiki/Mar%C3%ADa```

When I paste the actual URL everything works fine, but the Browser does only gives me the converted one and this is what Hexchat makes out of it:
```https://de.wikipedia.org/wiki/Mar%ADa```
![unbenannt](https://user-images.githubusercontent.com/7719590/30694055-a39390ce-9ed2-11e7-9128-98571b4f013e.png)

As you can see, the URL is wrong now and obviously leads to a 404 page. This is not limited to `í` but to any special char like `êâöäüÄÖÜ` and so on.

I'm using HexChat 0.12.4 on Linux Mint 18.2.

**Comment by TingPing** [comment]
`/set input_perc_color off`. You enabled that for some reason, its a bad idea.

**Comment by NoXPhasma** [comment]
I can't remember having set that option, but setting it to off works, thank you!
