### ISSUE TITLE
Add some shortcuts for channel switching

### ISSUE THREAD

**Issue by Massimo-B** [hexchat/hexchat#2063]
Hi, please add some shortcuts for faster channel switching like this:

CTRL+Tab: Switch to previously selected channel
??: Switch to channel with latest new message
??: Switch to channel with oldest new message
??: Switch to channel with latest highlighted message
??: Switch to channel with oldest highlighted message

**Comment by TingPing** [comment]
> ??: Switch to channel with latest new message

<kbd>Alt</kbd><kbd>`</kbd> does this. The rest would require more involved changes.

**Comment by Massimo-B** [comment]
I don't see this shortcut in the shortcut configurator, and it does not work. Do I need to configure that?
You really mean the backtick ` and not the single quote? My keyboard here has the "German (dead grave acute)" option here and only prints ` after space. Could that be a reason?

**Comment by TingPing** [comment]
You can rebind it to something better in *Settings > Keyboard Shortcuts*. The Action is *Change Page* with Data1 being *auto*.

**Comment by Massimo-B** [comment]
Thank you very much. That "Change Page auto" does the job.
I thought about a reasonable shortcut and decided to use C-^ like
http://5digits.org/help/pentadactyl/tabs.xhtml#%3CC-^%3E

**Comment by Massimo-B** [comment]
However it would be nice to have a Change Page with Data1 "highlight" to switch to the last highlighted tab -> #2075
