### ISSUE TITLE
Randomly getting "No ping reply for 62 seconds, disconnecting."

### ISSUE THREAD

**Issue by wgaylord** [hexchat/hexchat#2066]
When joining my ZNC server recently I began getting

> No ping reply for 62 seconds, disconnecting.

Is there any way to turn up this limit?

**Comment by dahainsworth** [comment]
this might be a dupe to https://github.com/hexchat/hexchat/issues/1956 .  try just disabling it with 
/set net_ping_timeout 0

**Comment by chibill** [comment]
Possible. I search for the key terms and only found a year old ticket that
the solution does not fix. I will try this.

**Comment by chibill** [comment]
Problem is it times out before I can enter that.

**Comment by wgaylord** [comment]
Because of this issue I gave up on hexchat. Because the solution no longer worked to solve the problem.
