### ISSUE TITLE
Windows: Transparency problem - would like to disable alpha blending (WS_EX_LAYERED)

### ISSUE THREAD

**Issue by cwallbaum** [hexchat/hexchat#2077]
Hi,

my problem: Because of the activated alpha blending, HexChat is entirely invisible in my VNC session.

The long story: I often use VNC with a "Screen Blanking" feature which uses alpha blending to work. It would be very nice to have an option to disable transparency completely. This means that the application does not set WS_EX_LAYERED. Currently we can set the "Window Opacity" in the "Preferences" dialog, but increasing this value to 255 doesn't mean that alpha blending is not used/deactivated. I would be happy if there is a checkbox which controls this behaviour (switching it on or off) or that alpha blending will be disabled when the opacity value is set to 255.

Thanks for reading this and best wishes,

Christian

**Comment by TingPing** [comment]
The behavior of the opacity feature is entirely up to Gtk and we have no control over it.

**Comment by learn-more** [comment]
@cwallbaum Could you please try the builds from the referenced PR to see if they resolve the issue?
Please note, after changing the opacity you will need to restart hexchat to notice it.

**Comment by cwallbaum** [comment]
Hi learn-more,

I could only find a build for Windows, but that was sufficient for me.

The patch works here on Win 7 Pro: I can set a value < 255 and transparency is set immediately, I only have to restart HexChat once I want to disable transparency by setting the value to 255.

I don't know if there is a function in GTK to unset transparency, but maybe you can use some Windows API code?

I wrote myself a little tool to remove WS_EX_LAYERED. It's in Pascal notation and I need the application handle:

procedure TForm1.Button1Click(Sender: TObject);
var
  Style: DWord;
begin
  // Take application handle from Edit control (HEX):
  WindowHandle := StrToQWord('$' + Edit1.Text);
  // Get window style
  Style := GetWindowLong(WindowHandle, GWL_EXSTYLE);
  // Remove WS_EX_LAYERED
  SetWindowLong(WindowHandle, GWL_EXSTYLE, Style and not WS_EX_LAYERED);
  // Repaint window(s)
  RedrawWindow(WindowHandle, nil, 0, RDW_ERASE or RDW_INVALIDATE or RDW_FRAME or RDW_ALLCHILDREN);
end;

Perhaps this is useful somehow?

Btw.: I'm not sure if 255 is set as default after a fresh installation of HexChat...? Did not test this.

Nevertheless thanks for patching.

Christian

**Comment by TingPing** [comment]
This could probably be changed upstream so when the value is 255 it properly disables it.

**Comment by learn-more** [comment]
@cwallbaum Sure I could use winapi to change the style, but I'd rather not call winapi in a cross platform application :)
@TingPing ideally yes, but I didnt feel like making a gtk build and all that, and I'm not clear on the process of getting code upstream.

**Comment by TingPing** [comment]
> @TingPing ideally yes, but I didnt feel like making a gtk build and all that, and I'm not clear on the process of getting code upstream.

https://bugzilla.gnome.org - I can poke people to move it along if needed and we can ship local patches until it is upstreamed.

**Comment by learn-more** [comment]
Here is a gtk patch:
[gtk-ws_ex_layered.zip](https://github.com/hexchat/hexchat/files/1412259/gtk-ws_ex_layered.zip)

**Comment by TingPing** [comment]
@tomek Can you make a Gtk build using that patch ^

**Comment by tomek** [comment]
I uploaded patched gtk & hexchat test builds here: https://dl.hexchat.net/hexchat/testing/

**Comment by learn-more** [comment]
There's a bug in the patch,
here is a fixed one:
[gtk-ws_ex_layered.zip](https://github.com/hexchat/hexchat/files/1419796/gtk-ws_ex_layered.zip)

**Comment by tomek** [comment]
I updated gtk stack & test builds - link is in my last comment

**Comment by learn-more** [comment]
Checking with WindowInspector I see the `WS_EX_LAYERED` correctly being dropped in this latest build.

**Comment by learn-more** [comment]
@cwallbaum Does this latest build solve your problem?

**Comment by cwallbaum** [comment]
Hi,

yes, the latest build solves the issue. WS_EX_LAYERED is correctly set/unset on the fly now, no restart necessary anymore :). Thanks for all your support and effort,

Christian

**Comment by learn-more** [comment]
[0001-GDK-W32-Remove-WS_EX_LAYERED-from-an-opaque-window.zip](https://github.com/hexchat/hexchat/files/1480014/0001-GDK-W32-Remove-WS_EX_LAYERED-from-an-opaque-window.zip)
A patch with author info.

**Comment by TingPing** [comment]
This patch has been added to our gtk build and will be fixed in the next release.
