### ISSUE TITLE
Crashes on connect if `/server ...` is in "connect commands"

### ISSUE THREAD

**Issue by lily-mayfield** [hexchat/hexchat#2084]
If I put `/server znc.y2k.cafe 7666 silvia:mypass` in my "connect commands" Hexchat crashes when connecting to that network. Bellow is the output:

```
$ hexchat
/usr/share/themes/Ambiance/gtk-2.0/apps/mate-panel.rc:30: error: invalid string constant "murrine-scrollbar", expected valid string constant
[1]    29098 segmentation fault (core dumped)  hexchat
```

Also here's the crash report I got: https://imgur.com/a/0Sxwy

**Comment by TingPing** [comment]
I fixed your crash, but don't do whatever you were trying to do. Create a network list entry for that server.
