### ISSUE TITLE
Windows installer does not check privileges

### ISSUE THREAD

**Issue by mvhconsult** [hexchat/hexchat#2089]
As said, the installer does not check or advertise that it needs rights to write to /program files. This causes an install failure when not enough privileges are available.

**Comment by learn-more** [comment]
I'm not sure what you are doing, but the setup elevates correctly here.

**Comment by TingPing** [comment]
Duplicate of #1735 ?

**Comment by mvhconsult** [comment]
Seems like dupe of #1735 
I am running under limited user abilities. Running installer without explicit 'run as administrator' does not generate the request for admin access. 
Win10, 64, 1709
