### ISSUE TITLE
ucrtbase.dll crashes hexchat (2.12.4 Win10 x64)

### ISSUE THREAD

**Issue by corefff** [hexchat/hexchat#2093]
Laptop went into sleep mode (net disconnected), after sending /quit while reconnect attempt in progress, client crashed.

(2f88.1bb8): Security check failure or stack buffer overrun - code c0000409 (!!! second chance !!!)
ucrtbase!invoke_watson+0x18:
00007ffc`752d2258 cd29            int     29h

**Comment by TingPing** [comment]
Duplicate of #600
