### ISSUE TITLE
Appstream IDs differ between appdata.xml file and Flatpak metadata

### ISSUE THREAD

**Issue by Pointedstick** [hexchat/hexchat#2103]
HexChat's Appstream ID on Flathub is `io.github.Hexchat` (https://github.com/flathub/io.github.Hexchat/blob/master/io.github.Hexchat.json#L2)

But HexChat's Appstream file uses a different Appstream ID: `hexchat.desktop` (https://github.com/hexchat/hexchat/blob/master/data/misc/hexchat.appdata.xml.in#L3)

This causes problems. The point of Appstream IDs is for each app has a unique one, but for it to be the same for that app across all distribution channels. If the same app has different Appstream IDs in different distribution channels, then it'll show up as different apps in clients that can display content from multiple sources, such as GNOME Software Center and KDE Discover. Here's what it looks like in KDE discover:

![two hexchats](https://user-images.githubusercontent.com/1097249/34287625-a48be790-e6a5-11e7-86fe-5e99ebd9331c.png)

The top one is the Flathub version, the bottom one is provided by my distro's packages.

If you unify the AppStream IDs (ideally standardizing on a reverse-DNS style such as `io.github.Hexchat`), then Discover and GNOME Software (and similar apps) can perform de-duplication correctly, marking both as the same app and offering the user the choice of which version they want to install.

Note: once you change the AppStream ID, you will need to do one of the following to retain the connection between the AppStream data and the desktop file:
- Rename the desktop file to match the AppStream ID (i.e."io.github.Hexchat.desktop")
- Add the following line to hexchat.appdata.xml.in: `<launchable type="desktop-id">hexchat.desktop</launchable>`

Relevant section of the AppStream spec: https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Application.html

[note: not an AppStream expert, take this with a grain of salt, etc]

**Comment by TingPing** [comment]
I believe the Flatpak can also include:
```xml
<provides>
  <id>hexchat</id>
</provides>
```

The only problem about this renaming is that it would break the dbus bus name but we can just not do that part here for now I suppose.

**Comment by TingPing** [comment]
So I tried to fix this on the other end: https://github.com/flathub/io.github.Hexchat/commit/f114c5a4d0e25e1a8a606c1dc27ac7d59f7f6053

Does Discover properly combine the two now?

**Comment by Pointedstick** [comment]
I'm afraid not. Are your changes supposed to be instantly available, or does anything need to be regenerated/updated on the Flathub or client side?

I'll be happy to help debug this, of course.

**Comment by TingPing** [comment]
They should already be there, just `flatpak update --appstream` (`--user` if needed ofc)

**Comment by Pointedstick** [comment]
Thanks. They're still listed separately, though. :slightly_frowning_face:

**Comment by TingPing** [comment]
Hmm, after the holiday I'll ask the appstream dev.
