### ISSUE TITLE
Full screen causes hex chat to allow clicking through to anything behind it

### ISSUE THREAD

**Issue by gufi** [hexchat/hexchat#2118]
while using any application that requires full screen when switching back i am able to click through hex chat, I can only recover by closing and relaunching or  minimizing to tray and the open it back up v 2.12.4.

Other notable things, hex chat is on right screen while the full screen app is on left ( main )

**Comment by gufi** [comment]
gonna close this, I am starting to think this has nothign to do with hex chat and every thing to do with nvidia drivers ( other applications are starting to do this now )

**Comment by brlafreniere** [comment]
I'm having an issue like this as well, and it seems to pertain to HexChat.

To recreate the problem, I have HexChat open, some programs like Google Chrome, or Steam.

I open a game such as Path of Exile. Something happens at this point, I don't know what exactly, perhaps when I alt+tab out of the game to HexChat. At this point, whenever I have HexChat open, and then I click on the HexChat window, whatever is immediately behind HexChat in the area that I clicked will be brought to the front.

So if I have Chrome behind HexChat, and then I click somewhere in the HexChat window, Chrome will be brought to the front.

This issue doesn't appear to happen with any other application except HexChat.
