### ISSUE TITLE
Feature Request: custom proxy command

### ISSUE THREAD

**Issue by mk-pmb** [hexchat/hexchat#2123]
Hi!
I'd really like an option to connect to an IRC network via a custom command.
HexChat should run that program and talk to its stdin/stdout (the program will act like an IRC server).
When disconnecting, HexChat shall kill the proxy program.
HexChat shall provide lots of context info via env vars, to help the proxy program decide upfront what to do; at least: network name, preferred nicknames, IRC username. (This is the part that xinetd can't solve.)

**Comment by TingPing** [comment]
This sounds like tons of extra complexity for little value and will never happen.
