### ISSUE TITLE
"OK/Cancel" buttons in Preferences window sometimes not reachable on Budgie desktop

### ISSUE THREAD

**Issue by Staudey** [hexchat/hexchat#2125]
**hexchat version:** 2.12.4
**OS:** Solus 3
**WM:** Budgie 10.4

The "Preferences" window is so big in some cases, that I can't reach the "OK" and "Cancel" buttons on my small laptop display (1366x768). It can't be moved further up than the top of the screen, and even hiding the panel doesn't show the buttons. See screenshot: [https://i.imgur.com/PJZfBd2.png](https://i.imgur.com/PJZfBd2.png)
I first raised this issue on the Budgie issue tracker, but they sent me here with the message "Hexchat needs to reduce the size of their dialog. Raise this on the hexchat issue tracker." (see [https://github.com/budgie-desktop/budgie-desktop/issues/1329](https://github.com/budgie-desktop/budgie-desktop/issues/1329)

**Steps to reproduce**
1. Have Budgie (or possibly Gnome) as WM on a low resolution display, with a widget theme that has big titlebars (like Adapta)
2. Open Hexchat
3. Open Settings->Preferences
4. Observe

**Comment by TingPing** [comment]
This is already fixed next release.
