### ISSUE TITLE
2.14/3.0 release?

### ISSUE THREAD

**Issue by stephenfin** [hexchat/hexchat#2129]
I was hoping to find a release with the fix from #1952 included. However, it appears this is yet available. Is there a timeline on when such a release might be made? :smile:

**Comment by TingPing** [comment]
I am [working on](https://github.com/hexchat/hexchat/commit/4d27a58d48dce3c4fab5d06112abae35403a0558) getting things building on Windows. I'll try to aim for a release within the month.
