### ISSUE TITLE
Feature request: mouse scrollwheel zoom

### ISSUE THREAD

**Issue by milkmiruku** [hexchat/hexchat#2133]
It's always handy, on the web, to be able to show some text to someone else in the room who is sitting a few meters away from the screen by temporarily ramping up the font size by holding down ctrl and using the mousewheel to zoom in. Such a feature for HexChat would be great for such situations, more easily making the experience a more locally communal one.

**Comment by TingPing** [comment]
Adding a keybinding for this would be great but scrolling seems like a bad idea.

**Comment by micgro42** [comment]
duplicate of #1855

**Comment by milkmiruku** [comment]
@micgro42 true, thanks
