### ISSUE TITLE
HexChat 2.14.0 on Windows fails doing emojis.

### ISSUE THREAD

**Issue by AlfredDaw** [hexchat/hexchat#2138]
I had emojis working back in 2.12.4, but since updating, they have stopped working, becoming the "Lego brick" type stand in character glyph.

`[14:43:26] text_font_alternative........: Arial Unicode MS,Lucida Sans Unicode,Unifont,Code2000,Code2001,Code2002,Segoe UI Emoji`
All of these fonts are installed, but such emoji as 😍😘😂😆😄😏 show up as the "Lego bricks."

**Comment by hypebro** [comment]
Also noticed this, spent a little while trying to figure out why emoji was broken on my new win10 install lol. As soon as i found this issue i rolled back to 2.12.4, emojis working perfectly again 😉

**Comment by p858snake** [comment]
I'm also experiencing this, which used to work previous to the current version:

Version: 2.14.1 x64
Primary font: Consolas 10
Alternative font list: Arial Unicode MS,Segoe UI Emoji,Lucida Sans Unicode,Meiryo,Symbola,Unifont,Quivira

**Comment by ashelley** [comment]
Just here to confirm this issue 2.14.1 broke using my alternative fonts for Unicode characters not in default font.  

- Win 10 10 x64
- Alternative fonts: Segoe UI Emoji,Arial Unicode MS,Lucida Sans Unicode,Meiryo,Symbola,Unifont

**Comment by Atario** [comment]
I'm getting this too, on Win7 x64 with HexChat 2.14.1 x64

**Comment by tobytteh** [comment]
I'm also experiencing this issue on my updated Win10 install.

Version: 2.14.1 x64
Alternative fonts: Segoe UI Emoji,Arial Unicode MS,Lucida Sans Unicode,Meiryo,Symbola,Unifont

**Comment by SonicFreak94** [comment]
Having this issue as well. Huge pain when Discord relays get into the mix.

**Comment by KryptonicDragon** [comment]
I'm also having this issue.

- Windows Home 10 x64 v1803
- HexChat v2.14.1 x64
- Alternative fonts: Segoe UI Emoji,Arial Unicode MS,Lucida Sans Unicode,Meiryo,Symbola,Unifont

**Comment by justarandomgeek** [comment]
Any hope of this getting fixed any time soon?

**Comment by TingPing** [comment]
This is reported to be fixed in 2.14.2.

**Comment by justarandomgeek** [comment]
Check for Updates didn't seem to recognized that 2.14.2 had been released, but I've updated manually and emoji do indeed work as expected now!
