### ISSUE TITLE
HexChat 2.14.1 Crashes upon connection loss

### ISSUE THREAD

**Issue by MrKeiKun** [hexchat/hexchat#2144]
Steps to Reproduce:
1. Connect to a working IRC Server
2. After connected, Press Alt + S + D, to disconnect
3. After disconnect, Press Alt + S + R, to reconnect
4. Doing it like 3x will result to crashing HexChat
5. Close the Not Responding HexChat

Logs:

Not sure how to get logs but willing to provide, because this issue exist ever since I last 2 years ago. And I just reported this right now because I got pissed already.

**Comment by TingPing** [comment]
Duplicate of #600
