### ISSUE TITLE
Shift+Click channel list binding isn't obvious

### ISSUE THREAD

**Issue by PaulW2U** [hexchat/hexchat#2147]
Ubuntu 18.04 (in development)
HexChat 2.14.1

I spent an afternoon evaluating HexChat as I had been made aware that a new release was available.

When I decided that I needed to close HexChat I wanted to see if it was possible to close multiple channels at the same time. I highlighted two channels on the same server but before i could check for any right-click option the second or lower channel in the tree closed.

I tried this on several severs for which several channels were open simultaneously open. The result was always the same - highlighting two channels results in one closing immediately..

**Comment by TingPing** [comment]
You can't select multiple channels, shift+click is just a binding to close a tab.

**Comment by TingPing** [comment]
Duplicate of #918

**Comment by TingPing** [comment]
Binding will be removed in next release.
