### ISSUE TITLE
Migrating to GDBus

### ISSUE THREAD

**Issue by qarkai** [hexchat/hexchat#2156]
According to [freedesktop.org](https://www.freedesktop.org/wiki/Software/DBusBindings) DBus-GLib is obsolete and [new] applications should use [GDBus](https://developer.gnome.org/gio/stable/ch35.html). Consider [migrating](https://developer.gnome.org/gio/stable/ch35.html) to GDBus.

**Comment by TingPing** [comment]
Duplicate of #252
