### ISSUE TITLE
Post checksums on website

### ISSUE THREAD

**Issue by Poorchop** [hexchat/hexchat#2159]
The repo for the site has the issue tracker disabled so I had to post this here.

**Comment by TingPing** [comment]
I think this is better handled by signing: #2134

**Comment by TingPing** [comment]
I totally agree its just that getting a trusted cert takes some doing and probably won't be free.

**Comment by einsteinsfool** [comment]
You don't need any certificate. I wasn't talking about any signing. You just calculate locally SHA512 and SHA256 for all files and post them on the website and in the file server. I don't see any cost (but time).

**Comment by TingPing** [comment]
The cert is more important since Windows itself checks for a valid one at install time. Sure a hash is better than nothing but requires manual user action.

**Comment by einsteinsfool** [comment]
Yeah. I'm going from project to project first asking about checksums and when that is completed I ask about signing files with PGP keys. I think if I asked from the start about PGP some maintainers would consider it too much work and, as you said, checksums are better than nothing.

Thanks for the commit!

I'll google how signing on Windows work. For now I only used PGP signatures.

**Comment by TingPing** [comment]
The source is already GPG signed by me, Windows installer requires something trusted by a CA though.
