### ISSUE TITLE
Getting hexchat to work on Mac OS / High Sierra

### ISSUE THREAD

**Issue by caronni** [hexchat/hexchat#2173]
G'day all,

seems that Homebrew forgot all about hexchat, one has to build it from source. As this was not entirely trivial, here the steps I took. Maybe you can use them to get hexchat back into Homebrew, or maybe somebody out there can use them to build hexchat on their own. Good luck!

If you have brew already installed, make sure Frameworks is there and sane. Upgrade to High Sierra seems to stomp on this. Eg:
```
sudo mkdir /usr/local/Frameworks
sudo chown $USER /usr/local/Frameworks/
xcode-select --install
```
If they are not there, and you create them half-way through, some things will stay misconfigured. Avoid.

So, assume a fresh start:
```
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install git python3 meson ninja gtk pkg-config libproxy libcanberra dbus-glib libnotify luajit gettext
export PATH="/usr/local/opt/gettext/bin:$PATH"
export PKG_CONFIG_PATH=/usr/local/Cellar/openssl/1.0.2o_1/lib/pkgconfig/
export CPPFLAGS=-I/usr/local/opt/openssl/include 
export LDFLAGS=-L/usr/local/opt/openssl/lib
git clone https://github.com/hexchat/hexchat.git && cd hexchat
meson build
```
Now find the pagezero_size statement in the build rule, and just remove it. I'm sure it's actually needed, but simply removing it will get you something built. And at first glance, things do work.
```
grep -r pagezero_size *
vi build/build.ninja 
ninja -C build
```
Enjoy:
`./build/src/fe-gtk/hexchat`

Don't know how to make an .app bundle. Would be nice to have :)

**Comment by TingPing** [comment]
Homebrew removed all graphical applications at some point, maybe they reverted that change I don't know.

Anyway all building on OSX info is sort of being handled here: #1931

**Comment by CyberManifest** [comment]
Is there any way to get Hexchat for macOS High Sierra WITHOUT installing homebrew ? Perhaps Appimage would be good for this ?
