### ISSUE TITLE
Feature request: better handling of long timestamps and username+chat window.

### ISSUE THREAD

**Issue by B3bomber** [hexchat/hexchat#2174]
I am used to using mIRC so the layout where the timestamp is not part of the txt display area and is an entirely separate area is a bit... weird. Also, apparently breaks and requires doing dumb things to fix it. Why not just do it the simple way and remove that left side bar thing entirely and output timestamp, nick, message all in 1 line for the window area? I use a full timestamp that never changes size so that part is never an issue. Reserving nick space is never an issue when that is part of the text display area.

The only semi odd part might be displaying emotive text/actions since hexchat does have a different setup here.

My timestamp format in case anyone wonders: [%A, %B %d, %Y][%I:%M:%S %p]

**Comment by TingPing** [comment]
*Preferences > Appearance > Indent nick names*

**Comment by B3bomber** [comment]
Thank you. I have to ask though, why is that option on by default and why is it so obscurely named?

**Comment by TingPing** [comment]
> why is that option on by default

Plenty of people like it. I disable it personally too.

>  why is it so obscurely named?

Well, that is what it does. Much of the settings could be more clear or perhaps even have a visual preview or something.

> Now with that on, there is a section on the left without a background. As in the client has a box, then an open space anything else behind the program shows through. It is where the initial now talking on channel text is, specifically the timestamp.

Not entirely sure what you are talking about. After changing that option you should restart the client for best results though.

**Comment by B3bomber** [comment]
I did. That glitch went away for now. How/why it happened at all though is something.

I sadly don't have many ideas on how some settings could be named to help out. Some are just plain weird. Thanks for the help though:)
