### ISSUE TITLE
in Windows 10 "Antimalware Service Executable" goes crazy

### ISSUE THREAD

**Issue by Mavrikant** [hexchat/hexchat#2178]
After opening and connecting to my ZNC server Antimalware Service Executable goes crazy and froze HexChat for 5 min.  After 5 min HexChat load all old messages and goes offline. If I wanna connect again it repeats. 

Here screenshot of Task Manager:
![image](https://user-images.githubusercontent.com/7313603/38778265-bd1acb7c-40bf-11e8-9da6-a4d8ef7e9bed.png)

----
HexChat version: 2.12.4
OS Name	: Microsoft Windows 10 Education
Version: 	10.0.16299 Build 16299
System Type:	x64-based PC
Processor:	Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz, 2592 Mhz, 2 Core(s), 4 Logical Processor(s)

**Comment by TingPing** [comment]
Yea nothing HexChat can do about that. Just whitelist hexchat and its directories.

**Comment by Zexaron** [comment]
One more reason to disable all this Win10 bloat, and use an alternative antivirus.
