### ISSUE TITLE
Building hexchat on msys2

### ISSUE THREAD

**Issue by ZachBacon** [hexchat/hexchat#2193]
Seems there's an issue with building hexchat on a msys2 environment, this seems to be the only issue that's causing issue for the moment.

> FAILED: data/misc/io.github.Hexchat.appdata.xml
> "E:/msys64/mingw64/bin/python3.exe" "E:/msys64/mingw64/bin/meson" "--internal" "msgfmthelper" "../data/misc/io.github.Hexchat.appdata.xml.in" "data/misc/io.github.Hexchat.appdata.xml" "xml" "../data/misc/../../po"
> msgfmt: cannot locate ITS rules for ../data/misc/io.github.Hexchat.appdata.xml.in

**Comment by TingPing** [comment]
Just needs a slightly newer gettext, `0.19.6`, I believe.

**Comment by ZachBacon** [comment]
Except I already have a version newer than 0.19.6
mingw64/mingw-w64-x86_64-gettext 0.19.8.1-3 [installed]

**Comment by ZachBacon** [comment]
doubtful, appdata.its seems to exist and sits at /mingw64 (or mingw32 if you want 32bit builds)/share/gettext-0.19.8/its/appdata.its 
it could be that meson isn't finding it properly?

**Comment by TingPing** [comment]
`meson` isn't involved in the process, it just calls the gettext cli tools.

**Comment by ZachBacon** [comment]
I'll ping the msys2 devs on this as well, see what's going on.

**Comment by ZachBacon** [comment]
Closing this as is resolved in recent commit from @TingPing other issues I am experiencing are actual mingw-w64 related.
