### ISSUE TITLE
Replace confusing Windows Store non-free posting with donation link

### ISSUE THREAD

**Issue by mcandre** [hexchat/hexchat#2196]
Hexchat is actually free on the Windows App Store, but is strangely published with non-free and "free trial" options. This is not how these pricing schemes are intended to function. Could Hexchat be published in a single, zero price, form on the Windows App Store, and provide a donation link instead?

**Comment by TingPing** [comment]
I agree its confusing and not at all how Microsoft intended it to be used but making two store entries for the exact same software, one paid and one not, is still confusing and not at all how Microsoft intended it to be used with the added bonus of doubling all the effort of publishing to it, getting reviewed, etc.

**Comment by TingPing** [comment]
Nobody donates to a link. I do wish the store was friendly to donations but it isn't so it will just continue to be a bit confusing.
