### ISSUE TITLE
GPLv2 or GPLv2+?

### ISSUE THREAD

**Issue by SoniEx2** [hexchat/hexchat#2199]
The README and *Help -> About -> License* both say hexchat is *GPLv2*, but every single source file in this repository says it's *GPLv2 __or later__*.

This is an important distinction, as *GPLv2 or later* would allow plugins to link to GPLv3 libraries such as [toxcore](https://github.com/TokTok/c-toxcore), I think.

The archlinux package goes with *GPLv2 or later*.

(IANAL tho)

**Comment by TingPing** [comment]
Most, if not all, of the sources should be *or later*.

**Comment by hppavilion1** [comment]
It appears to be GPLv2 or later, so I think this issue is probably resolved really.
