### ISSUE TITLE
Desktop notifications in Windows 8 for highlighted messages.

### ISSUE THREAD

**Issue by rymate1234** [hexchat/hexchat#220]
I've seen in windows 8 that you can have popup notifications. Are these available for desktop apps? If so, I feel these popup notifications would be a good way to implement desktop notifications on Windows 8, as they are already available in the Linux version of HexChat.

**Comment by Fironet** [comment]
Would love to see native W8 toast notifications :+1:

**Comment by TingPing** [comment]
Implemented in f4f27e438b0791e1c0708c4f031aa80c59d965b1

**Comment by Poorchop** [comment]
Can this be modified to ignore znc playback? If you have a lot of highlights in your playback history, then you get bombarded with toasts when you open HexChat.

**Comment by Arnavion** [comment]
@Poorchop #627
