### ISSUE TITLE
Request for Custom Aliases and Functions

### ISSUE THREAD

**Issue by v00v** [hexchat/hexchat#2200]
Ability to write custom aliases and functions in HexChat similar to KVIRC.

Examples from KVIRC:
Aliases: http://www.kvirc.net/doc/doc_aliases.html
Functions: http://www.kvirc.net/doc/doc_kvs_aliasesandfunctions.html

**Comment by TingPing** [comment]
For basic aliases: https://hexchat.readthedocs.io/en/latest/commands.html#user-commands  
For any more advanced functions: https://hexchat.readthedocs.io/en/latest/developers.html#scripting
