### ISSUE TITLE
Request Website Donors Page

### ISSUE THREAD

**Issue by v00v** [hexchat/hexchat#2201]
It would be nice to have a dedicated page with all the sponsors/donors on HexChat website. This could motivate more users to donate. Example; https://www.archlinux.org/donate/ Maybe even offer a link for those who donate the most.

**Comment by TingPing** [comment]
Most donations these days are through the Microsoft Store which doesn't expose (and shouldn't) personal information. Direct paypal donations are rare and small so not worth the effort.
