### ISSUE TITLE
Remove the fixed nick column

### ISSUE THREAD

**Issue by RoboMWM** [hexchat/hexchat#2207]
I know I'm probably some super tiny majority amongst nearly every hexchat user but of the few things bothering me is the fixed column width for nicknames in chat. In addition with nick coloring, I find this helpful when skimming through a channel to see who said what.

Here's an example of what I mean (from IRC Explorer): ![](https://i.imgur.com/sntB7H6.png)

Would an option be considered to remove this column and just plop in the timestamp and name along with the rest of the message?

**Comment by RoboMWM** [comment]
Oh neat! Not sure how I missed this option.

**Comment by SoniEx2** [comment]
@RoboMWM Try changing Settings -> Text Events -> Channel Message/Channel Msg Hilight

**Comment by RoboMWM** [comment]
Ah, thanks! Now if only the Windows Store version would sync over the settings... unless it does that now.
