### ISSUE TITLE
AppStream manifest generation should be optional

### ISSUE THREAD

**Issue by awilfox** [hexchat/hexchat#2219]
HexChat 2.14.1 fails to build from source on Adélie Linux, a small desktop distribution based on the musl libc, because AppStream manifest generation requires XML and templating support in `msgfmt`, which is [not supported by the implementation of gettext that we use](https://github.com/sabotage-linux/gettext-tiny/issues/36).

While the idea of AppStream seems nice, I personally feel the metadata generation should be optional so that the distros (or BSD, etc) that do not yet use it do not have to have the added step of generating the files when they will never be used.  If this would be okay, I would be willing to write a patch to the build system that would make AppStream generation a default-on option (like Lua).  This way, we (and others) could pass `-Dwith-appstream=false` to disable this.

**Comment by TingPing** [comment]
I'm ok with adding an option.
