### ISSUE TITLE
support for strikethrough

### ISSUE THREAD

**Issue by flameboii** [hexchat/hexchat#2232]
I'd like to see support for strikethrough in text formatting added. As per the definition here https://modern.ircdocs.horse/formatting.html#strikethrough

**Comment by Fr6jDJF** [comment]
Was looking for this option.*(coming from [readthedocs](https://hexchat.readthedocs.io/en/latest/index.html))

**Comment by TingPing** [comment]
This was added in 55e4f1c42e8d1131b01659fad67db5d084780227
