### ISSUE TITLE
 Missing Error Check in function DH_set0_key()

### ISSUE THREAD

**Issue by lc3412** [hexchat/hexchat#2245]
Hi,
Function DH_set0_key() returns 1 on success, 0 on error. However , the return value of function DH_set0_key() in hexchat/plugins/fishlim/dh1080.c is not checked. See the following code:

line : 223
![screenshot from 2018-09-17 14-08-05](https://user-images.githubusercontent.com/19151593/45608067-2049f500-ba83-11e8-8adc-481704d12b89.png)

==========================================================================

We find the return value of this call been checked in openssl project with the version of openssl 1.1.2.
Such as in openssl/crypto/dsa folder

dsa/dsa_lib.c
Ref : https://github.com/openssl/openssl/blob/master/crypto/dsa/dsa_lib.c
line : 223
![screenshot from 2018-09-17 14-11-59](https://user-images.githubusercontent.com/19151593/45608148-b1b96700-ba83-11e8-91a9-3aa8b20fb2e3.png)

Chi Li, Zuxing Gu, Jiecheng Wu

**Comment by BakasuraRCE** [comment]
@TingPing outdated, entire plugin core was replaced, please close this
