### ISSUE TITLE
HEXCHAT_SHOW_HELP for use with | HEXCHAT_EAT_HEXCHAT / | HEXCHAT_EAT_ALL

### ISSUE THREAD

**Issue by SoniEx2** [hexchat/hexchat#2258]
For commands, it would be helpful to be able to:

```rust
self.add_hook(ph.hook_command("foo", 0, |ph, word, word_eol| {
    if word.len() < 3 {
        return hexchat::EAT_ALL | hexchat::SHOW_HELP;
    }
    // etc
    hexchat::EAT_ALL
}, Some("help text")));
```

Such that when doing /foo, it shows the help text, while when doing /foo a b c, it doesn't show the help text.

**Comment by TingPing** [comment]
I don't think saving a single line to print help yourself is worthy of an API addition.

**Comment by SoniEx2** [comment]
My help is a wall of text. I do believe not having to type it twice is a good API addition, as it also reduces the probability of typos.
