### ISSUE TITLE
HTTP error 403 during install

### ISSUE THREAD

**Issue by vlanmx** [hexchat/hexchat#2261]
I am trying to install HexChat 2.14.2 for Windows 7+ 64 and getting the error during 'dotnet4.exe' file download.

The error is 'HTTP error 403' and install won't proceed.

![Screenshot of the HTTP error 1](https://my.mixtape.moe/juetdg.png)
![Screenshot of the HTTP error 2](https://my.mixtape.moe/wvsuth.png)

Clicking 'Retry' doesn't help and I am stuck.

**Comment by TingPing** [comment]
Fixed, sorry about that.
