### ISSUE TITLE
Various command parsers do not handle a colon before the last parameter

### ISSUE THREAD

**Issue by linuxdaemon** [hexchat/hexchat#2271]
This issue was first noticed when testing Hexchat with Inspircd v3, channel topic times keep showing as `0` in unix time. `CHGHOST` also does not seem to remove the colon before the last parameter resulting in a user's host being set to `@:<newhost>`.
Inspircd 3.0 changed its message formats a bit, resulting in a colon being prepended to the last parameter in every message from the server. According to the IRC RFCs, clients should generally just ignore the colon before the last parameter in all cases.
## Versions
HexChat: 2.12.4 and 2.14.1
[InspIRCd](https://github.com/inspircd/inspircd) built from commit https://github.com/inspircd/inspircd/tree/37977710a79472741c043b2dc8c17f520429c9f4

**Comment by TingPing** [comment]
Known issue for a while, it makes a lot of bad assumptions. Personally I think all the current parsing is just bad and touching it would be painful.

I wrote a new one here: https://github.com/TingPing/irc-client/blob/master/lib/irc-message.c

And while it would be an equally painful task to use it I think it would probably have the best results.

**Comment by SaberUK** [comment]
This is caused by incorrect protocol message parsing. According to the notes of section 2.3.1 of RFC 1459 a &lt;trailing&gt; parameter should be treated as equivalent to a &lt;middle&gt; parameter but HexChat does not do this.

You can test this behaviour on testnet.inspircd.org.

**Comment by prawnsalad** [comment]
+1
I'm starting to see more people report this error when connecting to insp3 testnets now it's nearing RC :(

**Comment by TingPing** [comment]
I've been quite busy but if you point out specific commands where you are hitting its going to be quicker to fix those. I know the entire parser is incorrect but that is a bigger change that won't happen in 10 minutes of free time.

You can also submit a PR that would look like: https://github.com/hexchat/hexchat/commit/7d78c6bca0e7f8dc08ed0b0e950ab231d5bf6687#diff-2aada67a1462b086f131ee4034b6ef1d

**Comment by linuxdaemon** [comment]
The specific commands I've observed breaking are:
- `333` (topictime)
- `CHGHOST`
- `MODE` specifically a `:` before a parameter
- `ACCOUNT`
- The ban/exception lists, timestamp is not handled correctly

This is all I could find so far if, #2294 would be the best option but as you said there, it does break API compat

**Comment by linuxdaemon** [comment]
It appears `341` breaks as well `[11:21:17] --- You're inviting ChanServ to :##test (irc.example.com)`

**Comment by TingPing** [comment]
Can you just do one line fixes for those events and open a PR?

**Comment by H7-25** [comment]
When a release including this fix ?
