### ISSUE TITLE
Blurry Fonts on Windows 10

### ISSUE THREAD

**Issue by joeedh** [hexchat/hexchat#2288]
Hi.  I noticed the fonts are pretty blurry (it's rather annoying) on Windows 10.  It's especially annoying when using larger font sizes; i.e. 16.  I imagine either freetype or pango are misconfigured. 

I'm currently going through the build process to see if I can't fix this, if I succeed I'll send a patch.

**Comment by joeedh** [comment]
Okay, I've tracked down the problem to Windows 10's high-DPI auto scaling.  Not sure if that makes this a HexChat bug or a GTK one.

**Comment by joeedh** [comment]
In case this isn't fixed anytime soon I've submitted a documentation pull request for manually disabling high-DPI auto scaling just for HexChat:

https://github.com/hexchat/documentation/pull/43

**Comment by TingPing** [comment]
Duplicate of #828
