### ISSUE TITLE
Change io.github.Hexchat.desktop.in.in to  Hexchat.desktop.in

### ISSUE THREAD

**Issue by scootergrisen** [hexchat/hexchat#2295]
In GhostBSD or FreeBSD i noticed the .desktop file for HexChat 2.14.2 is called:

    io.github.Hexchat.desktop

In https://github.com/hexchat/hexchat/tree/master/data/misc i see this file (note the double ".in"):

    io.github.Hexchat.desktop.in.in

Looking at other software should it not just be like this in the source?:

    Hexchat.desktop.in

And then like this when installed:

    Hexchat.desktop

Maybe change to small H or if want to use big H then perhaps change to big C. Personally i prefer all small so i can write it at the terminal more easy:

    hexchat.desktop
    HexChat.desktop

There are also another .desktop file and other files beginning with "io.github.". Maybe they should be changed to.

    io.github.Hexchat.Plugin.metainfo.xml.in
    io.github.Hexchat.ThemeManager.desktop.in
    io.github.Hexchat.ThemeManager.xml
    io.github.Hexchat.appdata.xml.in
    io.github.Hexchat.desktop.in.in

**Comment by TingPing** [comment]
No, the id is fine and I won't be changing for minor details.
