### ISSUE TITLE
Ubuntu 18.10 theme mismatch, input and title boxes white

### ISSUE THREAD

**Issue by cajuncooks** [hexchat/hexchat#2305]
How it looks in 18.04:
![image](https://user-images.githubusercontent.com/39109383/52909952-a85c4280-324d-11e9-9329-24efc7c140bb.png)

How it looks in 18.10:
![image](https://user-images.githubusercontent.com/39109383/52909942-7ba82b00-324d-11e9-9200-c0e6e35ee33a.png)

Note the title/user bar at the top and the input box at the bottom are both white now.

I recompiled with source just to get to the theme manager, which made no difference. Open to ideas, but GUI work is completely out of my wheelhouse. #1832 offers a temporary solution that makes the input box text legible, but I'm assuming another similar fix needs to be made for the new version of GNOME?

**Comment by TingPing** [comment]
This has nothing to do with HexChat really.

How fonts render is up to `freetype` and `fontconfig` which probably both saw changes between releases.

**Comment by TingPing** [comment]
You may just need to disable input box theming: *Preferences > Input > Use text box fonts and colors*

How that feature works is kinda hacky and always possible to break.

Ubuntu is a popular enough theme that we should probably handle it though.

**Comment by cajuncooks** [comment]
Yes, unchecking that option leaves the boxes white but defaults back to standard black text rather than the themed font/colors. Let me know if there's anything I can do to help solve this, I'm not familiar with GNOME theming but I can of course make sense of the commit that solved #1832... just don't know where to look for the solution.

**Comment by TingPing** [comment]
If you are comfortable with building software:

1. Find the gtk theme name: `gsettings get org.gnome.desktop.interface gtk-theme`
2. Add a check on this line: https://github.com/hexchat/hexchat/blob/57478b65758e6b697b1d82ce21075e74aa475efc/src/fe-gtk/fe-gtk.c#L299

```c
		if (g_str_has_prefix (theme_name, "Adwaita") || g_strcmp0 (theme_name, "UbuntuThemeName") == 0)
```

3. Build and test: https://hexchat.readthedocs.io/en/latest/building.html#unix

**Comment by cajuncooks** [comment]
Works great -- Yaru is the new gtk-theme name.
