### ISSUE TITLE
Why do I have to buy HexChat on Windows 10?

### ISSUE THREAD

**Issue by Edwin-Pratt** [hexchat/hexchat#2312]
So, I have received a little gift from my mother. I had a Dell Inspiron running Linux Mint 19.1.

I installed HexChat for free on Linux, however when trying to install it from Windows Store, I have to pay ZAR 169.

Are there alternative sites to download HexChat?
![HexChat](https://user-images.githubusercontent.com/34472632/54150381-392ed400-4430-11e9-8a9f-35a927c3cd7c.JPG)

**Comment by TingPing** [comment]
You don't, it has a trial option.
