### ISSUE TITLE
revert 30a223a6cb #397 (ctrl-w close channel)

### ISSUE THREAD

**Issue by shawnl** [hexchat/hexchat#2318]
30a223a6cb #397 

It seems like the people asking for the change are dvorak users, and they really should map their ctrl level to QWERTY.

ctrl-w is what browsers use so its nice to have this.

**Comment by TingPing** [comment]
Its almost like you completely ignored that discussion...

> Settings > Keyboard Shortcuts > ctrl+w > run command /close

Add what ever binding you want for what ever command you want.

**Comment by shawnl** [comment]
I did that before filing this bug.
