### ISSUE TITLE
How to prevent CTCP VERSION from sending OS and CPU info?

### ISSUE THREAD

**Issue by waldens** [hexchat/hexchat#2321]
I did modify CTCP VERSION replies in Setting - CTCP replies, but found that this setting seems not a substitute for original reply, but just a supplement. For example, after I set up as the picture below shows, others will receive the following reply. this setting seems only adds a reply, not replace the original reply, which still reveals users' privacy.

How can we prevent CTCP from revealing our privacy? Can users disable CTCP completely? or at least customize its replies (completely replacement)? Thanks.

![image](http://wx1.sinaimg.cn/large/0060lm7Tly1g1sigqyg8ej30cy0800sy.jpg)
![image](http://wx2.sinaimg.cn/large/0060lm7Tly1g1sigqy7ytj30tc019aa2.jpg)

**Comment by TingPing** [comment]
See the note here: https://hexchat.readthedocs.io/en/latest/settings.html#ctcp-replies
