### ISSUE TITLE
Furnet should not be in the default network list

### ISSUE THREAD

**Issue by TURBO64** [hexchat/hexchat#2324]
I don't think it is appropriate for a cartoon bestiality porn community to be advertised in Hexchat. I think I am an open-minded person when it comes to these things and what consenting adults want to do in their private lives is their business, but there's no need for bizarre sexual fetish networks to be included in the network selection dialog.

**Comment by TingPing** [comment]
I don't have too strong of an opinion over it, if somebody opens a PR removing it I'll accept it. (Just remove the 2 lines in `servlist.c`)

**Comment by SoniEx2** [comment]
what's bestiality, in your own words?

**Comment by jwshields** [comment]
I just submitted a PR which removes the referenced lines

**Comment by MoonriseUnicorn** [comment]
I was wondering why Furnet disappeared in the latest update... Of course, if you are gonna let the morality police determine what networks are included in your network selection dialog, there are a lot more you are probably going to have to remove than just Furnet. A quick scan through the list after the latest update reveals, at a minimum four more networks that probably have to be removed from the network selection dialog:

- Anthrochat
- Canternet
- DeltaAnime
- PonyChat

There are probably many more that have to go if you scan through their channel lists. If you are gonna let the morality police dictate what you do and do not include, that is.

**Comment by TingPing** [comment]
So here is the deal. I genuinely don't care what a network is about; However not every network needs to be in the network list as it is purely a convenience feature so my policy has generally been any popular network is fine there. At the same time if people complain about one being there I also don't care to defend every network nor want to appeal to some broad philosophical idea of free speech. It is just a low maintenance list of some networks people use, it is what it is. Yelling about morality police on here is not going to help your case.

**Comment by SoniEx2** [comment]
furnet is more popular than those other networks so we should replace them with furnet. that'll also make the list smaller.

**Comment by MoonriseUnicorn** [comment]
I'm not going to make a huge debate about it either. It's not a big deal for those who want to use Furnet to add the network manually.  However, it sounds to me that the person who originally filed the issue just has an axe to grind with furries in general or Furnet in particular. The OP claims to be open-minded, and then immediately mischaracterizes Furnet by claiming it is something it is not. It seems a little unfair to me to single out Furnet for deletion (given how long it has been in the list and no one complained until now) based on the complaint of one person who grossly mischaracterized what Furnet actually is. That's all.
