### ISSUE TITLE
Hexchat should recongnize mode q and a

### ISSUE THREAD

**Issue by sebastiannielsen** [hexchat/hexchat#2331]
Currently, if you get operator or voice status, it will look like this:
ChanServ gives channel operator status to Sebastian
ChanServ gives voice to Sebastian

but if you get channel owner status (q) or channel admin status (a), it will look like this:
ChanServ sets mode +q on #sebastian Sebastian
ChanServ sets mode +a on #sebastian Sebastian

it should instead say:
ChanServ gives channel owner status to Sebastian
ChanServ gives channel admin status to Sebastian

**Comment by TingPing** [comment]
Op and Voice are standardized, those are not. There could be ways to figure it out but its not worth exposing new events (which are effectively new API) for them IMO.

**Comment by sebastiannielsen** [comment]
What do you mean with standarized? Aren't q and a in fact a de-facto standard because of both Atheme and Anope (2 of the most common service packages) implementing q/a as owner/admin, even if its not a formal standard according to RFC?

**Comment by TingPing** [comment]
> What do you mean with standarized?

Well, for one op is mentioned in the original spec: https://tools.ietf.org/html/rfc1459#section-4.2.3.2 (voice mentioned in others).

But mostly that all real world servers use the same modes.

> Aren't q and a in fact a de-facto standard because of both Atheme and Anope (2 of the most common service packages) implementing q/a as owner/admin, even if its not a formal standard according to RFC?

No. I doubt 1/5th of the servers in HexChats default server list support them.

**Comment by sebastiannielsen** [comment]
@TingPing But if a server don't support it (servers that lack services or use ChanFix), it will not cause any problem right?

I just wonder, why its safe to define icons for ~ and & but not define corresponding labels for them?
Its not a big deal, but I just feel the client should support as much as possible.

**Comment by TingPing** [comment]
Sure it could, since its not specified anywhere a server can user modes q or a for anything.

**Comment by TingPing** [comment]
The icons map to prefixes not modes which is always valid.

**Comment by sebastiannielsen** [comment]
@TingPing yeah, but a simple check could be to check if the modes has arguments which are nicks.
This check could be done for all user status modes including op, voice, halfop etc to just ensure they are right.

**Comment by TingPing** [comment]
A user mode can still mean anything.
