### ISSUE TITLE
improve czech translations

### ISSUE THREAD

**Issue by jirislaby** [hexchat/hexchat#2333]
- There should be no colon:
https://github.com/hexchat/hexchat/blob/ba72cc7b6dad98daddd0bf5b9adc220983760234/po/cs.po#L1663

- This should be `Hledat v:`:
https://github.com/hexchat/hexchat/blob/ba72cc7b6dad98daddd0bf5b9adc220983760234/po/cs.po#L3368

- This should be `_Stáhnout seznam`:
https://github.com/hexchat/hexchat/blob/ba72cc7b6dad98daddd0bf5b9adc220983760234/po/cs.po#L3342

- This should be `kanály s`:
https://github.com/hexchat/hexchat/blob/ba72cc7b6dad98daddd0bf5b9adc220983760234/po/cs.po#L3355

**Comment by TingPing** [comment]
All translations are handled here: https://www.transifex.com/hexchat/hexchat/
