### ISSUE TITLE
Connection failed with ssl

### ISSUE THREAD

**Issue by yutayu** [hexchat/hexchat#2352]
* Looking up irc.goat.chat
* Connecting to irc.goat.chat (130.211.70.169:6697)
* * Subject: /C=BE/O=GlobalSign nv-sa/OU=Root CA/CN=GlobalSign Root CA
* * Issuer: /C=BE/O=GlobalSign nv-sa/OU=Root CA/CN=GlobalSign Root CA
* * Subject: /C=BE/O=GlobalSign nv-sa/CN=AlphaSSL CA - SHA256 - G2
* * Issuer: /C=BE/O=GlobalSign nv-sa/OU=Root CA/CN=GlobalSign Root CA
* * Subject: /OU=Domain Control Validated/CN=*.goat.chat
* * Issuer: /C=BE/O=GlobalSign nv-sa/CN=AlphaSSL CA - SHA256 - G2
* Connection failed ((337260938) error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small)

**Comment by TingPing** [comment]
Works fine here and its purely an SSL issue which would be a problem at a lower layer than hexchat.
