### ISSUE TITLE
How to compile with color emoji's like the flatpak version on ubuntu

### ISSUE THREAD

**Issue by IronWolve** [hexchat/hexchat#2356]
I noticed the flatpak version has color emoji's on linux, but when I compile from source off github, that emoji is black&white.  

Whats the secret configuration to enable this? I dont see it in "meson configure build"

**Comment by TingPing** [comment]
>  I dont see it in "meson configure build"

Because it has nothing to do with HexChat.

At a glance just have an up to date `cairo`, `pango`, `fontconfig`, as well as a font such as `noto-emoji-color`.

See also: https://blogs.gnome.org/mclasen/2017/08/18/post-guadec-distractions/
