### ISSUE TITLE
Ignore should have a text-ignore limit option (preferable using regex)

### ISSUE THREAD

**Issue by sebastiannielsen** [hexchat/hexchat#2358]
I have a suggestion, and that is allowing specific text ignores for certain users.
These specific text ignores, means the ignore will only be valid if the text contains the limiter.

Text ignores could be added by adding a : and then a regex.

Example:
`/ignore *!*@*:/Fuck you/i`

would block all messages that contain "Fuck You" regardless of case (/i option)

```
/ignore someuser
/ignore SomeBot!*@*:/^someuser: /
```

This would ignore someuser, but it would also ignore all messages from "SomeBot" that begins on "someuser:" preventing someuser from misusing bot to bypass ignores - while still allowing all other messages from SomeBot through.

**Comment by TingPing** [comment]
This is easy to script:

```lua
-- Also hook Channel Action and Hilight variants
hexchat.hook_print('Channel Message', function (args)
  if args[2]:find('...') then
    return hexchat.EAT_HEXCHAT
  end
end)
```

So while I won't say this feature will never happen its unlikely to be worked on in the near future so I'll just close this to avoid unactionable issues.
