### ISSUE TITLE
Feature Request: Seperate Highlighted Messages Dialogs

### ISSUE THREAD

**Issue by notmynamehere** [hexchat/hexchat#2360]
Can we please have seperate dialogs for "Highlighted Messages" which is in Settings => Chatting => Alerts ? Similar list dialogs like "Ignore list". So we can do have more organized word lists for "Extra words to highlight", "Nick names not to highlight" and "nick names to always highlight". You can even call it "Alerts" dialog and have 3 tabs for all of those. Seperate dialog for each is a plus. Thank you!

**Comment by TingPing** [comment]
Mass opening issues is not productive so I will be mass closing these. They may be useful features but leaving dozens of vague feature requests on the bug tracker is not helpful.
