### ISSUE TITLE
Feature Request: Ignore List for Specific Words

### ISSUE THREAD

**Issue by notmynamehere** [hexchat/hexchat#2362]
It would be nice to have a dedicated dialog to ignore specific words. If added in dialog, it will hide those words or messages from showing up in the window. This can be similar to "Ignore list" currently available for users. Regex is a plus. Thank you!

**Comment by TingPing** [comment]
Mass opening issues is not productive so I will be mass closing these. They may be useful features but leaving dozens of vague feature requests on the bug tracker is not helpful.
