### ISSUE TITLE
Feature Request: Redirect Messages To Tab

### ISSUE THREAD

**Issue by notmynamehere** [hexchat/hexchat#2365]
Redirect messages to new tab based on words or nickanmes. This can have its own "Redirect Messages" dialog box with custom specified words, nicks, regex, channels, tab-names etc. So if for example I define word "NEW" to open in new tab whenever it was seen in main window on specific channel. This can be very useful. Especially if you want to output something your friend is saying in main window. You can make a tab like "My Friend John Doe" and have all his messages output to seperate tab. But this can be done for anything if regex is allowed. ^_^ Thank you!

**Comment by TingPing** [comment]
Mass opening issues is not productive so I will be mass closing these. They may be useful features but leaving dozens of vague feature requests on the bug tracker is not helpful.
