### ISSUE TITLE
Proxy auth issue: long passwords are truncated by HC

### ISSUE THREAD

**Issue by nonlinear-chaos-order-etc** [hexchat/hexchat#2370]
1. When I enter the long password at GUI, it is saved to `hexchat.conf` in truncated form (with a maximum length of about 32 chars);

2. When I close the HC, then enter the long password at `hexchat.conf` and re-launch HC, `hexchat.conf` gets overwritten with this password in truncated form (with the same maximum length).

`hexchat.conf` variable: `net_proxy_pass =`

Telegram and Eclipse IDE HTTP streams socks5 clients allow for the password with length of about 54 characters, and my `dante` (a socks5 server) handles it okay. The password truncated by HC gets refused, of course.

Version: HexChat 2.14.1

**Comment by TingPing** [comment]
Duplicate of #1296
