### ISSUE TITLE
OMEMO support

### ISSUE THREAD

**Issue by kayront** [hexchat/hexchat#2371]
Are there any plans to add OMEMO support to hexchat?

I am not entirely sure whether [OMEMO](https://en.wikipedia.org/wiki/OMEMO) and IRC are a good match, in fact not a whole lot of discussion about this subject came up during research.

Having a modern, secure, robust way to communicate encrypted end-to-end on IRC would be awesome.

**Comment by nostromov** [comment]
Hey, pretty sure it's been mentioned, like, 1000 times and discussed... However, the issue still remains that IRC _needs_ some kind of ~~a~~ encryption ~~standard~~ :)

**Comment by kayront** [comment]
Could you give some more input on that?

The connection between client *and* server can and often already is encrypted, so I don't understand the point you were trying to make.

Or did you mean that changes to OMEMO are necessary to implement the protocol for IRC? «

**Comment by TingPing** [comment]
It sounds like an interesting discussion but honestly HexChat is not going to be the first implementation of this. I'd recommend looking into making a plugin to support this if somebody wants to try it out in practice. If you just want feedback on the protocol level maybe start a discussion here: https://github.com/ircv3/ircv3-ideas

Good luck.
