### ISSUE TITLE
Include instructions, please?!

### ISSUE THREAD

**Issue by LadyAleena** [hexchat/hexchat#2373]
Please include instructions on how to install things like plugins. A readme would do just fine.

For example, to install the perl plugin on a Debian system, do the following:

```
sudo apt install hexchat-perl
```

**Comment by TingPing** [comment]
I'm not sure we are the best people to document how to use various Linux distros.

Our package includes metainfo files for stores like GNOME-Software and Plamsa Discover to show installable plugins which is where I expect general users to search and more advanced users should know how to use their package managers.
