### ISSUE TITLE
Ugly status icon on KDE

### ISSUE THREAD

**Issue by emilengler** [hexchat/hexchat#2378]
It has a black background, is this normal?
I'm using hexchat 2.14.2
![](https://i.imgur.com/QITsA4h.png "Behavior")

**Comment by TingPing** [comment]
This is probably a bug in a KDE component. HexChat uses an old XEmbed style tray so thats what sets it apart from the others.

**Comment by emilengler** [comment]
@TingPing IT is new since yesterday

**Comment by TingPing** [comment]
Great then you can track down what updated and report it to them.
