### ISSUE TITLE
/py exec and console doesn't use the same interpreter as HexChat

### ISSUE THREAD

**Issue by KnuX** [hexchat/hexchat#2379]
Hi all,

I don't know if it's a bug or not, but I don't understand why I can't run my custom methods by "/py exec my_method(...)".

To do this, I have to append configdir+\\addons to sys.path and import my_module manually in this interpreter. Why the /py interpreter also used in the console is not the same as the interpreter which loaded my_module.py at startup? It can be usefull for live scripting/testing/debugging...

In the past, I used the TCL plugin and the /tcl used the same interpreter. So I was able to run my proc and access my variables using the /tcl command.

I'm running HexChat 2.14.2 x64 on Win10 with Python 3.6

**Comment by KnuX** [comment]
Not so insane for an IRC client. Look at mIRC.

But since you have already closed this question, I assume you don’t care about my (and others?) opinion ^^’

**Comment by TingPing** [comment]
`/py exec` will always be separate. Its just a separate script.

The lua plugin has a `/lua inject foo.lua do_whatever()` command that does what you want and makes more sense. I would welcome that addition to the Python plugin.
