### ISSUE TITLE
Documentation does not show the full list of supported Connect Commands.

### ISSUE THREAD

**Issue by tommai78101** [hexchat/hexchat#2380]
This is the only place I know in the documentations where it gives a list of supported commands:

https://hexchat.readthedocs.io/en/latest/commands.html#list-of-commands

But these commands are to be typed in the text field at the bottom of Hexchat. They are not the "Connect Commands" used when editing the server options in the Network List menu:

![](https://i.imgur.com/O4MlkuQ.png)

I would like to know more about the Connect Commands, what they all are, and where I can find a list of supported Connect Commands for Hexchat. The issue I have is, I don't know if I need to format the commands to be very similar to IRC, or I need to use the All-Caps command names usually found on server responses?

If I need to stick with RFC-#### (of some number), then I can do so, but the issue right now is the lack of information in the documentation. That's what my issue is about.

**Comment by TingPing** [comment]
The page mentions it:

> To get a full list of commands and what they do type /help -l.

There are just a lot of them so it doesn't make sense to maintain a list online.
