### ISSUE TITLE
No file interface options in snap.

### ISSUE THREAD

**Issue by scenicforest** [hexchat/hexchat#2383]
I see in another "issue" that it was recommended to use Flatpak rather than Snap. However, I'm mentioning this issue, anyway, in case it's useful for you to know about. 

I'm using the the HexChat snap on Ubuntu. When I go to Settings>Preferences>Sounds and click the "Browse" button, I can't get into any directories to select sounds: every directory gives me a "Permission denied" message. I assume this is because of snap confinement. 

I thought maybe I could put some sounds in /home and get access to those, but running "snap connections hexchat" in the terminal shows that HexChat doesn't seem to have any interfaces that would allow file access (such as the "home" interface).

**Comment by TingPing** [comment]
You can put the files in `~/snap/hexchat/current/.config/hexchat/sounds`.

I don't think weakening the sandbox is needed.
