### ISSUE TITLE
Clipboard contents from GNOME extensions cannot be pasted into Hexchat

### ISSUE THREAD

**Issue by flotwig** [hexchat/hexchat#2396]
Hi,

It seems like in GNOME 3.34.1 + Pop OS 19.10/Debian Sid + HexChat (latest, from source), pasting contents from GNOME Shell extensions is broken.

As detailed in maoschanz/emoji-selector-for-gnome#88, these GNOME shell extensions can no longer modify the clipboard that Hexchat is using:

* Clipboard Indicator extension
* Emoji Selector extension

Neither `PRIMARY` nor `CLIPBOARD` GTK clipboards seem to work with Hexchat. All other apps work fine.

Not sure if this is a `gnome-shell` issue or a Hexchat issue, but seeing as how Hexchat is the only application where I can't paste, I think there might be something Hexchat could be doing differently when it comes to the clipboard.

**Comment by maoschanz** [comment]
>from GNOME extensions

From GNOME Shell in general

**Comment by TingPing** [comment]
It is a normal GTK2 GtkEntry, I don't think anything here is actionable on HexChats side.

**Comment by flotwig** [comment]
I can also not **copy** from Hexchat to any other application... very strange. 

@TingPing This only happens with Hexchat, no other applications, are you sure? Just wanna make sure before I open another issue.

**Comment by maoschanz** [comment]
can't paste from Clipboard Indicator to Inkscape, so it's either from gnome-shell or from gtk2

**Comment by tracker1** [comment]
If it helps, I'm able to copy/paste out of gedit into hexchat...
