### ISSUE TITLE
IPv6 in "USER" message

### ISSUE THREAD

**Issue by rmorales87atx** [hexchat/hexchat#2399]
Hello,

Developing an ircd here and started using HexChat as a test client. I noticed an issue with HexChat's "USER" command when an IPv6 session is started to localhost (`::1`)

Here is a capture of the session:
```
W: :local.dev1 NOTICE * :*** Looking up your hostname...
W: :local.dev1 NOTICE * :*** Checking ident...
W: :local.dev1 NOTICE * :*** Found your hostname
R: CAP LS 302
W: :local.dev1 CAP * LS :account-notify account-tag away-notify draft/msgid userhost-in-names chghost echo-message extended-join invite-notify monitor multi-prefix draft/setname server-time
R: NICK rmora
R: USER rmora rmora ::1 :realname
W: :local.dev1 461 rmora USER :Not enough parameters
```

Numeric 461 generates due to the erroneous `::1` parameter; this results in a trail parameter of `:1 :realname`, and thus only generates 3 parameters instead of the required 4.

The simplest fix may be to follow RFC2812 and simply pass `"*"` as the third parameter: https://tools.ietf.org/html/rfc2812#section-3.1.3

**Comment by silverbacknet** [comment]
The bigger problem is that while ::1 is a valid IPv6 notation in generic contexts, it's not allowed in IRC; the standard says this should be 0:0:0:0:0:0:0:1. (With 0:0:0:FFFF:0:0:0:1 also accepted.)

**Comment by TingPing** [comment]
If nothing actually uses that information its fine to just get rid of.
