### ISSUE TITLE
2.14.3 *.asc file not available

### ISSUE THREAD

**Issue by EGD** [hexchat/hexchat#2409]
*.asc file for new 2.14.3 release not available
changelog not https://hexchat.readthedocs.io/en/latest/changelog.html not contains changes for this release

**Comment by TingPing** [comment]
It is: https://dl.hexchat.net/hexchat/hexchat-2.14.3.tar.xz.asc

It should: https://github.com/hexchat/documentation/commit/50302e224a1310ff609b3418247ee72779e57d55

I'll see whats wrong with readthedocs...
