### ISSUE TITLE
Hexchat's interface is in Polish, even when the system is set to English 

### ISSUE THREAD

**Issue by kpion** [hexchat/hexchat#2416]
Hey, I have a small issue here. It is very possible that it's my fault, but on the other hand, it happens only to hexchat.

The interface is in Polish, but I really really want it in English. 
This is the result of `cat /etc/default/locale`
```
konrad@konrad-desktop:~$ cat /etc/default/locale
#  File generated by update-locale
LANG=en_US.UTF-8
LC_NUMERIC="pl_PL.UTF-8"
LC_TIME="pl_PL.UTF-8"
LC_MONETARY="pl_PL.UTF-8"
LC_PAPER="pl_PL.UTF-8"
LC_NAME="pl_PL.UTF-8"
LC_ADDRESS="pl_PL.UTF-8"
LC_TELEPHONE="pl_PL.UTF-8"
LC_MEASUREMENT="pl_PL.UTF-8"
LC_IDENTIFICATION="pl_PL.UTF-8"
LC_ALL=en_US.UTF-8
```

As you can see it's mostly en_US.UTF-8 except things like lc_time etc. 

And here goes the printenv command:
```
konrad@konrad-desktop:~$ printenv | grep -i lang
LANG=en_US.UTF-8
LANGUAGE=en_US:pl
```

I want to tell my ubuntu about the fact that I use "PL" as well, because otherwise I have issues with setting my keyboard layout.

What should I do about it?

edit:  this might be the part of the problem: https://github.com/hexchat/hexchat/blob/57478b65758e6b697b1d82ce21075e74aa475efc/src/common/cfgfiles.c#L626

**Comment by TingPing** [comment]
`get_default_language()` is only used on Windows. On Unix HexChat does nothing to override gettext's default behavior AFAIK.

**Comment by kpion** [comment]
Thanks TingPing.

OK, it is an issue with my Ubuntu. I have selected *two* languages, EN and PL, although I made sure EN is at first position (that's in the gui settings). 

But even so, the system was partially in Polish.

Now I removed the second language, only left with one, and it seems to work fine now.

So, let me now close the issue. I think I'll file another one on Ubuntu.
