### ISSUE TITLE
The "s" and "p" channel modes aren't present in the Mode Buttons list

### ISSUE THREAD

**Issue by lkintact** [hexchat/hexchat#2420]
Select View > Mode Buttons, the list of channel mode buttons appears right to the topic line. The "s" and "p" modes are absent in the list, however.

HexChat 2.14.3
Windows 10 Home 1803.

**Comment by TingPing** [comment]
Yes that is fine. Modes are both numerous and not standardized so some things just aren't shown. The state of IRC is just that you have to use the command from time to time.
