### ISSUE TITLE
The "Push input line into history" action doesn't seem to work

### ISSUE THREAD

**Issue by lkintact** [hexchat/hexchat#2421]
Open Settings > Keyboard Shortcuts, click "Add", select a shortcut for "Key" and "Push input line into history" for "Action", click "Save".

Type a command in the Input box, for example `/join #test001` and hit the shortcut. The command text disappears and nothing else happens.

Sorry if I don't understand something, but shouldn't the command text appear in the Text box (and, perhaps, in the log file), according to the action description - "_Push input line into history_ but doesn't send to server"? (Also, it probably should be _Pushes_, not _Push_).

HexChat 2.14.3,
Windows 10 Home 1803.

**Comment by TingPing** [comment]
You have to hit Up (the `Last Command` keybinding) to retrieve it.

**Comment by lkintact** [comment]
@TingPing Ah, thank you, I now understand what the action actually does. Somehow I thought it's "Text box history", not "Input line history" that was meant by "history" in the action description.
