### ISSUE TITLE
Cant open hexchat

### ISSUE THREAD

**Issue by warmachine-pixel** [hexchat/hexchat#2423]
can open
![image](https://user-images.githubusercontent.com/59498388/72084243-c0570d80-32c8-11ea-8d13-40c7b091bfcc.png)
cant run as normal user. i am root using su to get to normal

**Comment by warmachine-pixel** [comment]
fix this bug fast

**Comment by TingPing** [comment]
Your `DISPLAY` env var probably isn't set.

**Comment by StephenAtty** [comment]
running hexchat from a shell works fine for me in Mint 19.3 - so, as @TingPing suggests it's not a bug in hexchat but something wrong with your configuration

**Comment by waweic** [comment]
I do have the same issue on Wayland (Sway). I can run basically any other app, but hexchat is not working. I believe that the OP also uses Wayland if they are using a recent version of Gnome. It could be something with my configuration, but tbh, my research did not lead to anything useful. If this could be resolved on my end, a wiki entry or something would be great

**Comment by TingPing** [comment]
I've used HexChat with XWayland for years, it works fine. If your error is the same as theirs it is very clear. The `DISPLAY` env var is not correct.

**Comment by waweic** [comment]
Well, I noticed that I forgot to install XWayland the other day ;)
