### ISSUE TITLE
Add a modifier for opening URLs in background

### ISSUE THREAD

**Issue by lkintact** [hexchat/hexchat#2424]
Sometimes people give several links in a row, for example, links to pictures. It would be more convenient to first open them all in background (i.e., without switching to the browser) and then switch to it, than open them all one by one with having to switch between HexChat and the browser for every link.

Perhaps, <kbd>Ctrl</kbd>+LClick would do?

HexChat 2.14.3,
Windows 10 Home 1803.

**Comment by TingPing** [comment]
HexChat has no control over that it just says "Default handler, here is a link". You can define a custom handler for right clicking a link though: https://hexchat.readthedocs.io/en/latest/settings.html#url-handlers
