### ISSUE TITLE
Two typos in German language file

### ISSUE THREAD

**Issue by haziegler** [hexchat/hexchat#2426]
There are two typos in the German translation:

https://github.com/hexchat/hexchat/blob/master/po/de.po#L1570:

Wrong:
"%C23*%O$tDer vorherige Verbindungsversucht wurde abgebrochen (%C24$1%O)."

Correct:
"%C23*%O$tDer vorherige Verbindungsversuch wurde abgebrochen (%C24$1%O)."

https://github.com/hexchat/hexchat/blob/master/po/de.po#L1665:

Wrong:
msgstr "Kann log Datei(en) nicht schreiben. Überprüfe die\\n Freigaben von %s"

Correct:
msgstr "Kann Logdatei(en) nicht schreiben. Überprüfe die\\n Freigaben von %s"

**Comment by TingPing** [comment]
Translations are handled here: https://www.transifex.com/hexchat/
