### ISSUE TITLE
checksum plugin causes freezes

### ISSUE THREAD

**Issue by nahemoth33** [hexchat/hexchat#2434]
After downloading a file, hexchat is freezing, while checksum-plugin is calculating the checksum.

hexchat version: 2.14.3
checksum version: 3.1
OS: debian gnu/linux (testing)

**Comment by TingPing** [comment]
I asked for a reproducer, step by step to get that result including a file example.

**Comment by nahemoth33** [comment]
what is a reproducer? what file-example?
sorry but I don't know what you mean

I only get files sent and after finishing, it freezes, till the checksum is calculated.

**Comment by nahemoth33** [comment]
Hello TingPing,
were you able to determine the bug? or do you need some further information?

**Comment by TingPing** [comment]
Yes the bug is actually quite clear I just have been very busy.

**Comment by Totto16** [comment]
Any Updates on this, since it still occurs?

**Comment by TingPing** [comment]
@Totto16 This function needs to be ran using Gio's Async APIs (or in a thread): https://github.com/hexchat/hexchat/blob/master/plugins/checksum/checksum.c#L128

**Comment by Totto16** [comment]
Ok thanks I'll look into it

**Comment by Totto16** [comment]
This is solved in the commits [here](https://github.com/hexchat/hexchat/commit/a01d9ea1528a33dfc8706b391324ef50afc97991) resulting from PR #2775 
So it can be closed now @TingPing
