### ISSUE TITLE
Incorrect implementation of VERSION command?

### ISSUE THREAD

**Issue by juliogonzalez** [hexchat/hexchat#2435]
According to RFC 1459 `VERSION` is part of the server query group of commands, that "has been designed to return information about any server which is connected to the network."
```
4.3.1 Version message

      Command: VERSION
   Parameters: [<server>]

   The VERSION message is used  to  query  the  version  of  the  server
   program.  An optional parameter <server> is used to query the version
   of the server program which a client is not directly connected to.
```
Konversation and irssi accept this command without parameters and the servers just return the version (+support in some cases):

![image](https://user-images.githubusercontent.com/4226070/74221938-7f7d5a80-4cb3-11ea-81cc-98275f782325.png)

However it seems Hexchat does not accept it.

If the user types `/VERSION`:

![image](https://user-images.githubusercontent.com/4226070/74222063-dbe07a00-4cb3-11ea-910a-b3cbca03aacb.png)

If the user types `/VERSION cherryh.freenode.net` (that is, with the `server` parameter`):

![image](https://user-images.githubusercontent.com/4226070/74222136-0599a100-4cb4-11ea-87df-f584de8ea473.png)

The only alternative is using `/QUOTE VERSION`:

![image](https://user-images.githubusercontent.com/4226070/74222166-1f3ae880-4cb4-11ea-8a59-25929e628995.png)

I am not 100% sure, but I'd say HexChat assumes that `/VERSION` is a call to `/CTCP VERSION`. Which is, IMHO, incorrect.

What I am sure of is that `/VERSION` never arrives to the server, and the error above about ` Bad arguments for user command.` is presented by HexChat.

**Comment by TingPing** [comment]
If you want to run server commands you can do `/quote version`, otherwise user commands (user adjustable in settings > user commands) take precedent.
