### ISSUE TITLE
win32: Update Python to 3.8

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [hexchat/hexchat#2438]
_[It's time.](https://www.youtube.com/watch?v=AiBqyXNtOEs&t=1m18s)_

**Comment by TingPing** [comment]
PR welcomed, it would be done similar to this: https://github.com/hexchat/hexchat/commit/63e9c721148f8a91bc68484c3f9ee42cfbc4316f

**Comment by TingPing** [comment]
Oh also one potential problem is 3.8 is probably built against a different runtime which may introduce issues.
