### ISSUE TITLE
Underscores not rendered in Monospace 11/12 font

### ISSUE THREAD

**Issue by lathiat** [hexchat/hexchat#2449]
I am finding that underscores don't render, appearing as spaces, when using the default Monospace 11 or Monospace 12 font on Ubuntu 20.04 (Focal, development beta, but due to be released this month). This occurs in both the package of 2.14.3-3 and the current master branch as of today.

Increasing to Monospace 13 causes them to appear and they work in some other fonts at various sizes. I suspect most likely that the calculated bounding box for the row is being incorrectly calculated somehow to be too short.

I imagine most likely this is either in xtext or an interaction with one of it's rendering dependencies but I'm not really sure where to start on debugging it. I'm happy to do any testing or even work towards solving it but somewhere to start would be great!

**Comment by TingPing** [comment]
Monospace is not a font. I believe `fc-match Monospace` will tell the actual font.

Anyway I *think* this is a font problem. xtext queries the line height from the font.

**Comment by konomikitten** [comment]
While I don't know what font the reporter is using I can confirm that I am seeing this in hexchat v2.14.3 also with the following font.

```
$ fc-match monospace
DejaVuSansMono.ttf: "DejaVu Sans Mono" "Book"
```
Screenshots:

Hexchat
![hexchat](https://user-images.githubusercontent.com/12713710/79108219-37fd7280-7db9-11ea-9123-3e5b02efaead.png)

Kitty Terminal and Weechat
![kitty weechat](https://user-images.githubusercontent.com/12713710/79108238-42b80780-7db9-11ea-8d82-5834442c74eb.png)

**Comment by jpiszcz** [comment]
The 'g' is also particularly impacted:
https://imgur.com/a/YRkXm9X

DejaVuSansMono.ttf: "DejaVu Sans Mono" "Book"

This change appeared to occur in the past ~14 days.. (running Debian testing)

**Comment by TingPing** [comment]
@jpiszcz Could you find out if the `pango` package has updated recently and test older versions of it?

**Comment by jpiszcz** [comment]
That was it!  Everything is rendering perfectly once again!

The workaround is to downgrade these packages to the following versions:
dpkg -i libpango-1.0-0_1.42.4-7~deb10u1_amd64.deb  libpangoxft-1.0-0_1.42.4-7~deb10u1_amd64.deb libpangocairo-1.0-0_1.42.4-7~deb10u1_amd64.deb  libpangoxft-1.0-0_1.42.4-7~deb10u1_amd64.deb  gir1.2-pango-1.0_1.42.4-7~deb10u1_amd64.deb  libpangoft2-1.0-0_1.42.4-7~deb10u1_amd64.deb

I found the old versions here:
http://http.us.debian.org/debian/pool/main/p/pango1.0/

![fix](https://user-images.githubusercontent.com/6805592/79209888-01077b00-7e12-11ea-9c7e-fc8ce5545d92.PNG)

**Comment by TingPing** [comment]
So ideally somebody could bisect the code to see what caused the regression. But I guess you can just open an issue against Pango with the exact version where the line height of a font no longer seems accurate (this isn't exactly verified to be the exact problem).

**Comment by jpiszcz** [comment]
Someone also submitted a Debian bug report:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=956633

Will submit these two links to the pango issues section.
https://gitlab.gnome.org/GNOME/pango/-/issues/471

**Comment by s7sost** [comment]
I tried downgrading by following the instructions posted above (since my issue was exactly as reported in this thread), but then I encountered the following issues:

```
dpkg: error processing package libpango-1.0-0:amd64 (--install):
 package libpango-1.0-0:amd64 1.42.4-7~deb10u1 cannot be configured because libpango-1.0-0:i386 is at a different version (1.44.7-2ubuntu4)
dpkg: dependency problems prevent configuration of libpangoxft-1.0-0:amd64:
 libpangoxft-1.0-0:amd64 depends on libpango-1.0-0 (>= 1.22.0); however:
  Package libpango-1.0-0:amd64 is not configured yet.
 libpango-1.0-0:i386 (1.44.7-2ubuntu4) breaks libpangoxft-1.0-0 (<< 1.44.7) and is broken due to postinst failure.
  Version of libpangoxft-1.0-0:amd64 to be configured is 1.42.4-7~deb10u1.

dpkg: error processing package libpangoxft-1.0-0:amd64 (--install):
 dependency problems - leaving unconfigured
dpkg: error processing package libpangocairo-1.0-0:amd64 (--install):
 package libpangocairo-1.0-0:amd64 1.42.4-7~deb10u1 cannot be configured because libpangocairo-1.0-0:i386 is at a different version (1.44.7-2ubuntu4)
dpkg: dependency problems prevent configuration of gir1.2-pango-1.0:amd64:
 gir1.2-pango-1.0:amd64 depends on libpango-1.0-0 (>= 1.42.0); however:
  Package libpango-1.0-0:amd64 is not configured yet.
 gir1.2-pango-1.0:amd64 depends on libpangocairo-1.0-0 (>= 1.22.0); however:
  Package libpangocairo-1.0-0:amd64 is not configured yet.
 gir1.2-pango-1.0:amd64 depends on libpangoxft-1.0-0 (>= 1.14.0); however:
  Package libpangoxft-1.0-0:amd64 is not configured yet.

dpkg: error processing package gir1.2-pango-1.0:amd64 (--install):
 dependency problems - leaving unconfigured
dpkg: error processing package libpangoft2-1.0-0:amd64 (--install):
 package libpangoft2-1.0-0:amd64 1.42.4-7~deb10u1 cannot be configured because libpangoft2-1.0-0:i386 is at a different version (1.44.7-2ubuntu4)
Processing triggers for libc-bin (2.31-0ubuntu9) ...
Errors were encountered while processing:
 libpango-1.0-0:amd64
 libpangoxft-1.0-0:amd64
 libpangocairo-1.0-0:amd64
 gir1.2-pango-1.0:amd64
 libpangoft2-1.0-0:amd64
```
On top of that, when trying to do `apt-get install -f` or `apt --fix-broken install`, it refuses to reinstall the previous (updated) versions to revert the process. This is just one of the many issues I've had since upgrading to Ubuntu 20.04, but at least this one seems to have a clear (albeit unsuccessful for me) solution.

**Comment by jpiszcz** [comment]
> Ubuntu 20.04

The instructions were for Debian Testing (x86_64) arch, for Ubuntu or other distributions you will need to determine how to downgrade and then once done make sure you pin the packages so they don't break again.

`system:/etc/apt# cat preferences
# pin packages here

# 2020-04-14 pin pango related packages otherwise the fonts look bad
Package: libpango*
Pin: release a=testing
Pin-Priority: -1

# 2020-04-14 pin pango related packages otherwise the fonts look bad
# look jacked up in hexchat
Package: gir1.2*
Pin: release a=testing
Pin-Priority: -1
`

**Comment by jacob1** [comment]
Also getting the same issue (Debian testing), downgrading pango fixed it.

@s7sost Looks like you have i386 packages, so you'll also need to download and install the downgraded versions of those too.
Also, to fix --fix-broken, I had to remove all the files it complains about:
sudo rm /usr/share/doc/libpangocairo-1.0-0/copyright /usr/share/doc/libpango-1.0-0/copyright /usr/share/doc/libpango-1.0-0/changelog.Debian.gz /usr/share/doc/libpangoft2-1.0-0/copyright /usr/share/doc/libpangocairo-1.0-0/changelog.Debian.gz /usr/share/doc/libpango-1.0-0/NEWS.gz /usr/share/doc/libpangoft2-1.0-0/changelog.Debian.gz

Then --fix-broken will start working again.

**Comment by machine-outboundengine** [comment]
I had the same problem on Fedora 31 and now on Fedora 32.
The workaround for me was:
rpm -U --oldpackage pango-1.43.0-4.fc31.x86_64.rpm

Works:
pango-1.43.0-4.fc31

Broken:
pango-1.44.4-1.fc31
pango-1.44.7-2.fc32

**Comment by edgan** [comment]
I had the same problem on Fedora 31 and now on Fedora 32.
The workaround for me was:
rpm -U --oldpackage pango-1.43.0-4.fc31.x86_64.rpm

Works:
pango-1.43.0-4.fc31

Broken:
pango-1.44.4-1.fc31
pango-1.44.7-2.fc32

**Comment by ibahnasy** [comment]
This is happening for me too on Arch Linux with pango 1.44.7 and I have no way to downgrade.

**Comment by Deek** [comment]
Pango added the use of typographic metrics (sTypo*) and a line height attribute around then. It's possible that was the start of the problem. Locally, I "fixed" it (may not be a correct fix) by doing this:
```diff
--- src/fe-gtk/xtext.c
+++ src/fe-gtk/xtext.c
@@ -283,6 +283,7 @@ backend_font_open (GtkXText *xtext, char
 	metrics = pango_context_get_metrics (context, xtext->font->font, lang);
 	xtext->font->ascent = pango_font_metrics_get_ascent (metrics) / PANGO_SCALE;
 	xtext->font->descent = pango_font_metrics_get_descent (metrics) / PANGO_SCALE;
+	xtext->fontsize = pango_font_metrics_get_height (metrics) / PANGO_SCALE + 1;
 	pango_font_metrics_unref (metrics);
 }
 static int
@@ -3479,7 +3480,7 @@ gtk_xtext_set_font (GtkXText *xtext, cha
 	if (xtext->font == NULL)
 		return FALSE;
 
-	xtext->fontsize = xtext->font->ascent + xtext->font->descent;
+//	xtext->fontsize = xtext->font->ascent + xtext->font->descent;
 
 	{
 		char *time_str;
```

**Comment by TingPing** [comment]
@Deek It doesn't look crazy. Could you open a PR for that and I'll ask some Pango folks to review it.

**Comment by TingPing** [comment]
Ok so that is new in 1.44, put it in an `#if PANGO_CHECK_VERSION(1, 44, 0)`

**Comment by jlevon** [comment]
Some more detail here: https://gitlab.gnome.org/GNOME/pango/-/issues/392

@Deek if you don't want to open a PR for this, maybe I could take a look if your fix still works?

**Comment by Deek** [comment]
The fix does still work; it could well be a bug in Pango itself causing it (that +1 I had to put in is suggestive), but it does seem to result in text that doesn't get cut off.

**Comment by jlevon** [comment]
@Deek do you really need the +1 ? I tested both with and without, and the fix is sufficient for me to see underscores again. But I slightly prefer the additional pixel space.

**Comment by Deek** [comment]
I seem to recall not adding the 1 did partially restore most underscores, but that they were still cut off a bit; adding the +1 seemed to make hexchat look just like it did before the Pango change.

**Comment by nerozero** [comment]
The issue is still present for me....

**Comment by jarnos** [comment]
My bug report in https://bugs.launchpad.net/hexchat-irc/+bug/1920974

**Comment by mapreri** [comment]
If somebody here runs Ubuntu 20.04 focal and is affected by this bug, I've proposed a patch on https://bugs.launchpad.net/hexchat-irc/+bug/1920974 msg#4 ; I need somebody to fill in the "test plan" (i.e. how to reproduce the bug) and try out my proposed package, after which if the bug is confirmed fixed I can upload it to the main archive.

TIA!

**Comment by mapreri** [comment]
Also sorry it took me so long to fix it on focal, it totally slipped my mind to check it there when I fixed it for Debian…
