### ISSUE TITLE
Auto Connect failed to connect in Debian Linux Stable

### ISSUE THREAD

**Issue by randalsouth** [hexchat/hexchat#2463]
There are three primary problems with the auto connect feature:

1)  Only part of the network command is transferring over to the network resulting in my ability to auto identify.
2)  Once all of the user names are used up the auto connect should be able to use my username anyway by adding a character.

These problems are long standing, and have existed for years, but Hexchat is great for other things because of its simplicity, and easy to follow interface.  However, new users might get discouraged from using Linux if they don't have tools that work, and automating the identity in Freenode is an important fix that needs to be done.

**Comment by randalsouth** [comment]
3)  The third problem is that characters can't be properly imputed into the auto connect command.

EX:  I need to enter /msg nickserv identify "password"
but instead the following is displayed after my entry
msg nickserv identify "password"
and the / appears to be missing.
This is in addition to the commands not transferring to the network for identifying.

**Comment by TingPing** [comment]
Just put your password in the password field.

There is no issue with authentication.
