### ISSUE TITLE
A way to get notification on notification center?

### ISSUE THREAD

**Issue by spirulin** [hexchat/hexchat#2468]
I am using right now Manjaro 20 XFCE with xfce4-notifyd. 
But HexChat doesn't show as a program that would send notifications.
Was using Windows a couple of days ago - the same thing. No notifications in the Notification Center.
Any way this could be added? At least for Mention notifications.
Would be very useful.
Something like "X nickname mentioned you in a #channel" .
Would be highly appreciated.

**Comment by TingPing** [comment]
*Settings > Alerts > Show notification on:*
