### ISSUE TITLE
Enhancement: Add Button UIs to order autojoin channels in the "Edit Network" UI.

### ISSUE THREAD

**Issue by tommai78101** [hexchat/hexchat#2469]
Using Ubuntu 18.04.3 LTS. 
HexChat 2.14.1
Kernel: Linux 5.3.0-51-generic

I am referring to this small UI cropped screenshot here:

![image](https://user-images.githubusercontent.com/6444116/81969646-49ba7b80-95ec-11ea-9340-b74c0456a68a.png)

Currently, Hexchat is set up so the last autojoin channel in the list is the channel that will be focused after the network has joined. There is no way for us to move the autojoin channel in the list up or down. We have to remove the channel from the list, and then re-add the channel back into the list, so the channel we wanted to focus on is at the bottom of the list.

I would like to request for button elements somewhere next to the list be added for us to move or re-order the autojoin channels' positions up/down in the list.

I don't mind about sorting the autojoin channels. I just feel it's an inconvenience to have to remove the channel, then re-add the channel back into the list, so that we can re-order which channel that will be connected to the last, so Hexchat can auto-focus on that channel in the network.

Thank you.

**Comment by mxdamien** [comment]
Hi !
You can move a channel up or down in the list my holding down SHIFT und use the arrow keys.

**Comment by tommai78101** [comment]
@mxdamien Oh cool! This is pretty obscure, or maybe it's in the guide somewhere that I somehow glossed over?

**Comment by mxdamien** [comment]
@tommai78101 .. I have to admit that I found it in the source code when looking into how your requested feature could be implemented. I checked the documentation and the shortcut is 
mentioned there but only in connection with the network list.

https://hexchat.readthedocs.io/en/latest/settings.html

Last paragaph in the section "Networks".

**Comment by tommai78101** [comment]
@mxdamien That explains it. Then I definitely glossed over this page. Thanks again for your help.
