### ISSUE TITLE
Can't write and read with arabic

### ISSUE THREAD

**Issue by lamjed001** [hexchat/hexchat#2471]
i can't write and read with arabic any solution ?
![image](https://user-images.githubusercontent.com/23016064/82593749-dcce5500-9b9a-11ea-9d1a-c729a86712d8.png)

**Comment by TingPing** [comment]
Try following this: https://hexchat.readthedocs.io/en/latest/tips.html#special-glyphs

**Comment by lamjed001** [comment]
thanks it works ♥

**Comment by lamjed001** [comment]
> Try following this: https://hexchat.readthedocs.io/en/latest/tips.html#special-glyphs

thanks it works ♥
