### ISSUE TITLE
Connect commands should be executed synchronously

### ISSUE THREAD

**Issue by mdcclxv** [hexchat/hexchat#2476]
Hi there.

Title says it all, I'll just elaborate on my use case.

I need to automatically join an invite only channel on a private server. The System bot, which is responsible for sending the invite, will only accept invite requests from identified users. As of now, HexChat isn't waiting for the `/msg NickServ identify` command to finish, instead it issues the next command (the invite request) immediately, which, of course, is rejected by the bot because I'm not identified yet.

Please add an option in the network edit dialog to execute connect commands synchronously.

Thank you.

**Comment by TingPing** [comment]
IRC is entirely asynchronous and for the most part the client has no idea when things finish.

If you want synchronous authentication you use SASL.

If you want more complex behavior parsing the response of some service to know when things happen you need to make a script.
