### ISSUE TITLE
Fix typo in fr.po

### ISSUE THREAD

**Issue by anto1ne** [hexchat/hexchat#2490]
Hi

A small issue to mention a typo in the french translation

https://github.com/hexchat/hexchat/blob/aec72593f265b09bc53291d00300490a5d0d9911/po/fr.po#L6096

Advanced should be translated as Avancés, the "_" should be removed

**Comment by TingPing** [comment]
All translations are handled here: https://www.transifex.com/hexchat/hexchat/
