### ISSUE TITLE
More Friends list

### ISSUE THREAD

**Issue by Sirath5** [hexchat/hexchat#2503]
can we have a bigger friends list please? because i dont think 100 is enough.
or is there a addon that i can add to hexchat to increase  the size?
if theres no addon can someone make one please?
im no good at coding.

**Comment by TingPing** [comment]
At a glance there is no limit on the size, how is it behaving for you?

**Comment by Sirath5** [comment]
> At a glance there is no limit on the size, how is it behaving for you?

it says theres a 128 limit size.  "Maximum size for WATCH-list is 128 entries"

**Comment by TingPing** [comment]
Oh, well that sounds like the server telling you this. Nothing we can do about that.
