### ISSUE TITLE
[i18n] Translating to Serbian

### ISSUE THREAD

**Issue by kizule** [hexchat/hexchat#2504]
Hello,
I want to help with translations to Serbian language. How I can work on it?

**Comment by TingPing** [comment]
All translations are handled on Transifex: https://www.transifex.com/hexchat/

**Comment by kizule** [comment]
Thanks @TingPing, but that page shows me "error 404".

**Comment by kizule** [comment]
Oh, it was https://www.transifex.com/hexchat/hexchat/ . I've sent request to join.
