### ISSUE TITLE
WHO command being spammed at every channel on join.

### ISSUE THREAD

**Issue by C4J3** [hexchat/hexchat#2512]
Okay Spam might be an extreme description but whenever I connect to a bunch of twitch channel chats it seems to send a WHO command to each one and then get a response from Twitch (the 'main' server not each channel/chat) saying:  `WHO :Unknown command` in the server window.

I don't have any connect commands for the server and this is only happening on the Twitch chat server; I'm guessing that HexChat is automatically doing something that works on regular IRC servers.

If I've missed any important information let me know.

**Comment by TingPing** [comment]
Yes that is how tracking user state works on IRC. You can disable it with `/set irc_who_join off`.

**Comment by C4J3** [comment]
Added set `irc_who_join off` to autojoin commands, seems to have fixed it 👍

**Comment by TingPing** [comment]
Settings persist so you only had to run it once.
