### ISSUE TITLE
[fishlim] HexChat 2.14.3 (win x64) ships with outdated hcfishlim.dll

### ISSUE THREAD

**Issue by krystalgamer** [hexchat/hexchat#2525]
The hcfishlim.dll that comes with the installer is an older version of what's in the repository and doesn't support CBC mode(/keyx).

Compiling the plugin from src works just fine.

**Comment by TingPing** [comment]
Well yes there hasn't been a release. I'll close this but I understand a new release would be nice.

**Comment by fred0r** [comment]
Thx for posting that Issue!
