### ISSUE TITLE
hexchat broken after upgrading to python 3.9

### ISSUE THREAD

**Issue by truexfan81** [hexchat/hexchat#2528]
complains about missing libraries and then segfaults, i will attach an strace
[strace.log](https://github.com/hexchat/hexchat/files/5646225/strace.log)

**Comment by mapreri** [comment]
that's fixed in master thanks to the whole rewrite of the python plugin using cffi.

FTR, downstream bugs:
 * https://bugs.debian.org/975393
 * https://bugzilla.redhat.com/show_bug.cgi?id=1883982

**Comment by TingPing** [comment]
First found bug in the new plugin: #2531

**Comment by v00v** [comment]
@truexfan81, @mapreri 
Confirmed installing "python-cffi" fixes this issue.
