### ISSUE TITLE
Autojoin delay is ignored

### ISSUE THREAD

**Issue by Ottaviocr** [hexchat/hexchat#2539]
Hi, I'm using hexchat 2.14.3 built from sources using pkgsrc on Debian Stretch.

I have a problem with a particular channel on OFTC. It won't let me autojoin and it throws this error:

 <pre>#debian-hams :Cannot join channel (Need to be identified and verified to join this channel, '/msg NickServ help' to learn how to register and verify.)</pre>

But my nick is registered and verified.

From the timestamps, it looks like the connection attempt is immediate, whereas I have setup an autodelay of 10 (I assume it is seconds) in Preferences > Chatting > Adanced.

<pre>$ grep join_delay  .config/hexchat/hexchat.conf 
irc_join_delay = 10 </pre>

~~I use password-less SASL external certificate authentication.~~

**Comment by JulianGro** [comment]
This works fine on 2.14.1 for me

**Comment by Fohdeesha** [comment]
Having the exact same issue, also on OFTC (but different channels, even though ironically I am also a ham, and also use debian)  

Also using password-less SASL identification (which works fine, and succesfully identifies). Like the OP, the logs show it trying to connect to my auto-connect channels way before the auto-join delay (which is 30 seconds in my case). All my other IRC networks in hexchat obey the 30 second delay, but I'm not using SASL ident on any of them. OFTC with SASL ident seems to try auto-joining immediately after the server's MOTD is sent

**Comment by TingPing** [comment]
@Fohdeesha The autojoin delay is only used when you have connect commands, nickserv, or server password set as the auth type.

If you use SASL it won't delay because there is no reason for it to.

**Comment by Fohdeesha** [comment]
What do you mean no reason, does SASL not have a slight ident delay on other servers? At least on OFTC, when using SASL I still have to wait on nickserv to verify the matching certificate and mark me as identified - hexchat tries to autojoin before this, which doesn't work because the channels require me to be identified:

```
Jun 23 14:15:01 *	- Thanks and enjoy your stay! The OFTC team.
Jun 23 14:15:01 *	End of /MOTD command.
Jun 23 14:15:01 *	Fohdeesha sets mode +i on Fohdeesha
Jun 23 14:15:01 *	#xcp-ng :Cannot join channel (Need to be identified
Jun 23 14:15:01 *	#xen-orchestra :Cannot join channel (Need to be identified
Jun 23 14:15:01 -NickServ-	This nickname is registered and protected.  If it is your nickname, you may
Jun 23 14:15:01 -NickServ-	authenticate yourself to services with the IDENTIFY command.  You are
Jun 23 14:15:01 -NickServ-	getting this message because you are not on the access list for the
Jun 23 14:15:01 -NickServ-	Fohdeesha nickname.
Jun 23 14:15:01 *	Fohdeesha sets mode +R on Fohdeesha
Jun 23 14:15:01 -NickServ-	You are connected using SSL and have provided a matching client certificate
Jun 23 14:15:01 -NickServ-	for nickname Fohdeesha.  You have been automatically identified.
```

**Comment by TingPing** [comment]
SASL does not have a delay. Just checking now OFTC does not support SASL.

A workaround would be to select the "Custom" auth type and just set a random command in connect commands like `echo nothing`.

**Comment by Ottaviocr** [comment]
On Thu, 24 Jun 2021 at 01:09, Patrick ***@***.***> wrote:
>
> SASL does not have a delay. Just checking now OFTC does not support SASL.
>

No, but it does support CertFP. In any case, I have not had this issue
for a few months now. Please panel, let me know if I have to close
this issue or leave it open.

**Comment by Fohdeesha** [comment]
> SASL does not have a delay. Just checking now OFTC does not support SASL.
> 
> A workaround would be to select the "Custom" auth type and just set a random command in connect commands like `echo nothing`.

That worked and I'm still succesfully authenticating with CertFP, thanks!

**Comment by kyawthusoe45** [comment]
ECHO Hello workaround on Debian Bullseye works.
