### ISSUE TITLE
Changing the colour/theme of window borders on Linux Mint

### ISSUE THREAD

**Issue by xbeyond1** [hexchat/hexchat#2540]
It's fairly easy to do on Windows by extracting the gtk theme to HexChat's folder, but is there a similar way to do it on Linux Mint 20 as well? I managed to change the colour of the chatbox and userlist easily, but the bright window borders (see picture) are very distracting. 
![Screenshot from 2021-02-15 13-17-06](https://user-images.githubusercontent.com/22633092/107940123-6a0ad280-6f90-11eb-9127-78266b1408b8.png)

**Comment by TingPing** [comment]
That is set by gtk and has nothing to do with hexchat. See the GTK_RC_FILES env car to override per app.
