### ISSUE TITLE
HexChat v3.0 Release Updates?

### ISSUE THREAD

**Issue by FunctionNotFound** [hexchat/hexchat#2548]
Any news on hexchat version 3.0? Last release was back in Dec/2019 and its 2021 now. Maybe you or some other maintainers can do a more freaquent updates like every 6 months with smaller changes? Perhaps those who are interested can do a pull request if you allow it.

**Comment by aklapper** [comment]
Please do not post random questions as Issues. 

Issues are for bug reports and feature requests. 

Use support forums for questions. Thanks.

**Comment by TingPing** [comment]
A new maintainer would be nice. No new release is planned atm.
