### ISSUE TITLE
HexChat doesn't redraw after updating to Ubuntu 20.10

### ISSUE THREAD

**Issue by Saurbaum** [hexchat/hexchat#2550]
After the initial load HexChat stops updating the display, You can type a message (but not see it while you are typing) and you can select the room text to force that to redraw.

Dialogs appear with no content visible and menus appear only as an outline.

I tried with the version fetched by apt and also with snap.

**Comment by fred0r** [comment]
please remove your already available hexchat-conf folder:
`mv ~/.config/hexchat ~/.config/hexchat.bak`
then recheck pls.

**Comment by Saurbaum** [comment]
No change to the UI behaviour

**Comment by Saurbaum** [comment]
Something updated somewhere in the chain and the UI redraws again now.
