### ISSUE TITLE
autojoin doesnt work

### ISSUE THREAD

**Issue by odarcan** [hexchat/hexchat#2552]
Even when I have autojoin on, hexchat does not do it on some channels, I looked it is checked, but when I restart the program that channel is gone.

When I join manually, and right click the channel autojoin is ticked!

Does not happen to all channels, one that it does to is ##linux on freenode.

**Comment by odarcan** [comment]
ah ok the problem is that linux channel requires registration

and when opening freenode it tries to do nickserv identify AFTER it attempts to do the autojoins

how do I change that?

**Comment by odarcan** [comment]
okay so I figured it out

recommended nickserv identify has some issues on freenode, doing another method sasl user +pass works now

**Comment by fred0r** [comment]
@odarcan - please close that issue then
