### ISSUE TITLE
How to install hexchat after cloning it?

### ISSUE THREAD

**Issue by nagharshita16** [hexchat/hexchat#2553]
Which particular file has to be run? I went through the folder, couldn't get it.

**Comment by mjeveritt** [comment]
Unwittingly I hit upon this issue when I opened up the repository earlier.
An awkward exchange on the freenode IRC support channel later, I found this: https://hexchat.readthedocs.io/en/latest/building.html . It would be nice if this was slightly more obvious from eg. the git repo.

**Comment by nagharshita16** [comment]
Fails while running meson build. And when I try installing meson, then "Package meson is not available but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source"

**Comment by fred0r** [comment]
this is no hexchat error - pls close.
