### ISSUE TITLE
Setting up a virtualenv for the Python scripting interface

### ISSUE THREAD

**Issue by Lvl4Sword** [hexchat/hexchat#2565]
Would be nice to have the ability to specify a specific Python virtual environment for the scripting interface.
This isn't straightforward, and there's nothing documenting ( as far as I can find ) that this is even possible right now.

**Comment by TingPing** [comment]
I imagine none of that is hexchat specific?

You create a virtualenv and enter it. Then start hexchat in that env?

**Comment by Lvl4Sword** [comment]
The linked library part was why I made the issue.
Having an option within HexChat itself would make this a lot easier.
