### ISSUE TITLE
libnotify can block

### ISSUE THREAD

**Issue by edman007** [hexchat/hexchat#2567]
Annoying problem I finally figured out, and it needs to be fixed in hexchat.

Hexchat uses libnotify to display notifications, specifically by calling notify_notification_show() (this is called from within notification_backend_show() ), if no notification daemon is running it hangs for a while (120 seconds I think?), and then returns an error. HexChat assumes it returns instantly, but it does not. This hangs hexchat, it doesn't respond to UI, and it doesn't respond to network traffic. The result is if someone mentions me when no notification daemon, hexchat hangs and then disconnects from all networks.

Very very annoying.

**Comment by TingPing** [comment]
`libnotify` is a terrible library and needs to be replaced at some point.

**Comment by TingPing** [comment]
Fixed by c144d0468b5643cafd702000aee65eef8c5c1565
