### ISSUE TITLE
Reasonable copy and text input behaviour

### ISSUE THREAD

**Issue by Thermi** [hexchat/hexchat#2569]
As of now, copying is done via ctrl+shift+c. Please make it so normal ctrl+c works. That's what users expect. I only found out from the help text in the settings.

Also, please enable the normal text deletion and selection feature via alt+delete and shift+arrow keys of text input boxes

**Comment by TingPing** [comment]
The entire application is designed around the input box having focus, thus copy from the text box must have a different shortcut.

I'm not sure I understand your other complaints. The input box behaves like a normal entry.
