### ISSUE TITLE
everytime i download anything from hexchat, my internet adapter disables itself and i'm forced to restart to re enable it 

### ISSUE THREAD

**Issue by jack652** [hexchat/hexchat#2575]
everytime i download anything from hexchat, my internet adapter disables itself and i'm forced to restart to re enable it

**Comment by TingPing** [comment]
HexChat is a simple application and does nothing particularly special. Your hardware issues are its issues.

**Comment by jack652** [comment]
My internet adapter only stops working when downloading files with Hexchat

**Comment by TingPing** [comment]
Your network hardware very well may try to interfere with DCC connections. Nothing the client can do about that.
