### ISSUE TITLE
macOS Support?

### ISSUE THREAD

**Issue by dbarnes181** [hexchat/hexchat#2593]
Hi,

On the Downloads page there isn't a download link for a macOS version?
Is this somewhere else, or does it just not exist?
If it doesn't exist, please could you consider making one, because macOS is probably the 2nd most popular desktop OS(after ~~the worst OS~~ Windows)

I'm using macOS Catalina(10.15.7) and have been struggling to find a free IRC desktop app for macOS(All Linux and Windows ~~urgh~~). I found this, and hoped I could use it. However, no macOS support.

So please could you consider adding support?
I think a lot of people, including me, would like it.

**Comment by TingPing** [comment]
Its not supported. The libraries used and not maintained there and a huge pain to get working. Nobody is volunteering time to do it.
