### ISSUE TITLE
Python Interface - Hexchat freeze when calling the `sys.exit()` function

### ISSUE THREAD

**Issue by deagrut** [hexchat/hexchat#2595]
## Context

Hello,
I was writing a Python script for HexChat when I noticed a problem with the use of the python module `argparse`.
Indeed, in some situations, this module calls internally the `sys.exit()` function, which results in freezing HexChat completely.
The mouse cursor even disappears completely when hovering over the HexChat window and there's no way to interract with the keyboard.

I haven't found any other way to recover the execution of HexChat. The only solution I found at the moment is to kill the process (via Windows task manager / command line).

## Process

Here is a simplified way to reproduce the issue with the Python Console in HexChat.

1. Open HexChat and connect to any server, in order to get the default chat view.
    (Load the python interface  module if it's not already launch)
2. Start the Python console of the Python interface module by executing the command `/PY CONSOLE`.
3. Import python `sys` standard library by running : `import sys`
4. Execute the `exit` function with any argument by running : `sys.exit()`
5. Use your eyes to discover with amazement the freezing of all HexChat windows (i mean, the main and the detached windows).
6. Cry

The same thing happens if HexChat loads a python module that runs this same code.

Code sample :
```python
import sys
sys.exit()
```

## Expected result

The call of the `sys.exit()` function or the raising of a `SystemExit` exception should be handled by the python interface module. A message could be displayed by the python interface module, and/or the module calling the function could be unloaded.

## Current result

HexChat main window and all its detached windows freeze

## Possible Fix

- Surround the code that could call the `sys.exit()` function with a `try/catch` statement and catch the `SystemExit` exception.
Example :
```python
import sys
try:
    sys.exit(0)
except SystemExit as e:
    print("SysExit catch : {}".format(e))
```
However, this solution should be used with caution.

## Environment
- OS : Windows 10 - Version 21H1
- HexChat 2.14.3
- HexChat Python Interface module version 1.0/3.6, hcpython3.dll
- Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]

**Comment by TingPing** [comment]
I think this is already fixed in master. You can try an installer here: https://github.com/hexchat/hexchat/actions/runs/956835342
