### ISSUE TITLE
Nicklist not updating on changes level changes

### ISSUE THREAD

**Issue by adamus1red** [hexchat/hexchat#2599]
When a user joins a channel in some cases the nicklist does not update with the users channel level if they get voiced. Manually running `/NAMES` will update the nicklist levels properly

User joins and gets voiced after identification to services.
![image](https://user-images.githubusercontent.com/2502582/123883246-8bb59680-d940-11eb-9e0d-1e002bcf47fe.png)

Nicklist does not get updated to show changes.
![image](https://user-images.githubusercontent.com/2502582/123883260-92dca480-d940-11eb-81cf-3bd2a0e3fcf9.png)

Network information:

- UnrealIRCd 5.2.0.1
- CAP LS
  - Capabilities supported: account-notify away-notify batch cap-notify echo-message extended-join multi-prefix server-time userhost-in-names znc.in/batch znc.in/self-message znc.in/server-time-iso
  - Capabilities requested: account-notify away-notify cap-notify extended-join multi-prefix server-time userhost-in-names znc.in/server-time-iso 
  - Capabilities acknowledged: account-notify away-notify cap-notify extended-join multi-prefix server-time userhost-in-names znc.in/server-time-iso

**Comment by RealKindOne** [comment]
>UnrealIRCd 5.2.0.1

You might be hitting one of these UnrealIRCd desync bugs that have been fixed in 5.2.1


https://bugs.unrealircd.org/view.php?id=5934

https://bugs.unrealircd.org/view.php?id=5916

**Comment by Polsaker** [comment]
Not a desync bug, this has been happening to me too.

**Comment by adamus1red** [comment]
> You might be hitting one of these UnrealIRCd desync bugs that have been fixed in 5.2.1

I don't think it's the desync bug that UnrealIRCd fixed in 5.2.1 since I've tested it on a channel of 3 and it still happens. The notes state that the desync was only caused when syncing large channels.

**Comment by wolfy1339** [comment]
I'm encountering this as well
Last known good version is 2.14.3
