### ISSUE TITLE
Removing freenode from network list

### ISSUE THREAD

**Issue by TheMesquito** [hexchat/hexchat#2604]
Due to the fact that Freenode has likely been taken over by a hostile entity (see [here](https://gist.github.com/joepie91/df80d8d36cd9d1bde46ba018af497409)), It would probably be a good idea to remove the the network from the network list entirely and adding [Libera](https://libera.chat/) to the list, as it is run by former staff of freenode that where forced to resign during the takeover. I feel like this would probably be a safe thing to do, since we have no idea how the new owner is going to handle freenode, and how a ton of FOSS projects have moved off of freenode due to the change.

**Comment by CensorshipAlert** [comment]
The author of that gist was busted today using censorship and misdirection to steer a false narrative:

https://twitter.com/Equitis_Rubrum/status/1413925219794837506

It should also be noted that both the OP and author of said gist are collaboratively working with the Libera staff to defame the Freenode network.  No recommendation intended, this is an informational notice only.
