### ISSUE TITLE
Hexchat for "Apple Silicon" arm64?

### ISSUE THREAD

**Issue by danielktdoranie** [hexchat/hexchat#2617]
Hi, is there a "universal binary" for Hexchat allowing Hexchat to run "native" on Apple Silicon (M1 SoC)? 

Does this exist? If not, is it coming? Lastly, if not, can I compile it myself using Xcode?

Thanks!

**Comment by TingPing** [comment]
HexChat does not even support macOS in the first place. Its frustrating and a hassle to build and the end result is a buggy unsupported mess.

That said. It probably can build on arm, hexchat and all of its dependencies are very portable. Xcode is not used for any part of building though. You need a "unixy" build environment like macports, homebrew, etc.

**Comment by danielktdoranie** [comment]
Rude. Crappy atitude. If Hexchat runs on arm64 (it does, I run it on my Raspberry Pi w/ the "beta" 64-bit OS build) then it should work on "Apple Silicon" which is also arm64.

Just more neckbeard anti-apple mentality.

**Comment by TingPing** [comment]
> Just more neckbeard anti-apple mentality.

No, you are the rude one. I spent months of my life building and distributing HexChat on macOS. Never did I say *anything* about Apple or the OS.

*HexChat* is frustrating and a hassle to build there. *HexChat* is a buggy unsupported mess there.

**Comment by danielktdoranie** [comment]
No, u.

I note you don’t even respond to this:

“If Hexchat runs on arm64 (it does, I run it on my Raspberry Pi w/ the "beta" 64-bit OS build) then it should work on "Apple Silicon" which is also arm64.”

Nothing to say about that, eh? 

“I spent months of my life building and distributing HexChat on macOS. Never did I say anything about Apple or the OS.

HexChat is frustrating and a hassle to build there. HexChat is a buggy unsupported mess there.”

Sounds like you spent that time on INTEL macOS?

At any rate, who’s fault is this?
