### ISSUE TITLE
Certificate chains including DST Root CA X3 are rejected

### ISSUE THREAD

**Issue by sagamusix** [hexchat/hexchat#2632]
Today, Let's Encrypt's older DST Root CA X3 root certificate [expired](https://tech.slashdot.org/story/21/09/22/1752239/lets-encrypts-root-certificate-is-about-to-expire-and-it-might-break-your-devices). As many older devices still do not ship LE's new root certificate, they are currently applying a trick that causes certificates to contain two chains including their new (and still valid) certificate and an alternative chain including the old DST Root CA X3 root certificate. It seems like this upsets HexChat:

```
* Connecting to example.org (...)
* * Subject: /O=Digital Signature Trust Co./CN=DST Root CA X3
* * Issuer: /O=Digital Signature Trust Co./CN=DST Root CA X3
* * Subject: /O=Digital Signature Trust Co./CN=DST Root CA X3
* * Issuer: /O=Digital Signature Trust Co./CN=DST Root CA X3
* * Subject: /C=US/O=Internet Security Research Group/CN=ISRG Root X1
* * Issuer: /O=Digital Signature Trust Co./CN=DST Root CA X3
* * Subject: /C=US/O=Let's Encrypt/CN=R3
* * Issuer: /C=US/O=Internet Security Research Group/CN=ISRG Root X1
* * Subject: /CN=example.org
* * Issuer: /C=US/O=Let's Encrypt/CN=R3
* * Certification info:
*   Subject:
*     CN=example.org
*   Issuer:
*     C=US
*     O=Let's Encrypt
*     CN=R3
*   Public key algorithm: rsaEncryption (4096 bits)
*   Sign algorithm sha256WithRSAEncryption
*   Valid since Sep 30 15:28:31 2021 GM to Dec 29 15:28:30 2021 GM
* * Cipher info:
*   Version: TLSv1/SSLv3, cipher ECDHE-RSA-AES128-GCM-SHA256 (128 bits)
* * Verify E: certificate has expired.? (10)
```

As you can see, my bouncer's own certificate itself is not expired, but since earlier today I can no longer connect to it, presumably because of the expired root certificate. I also regenerated `cert.pem` that is shipped with HexChat just in case the new root certificate was missing (it isn't), but that also didn't help. For now I can ignore SSL errors but in the long run, I think HexChat's treatment of root certificates might have to chance. From my understanding, browsers have no issue with this certificate because there is one valid chain leading to the newer ISRG Root X1 certificate, and they ignore the chain leading to the expired DST Root CA X3 certificate.

**Comment by sagamusix** [comment]
Seems like OpenSSL 1.0.2 and older (which is exactly the version that ships with HexChat for Windows) is at fault: https://twitter.com/InspIRCdTeam/status/1443626719693479937

**Comment by RagingCactus** [comment]
And on the server side you can use the shorter `ISRG Root X1` certificate chain to make clients work without modification, but at the cost of older Android clients that will not trust that chain. Check the documentation of your ACME client on how to set a non-default preferred chain.

See https://community.letsencrypt.org/t/openssl-client-compatibility-changes-for-let-s-encrypt-certificates/143816 and https://letsencrypt.org/2020/12/21/extending-android-compatibility.html

**Comment by RePlay-be** [comment]
> Removing DST Root CA X3 from cert.pem that ships with HexChat is probably the easiest way of fixing this issue. It works for me.

For anyone wondering how to do this, the file can be found in the root folder of your HexChat installation (e.g. C:\Program Files\HexChat) and can be edited with just a text editor.

**Comment by BtbN** [comment]
Updating the openssl version shipped with HexChat on Windows would seem like a good idea either way, and would also solve this issue.
It's not even shipping the latest 1.0.2 version, and in turn has a whole bunch of known vulnerabilities.

**Comment by baronblod** [comment]
> And on the server side you can use the shorter `ISRG Root X1` certificate chain to make clients work without modification, but at the cost of older Android clients that will not trust that chain. Check the documentation of your ACME client on how to set a non-default preferred chain.

For Certbot version 1.6.0 and above you can add `--preferred-chain="ISRG Root X1"`.

**Comment by TingPing** [comment]
I've made a new release with updated OpenSSL + certificates.

**Comment by ksze** [comment]
It appears that the version in the Microsoft Store hasn't been updated yet?
