### ISSUE TITLE
built-in updater does not detect 2.16.0 update

### ISSUE THREAD

**Issue by FrostKiwi** [hexchat/hexchat#2642]
The built-in update check function (Help -> Check for Updates) on Windows does not detect the 2.16.0 update and does not prompt the ability to update.
This has been tested and confirmed on versions 2.14.1 and 2.14.3 and on the IRC channel #hexchat on server Libera by user "MetaNova" with the version 2.14.3.
The Nix* versions of Hexchat do not have the built-in update function, as the package manager takes care of that, as such only Windows is affected.

**Comment by TingPing** [comment]
I triggered it.
