### ISSUE TITLE
Downloading hexchat on macos is a mess

### ISSUE THREAD

**Issue by Akuli** [hexchat/hexchat#2649]
- If you click "Downloads" button on https://hexchat.github.io/ you find absolutely nothing for Mac
- If you go to github, click "Releases", and then click the "Downloads" link of the latest release, you end up at https://dl.hexchat.net/hexchat/ which only has hexchat 2.10 in the `osx/` folder
- `sudo brew install hexchat` doesn't work, because `brew` doesn't have hexchat
- `sudo port install hexchat` installs 2.14.2, which is a few years old but not unreasonably old.

There doesn't seem to be any way to get the latest hexchat on macos, unless you are ready to compile it yourself. If you don't want the latest hexchat, out of the 4 potential ways to install it that come to mind, only 2 work, and only 1 installs a reasonably new hexchat.

**Comment by Akuli** [comment]
And `sudo port install hexchat` doesn't even work :D

```
<ThePhilgrim> Lol, fucking useless.. Installed macports, ran the command for installing hexchat.. It installed 850 000 dependencies over 10 minutes.. including python 3.9 and 2.7 and a bunch of random stuff.. and after "building hexchat"..it failed
```

**Comment by TingPing** [comment]
Yeah, its not very good on macos, nobody really used or maintained it so it just isn't supported.

Feel free to get it packaged where-ever you want and contribute fixes here.
