### ISSUE TITLE
(documentation mismatch) Commands started with /exec do not timeout.

### ISSUE THREAD

**Issue by lockywolf** [hexchat/hexchat#2651]
According to the documentation, commands lauched with /exec should automatically get killed after 10 seconds: https://hexchat.readthedocs.io/en/latest/addons.html#exec

```
With Exec you can perform commands as if you ran them in the command line. The output will be printed at once, in the end of execution. If the command takes more than 10 seconds to complete, it gets aborted to avoid locking down HexChat. Usage:

/exec ping google.com
```

this is not the case, however. Either the documentation, or the behaviour are incorrect.

**Comment by TingPing** [comment]
I think this is a Windows vs Linux detail. Which platforms did you try?

**Comment by lockywolf** [comment]
Linux. Sorry, I do not have any Windows machines to try. :(

**Comment by TingPing** [comment]
Yeah that section is about the Windows plugin.

Linux has a bunch more powerful commands, see `/help` for all of these: EXEC, EXECCONT  EXECKILL, EXECSTOP, EXECWRITE

**Comment by lockywolf** [comment]
Would it be possible to correct the documentation then?

Something like: "Because the /exec plugin is loaded from a separate file on Windows, and is built-in in compile time on Unix, the behaviour is different. When loaded as a plugin it times out after 10 seconds, and when compiled in, it never times out"

**Comment by TingPing** [comment]
https://github.com/hexchat/documentation/commit/0d5ee6968fa0e2df0430fb0ba79592856d19bffe
