### ISSUE TITLE
[Bug] HexChat doesn't update Certificates. (Even after 3 reinstalls and deleting of all related files i could find)

### ISSUE THREAD

**Issue by Speiger** [hexchat/hexchat#2661]
Hello I had to deal with this issue more then 4 times now and had to work with RNG to fix it every single time.
This is the time where I don't care about SSL anymore and disable it, but this shouldn't be an issue...

My Problem (SSL Related):
```
* Connecting to irc.esper.net (51.255.119.242:6697)
* * Subject: /C=US/O=Internet Security Research Group/CN=ISRG Root X1
* * Issuer: /C=US/O=Internet Security Research Group/CN=ISRG Root X1
* * Subject: /C=US/O=Let's Encrypt/CN=R3
* * Issuer: /C=US/O=Internet Security Research Group/CN=ISRG Root X1
* * Subject: /CN=*.esper.net
* * Issuer: /C=US/O=Let's Encrypt/CN=R3
* * Subject: /CN=*.esper.net
* * Issuer: /C=US/O=Let's Encrypt/CN=R3
* * Certification info:
*   Subject:
*     CN=*.esper.net
*   Issuer:
*     C=US
*     O=Let's Encrypt
*     CN=R3
*   Public key algorithm: rsaEncryption (2048 bits)
*   Sign algorithm sha256WithRSAEncryption
*   Valid since Sep 20 08:34:36 2021 GM to Dec 19 08:34:35 2021 GM
* * Cipher info:
*   Version: TLSv1.3, cipher TLS_AES_256_GCM_SHA384 (256 bits)
* Connection failed (certificate has expired.? (10))
*
```

So basically certificate is outdated. Congrats. Why isn't it automatically updated?
Why can't a reinstall fix this issue? I had random luck deleting all Files that I could find on Hexchat that it would update certificates.
After the 5th reinstall though...

Yeah this time my RNG luck was running out.

And I already tried all the methods that I was able to find with google foo, and this point I am rage quitting and dropping SSL.
And before I become so negative that it will result in a random ban I am asking you: Why cant this software update itself automatically even after 3 reinstalls?

**Comment by MAGICCC** [comment]
Looks like espernets ssl cert got expired

**Comment by Speiger** [comment]
@MAGICCC 
> So basically certificate is outdated. Congrats. Why isn't it automatically updated?

**Comment by MAGICCC** [comment]
Blame espernet and not Hexchat? A client cant upgrade server certs

**Comment by Speiger** [comment]
@MAGICCC I think multiple users using Espernet and a 24 hour wait before retrying the regaining of the certificate clearly shows that espernet isn't at fault. 
On top of that: Why is there no "manual" update button of certificates or no indicator why certificates aren't updated?
Like any indicator why the issue shouldn't be on Hexchat side?

**Comment by Speiger** [comment]
Just to give a small update:
Logged into anarchy.esper.net which a friend was using at the same time and couldn't connect. According to him the certificate updated for him a couple days ago. So its not a "esper.net" problem like @MAGICCC tries to blame shift but HexChats problem because clearly other connections don't have the issue.

**Comment by Speiger** [comment]
And Just managed to log into esper.net with the Konversation Client without any issues on the second try because I was new to that client.
So @MAGICCC (and yes i will ping you on every message where its clear that esper.net isnt the issue) clearly it isn't espernets fault but HexChats fault.

**Comment by Speiger** [comment]
Update again.
Leaving the original title so the devs finally deal with this issue.
Certificates on Esper.net are outdated. And HexChat basically doens't allow you to join the connection unless you find a very hidden setting.
With VERY BAD information on what is actually going on.

I tried using Konversation which "Promts" you "Hey SSL Certificates are outdated so you might not have a secure connection, do you want details? Do you want to continue? Do you want to cancel?"
![konversation_figezt6v2C](https://user-images.githubusercontent.com/2556269/146828612-a9287071-ca96-4b51-90ee-eeb28f0d3a80.png)

Sorry but HexChat, If you basically Block me from joining a chat or deciding for me I have to find a very hidden setting in a server select to continue on and basically get a VERY Obscure message that has no indication on what is going on (unless you are very experienced in that field) makes this a BAD CLIENT.

Bugfix: Add A client like Konversation that tells you what is wrong and that asks you if you want to continue and maybe if it is a "Per session setting" or "Always Setting".

For me this results into 2 things...
- 1: I Drop HexChat bad design completely and Jump to a Better IRC Client.
- 2: I Disable all SSL Checks by default so I dont have to deal with your very unfriendly solution with bad SSL Certificates...

**Comment by Speiger** [comment]
Oh yeah and to be more assholerish then HexChats design Choices @MAGICCC

**Comment by MAGICCC** [comment]
Good thing I am not a dev here.

>Certificates on Esper.net are outdated. And HexChat basically doens't allow you to join the connection unless you find a very hidden setting.

![image](https://user-images.githubusercontent.com/3279213/146829457-6b3a10e0-4059-4b0b-8563-99e8c083443f.png)


I was trying to help you but insulting devs and me is just a nogo. Opensource is always a give and take.

**Comment by TingPing** [comment]
There is a misunderstanding here.

The error is that espernets certificate expired, it is their job to renew it and serve a non-expired certificate.

I agree HexChat could show better and more clear error information.
