### ISSUE TITLE
/execwrite aka cmd_execw (common/outbound.c)  echos parameters

### ISSUE THREAD

**Issue by orcus-de** [hexchat/hexchat#2666]
/execwrite aka cmd_execw (common/outbound.c)  echos parameters unconditionally at client textbox using PrintText

This looks like some (forgotten?) debug-output:
I would normally expect some -d (or other debug option) to explicitly echo input-data.
In case the current behavior should not be changed for some unknow reasons - as an alternative some -q (quiet) would help me too.

Background:
I'm using /exec to run external commands and want to feed in data using /execwrite (to avoid parameter expansion by the shell if being added to /exec directly).
As the run tool is used by some more users, its a bit unexpected for them to get the used parameters shown at the textbox.

**Comment by orcus-de** [comment]
Idk if this would help working on the topic - I've tested my two suggested variants by modifying
common/outbound.c accordingly - where adding and handling an optional -q parameter would
keep up compatibility with the previous version, but would allow users to suppress the textbuffer
output if needed ...

```
static int
cmd_execw (struct session *sess, char *tbuf, char *word[], char *word_eol[])
{
	int len;
	char *temp;
	exec_check_process (sess);
	if (sess->running_exec == NULL)
	{
		EMIT_SIGNAL (XP_TE_NOCHILD, sess, NULL, NULL, NULL, NULL, 0);
		return FALSE;
	}

#if 0
	// variant 1 - use a switch -d to show debug output at the text buffer
	// this will change the default behavior compared to previous version
	// orcus - only echo to textbuffer if -d being used
	if ( 0==strcmp (word[2], "-d") )
	{
		len = strlen(word_eol[3]);
		temp = g_strconcat (word_eol[3], "\n", NULL);
		PrintText(sess, temp);
	}
	else
	{
		len = strlen(word_eol[2]);
		temp = g_strconcat (word_eol[2], "\n", NULL);
	}
#else
	// variant 2 - use a switch -q to quiet/suppress output at the text buffer
	// this will keep the default behavior compared to previous version
	// orcus - only suppress echo to textbuffer if -q being used
	
	if ( 0==strcmp (word[2], "-q") )
	{
		len = strlen(word_eol[3]);
		temp = g_strconcat (word_eol[3], "\n", NULL);
	}
	else
	{
		len = strlen(word_eol[2]);
		temp = g_strconcat (word_eol[2], "\n", NULL);
		PrintText(sess, temp);
	}
#endif
	write(sess->running_exec->myfd, temp, len + 1);
	g_free(temp);

	return TRUE;
}
```

**Comment by TingPing** [comment]
Feel free to open an MR adding `-q`. Just add it to the help string too.

**Comment by orcus-de** [comment]
done - [https://github.com/hexchat/hexchat/pull/2675]()
