### ISSUE TITLE
#gnome doesn't show up in channel list

### ISSUE THREAD

**Issue by raffaem** [hexchat/hexchat#2682]
When I list the channels in GIMPNet, #gnome doesn't show up:

![image](https://user-images.githubusercontent.com/54762742/155143137-229ad2c1-a324-479b-8192-85c92ea4845a.png)

After I manually join into it with `/join #gnome` and re-download the channel list, it then shows up:

![image](https://user-images.githubusercontent.com/54762742/155143307-7d8170db-16dd-4c20-a10d-af3d9e02eff6.png)

**Comment by TingPing** [comment]
The `+s` mode is secret I believe so its hidden from the list. It reduces spam.
