### ISSUE TITLE
Error printed when no notification service installed

### ISSUE THREAD

**Issue by 0pLuS0** [hexchat/hexchat#2684]
Hello,

I'm compiling 2.16.1 in Slackware 15.0, when I run hexchat it says in the window;

```Failed loading notification plugin: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files```

In Slackware 14.2 I was running 2.16.0 and I never saw this message, but I also had xfce-notifyd installed, is this related to notifications that xfce-notifyd as an example would provide, OSD?

THANKS

**Comment by TingPing** [comment]
> In Slackware 14.2 I was running 2.16.0 and I never saw this message, but I also had xfce-notifyd installed, is this related to notifications that xfce-notifyd as an example would provide, OSD?

Yes exactly.

Maybe this could be changed to not print it. It should be harmless.

**Comment by 0pLuS0** [comment]
I have it fixed now, I use xfce4-notifyd, I compiled it and it's needed deps by hand, I don't have xfce installed, so I could have notifications in Openbox.

I had a previous /usr/share/dbus-1/services/org.xfce.xfce4-notifyd.Notifications.service file in Slackware 14.2

[D-BUS Service]
Name=org.freedesktop.Notifications
Exec=/usr/lib64/xfce4/notifyd/xfce4-notifyd

I put that in now for Slack 15.0 and all good!

THANKS
