### ISSUE TITLE
Python 2 plugin fails to load any addon on HexChat v2.16.1

### ISSUE THREAD

**Issue by tNbh2KonoPZ7IonJYdt1d4je1lnoOXNG** [hexchat/hexchat#2690]
## Issue
The Python function `open()` supports the optional `encoding` argument in [version 3](https://docs.python.org/3/library/functions.html#open), but not in [version 2](https://docs.python.org/2/library/functions.html#open). Passing it [here](https://github.com/hexchat/hexchat/blob/133f62806441a5db1156653aa1f077d2e8deeb34/plugins/python/python.py#L149) since commit 6fd8a8f9bf48562fbbc42f908321b67d436c097e (2021-10-02) to fix issue #2634 causes loading **any** Python 2 addon to fail:
<details>
<summary>log</summary>

```
Python interface loaded
Failed to load module: 'encoding' is an invalid keyword argument for this function
Traceback (most recent call last):
  File "<init code for '_hexchat_embedded'>", line 149, in loadfile
TypeError: 'encoding' is an invalid keyword argument for this function
```
</details>

## Fix
This can be fixed by only passing `encoding` for Python 3:
<details>
<summary>patch</summary>

```diff
--- plugins/python/python.py.bak
+++ plugins/python/python.py
@@ -149,2 +149,6 @@
-            with open(filename, encoding='utf-8') as f:
-                data = f.read()
+            if sys.version_info[0] == 2:
+                f = open(filename)
+            else:
+                f = open(filename, encoding='utf-8')
+            data = f.read()
+            f.close()
```
</details>

## Workaround
The following workaround was successfully tested on Ubuntu 20.04.4 LTS as well as Windows 10 and can be used to avoid building from source (again) or waiting for the next release:
<details>
<summary>Linux</summary>

```bash
cd /usr/local/lib/x86_64-linux-gnu/hexchat/plugins
own=$(stat -c %U:%G python.so)
mod=$(stat -c %a python.so)
off=$(LANG=C grep -Pboam1 ", encoding='utf-8'" python.so | cut -d":" -f1)
sudo cp python.so python.so.bak
printf "                  " | sudo dd of=python.so bs=1 seek=$off conv=notrunc status=none
sudo chown $own python.so
sudo chmod $mod python.so
```
</details>
<details>
<summary>Windows</summary>

1. Open `%PROGRAMFILES%\HexChat\plugins\hcpython2.dll` in a hex editor (such as [HxD](https://mh-nexus.de/en/hxd/)).
2. Replace (Ctrl+R) `, encoding='utf-8'` with **18** spaces (see below).
3. Save the file.
```
Please copy the following line (Markdown collapses spaces between backticks):
                  
```
</details>

**Comment by TingPing** [comment]
We still want to decode it as UTF-8 on Python 2 I think.

**Comment by DjLegolas** [comment]
I think to solve this, you should open the file in binary mode, and decode it to `UTF-8`.
Opened a MR.
