### ISSUE TITLE
Add options in the installer for taskbar/desktop shortcuts

### ISSUE THREAD

**Issue by Felipefpl** [hexchat/hexchat#2699]
It'd be a nice thing to allow us to choose if in the end of the installation we'd like to create options to:

Add a shortcut on desktop/taskbar/start menu or then add none, it's a small nice feature that is surely missed.

**Comment by TingPing** [comment]
A script can easily move the window to a specific display. I'm not sure it really makes sense as an option.

**Comment by DjLegolas** [comment]
@TingPing @Felipefpl - from what I have seen in the InnoSetup script, there are several points to this:
* the start manu is being created when installing in non-portable mode
* the desktop icon and quick launch are not being created at all
* adding shortcuts to quick launch folder, does not add it to the start bar
what do you think is the best solution for this?
is it a good-enough behavior?

**Comment by Felipefpl** [comment]
The best solution would be the ability to create a shortcut to the 3 places: quick launch/desktop/taskbar, desktop is the main option of course since most of apps create shortcuts for it, ;)

**Comment by DjLegolas** [comment]
It took too long to complete... 🤦‍♂️ 
MS removed in windows 10 the ability of programs to pin themselves to taskbar...

Anyway, can you check the MR @Felipefpl? Try the installer from the artifacts.

**Comment by Felipefpl** [comment]
Thank you for the additions but where are the artifacts? I searched github/hexchat's site and i didnt find anything except the common installer.

**Comment by DjLegolas** [comment]
You can find the installer artifacts in the Windows build test:
https://github.com/hexchat/hexchat/actions/runs/2316542167

**Comment by Felipefpl** [comment]
Thank you for the link, i downloaded, installed it and it worked except it didnt create a shortcut on taskbar, i'm on win7 x64 and i got the x86 version.

**Comment by DjLegolas** [comment]
You have in there 2 installers, one for x86 and one for x64. Make sure you have downloaded the correct one :upside_down_face:
Regarding pinning to taskbar, I'm using a third party utility that should work on win7...
But @TingPing don't want to use it anyway so I'll have to find another way to do it.
Maybe in a later MR, as pinning to taskbar is the very easy.

**Comment by Felipefpl** [comment]
I dont understand why using a 32 bit installer would cause problems, never had this problem with other programs before.

I tried 64 bit installer and it didnt work but this time i clicked on details while installing and i noticed the installer didnt download syspin. That must be the reason that the taskbar's shortcut isnt installed.
