### ISSUE TITLE
python 2.7 script not loaded

### ISSUE THREAD

**Issue by andreagonzalez2k** [hexchat/hexchat#2728]
I have a python 2.7 script that worked fine in 2.16.0 version. In 2.16.1 version it does not work. In changelog I have seen that in the last version it has been fixed "Python scripts not being opened as UTF-8". Hexchat installed to execute python 2 scripts.

For test purposes I use a simple script saved in a file encoded as ANSI in the addons directory:

```
__module_name__ = "respuesta_automatica"
print "%s cargado" % __module_name__
```

The log in the hexchat script says:

```
 Lua version 1.3/5.1 loaded.
 Python interface loaded
 Failed to load module: 'encoding' is an invalid keyword argument for this function
 Traceback (most recent call last):
   File "<init code for '_hexchat_embedded'>", line 149, in loadfile
 TypeError: 'encoding' is an invalid keyword argument for this function
```

It seem that it has just been solved in
https://github.com/hexchat/hexchat/commit/6da8f97e37f1eb57c1dcb9fc094f386385dae22b

four months ago but it is not solved yet in the las release version...

does anyone have any clue to fix this without unistalling 2.16.1 and install 2.16.0 version?

**Comment by TingPing** [comment]
You can download the newest version of the installers here: https://github.com/hexchat/hexchat/actions/runs/2899543476

(I do also recommend porting the script to Python 3. Version 2 is dead and will be removed eventually)

**Comment by andreagonzalez2k** [comment]
Thanks
