### ISSUE TITLE
crash hexchat assert faiure:tcache_thread_shutdown(): unaligned tcache chunk detected

### ISSUE THREAD

**Issue by jeready** [hexchat/hexchat#2732]
occurs in threading Timer

**Comment by TingPing** [comment]
Unless you have a more detailed backtrace or other information this isn't actionable.

**Comment by jeready** [comment]
Executable Path
   /usr/bin/hexchat
Package 
   hexchat 2.16.0-4build1
Problem Type
    crash
Title
    hexchat assert failure:tcache_thread_shutdown(): unaligned tcache chunk detested
Apport Version
    2.20.11-ubuntu82.1
Architecture
    amd64
AssertionMessage
    tcache_thread_shutdown(): unaligned tchache chunk detected
CasperMDSCheckResult
    pass
CrashCounter
    1
CurrentDesktop
    ubuntu:GNOME
Date
Wed sep 14 14:15:39 2022
DistroRelease
    Ubuntu 22.04
InstallationDate
    Installed on 2022-06-14
ProcCwd
    /home/jeready
ProcEnviron
   PATH=
   XDG_RUNTIME_DIR=<set>
   LANG=en_us.URF-8
   SHELL=/bin/bash
StacjtraceAddressSignature
   /usr/bin/hexchat:6/usr/lib/x86_65-linux-gnu/lib.so.6+7f3:/usr/lib/x86_64-linux--gnu/libc.so.6+616f6/usr/lib......
Tags
   wayland session jammy

**Comment by jeready** [comment]
hope this helps

would be nice if I knew hot to just copy and paste this info :)
