### ISSUE TITLE
Problematic behavior during search from Channel List

### ISSUE THREAD

**Issue by stefanos82** [hexchat/hexchat#2742]
I press the `Download List` button and searched for Ardour.

![image](https://user-images.githubusercontent.com/1777466/196201948-a06eaff4-4399-4641-aa10-72e24a5408ba.png)

Seems like it cannot find it nor includes it in downloaded list for some reason.

![image](https://user-images.githubusercontent.com/1777466/196202733-5ffaa5b1-e767-4ae3-b566-368df658708e.png)

**Comment by TingPing** [comment]
The channel has mode `+s`, secret, so does not show up in list.

https://libera.chat/guides/channelmodes
