### ISSUE TITLE
SSL routines::unexpected eof while reading

### ISSUE THREAD

**Issue by stephenbond** [hexchat/hexchat#2767]
Hi,

After an Ubuntu update, Hexchat fails to connect to some networks with the error:

`Connection failed ((167772454) error:0A000126:SSL routines::unexpected eof while reading)`

Ubuntu 22.04 LTS
Hexchat 2.16.0

I think it was when libsasl got an upgrade that it broke...

**Comment by TingPing** [comment]
HexChat doesn't use libsasl.

Anyway I don't think this is actionable at all. The connection is disconnecting.
