### ISSUE TITLE
User Commands truncate after 3 arguments

### ISSUE THREAD

**Issue by dalepsmith** [hexchat/hexchat#2776]
A user command like
`privmsg nick one two three four`
only sends
`privmsg nick one`

As if it truncates the command after the third whitespace delimited word.

**Comment by dalepsmith** [comment]
Never mind. Needed a colon as in:
`privmsg nick :one two three four`

**Comment by TingPing** [comment]
This is a detail of the IRC protocol:

- https://modern.ircdocs.horse/#parameters
- https://modern.ircdocs.horse/#nick-message

**Comment by dalepsmith** [comment]
On 4/4/23, Patrick ***@***.***> wrote:
> This is a detail of the IRC protocol:
>
> - https://modern.ircdocs.horse/#parameters
> - https://modern.ircdocs.horse/#nick-message

Yeah, vague memories of hacking on a bot years ago reminded me.

-Dale
