### ISSUE TITLE
Whois sometimes is required to be done inside /query to show Idle time.

### ISSUE THREAD

**Issue by ComputerTech312** [hexchat/hexchat#2783]
So sometimes when i whois a nick, and look for idle time, the idle line is completely missing, the only way i may view the idle time is if i do a /query with said nick and it'll show the idle time then. I've only tested this on Windows Hexchat, not sure of the Linux version yet.

**Comment by TingPing** [comment]
If the idle time is given or not is up to the server. Where it is ran from means nothing.
