### ISSUE TITLE
Python 2.7 removed in Windows GitHub Actions runner, Windows builds failing

### ISSUE THREAD

**Issue by nattofriends** [hexchat/hexchat#2792]
Python 2.7 was removed from windows-2019 in https://github.com/actions/runner-images/pull/7646, so Windows builds in GitHub Actions are failing. If there's no actual usage of Python 2.7 in Hexchat any more, maybe just [removing these lines](https://github.com/hexchat/hexchat/blob/master/.github/workflows/windows-build.yml#L45) is enough?

**Comment by TingPing** [comment]
We do still build a Python 2.7 plugin. It might be time to retire it though.

More things that need to be removed:

- python2 bits here: https://github.com/hexchat/hexchat/blob/master/win32/installer/hexchat.iss.tt
- https://github.com/hexchat/hexchat/blob/master/win32/copy/copy.vcxproj#L68
- python2 project files: https://github.com/hexchat/hexchat/tree/master/plugins/python

**Comment by TingPing** [comment]
Removed in a1f154cd5ee63ec6b9ac154b8dc6d5a5d97c2c28
