### ISSUE TITLE
Changing hexchat.conf at load causes errors

### ISSUE THREAD

**Issue by rozzrr** [hexchat/hexchat#2798]
I've been experiencing a problem where when I run up hexchat its fine, but when I change the hexchat.conf file to update the nicknames when I first launch it, I get permission errors and a further error message box that just alerts me there is an error. the config file is fine and will load. If I close down the error warnings instead of pressing 'ok' it also launches ok. it just seems a bit weird behaviour that when i change the config file, load the application, it just seems to have a bit of a panic. 

the reason in which i am changing the nicknames at runtime is because i store the conf file in the users roaming profile, so I need to populate the user nick names as they are managed by a gpo which allocated blank nick names in the file as its generic. 

i just don't be able to seem to escape these errors when changing the .conf file. any help is appreciated :)

**Comment by TingPing** [comment]
HexChat doesn't reload its configuration file at runtime. I have no idea what error you speak of but it doesn't matter because it will do nothing.

You can use the `/set` command to change settings while HexChat is running.
