### ISSUE TITLE
Channel list: cannot maximise

### ISSUE THREAD

**Issue by mrx23dot** [hexchat/hexchat#2800]
There are ton on info in that window, would be great to be able to have a maximize button.

Otherwise I have to do it manually.

![2023-08-29_213323_Yl](https://github.com/hexchat/hexchat/assets/4163396/a6392b0e-1537-4f1e-8208-9c7ebadc34b8)

**Comment by TingPing** [comment]
This is pretty standard design used throughout GTK applications.

Dialogs are transient windows, tied to a main window, and don't have features like maximize.
