### ISSUE TITLE
Default Installation Settings Can't Connect to Undernet

### ISSUE THREAD

**Issue by dsnvwlmnt** [hexchat/hexchat#2817]
Until you unselect the "_Use SSL for all the servers on this network_" setting, HexChat will forever fail to connect to Undernet. Apparently Undernet doesn't use SSL, but I'm no expert.

In any case, I'd suggest:

a) unselect this option for Undernet in the base installation; or

b) if the issue is deeper than I know, at least pointing the end user in any kind of direction towards turning off that setting, with security warnings if appropriate

**Comment by TingPing** [comment]
Was fixed by https://github.com/hexchat/hexchat/commit/6155c18315556a4ee4e59c3f61a0d95b96deae41

**Comment by TingPing** [comment]
Actually the default config there doesn’t even specify ssl, maybe that was changed earlier.

**Comment by dsnvwlmnt** [comment]
FWIW I'd tried both us.undernet.org & irc.undernet.org. Neither worked until I turned off the "Use SSL" setting.
