### ISSUE TITLE
URL encoded links can cause a crash when opening (regression?)

### ISSUE THREAD

**Issue by evilantishad0w** [hexchat/hexchat#2820]
https://github.com/hexchat/hexchat/issues/2687

Example link crashes HexChat 2.16.0

**Comment by TingPing** [comment]
You can grab an updated installer here: https://github.com/hexchat/hexchat/actions/runs/6761549784

**Comment by evilantishad0w** [comment]
Using Linux Mint, 2.16.0 is apparently the latest version available via apt..  Using the jammy archive.

**Comment by TingPing** [comment]
You can install an up to date Linux build from here: https://flathub.org/apps/io.github.Hexchat
