### ISSUE TITLE
HexChat crashes when network connection dies.

### ISSUE THREAD

**Issue by tomek** [hexchat/hexchat#30]
I was able to reproduce this problem - basically, when my net disconnects (my ISP enforces dc every 24h) Hexchat crashes and I need to kill it in task manager. I'm using Hexchat 2.9.1 x86 on Win7sp1:

```
HexChat 2.9.1

A multiplatform IRC Client

OS: Windows 7 [1.87GHz]
Charset: CP932 GTK+: 2.16.6
XChat Revision: r1521
Compiled: Jul 27 2012
Portable Mode: No
Build Type: x86
```

When I was using Xchat-WDK it never happened to me.

**Comment by Fixer-007** [comment]
Why this still not fixed in 2016? What is the excuse?

**Comment by Poorchop** [comment]
>What is the excuse?

The fact that this is an open source project and the developers aren't being paid a cent for their work. It's a labor love any everyone is expected to contribute. You should very well be asking the same question of yourself.

**Comment by linkin-park** [comment]
still same
