### ISSUE TITLE
Only one instance by default not working on Windows 8

### ISSUE THREAD

**Issue by mloskot** [hexchat/hexchat#309]
First, I'm not sure what is the current status of this feature, if it's supported but needs some improvements or it's been removed. I'm using HexChat 2.9.4 (64-bit) and I have only tested  the issue on Windows 8, I'm not sure if it applies to other Windows versions.

The [Improved HexChat default settings](https://www.bradicaljh.com/improved-hexchat-default-settings/) news item says

> Only one instance of HexChat can run at once by default

But, the 2.9.4 [changelog](http://www.hexchat.org/home/changelog) says

> disable faulty one instance option

The HexChat.conf file installed and copied to user's profile does not specify the [gui_one_instance](http://www.hexchat.org/tips-tricks/set-variables) either.

Nevertheless, multiple HexChat launches lead to multiple instances, what is a bit unfortunate, especially if one wants to operate HexChat pinned to taskbar to open the application window.

The issue  #80 may be related to this problem too.

**Comment by DamonGant** [comment]
I just ran into this issue, are there any plans to get this back in?

**Comment by Arnavion** [comment]
@DamonGant See #252 that this is a duplicate of.
