### ISSUE TITLE
URLs not loading all the time when gui_url_mod is 0

### ISSUE THREAD

**Issue by AlannahDaw** [hexchat/hexchat#363]
Sometimes when left clicking an URL it does not load, even though gui_url_mod is set to 0. 

I thought it might have just been something that only I experienced, but today I heard more anecdotal evidence that it doesn't always work for others.

Steps to reproduce:
/set gui_url_mod 0
Click lots of links until one fails.

**Comment by MightyPork** [comment]
It is not a bug [explains how it's broken and a possible workaround]

really? Why not admit it's a bug at least?
