### ISSUE TITLE
Hexchat autoreconnects on /kill

### ISSUE THREAD

**Issue by apeiron** [hexchat/hexchat#365]
Don't do this. If an oper uses /kill it means they want the client to stay disconnected. Reconnecting automatically only yields an irate oper.

**Comment by ajloveslily14** [comment]
it can be disabled on the client side with /set IIRC

**Comment by apeiron** [comment]
On Sat, Feb 06, 2016 at 22:16:53 -0800, ajloveslily14 wrote:
> it can be disabled on the client side with /set IIRC

It shouldn't even be an option. If an oper /kills you, they want you
gone. Reconnecting only makes it worse.

-- 
Thanks,
Chris

**Comment by Arnavion** [comment]
The client is doing nothing the user can't do themselves.

If the operator wants the client to stay disconnected, then they should do that in addition to killing their current connection.

**Comment by TingPing** [comment]
@Arnavion I think it is pretty reasonable for the client to not auto-retry..

**Comment by apeiron** [comment]
On Sun, Feb 07, 2016 at 13:21:19 -0800, Arnav Singh wrote:
> The client is doing nothing the user can't do themselves.
> 
> If the operator wants the client to stay disconnected, then they should do that in addition to killing their current connection.

Judging by your dismissal of this issue, I'm guessing you're not, and
never have been, an IRC oper. I have been. A /kill means "get off this
network". It does *NOT* mean "please feel free to reconnect
immediately". It is poor etiquette and would only serve to enrage an
oper further.

Please consider others' points of view.


-- 
Thanks,
Chris

**Comment by ajloveslily14** [comment]
> Judging by your dismissal of this issue, I'm guessing you're not, and
> never have been, an IRC oper. I have been. A /kill means "get off this
> network". It does *NOT* mean "please feel free to reconnect
> immediately". It is poor etiquette and would only serve to enrage an
> oper further.
> 
> Please consider others' points of view.


Seems pretty subjective to me. If you want someone off of the network k-line them, else there is no point other than to cause a minor inconvenience

**Comment by Arnavion** [comment]
>A /kill means "get off this network".

No, it means "I want you to disconnect." and that is exactly what it does. Even if HC did not auto-retry, someone would just write a script to do it anyway. In fact such scripts already exist for rejoining channels on being kicked, requesting unban after being banned, etc.

/kill does not mean "I want you to stay disconnected." You have another command for that. Use it.

**Comment by TingPing** [comment]
It isn't about helping the network it is about users accidentally being more severely punished because their client keeps reconnecting, I know it is silly that is even a thing but multiple users have brought it up.
