### ISSUE TITLE
HexChat 2.9.4 Linux - No Tcl plugin

### ISSUE THREAD

**Issue by Alcheri-zz** [hexchat/hexchat#391]
It's a bit like a three legged horse.

Why is the *nix version missing a Tcl plugin?

**Comment by KnuX** [comment]
Hm... it crashes on my 32bit setup too... dll is loaded by if I try to load any .tcl file, HexChat crashes.

**Comment by tomek** [comment]
well @KnuX I'm now even supprised, that plugin wasn't updated for over 4 years - you should switch to python/lua

**Comment by dstasinski** [comment]
On Feb 17, 2018 12:06 PM, "Tomasz Szczepański" <notifications@github.com>
wrote:

well @KnuX <https://github.com/knux> I'm now even supprised, that plugin
wasn't updated for over 4 years - you should switch to python/lua


Yes it has...

https://www.saidsimple.com/daniel/blog/117917/hexchat-tcl-plugin-for-linux

Daniel

**Comment by tomek** [comment]
fancy, didn't know about it. but still that's only linux plugin, not for windows. I don't have project files I used before (which I cherry-picked from some ancient HC revision) so you'd need to try to compile it yourself.

**Comment by Alcheri** [comment]
@dstasinski Thanks you for the link. I use HexChat exclusively in a Linux guest VM on Windows 10 so this finally gives me the chance to test and use Tcl code. The HexChat developers (from memory) were only ever interested in Perl and Python so the Tcl plugin was always going to be dropped.
