### ISSUE TITLE
Proxy not working with tor correctly

### ISSUE THREAD

**Issue by fake2013** [hexchat/hexchat#392]
if i'm connecting to a ssl server thought tor. i get an error ssl handshake failed.
i looks like it trying to connect to tor using ssl

i something get cannot find host maybe i misspelled it.
it is because it does a dns lookup before connecting to tor
so it cannot find the server (the server can only be seen using tor)

FYI: it works about 20% of the time (odd)

**Comment by sryze** [comment]
I have the same problem. Everything worked for ages but a week or two ago it just stopped connecting. I'm using HexChat 2.9.6 on Ubuntu 14.04.

**Comment by TingPing** [comment]
>Everything worked for ages but a week or two ago it just stopped connecting

Meaning the issue is entirely external to HexChat. Most tor nodes are far from reliable. Freenode recently shut theirs down because of abuse.

**Comment by ChrisRonaasen** [comment]
Still happening on 2.12 on Linux Mint 17.3 with all the normal settings. Weird...

**Comment by Kreyren** [comment]
same issue on hexchat 2.14.3

```
* Looking up ******.onion
* Looking up 127.0.0.1
* Connecting to 127.0.0.1 (127.0.0.1:9050)
SOCKS Proxy failed to connect to host (error 5).
 Proxy traversal failed.
* Stopped previous connection attempt (351709)
```

**Comment by usernamer-git** [comment]
Same here, but what i found reading, seems most Tor exit nodes do not support connection to IRC due to prevent abuses. Thus you have to wait for Tor to cycle through nodes until it find one that supports IRC and then build a route to it.
https://labs.parabola.nu/issues/2045
