### ISSUE TITLE
Immediate crash after clicking Connect in network list

### ISSUE THREAD

**Issue by antivirtel** [hexchat/hexchat#442]
I'm using Windows 7 x86 (32 bits) and I wanted to try the HexChat. 

Unfortunately, when I hit the Connect button in the channel list, the application instantly crashes. 

Selecting other network/nick doesn't help.
I've tried also delete the %appdata%\HexChat dir, but the result is the same.
Tried the latest 2.9.4 stable & 2.9.5 test build - the same.
I've installed VC++ 2010.

Is there any debug option, crash/error log?

(Ps. I've not installed Perl & Python or any spell check, and it is working on Linux).

**Comment by fordcars** [comment]
Lucky me, yes definitely crashes when Perl is unchecked, but Python and friends is in custom install

**Comment by jordan-wright** [comment]
I was also able to replicate this issue with the latest version of Hexchat. By checking "Python", the application would crash upon clicking "Connect".

Reinstalling with neither language support fixed the issue.
