### ISSUE TITLE
Changing tab keyboard shortcuts

### ISSUE THREAD

**Issue by davidgomes** [hexchat/hexchat#46]
It would be nice to have Ctrl+Tab and Ctrl+Shift+Tab to go forward and backward a tab (respectively).

Alt+Right/Left to do the same thing would be nice too.

Thank you.

**Comment by josephernest** [comment]
@davidgomes  @TingPing 

For future reference, "Change page +1 (Relative)" is this feature:

![image](https://user-images.githubusercontent.com/6168083/99900638-236b4c00-2cb1-11eb-8758-cacc50b8e99c.png)
