### ISSUE TITLE
Crash when changing channels too quickly

### ISSUE THREAD

**Issue by BrandonDusseau** [hexchat/hexchat#535]
I generally hold Ctrl+PgUp to clear all of the notifications on the channel tree. Since the update from 2.9.4, it seems that doing this for too long will cause the application to crash.

Expected result: Channels switch with no issue
Actual result: Application crashed with "Hexchat has stopped working"
.
Application information:
Version: 2.9.5
Compiled: Apr  1 2013
Portable Mode: No
Build Type: x64
OS: Windows 7
Charset: CP1252

Edit: It may help to mention that all of my crash experience thus far has occurred within an RDP session. It even crashed when I brought the RDP session to the foreground, and when I opened my start menu. The crashes have not occurred while working locally on the same machine/account.

Edit: I've attached a screenshot of one of the crashes. It may or may not be worth noting that you can see here that the buffer contains two different channels (it may have been in the middle of updating when it crashed), and the user list is for neither of the channels. My roommate suggests that it could be something about Windows XP's RDP implementation that's causing the issue, because I have not been able to reproduce it locally or via RDP on Windows 7.

![Capture](https://f.cloud.github.com/assets/3901864/375478/21c0435c-a3bf-11e2-83dd-c288fd4c28a8.PNG)

**Comment by TingPing** [comment]
Closing this since the various RDP issues are upstreams problems.

**Comment by Arnavion** [comment]
@TingPing Can you add bug URLs if there are any?

**Comment by TingPing** [comment]
> @TingPing Can you add bug URLs if there are any?

Only related issue I found is: https://bugzilla.gnome.org/show_bug.cgi?id=704731
