### ISSUE TITLE
Log folder location as an option

### ISSUE THREAD

**Issue by s4wny** [hexchat/hexchat#650]
It would be great if you created a option for where to save the log files.

For example I have a backup disk (`B:\logs\IRC\`) there I want to save my logfiles instead of the default location `%APPDATA%\HexChat\logs`.

**Comment by survivor303** [comment]
I suggest that this comes to options menu, i still not understand why it isnt there already, one of the basic things.

Sure users has differend ways how to want archive these kind of files, so programs need to respect that and not force users doing things how somebody else want to do it, that isnt freedom.

**Comment by TingPing** [comment]
@survivor303 I'm not sure what you are referring to, this issue already concluded this feature already existed when opened.

**Comment by survivor303** [comment]
@TingPing existed where? In the options? What version exactly has it? Linux/windows?

**Comment by TingPing** [comment]
https://github.com/hexchat/hexchat/issues/650#issuecomment-19788046

**Comment by survivor303** [comment]
@TingPing does it understand vfs mounts?

**Comment by TingPing** [comment]
It just calls `open()`, try it and see.
