### ISSUE TITLE
Blowfish Diffie Hellman key exchange

### ISSUE THREAD

**Issue by Shou** [hexchat/hexchat#653]
It'd be nice if we could have DH key exchange added to the fish plugin bundled with HexChat. This [weechat script](http://www.weechat.org/scripts/source/fish.py.html/) implements it, for example.

**Comment by philicious** [comment]
Here you go guys. My build https://mega.co.nz/#!PsphHY6A!kHcBtToVRrAoFJQcrG6gK5zvna8yTvRgElgYLeMIls8

until #1440 gets merged
