### ISSUE TITLE
(Re)connect command in the right click menu of disconnected channels

### ISSUE THREAD

**Issue by kmg90** [hexchat/hexchat#654]
Having had a few issues with getting disconnected from IRC a few times, I've had to deal with having reconnecting to IRC then rejoining channels that are still open but don't rejoin on reconnect (might be a separate feature request but not my main issue at the moment)

I've attached a example of the current right click menu and all of its < none>thingness for reference

![2013-06-23 14_26_26-hexchat exe](https://f.cloud.github.com/assets/4296643/692657/f5dfbe7a-dc3a-11e2-9415-f8a4f7c3a567.png)

**Comment by HumanG33k** [comment]
@TingPing but the top bar menu server know how to reconnect the selected currently disconnect server right ?
