### ISSUE TITLE
Occasional crashes or freezes during startup on Win7 x64

### ISSUE THREAD

**Issue by sagamusix** [hexchat/hexchat#673]
Sometimes, when starting HexChat, it just crashes during connection or receiving the backlog from my IRC bouncer. I'm running on Win7 64bit. I caught both a crash during startup and another freeze in the debugger, so I can provide memory dumps if you need them.

**Comment by lqv127604** [comment]
Look like the auto update checker plugin causes HexChat hanging right after starting it. I reinstall HexChat (on Portable mode as I always do) and uncheck the auto update checker plugin. And it's fine now, no hang and HexChat run smooth than ever.

**Comment by TingPing** [comment]
This was fixed way back in https://github.com/hexchat/hexchat/commit/b6877ccf5c7676a7b7c64797d38cf8833692e1ae btw, guess it was never mentioned here.
