### ISSUE TITLE
Fishlim plugin causes crash (was: Hexchat randomly crashes.)

### ISSUE THREAD

**Issue by Groil** [hexchat/hexchat#674]
Sorry about the title it's the best I could come up with.

I've been having some problems with random crashes lately. Visual studio seems to think that the problem is in gtk_xtext_append_entry.

I've also found this bug report: http://sourceforge.net/p/xchat/bugs/589/ which seems to confirm that something is wrong with gtk_xtext_append_entry.

**Comment by TingPing** [comment]
It has been a few years and hexchat is much more strict about garbage bytes coming in, so I'll assume it has been fixed, feel free to reopen if this is incorrect.
