### ISSUE TITLE
The colour codes on hexchat are different to on xchat2

### ISSUE THREAD

**Issue by abc-mikey** [hexchat/hexchat#682]
I have copied across the colour scheme from xchat2 into hexchat. As you can see from these images they are now exactly the same:

https://dl.dropboxusercontent.com/u/38280833/xchat-colours.png
https://dl.dropboxusercontent.com/u/38280833/hexchat-colours.png

Each colour has a number and each colour number has a colour assigned to it. For both Hexchat and XChat2 on my system all of these are the same.

However the colours as seen in the channel tabs and in the server tab are different:

https://dl.dropboxusercontent.com/u/38280833/xchat-chat.png
https://dl.dropboxusercontent.com/u/38280833/hexchat-chat.png

https://dl.dropboxusercontent.com/u/38280833/xchat-server-message.png
https://dl.dropboxusercontent.com/u/38280833/hexchat-server-message.png

Notice particularly the "Quit" and "Join" messages are different and so is the "-NickServ-". The server connection notification is also now highlighted, but the channel join notification is now not highlighted. 

That is what I've noticed from a quick comparison. 

Why are there so many differences? Particularly the swapping of colours for Join and Quit messages. If Hexchat is using seemingly the same colour definitions as XChat2 was why swap some of them? If Hexchat wanted to change the colours for those messages it should have changed the colours assigned to those colour numbers not swapped the numbers.

**Comment by barleyer** [comment]
@barleyer
