### ISSUE TITLE
"Don't highlight anything" setting for a channel

### ISSUE THREAD

**Issue by NoneGiven** [hexchat/hexchat#694]
Since highlights are not per-channel or per-server, I run into issues where highlights are triggered that are meaningful in another channel but meaningless in the one they're appearing in at the time, which is annoying. A proposed solution is a "don't notify" or "no highlights" option which can be set on a channel by channel basis, like disk logging and hidden join/part messages.

Presumably this is easier to implement (and use) than channel-specific highlight words, since Hexchat doesn't really "favorite" or otherwise record visited channels in a way that would let you set specific settings like you can with servers.

**Comment by Zombaya** [comment]
The link provided by TingPing does not work anymore.  There is a plugin in this repository though which I found at [https://github.com/hexchat/hexchat-addons/blob/master/perl/channel_highlight/channel_highlight.pl](url)

#### From previous weblink: 
Configuration is done in file and requires a bit of regular expression knowledge.
Currently, all configuration must be done in file, locate the following code:
```
my %chan_highlights = (
	'#chan1' => '(!admin|@george)',
	'#chan2' => '(peppers)'
);
```
Specify the channel name infront in lower case (wild cards not allowed), and the pattern to match after the => between single quotes. To specify multiple words or patterns, keep things in the group and use the vertical bar (|). You can also use ^ to signify the beginning of a line, and $ for the end.
