### ISSUE TITLE
Any plan for ruby plugin?

### ISSUE THREAD

**Issue by youknowone** [hexchat/hexchat#703]
I am not a real hexchat user. So I may say something wrong.

I found hexchat doesn't have ruby in the plugin repository.

I tried https://github.com/xchataqua/xchatruby this project to XChat Aqua and found it works - though not very well.

If you have any plan for ruby plugin, I hope this project helps you.

**Comment by RoUS** [comment]
As a heavy Ruby user, and just now switching from XChat to Hexchat, I'm interested in this topic, and quite possibly with making it happrn.

**Comment by TingPing** [comment]
@RoUS I still don't think it will be an official plugin but best of luck modernizing it and if you have any questions about the plugin API feel free to stop by #hexchat on freenode.
