### ISSUE TITLE
'HexChat IRC client has stopped working' every time I open it

### ISSUE THREAD

**Issue by vullithe** [hexchat/hexchat#741]
Starting yesterday, hexchat just won't work for me. After 2 minutes of having it open I'd get 'HexChat IRC client has stopped working'. When it is first opened, two of my autojoin servers are listed as <none>. Rizon.net says it failed to connect, and the other one is saying it can't even find it. I tried updating, uninstalling, reinstalling, restarting comp, but nothing at all changed. Does anyone have any ideas what the issue might be?
http://i.imgur.com/gPxEShY.png

**Comment by AndersBillLinden** [comment]
Happens for me in hexchat 2.12.4, windows 10 x64. It just started to happen (worked before to start hexchat).

**Comment by AndersBillLinden** [comment]
I tried to remove the roaming/HexChat folder. Now I first have to connect to a server before the application crashes.
