### ISSUE TITLE
Copy/Paste behaviour

### ISSUE THREAD

**Issue by CounterPillow** [hexchat/hexchat#77]
Hello,
I'd be more than happy if instead of CTRL+Shift+C the usual key combo CTRL+C could be used to copy, as it makes little to no sense when Paste is CTRL+V.

**Comment by Ketsuban** [comment]
I would suggest there's not much utility in allowing text to be selected in the input box and the window area  at the same time—if that wasn't the case Ctrl-C would be completely unambiguous. (Consider the old adage that "IRC is multiplayer Notepad"; the input box is more of an extension to the channel area than a separate widget.)
