### ISSUE TITLE
Opening irc:// links in same application

### ISSUE THREAD

**Issue by Chibicon** [hexchat/hexchat#80]
Would it be possible to make Hexchat open multiple irc:// links in the same application? Currently clicking on a link such as irc://irc.rizon.net/commie-subs will open Hexchat and then go to that channel IF Hexchat isn't already open.

Clicking on a different irc link such as irc://irc.rizon.net/gg won't even open the channel if you have "Allow only one instance of Hexchat to run" checked. If you don't have this checked it will open the channel in a new Hexchat and your current nick won't even be used because you're already identified in the previous Hexchat.

**Comment by PowaBanga** [comment]
i do not understand, what I have to do for make than all irc link are openned in the current window ???

**Comment by TingPing** [comment]
@PowaBanga Nothing, it isn't supported on Windows currently.

**Comment by PowaBanga** [comment]
yes, but me I am on Ubuntu for now, is it the case too ?

**Comment by TingPing** [comment]
@PowaBanga Your version is just really old, grab the PPA on https://hexchat.github.io

**Comment by PowaBanga** [comment]
My version of hexchat is 2.12.4... isn't it the last ?

**Comment by TingPing** [comment]
Yes then it should work fine, how are you reproducing your issue?

**Comment by PowaBanga** [comment]
so, when hexchat is open, and i clic on an irc link in firefox, this open my link in a new widows of hexchat with a new task icon...

Maybe I will not have very much time now to do this correctly, but i will come back.

**Comment by bingoxo** [comment]
anyone figured out how to fix this ?

**Comment by bingoxo** [comment]
why has my comment been deleted ? it's been 7 years and the issue is still there
