### ISSUE TITLE
High CPU usage while typing

### ISSUE THREAD

**Issue by shogoonn** [hexchat/hexchat#830]
HexChat 2.9.6.1 (build date: 2013-09-15, both x86 and x64 non-portable builds, clean install of x64 build and then x86 to see if it makes a difference).
OS: Windows 8.1 64-bit
The CPU is quad core i5-4570. When idle, the CPU runs at ~800MHz. Fast typing in a message box causes the frequency to rise up to ~3 GHz, and the CPU usage in this state is up to 20% (total of all cores). One of the cores is being loaded up to 80% (with some core switching). Slower typing causes less CPU load (on average). The power consumption rises from ~28W to more than 40W (I have a watt meter plugged in). 

Sometimes the CPU load stays that high after I had finished typing, and drops back to normal only after I switch to another window.
No suspicious activity found with Sysinternals Process Monitor (disk writes, sockets, registry, etc.). No visible changes in memory usage while typing.

The CPU load is caused by a key release event. When I hold down a key, the CPU usage stays low until I release it. Releasing a key adds about 0.5 seconds to the "CPU user time" performance counter of the process.
I think it may have something to do with GTK+'s crappy keyboard handling. There's no information on the GTK+ version in Help->About window.

**Comment by tahg** [comment]
Cannot confirm either, Win7 Hexchat 2.10.1.  Seems like an issue exclusive to one or more versions of Windows 8.x

**Comment by MadClown** [comment]
I can confirm that this issue is happening on my computer also. My CPU usage did indeed jump up quite a bit from typing like how it was described by the OP. Typically CPU usage was about 10-15% when typing quickly and only happened when keys got released. Holding a key down did not increase CPU usage.

Windows 8.1
HexChat 2.11.0 x64 (spell check disabled)

**Comment by Warpten** [comment]
Upgraded to Win 8.1 x64, hexchat 2.10.2, successfully reproduced.

**Comment by LuqJensen** [comment]
Reproduced on win10 x64 using hechat 2.10.2

**Comment by petska** [comment]
Do portable install use more CPU time than nonportable?

**Comment by jackpoz** [comment]
Any plan to update the dependencies in case they are the root cause (in particular GTK+) ?

I provided detailed informations about where the CPU is wasting time 1 year ago in https://github.com/hexchat/hexchat/issues/830#issuecomment-52079358 and https://github.com/hexchat/hexchat/issues/830#issuecomment-52098530 but there has been no followup from either @Arnavion (who asked for the callstack) or anyone else.

**Comment by Arnavion** [comment]
- Test builds use whatever GTK is mentioned in https://github.com/hexchat/gtk-win32/issues/10 which at the moment is latest
- Your call stack shows GTK spending time in the code it constantly calls anyway (polling for new events). The reason why it's polling so much that it's pegging a core to max is unknown.
- I don't see I said it before in this thread, so try with 32-bit build. I see atleast one user says they could not repro with 32-bit build.

**Comment by genbtc** [comment]
Reproduced on Hexchat 2.10.2 x64 on windows 10. (the hexchat about box says "Windows 8")
On a hyperthreaded quadcore I7, its using 11% total CPU, (over 40% on 1 core).
Please people fix this. I do not have time to be recompiling hexchat fiddling with GTK libraries I know nothing about.

**Comment by Arnavion** [comment]
@genbtc Read the comment directly before yours, especially the third point.

**Comment by jackpoz** [comment]
41% CPU usage pressing CTRL on "Nick name" using "HexChat 2.10.2 x86.exe" on WIndows 10 x64

![32 bits](https://cloud.githubusercontent.com/assets/1153754/9746771/20d05412-567a-11e5-9519-ce888da2d89a.png)

Is there any hexchat developer who uses Windows x64 ?

**Comment by Arnavion** [comment]
It's unfortunate that the 32-bit version has the same issue.

>Is there any hexchat developer who uses Windows x64 ?

Yes, but I use W7 which does not demonstrate this issue (as mentioned before in this thread). @tomek You're on 8.1?

**Comment by genbtc** [comment]
X86 version totally does it too: http://puu.sh/k5jGU/a7eac9d48f.png
And yes, It was fine on win7. I read somewhere that windows 8->10 has some kind of internal spell checker, and I tried to disable it with these registry keys:
[HKEY_CURRENT_USER\Software\Microsoft\TabletTip\1.7]
"EnableAutocorrection"=dword:00000000
"EnableSpellchecking"=dword:00000000

But my computer has all the "tablet" shit explicitly disabled on purpose, and this did not fix it.

**Comment by TingPing** [comment]
> I read somewhere that windows 8->10 has some kind of internal spell 

Windows 8 added spell checking and HexChat < 2.11.0 never made use of it.

**Comment by Mo0NTan** [comment]
I just discovered a way to dramatically decrease the CPU usage when typing, I disabled the Runtime broker in the task manager. This shuts off the built in windows 10 spell check in hexchat making every word have a red line under it, I then put my old windows 7 spellcheck enchant folder in my hexchat shared folder (i am using a portable install). This stopped the spell checker to not make red lines under every word.
![runtime-broker](https://cloud.githubusercontent.com/assets/14211407/9780488/4674d1ec-573e-11e5-8915-1661674729b1.jpg) I believe there is a registry hack to disable the Runtime broker permanently, but every time you re-open hexchat or any other program that depends on it the Runtime process restarts. I just disable it again.  There is still a little cpu usage but not nearly as much as it did.

**Comment by Mo0NTan** [comment]
I forgot to add... You should wait like 5 minutes to really tell the difference after you disable it, I've also noticed if you disable Cortana  along with the Runtime broker it is even better. but then Cortana kicks back in along with the Runtime broker in less then a minute, So for now i just keep the runtime broker disabled

**Comment by TingPing** [comment]
@Mo0NTan Uh what version do you use? I already said *"Windows 8 added spell checking and HexChat < 2.11.0 never made use of it."*. Also does disabling it in *Preferences > Input* do nothing compared to this?

**Comment by genbtc** [comment]
@Mo0NTan Dude dont mess with runtimebroker...You disable it from PC Settings->Devices->Typing , and I checked on my system, closing runtimebroker did not help anything, and I would never use Cortana on.... :
![2015-09-10_03-10-22](https://cloud.githubusercontent.com/assets/3683744/9782241/9fbfdcbc-5769-11e5-8318-b81f205cf12d.png)

**Comment by Mo0NTan** [comment]
oh, Thanks,That seems to work too, i did manage a hack to disable cortana, but that didn't significantly help at all, Seems the spellcheck does a bit. It goes to like 10 to 15% apposed to 30% and don't get stuck at 30. It could be video card driver related. I don't know?

**Comment by jackpoz** [comment]
The CPU usage issue affects only HexChat and not other applications like Notepad++, trying random things like killing Windows processes doesn't look much useful.

**Comment by Mo0NTan** [comment]
I wonder if an older version of hexchat regardless of the security holes wouldn't have this issue. I just realized how hot this is on my legs while on my laptop,

**Comment by jackpoz** [comment]
This issue is now 2 years old. In the meantime a new OS version came out (Windows 10) and still has the same issue.
If the root cause is in GTK+ then the issue should be reported to that project so they can fix it, there are already clear How To Reproduce steps

**Comment by genbtc** [comment]
Can one of us unofficially modify GTK and provide a diff patch so that we can share it amongst ourselves in the meantime ? I would gladly recompile and unless someone gets the ball rolling, and at least proves that modifying GTK can fix the issue and that theres no other way to fix hexchat itself, then I doubt the GTK people will admit theres a problem on their end.

**Comment by TingPing** [comment]
@genbtc We already ship a few patches that never made it upstream, so if somebody solves this that would be acceptable.

**Comment by Arnavion** [comment]
>I think it might warrant a note in the Developer Docs that "powershell.exe" has to be in your PATH variable

`%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\` is in PATH on a default Windows install. It doesn't need to be mentioned in docs.

>End result, the PATH variable still wasnt enough

You probably didn't restart VS to make it pick up the new value after you edited it.

>I managed to download the source for hexchat and compile it. The problem still exists.

You're building HC using GTK+openssl built by us. To make changes to GTK you will need to build GTK.

**Comment by jackpoz** [comment]
Did any developer update to Windows 10 in the meantime ?

**Comment by jackpoz** [comment]
Tested HexChat 2.12.0 on Windows 10 x64, still same issue. I saw some Windows 8 features in the changelog, am I to believe finally someone upgraded to Windows 8+ and can now work on this issue ?

**Comment by jackpoz** [comment]
Looking at the data I gathered 596 days ago https://github.com/hexchat/hexchat/issues/830#issuecomment-52079358 it could be that MsgWaitForMultipleObjectsEx() is called with a timeout too small

**Comment by Arnavion** [comment]
>or will they just stare at the issue

Instead of waiting on us (which for gtk-win32 issues is basically just me), you can compile gtk-win32 yourself and test any patches you want.

**Comment by jackpoz** [comment]
HexChat build system is a nightmare, with custom Visual Studio build steps that don't support special characters or spaces and cryptic build errors. The repo layout HexChat chose scares away any developer who would attempt to build it (tried and gave up 3 times so far).

https://github.com/hexchat/gtk-win32/blob/master/README.md doesn't provide any way to get a .sln with HexChat and all the dependencies so one can just F5 and debug into the application and all related dependencies.

I profiled the issue, found a patch, opened a ticket to GTK+ https://bugzilla.gnome.org/show_bug.cgi?id=764415 and all you could write was "build it yourself". Going back to my question
>Would any hexchat developer feel like working together to fix this issue ?

the answer is clearly "No"

**Comment by jtanx** [comment]
Hello, I noticed this bug while searching on the internet. I experienced the same issue and I think I've found the problem. See here: https://bugzilla.gnome.org/show_bug.cgi?id=771568

The patch is to GDK.

**Comment by jackpoz** [comment]
Thanks for the heads up @jtanx and for the patch.
@TingPing it seems the patch provided at https://bugzilla.gnome.org/show_bug.cgi?id=771568 for gtk+ fixes the issue, could it be merged ?

**Comment by TingPing** [comment]
@jackpoz Looks like they didn't backport that patch to Gtk2, I left a message so it will get into the next release.

**Comment by genbtc** [comment]
Please do

**Comment by jackpoz** [comment]
Any update on this ?

**Comment by TingPing** [comment]
These patches have been commited to gtk-2-24 upstream. So next time HexChat gets a release on a new enough gtk version it will be fixed.
