### ISSUE TITLE
Missing .dll

### ISSUE THREAD

**Issue by ghost** [hexchat/hexchat#833]
Hello, I installed hexchat and microsoft c++, and it gives me error
`The program can't start because MSVCR110.dll is missing...`
any help?

**Comment by t-mart** [comment]
The VS link there did not solve my problem; Instead, use the redistributable from the official download page, up to date with VS 2013. https://hexchat.github.io/downloads.html

**Comment by tomek** [comment]
@t-mart that link was for vs2012 (issue is nearly 2 years old), and right now our installer takes care of downloading/installing vs redist.

**Comment by t-mart** [comment]
I recently restarted my Windows 8 machine after a system update and got the same error as OP (or I installed something that broke it, not sure). Either way, I was in need of a repair to my VS2013, and the link on page I posted before solved my problem.
