### ISSUE TITLE
Problem with SOCKS5 + Tor + Freenode

### ISSUE THREAD

**Issue by ghost** [hexchat/hexchat#849]
Freenode's tor hidden service is unstable, but it provides me 4 different nameservers, I need hexchat tries connection at all of them before reporting error but this doesn't happen.
Log:
- Connecting to 127.0.0.1 (127.0.0.1) port 31786...
  SOCKS Proxy failed to connect to host (error 5).
  Proxy traversal failed.
- Stopped previous connection attempt (pid=13279)

At the time of this connection I have 3 other nameservers to hexchat try, but he doesn't just hang up here.
Note: The proxy works, I'm 100% sure, maybe a little more.
Thanks for hexchat, it's really cool.

**Comment by iyx** [comment]
Hopefully this will get fixed eventually, although reported already more than a year ago.

Only possible workaround I can think of would be a script that would trigger on this 'Proxy traversal failed' error and start reconnect to the network.

**Comment by Mikaela** [comment]
It might also be worth noting that freenode's tor hidden service is temporarily disabled because of abuse and it has been that way for some time now.

```
2015-03-14 22:12:09+0200 -- Topic for #freenode is "Welcome to #freenode | Due to ongoing abuse the tor-sasl hidden service has been temporarily disabled | Staff are voiced; some may also be on /stats p -- you can /msg us at any time | FAQ: https://freenode.net/faq.shtml | Channel guidelines: https://freenode.net/poundfreenode.shtml | Blog: https://blog.freenode.net | Please don't comment on spam/trolls"
2015-03-14 22:12:09+0200 -- Topic set by mquin on 2015-02-09 20:04:38+0200
```

**Comment by lnostdal** [comment]
This is still a problem in 2.12.4-5build2 (Xubuntu).

**Comment by dry-75** [comment]
Still an issue here , hexchat 2.14.2 ...  Would be great if it's fixed ?

**Comment by olof486** [comment]
> 
> 
> Still an issue here , hexchat 2.14.2 ... Would be great if it's fixed ?

here too. But strange issue: Yesterday it works (but no update at tor or hexchat) or changes at the system. Restarts and 10 tries, no connection to localhost 

```
SOCKS Proxy failed to connect to host (error 5).
 Proxy traversal failed.
* Stopped previous connection attempt (11176)
* Looking up irc.xyz
* Looking up 127.0.0.1
```

And than, twenty minutes later it connect. What could here happend?

```
* Looking up irc.xyz.....
* Looking up 127.0.0.1
* Connecting to 127.0.0.1:9150 (127.0.0.1:9150)
* Connected. Now logging in.
* *** Looking up your hostname...
* *** Found your hostname (exit.tor.xyz)
```
