### ISSUE TITLE
[Python 3] HexChat passing non Unicode strings to Python 3

### ISSUE THREAD

**Issue by Motoko11** [hexchat/hexchat#869]
I've run into a problem where HexChat will pass non Unicode encoded strings into python when using the hexchat.hook_print("Key Press") function. This raises the unicode error,  `"UnicodeDecodeError: 'utf-8' codec can't decode byte 0x## in position 0: invalid start byte"`. Due to Python 3 expecting all strings to be Unicode, there is no real way to fix this in the code itself as trying to access the variable containing the invalid string (In this case 'word') results in that exception. So far I've seen this exception work when you press the €, ¬, ¦ or £ keys. Also all accented characters are affected also. I expect it to be the same for any ANSI characters above 127. The following code will show you the error if you run it on Python 3.

```py
import hexchat

__module_name__ = "Unicode Error"
__module_version__ = "1.0"
__module_description__ = "Will cause unicode error if ANSI > 127 character is pressed."

def crash_cb(word, word_eol, userdata):
	print(word)
	return hexchat.EAT_NONE

hexchat.hook_print("Key Press", crash_cb, priority=hexchat.PRI_HIGHEST)
```

Also, I am using HexChat 2.9.6, and Python 3.3

Edit: Confirmed by a friend, the same error is achieved with the keys å, ä, ö and µ.

**Comment by TingPing** [comment]
With the help of @bendem (since I cannot repro) I have tried to solve this using ```gdk_keyval_to_unicode()``` as mentioned above. Taking this value and converting to utf8 using ```g_unichar_to_utf8()``` resulted in invalid utf8 (failing ```g_utf8_validate()```) on his machine which triggers the same error as above.

So at this point I don't know of a solution unless @Arnavion has any ideas.

**Comment by TingPing** [comment]
Turns out ```g_unichar_to_utf8()``` does not nul-terminate so with that fixed it works fine.

**Comment by FichteFoll** [comment]
I receive UnicodeDecodeErrors when accessing `word[0]` in my `hook_print('Key Press', ...)` callback whenever I type any of these:

öäüÖÄÜ€

HexChat 2.10.2, Win7, Python 3.4.1 (everything x64)

**Comment by tomek** [comment]
@FichteFoll use test build from here: https://dl.hexchat.net/hexchat/testing/

**Comment by FichteFoll** [comment]
@tomek that works, thanks
