### ISSUE TITLE
Possible newline character in title bar picked up by XFCE 4.10

### ISSUE THREAD

**Issue by spicypixel-** [hexchat/hexchat#879]
Fresh install of Xubuntu 14.04 Alpha and latest package from the gwendal-lebihan-dev/hexchat-stable PPA. Numix window manager theme applied.

![7yvkazm](https://f.cloud.github.com/assets/933423/1897390/a36985a0-7bdf-11e3-92b2-589b0bae1fa4.png)

Seemingly causing a newline before the forward slash in the title bar. In two row mode on the panel the title is still exhibiting the same behaviour inside the confines of the button.

**Comment by ivan** [comment]
This also results in really confusing output from `xdotool getactivewindow getwindowname` for hexchat, where the first line appears to be entirely missing, but is visible if you pipe it into a file and use `less`.

(Tested HexChat 2.10.2 on Ubuntu 15.10)

**Comment by ivan** [comment]
This was happening because my `servlist.conf` was imported from Windows and had CRLF newlines.

**Comment by TingPing** [comment]
@ivan Thanks for tracking this down, that problem is being handled in #834.
