### ISSUE TITLE
URL Default to Open

### ISSUE THREAD

**Issue by davidgomes** [hexchat/hexchat#88]
If there isn't yet a way to just use the left mouse button to automatically open a link, I think there should be.

Basically , I always have to right click and then select "Open Link in Browser". The default (left button) should Open Link in Browser, it'd be much easier.

Thank you.

**Comment by marsjaninzmarsa** [comment]
Should be default...

**Comment by TingPing** [comment]
@marsjaninzmarsa It has been default for years by now...

**Comment by marsjaninzmarsa** [comment]
Umm, so maybe it's cause of my migration from XChat... :x

**Comment by TingPing** [comment]
@marsjaninzmarsa Yes; It is generally recommended to not migrate because of such stupid settings.
