### ISSUE TITLE
cannot change nick after reconnect to a server

### ISSUE THREAD

**Issue by AlexCppns** [hexchat/hexchat#901]
the command /nick does not work after I reconnect to a server. 

Repeatability: all the time
OS: Windows 7
Version: 2.9.5
Build type: x86

**Comment by AlbertoGP** [comment]
Hi, this happens to me too, HexChat 2.14.2. Network is freenode.

I’m registered with my nick and password, the network connection is lost, and when it comes back my nick changes to an unregistered alternative.
Clicking on my nick next to the input text box shows the change dialog, but when I put there my registered nick it gets changed back.
Checking with /whois <my-registered-nick> does not show it being in use.

I’ve tried the “reconnect” menu command, but the problem stays the same.

However, if I go to the server list and click “Connect”, the new connection uses my registered nick as usual. At this point I see at the left-side pane (channel selector tree) two trees, with the same IRC network (freenode) and inside the same channels, the ones I’m connected to.

The raw log is as follows (nick replaced by <my-registered-nick>, channel with #<channel>):
```
<< NICK <my-registered-nick>
>> :card.freenode.net 435 <alternative-nick> <my-registered-nick> #<channel> :Cannot change nickname while banned/quieted on channel
```

**Comment by TingPing** [comment]
@AlbertoGP The message you got was clear, HexChat doesn't control your nick the network does.
