### ISSUE TITLE
No system beep alert (worked in xchat)

### ISSUE THREAD

**Issue by barjac** [hexchat/hexchat#902]
hexchat-2.9.6.1-3.mga5
Compiled: Feb  5 2014
OS: Linux 3.12.13-desktop-2.mga5 (x86_64)
KDE 4.12.2 (With system alerts redirected to beep in systemsettings)

I do not use the sound system ( as in alsa etc.) most of the time, but prefer to use the mother board 'bell' or beeper as a sound alert.

This works fine in xchat, however when I switched to hexchat today, I cannot make this work. I have read the notes in the FAQ but this only mentions sound as in alsa.

The beep sounds in hexchat when I attempt to backspace at the start of the text entry box for example.

**Comment by sven337** [comment]
Seconded, this should be an option in hexchat. You seem to insist on canberra being the default beeping method - why not, but that doesn't imply that you have to make it hard to bypass it and get back to good old pc speaker beeping. Would you please consider that?
