### ISSUE TITLE
Modify userlist with plugin (Twitch IRC Userlist Fix)

### ISSUE THREAD

**Issue by cryzed** [hexchat/hexchat#913]
Hello, since Twitch.tv stopped responding to the /WHO command on their IRC servers the userlist always appears empty. I wanted to write a plugin that retrieves the userlist from their website for a given stream and then manually populate the userlist -- but it seems the plugin API doesn't offer that option. Could it be added?

**Comment by RobNuts** [comment]
This issue started again a few days ago. Chatty seems to be updated to work properly but HexChat still doesn't show the userlist. The "plugin" listed here doesn't seem to help any.

**Comment by TingPing** [comment]
@RobNuts Since E3 started they completely disabled JOIN and PART events. So any normal client is completely busted.

**Comment by Anaerin** [comment]
They're disabled, but you can request them. On connect, you need to send ````CAP REQ :twitch.tv/membership```` which will then tell the server you want to see joins and parts - Note they will be batched, so you may see someone talk before you get a JOIN for them.

**Comment by mB-PiBox** [comment]
@Anaerin your commenting on a 3 year old issue that hasn't had a comment in 2 years.

**Comment by TingPing** [comment]
Also HexChat requests `twitch.tv/membership` itself now.

**Comment by radical-equanimity** [comment]
I 'm reviving this because the issue doesn't seem closed. Hexchat requests twitch.tv/membership but that doesn't mean the userlist is populated with users already in the streamer's channel.

**Comment by TingPing** [comment]
Twitch doesn't expose the full list over IRC so it will always require a third party plugin for that.

**Comment by Anaerin** [comment]
The joins and parts are batched and only appear every minute or so, so someone could be chatting away while not in the list. Also, in channels with over a thousand members, twitch doesn't send JOIN/PARTs at all.
