### ISSUE TITLE
segfault connecting via ssl with /server and with client cert

### ISSUE THREAD

**Issue by kytvi2p** [hexchat/hexchat#950]
I can consistently reproduce this problem on my system.

Debian unstable x64
Hexchat, Debian package version 2.9.6.1-2
openssl 1.0.1g-2

```
Program received signal SIGSEGV, Segmentation fault.
0x00000000004590fc in ?? ()
(gdb) bt
#0  0x00000000004590fc in ?? ()
#1  0x0000000000475561 in ?? ()
#2  0x0000000000467538 in ?? ()
#3  0x00007ffff36ffce5 in g_main_dispatch (context=0x74ac30) at /tmp/buildd/glib2.0-2.40.0/./glib/gmain.c:3064
#4  g_main_context_dispatch (context=context@entry=0x74ac30) at /tmp/buildd/glib2.0-2.40.0/./glib/gmain.c:3663
#5  0x00007ffff3700048 in g_main_context_iterate (context=0x74ac30, block=block@entry=1, dispatch=dispatch@entry=1, 
    self=<optimized out>) at /tmp/buildd/glib2.0-2.40.0/./glib/gmain.c:3734
#6  0x00007ffff370030a in g_main_loop_run (loop=0xf1c330) at /tmp/buildd/glib2.0-2.40.0/./glib/gmain.c:3928
#7  0x00007ffff6a4c147 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#8  0x00000000004207c9 in ?? ()
#9  0x000000000041506a in ?? ()
#10 0x00007ffff3112b45 in __libc_start_main (main=0x414f50, argc=1, argv=0x7fffffffe118, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffe108) at libc-start.c:287
#11 0x00000000004150db in ?? ()
```

Steps:
1. Add default client cert (`$HOME/.config/hexchat/certs/client.pem`)
2. Set socks proxy.
3. Add server to network list, but set `bypass proxy server` and `SASL external auth`. Note: The server cannot be reached via the proxy.
4. Connect to server from the network list. The cert is sent and my nick is authenticated.
5. Connect to the server using `/server local.server.ip.address +6697` or `/server -ssl local.server.ip.address`. Note: It will not try to traverse the proxy. Instead, it connects directly to the server.
6. Crash. 

Just before the crash, the following is displayed:

```
* Capabilities supported: away-notify extended-join account-notify multi-prefix sasl tls userhost-in-names
* Capabilities requested: away-notify extended-join account-notify multi-prefix 
* Capabilities acknowledged: away-notify extended-join account-notify multi-prefix
```

Restarting after the crash, `/server server.ip.address +6697` correctly fails to connect through the proxy.

```
SOCKS Proxy refused to connect to host (not allowed).
 Proxy traversal failed.
* Stopped previous connection attempt (12498)
```

Connecting via the Network List has not yielded a segfault in my testing.

**Comment by mapreri** [comment]
I think this was https://bugs.debian.org/779892 (see also https://bugs.debian.org/862006) - caused by a debian patch, fixed earlier this year (better late than never, I guess…).
